name: 'Install dependencies'
description: 'Install dependencies to build shadow-utils'
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      sudo apt-get update -y
      sudo apt-get install -y ubuntu-dev-tools
      sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
      sudo apt-get update -y
      sudo apt-get -y build-dep shadow
