name: 'Install dependencies'
description: 'Install dependencies to build shadow-utils'
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      sudo cat /etc/apt/sources.list.d/ubuntu.sources
      sudo sed -i 's/^Types: deb/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
      export DEBIAN_PRIORITY=critical
      export DEBIAN_FRONTEND=noninteractive
      # let's try to work around upgrade breakage in a pkg we don't care about
      sudo apt-mark hold grub-efi-amd64-bin grub-efi-amd64-signed
      sudo apt-get update
      sudo apt-get -y dist-upgrade
      sudo apt-get -y install ubuntu-dev-tools automake autopoint xsltproc gettext expect byacc libtool libbsd-dev pkgconf
      sudo apt-get -y build-dep shadow
