.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: groups.1,v 1.4 2003/04/28 02:07:12 kloczek Exp $
.\"
.TH GROUPS 1
.SH NÉV
groups \- kiírja a jelenlegi csoportazonosító neveket
.SH ÁTTEKINTÉS
.B groups
.RI [ felhasználó ]
.SH LEÍRÁS
A
.B groups
parancs kiírja a jelenlegi csoportazonosító neveket vagy számértékeket. Ha
nincs az értéknek megfelelõ bejegyzés a \fI/etc/group\fR fájlban, akkor a
csoport azonosító számát írja ki. Az opcionális \fIfelhasználó\fR paraméter
esetén azokat a csoportokat írja ki, amelyekbe a megadott \fIfelhasználó\fR
tartozik.
.SH MEGJEGYZÉS
Azok a rendszerek, amelyek nem támogatják a konkurrens csoportbeállításokat,
a kiírt információkat a \fI/etc/group\fR fájlból gyûjtik. A felhasználónak
muszáj a \fBnewgrp\fR vagy a \fBsg\fR parancsot használniuk, hogy
megváltoztassák a jelenlegi valódi és effektív csoportazonosítójukat.
.SH FÁJLOK
\fI/etc/group\fR \- információ a csoportokról
.SH LÁSD MÉG
.BR newgrp (1),
.BR getgid (2),
.BR getgroups (2),
.BR getuid (2)
.SH AUTHOR
Julianne Frances Haugh (jfh@tab.com)
.SH MAGYAR FORDÍTÁS
ifj. Dyekiss Emil <emil2@cds.hu>
