.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH CHSH 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
chsh \- ändert den Loginshell Eintrag in der Paßwortdatei
.SH SYNTAX 
.B chsh
.RI [ Benutzer ]
.RI [ Shell ]
.SH BESCHREIBUNG
.B chsh
ermöglicht es jedem eingetragenen Benutzer, seine Loginshell selbst, das
heißt ohne Hilfe des Superusers (root) zu verändern.  Die Loginshell wird
in der Paßwortdatei /etc/passwd festgelegt.  Diese Datei kann nur mit
Rootprivilegien verändert werden.  Um auch den anderen Anwendern das
Verändern des Eintrages zu erlauben, läuft das
.B chsh
Programm SUID root.  Das heißt, bei seiner Ausführung wird die effektive
Benutzerkennung des Superusers gesetzt.  Um die Systemsicherheit trotzdem
zu gewährleisten, können nur Programme, die in der Datei /etc/shells
eingetragen sind als Loginshell benutzt werden.
.PP
Normalerweise kann ein Anwender nur seine eigene Loginshell ändern.  Der
Superuser selbst kann das Programm aber auch für andere Benutzer anwenden,
indem er den Benutzernamen in der Kommandozeile angibt.
.SH AUTOR
Peter Orbaek

