.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH GROUPS 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
groups \- zeigt alle Gruppen, denen der Benutzer angehört
.SH SYNTAX 
.B groups
.RI [ Benutzer ...]
.SH BESCHREIBUNG
.B groups
gibt die Namen aller Gruppen vom
.I Benutzer
aus. Wird kein Name angegeben, werden die Gruppen des aktuellen Prozesses
gezeigt.
.SH "SIEHE AUCH"
.B groups
ist ein Shellscript und benutzt
.B id

