.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH NEWGRP 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
newgrp \- ändert die Gruppenkennung des aktuellen Benutzers
.SH SYNTAX 
.B newgrp
.RI [ Gruppe ]
.SH BESCHREIBUNG
Das 
.B newgrp
Kommando ändert die aktive Gruppenkennung des Anwenders.  Ohne Angabe
einer Gruppe wird zu der in der /etc/passwd Datei festgelegten Standardgruppe
des Benutzers gewechselt. Sonst wird in die angegebene Gruppe gewechselt,
wenn der Benutzer in der Datei /etc/group als Mitglied dieser Gruppe
eingetragen ist.  Das
.B newgrp
Kommando unterstützt keine paßwortgeschützten Gruppen.
.PP
Die Gruppe kann nur mit ihrem Namen angegeben werden.
.SH "SIEHE AUCH"
das LunetIX Linuxhandbuch
.SH AUTOR
Michael Haardt, Peter Orbaek

