.\"
.\"	Copyright 1993 Sebastian Hetze und der/die in der Sektion
.\"	AUTOR genannten Autor/Autoren
.\"
.\"	Dieser Text steht unter der GNU General Public License.
.\"	Er darf kopiert und verändert, korrigiert und verbessert werden.
.\"	Die Copyright und Lizenzbestimmung müssen allerdings erhalten
.\"	bleiben. Die Hinweise auf das LunetIX Linuxhandbuch, aus dem
.\"	dieser Text stammt, dürfen nicht entfernt werden.
.\"
.TH PASSWD 1 "1. Juli 1993" "LunetIX Linuxhandbuch" "Dienstprogramme für Benutzer"
.SH BEZEICHNUNG 
passwd \- ändert das Paßwort zum System
.SH SYNTAX 
.B passwd
.RI [ Username ]
.SH BESCHREIBUNG
Die Paßwörter aller Benutzer werden in der Datei /etc/passwd gespeichert.  
Diese Datei ist lesbar aber schreibgeschützt.  Um dem Benutzer die
Möglichkeit zu geben, sein eigenes Paßwort zu ändern, läuft
.B passwd
SUID
.BR root ".
Deshalb hat der Anwender zur Laufzeit des Programms Rootprivilegien und darf
in die Datei schreiben.
.PP
Bei einigen Linuxinstallationen wird das Benutzerpaßwort in einer separaten
Datei namens
.B shadow
gespeichert, um den normalen Benutzern den Lesezugriff auf diese Daten zu
verwehren.  Die Einzelheiten zu diesem Paßwortsystem sind in den englischen
Manualpages beschrieben.  
.SH SIEHE AUCH
.BR chsh (1),
.BR newgrp (1)
und das LunetIX Linuxhandbuch
.SH AUTOR
Peter Orbaek

