.\"$Id: vipw.8,v 1.3 2005/12/01 20:38:25 kloczek Exp $
.\"
.\"Translated into german by Helge Kreutzmann <kreutzm@itp.uni\-hannover.de>
.TH VIPW 8 "21 Jul 2004"
.SH NAME
vipw, vigr \- bearbeitet die Passwort\-, Gruppen, Shadow\-Paßwort oder Shadow\-Gruppen\-Datei.
.SH SYNTAX
\fBvipw\fR [\fB\-s\fR]
.br
\fBvigr\fR [\fB\-s\fR]
.SH BESCHREIBUNG
.BR vipw " und " vigr
bearbeiten die Dateien
.IR /etc/passwd " bzw. " /etc/group .
Mit dem 
.B \-s
Schalter bearbeiten sie die Shadow\-Version dieser Dateien,
.IR /etc/shadow " bzw. " /etc/gshadow .
Diese Programme setzen die entsprechenden Locks um Dateibeschädigung
zu verhindern.

Bei der Auswahl des Editors überprüfen die Programme zuerst
die Umgebungsvariable
.BR VISUAL ,
dann die Umgebungsvariable
.BR EDITOR ,
und schließlich den Aufruf des Standard\-Editors
.BR vi (1).
.SH "SIEHE AUCH"
.BR group (5),
.BR passwd (5),
.BR shadow (5)
