.\" $Id: shadowconfig.8,v 1.2 1997/12/14 20:07:22 marekm Exp $
.TH SHADOWCONFIG 8 "19 Apr 1997" "Debian GNU/Linux"
.SH NAME
shadowconfig \- toggle shadow passwords on and off
.SH SYNOPSIS
.B "shadowconfig"
.IR on " | " off
.SH DESCRIPTION
.PP
.B shadowconfig on
will turn shadow passwords on;
.B shadowconfig off
will turn shadow passwords off.
.B shadowconfig
will print an error message and exit with a nonzero code if it finds
anything awry.  If that happens, you should correct the error and run
it again.

Turning shadow passwords on when they are already on, or off when they
are already off, is harmless.

Read
.I /usr/doc/passwd/README.debian.gz
for a brief introduction to shadow passwords and related features.
