.\"$Id: chpasswd.8,v 1.10 2002/03/08 04:39:11 kloczek Exp $
.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH CHPASSWD 8
.SH NAME
\fBchpasswd\fR - update password file in batch
.SH SYNOPSIS
\fBchpasswd\fR [\fB-e\fR]
.SH DESCRIPTION
\fBchpasswd\fR reads a file of user name and password pairs
from standard input and uses this information
to update a group of existing users. Without the -e switch, the
passwords are expected to be cleartext. With the -e switch, the
passwords are expected to be in encrypted form.
Each line is of the format
.sp 1
	  \fIuser_name\fR:\fIpassword\fR
.sp 1
The named user must exist.
The supplied password will be encrypted as necessary, and the password age
updated, if present.
.PP
This command is intended to be used in a large system environment where
many accounts are created at a single time.
.SH CAVEATS
.\" The \fBmkpasswd\fR command must be executed afterwards to update the
.\" DBM password files.
The input file must be protected if it contains unencrypted passwords.
.\" This command may be discarded in favor of the newusers(8) command.
.SH SEE ALSO
.\" mkpasswd(8), passwd(1), useradd(1)
.BR passwd (1),
.BR newusers (8),
.BR useradd (8)
.SH AUTHOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
