.\"$Id: dpasswd.8,v 1.8 2001/01/27 02:55:52 kloczek Exp $
.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH DPASSWD 8
.SH NAME
\fBdpasswd\fR - change dialup password
.SH SYNOPSIS
\fBdpasswd\fR [(\fI-af\fR|\fB-d\fR)] \fIshell\fR
.SH DESCRIPTION
\fBdpasswd\fR adds, deletes, and updates dialup passwords for user
login shells.
The dialup password is prompted for after a user's password has been
authenticated whenever the user logs in over a dialup line.
\fBdpasswd\fR will prompt for the new password twice to insure it
has been entered correctly.
.PP
The \fIshell\fR argument must be the complete pathname of the login
program.
.SH FILES
.br
/etc/d_passwd
.br
/etc/dialups
.SH SEE ALSO
.BR login (1)
.SH AUTHOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
