.\"     Title: expiry
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/30/2006
.\"    Manual: User Commands
.\"    Source: User Commands
.\"
.TH "EXPIRY" "1" "07/30/2006" "User Commands" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
expiry \- check and enforce password expiration policy
.SH "SYNOPSIS"
.HP 7
\fBexpiry\fR [\-c] [\-f]
.SH "DESCRIPTION"
.PP

\fBexpiry\fR
checks (\fB\-c\fR) the current password expiration and forces (\fB\-f\fR) changes when required. It is callable as a normal user command.
.SH "FILES"
.TP 3n
\fI/etc/passwd\fR
User account information.
.TP 3n
\fI/etc/shadow\fR
Secure user account information.
.SH "SEE ALSO"
.PP

\fBpasswd\fR(5),
\fBshadow\fR(5).
