.\" $Id: faillog.8,v 1.19 2005/04/09 17:09:56 kloczek Exp $
.\" Copyright 1989 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH FAILLOG 8
.SH NAME
faillog \- display faillog records or set login failure limits
.SH SYNOPSIS
.TP 6
\fBfaillog\fR [\fBoptions\fR]
.SH DESCRIPTION
\fBfaillog\fR formats the contents of the failure log from \fI/var/log/faillog\fR
database. It also can be used for maintains failure counters and limits.
Run \fBfaillog\fR without arguments display only list of user faillog records
who have ever had a login failure.
.SH OPTIONS
The options which apply to the \fBfaillog\fR command are:
.IP "\fB\-a\fR, \fB\-\-all\fR"
Display faillog records for all users.
.IP "\fB\-h\fR, \fB\-\-help\fR"
Display help message and exit.
.IP "\fB\-l\fR, \fB\-\-lock\-time\fR \fISEC\fR"
Lock accout to \fISEC\fR seconds after failed login.
.IP "\fB\-m\fR, \fB\-\-maximum\fR \fIMAX\fR"
Set maiximum number of login failures after the account is disabled to
\fIMAX\fR. Selecting \fIMAX\fR value of 0 has the effect of not placing a
limit on the number of failed logins. The maximum failure count should
always be 0 for \fBroot\fR to prevent a denial of services attack against
the system.
.IP "\fB\-r\fR, \fB\-\-reset\fR"
Reset the counters of login failures or one recor if used with \-u
\fILOGIN\fR option. Write access to \fI/var/log/faillog\fR is required for
this option.
.IP "\fB\-t\fR, \fB\-\-time\fR \fIDAYS\fR"
Display faillog records more recent than \fIDAYS\fR. The \fB\-t\fR flag
overrides the use of \fB\-u\fR.
.IP "\fB\-u\fR, \fB\-\-user\fR \fILOGIN\fR"
Display faillog record or maintains failure counters and limits (if used
with \fB\-l\fR, \fB\-m\fR or \fB\-r\fR options) only for user with \fILOGIN\fR.
.SH CAVEATS
\fBfaillog\fR only prints out users with no successful login since the last
failure. To print out a user who has had a successful login since their last
failure, you must explicitly request the user with the \fB\-u\fR flag, or
print out all users with the \fB\-a\fR flag.
.SH FILES
\fI/var/log/faillog\fR	\- failure logging file
.SH SEE ALSO
.BR login (1),
.BR faillog (5)
.SH AUTHOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
