.\"     Title: gpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: User Commands
.\"    Source: User Commands
.\"
.TH "GPASSWD" "1" "06/24/2006" "User Commands" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
gpasswd \- administer the /etc/group file
.SH "SYNOPSIS"
.HP 8
\fBgpasswd\fR \fIgroup\fR
.HP 8
\fBgpasswd\fR \-a\ \fIuser\fR \fIgroup\fR
.HP 8
\fBgpasswd\fR \-d\ \fIuser\fR \fIgroup\fR
.HP 8
\fBgpasswd\fR \-R\ \fIgroup\fR
.HP 8
\fBgpasswd\fR \-r\ \fIgroup\fR
.HP 8
\fBgpasswd\fR [\-A\ \fIuser,\fR...] [\-M\ \fIuser,\fR...] \fIgroup\fR
.SH "DESCRIPTION"
.PP

\fBgpasswd\fR
is used to administer the
\fI/etc/group\fR
file (and
\fI/etc/gshadow\fR
file if compiled with SHADOWGRP defined). Every group can have administrators, members and a password. System administrator can use
\fB\-A\fR
option to define group administrator(s) and
\fB\-M\fR
option to define members and has all rights of group administrators and members.
.SS "Notes about group passwords"
.PP
Group passwords are an inherent security problem since more than one person is permitted to know the password. However, groups are a useful tool for permitting co\-operation between different users.
.\" end of SS subsection "Notes about group passwords"
.SH "OPTIONS"
.PP
Group administrator can add and delete users using
\fB\-a\fR
and
\fB\-d\fR
options respectively. Administrators can use
\fB\-r\fR
option to remove group password. When no password is set only group members can use
\fBnewgrp\fR
to join the group. Option
\fB\-R\fR
disables access via a password to the group through
\fBnewgrp\fR
command (however members will still be able to switch to this group).
.PP

\fBgpasswd\fR
called by a group administrator with group name only prompts for the group password. If password is set the members can still
\fBnewgrp\fR(1)
without a password, non\-members must supply the password.
.SH "FILES"
.TP 3n
\fI/etc/group\fR
Group account information.
.TP 3n
\fI/etc/gshadow\fR
Secure group account information.
.SH "SEE ALSO"
.PP

\fBnewgrp\fR(1),
\fBgshadow\fR(5),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBgrpck\fR(8),
\fBgroup\fR(5).
