.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GROUPMOD" "8" "11/05/2005" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
groupmod \- modify a group
.SH "SYNOPSIS"
.HP 9
\fBgroupmod\fR [\-g\ \fIgid\fR\ [\-o\ ]] [\-n\ \fInew_group_name\fR] \fIgroup\fR
.SH "DESCRIPTION"
.PP
The
\fBgroupmod\fR
command modifies the system account files to reflect the changes that are specified on the command line.
.SH "OPTIONS"
.PP
The options which apply to the
\fBgroupmod\fR
command are:
.TP
\fB\-g\fR \fIgid\fR
The numerical value of the group's ID. This value must be unique, unless the
\fB\-o\fR
option is used. The value must be non\-negative. Values between 0 and 999 are typically reserved for system groups. Any files which the old group ID is the file group ID must have the file group ID changed manually.
.TP
\fB\-n\fR \fInew_group_name\fR
The name of the group will be changed from
\fIgroup\fR
to
\fInew_group_name\fR.
.SH "FILES"
.TP
\fI/etc/group\fR
group account information
.TP
\fI/etc/gshadow\fR
secure group account information
.SH "EXIT VALUES"
.PP
The
\fBgroupmod\fR
command exits with the following values:
.TP
\fI0\fR
success
.TP
\fI2\fR
invalid command syntax
.TP
\fI3\fR
invalid argument to option
.TP
\fI4\fR
specified group doesn't exist
.TP
\fI6\fR
specified group doesn't exist
.TP
\fI9\fR
group name already in use
.TP
\fI10\fR
can't update group file
.SH "SEE ALSO"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8).
