.\"     Title: groupadd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/06/2006
.\"    Manual: System Management Commands
.\"    Source: System Management Commands
.\"
.TH "GROUPADD" "8" "06/06/2006" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
groupadd \- create a new group
.SH "SYNOPSIS"
.HP 9
\fBgroupadd\fR [\-g\ \fIGID\fR\ [\-o]] [\-f] [\-K\ \fIKEY\fR=\fIVALUE\fR] \fIgroup\fR
.SH "DESCRIPTION"
.PP
The
\fBgroupadd\fR
command creates a new group account using the values specified on the command line and the default values from the system. The new group will be entered into the system files as needed.
.SH "OPTIONS"
.PP
The options which apply to the
\fBgroupadd\fR
command are:
.TP 3n
\fB\-f\fR
This option causes to just exit with success status if the specified group already exists. With
\fB\-g\fR, if specified GID already exists, other (unique) GID is chosen (i.e.
\fB\-g\fR
is turned off).
.TP 3n
\fB\-g\fR \fIGID\fR
The numerical value of the group's ID. This value must be unique, unless the
\fB\-o\fR
option is used. The value must be non\-negative. The default is to use the smallest ID value greater than 999 and greater than every other group. Values between 0 and 999 are typically reserved for system accounts.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Display help message and exit.
.TP 3n
\fB\-K \fR\fB\fIKEY\fR\fR\fB=\fR\fB\fIVALUE\fR\fR
Overrides
\fI/etc/login.defs\fR
defaults (GID_MIN, GID_MAX and others). Multiple
\fB\-K\fR
options can be specified.
.sp
Example:
\fB\-K \fR\fIGID_MIN\fR=\fI100\fR
\fB \-K \fR\fIGID_MAX\fR=\fI499\fR
.sp
Note:
\fB\-K \fR
\fIGID_MIN\fR=\fI10\fR,\fIGID_MAX\fR=\fI499\fR
doesn't work yet.
.TP 3n
\fB\-o\fR
This option permits to add group with non\-unique GID.
.SH "FILES"
.TP 3n
\fI/etc/group\fR
Group account information.
.TP 3n
\fI/etc/gshadow\fR
Secure group account information.
.TP 3n
\fI/etc/login.defs\fR
Shadow password suite configuration.
.SH "CAVEATS"
.PP
Groupnames must begin with a lower case letter or an underscore, and only lower case letters, underscores, dashes, and dollar signs may follow. In regular expression terms: [a\-z_][a\-z0\-9_\-]*[$]
.PP
Groupnames may only be up to 16 characters long.
.PP
If the groupname already exists in an external group database such as NIS,
\fBgroupadd\fR
will deny the group creation request.
.PP
Groupnames may only be up to 16 characters long.
.SH "EXIT VALUES"
.PP
The
\fBgroupadd\fR
command exits with the following values:
.TP 3n
\fI0\fR
success
.TP 3n
\fI2\fR
invalid command syntax
.TP 3n
\fI3\fR
invalid argument to option
.TP 3n
\fI4\fR
GID not unique (when
\fB\-o\fR
not used)
.TP 3n
\fI9\fR
group name not unique
.TP 3n
\fI10\fR
can't update group file
.SH "SEE ALSO"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8).
