.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.0).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GROUPS" "1" "08/03/2005" "User Commands" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
groups \- display current group names
.SH "SYNOPSIS"
.HP 7
\fBgroups\fR [\fIuser\fR]
.SH "DESCRIPTION"
.PP
\fBgroups\fR 
displays the current group names or ID values. If the value does not have a corresponding entry in 
\fI/etc/group\fR, the value will be displayed as the numerical group value. The optional 
\fIuser\fR 
parameter will display the groups for the named 
\fIuser\fR.
.SH "NOTE"
.PP
Systems which do not support concurrent group sets will have the information from 
\fI/etc/group\fR 
reported. The user must use 
\fBnewgrp\fR 
or 
\fBsg\fR 
to change their current real and effective group ID.
.SH "FILES"
.TP
\fI/etc/group\fR
group account information
.SH "SEE ALSO"
.PP
\fBnewgrp\fR(1), 
\fBgetgid\fR(2), 
\fBgetgroups\fR(2), 
\fBgetuid\fR(2)
.SH "AUTHOR"
.PP
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
