.\"     Title: groups
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/06/2006
.\"    Manual: User Commands
.\"    Source: User Commands
.\"
.TH "GROUPS" "1" "06/06/2006" "User Commands" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
groups \- display current group names
.SH "SYNOPSIS"
.HP 7
\fBgroups\fR [\fIuser\fR]
.SH "DESCRIPTION"
.PP

\fBgroups\fR
displays the current group names or ID values. If the value does not have a corresponding entry in
\fI/etc/group\fR, the value will be displayed as the numerical group value. The optional
\fIuser\fR
parameter will display the groups for the named
\fIuser\fR.
.SH "NOTE"
.PP
Systems which do not support concurrent group sets will have the information from
\fI/etc/group\fR
reported. The user must use
\fBnewgrp\fR
or
\fBsg\fR
to change their current real and effective group ID.
.SH "FILES"
.TP 3n
\fI/etc/group\fR
Group account information.
.SH "SEE ALSO"
.PP

\fBnewgrp\fR(1),
\fBgetgid\fR(2),
\fBgetgroups\fR(2),
\fBgetuid\fR(2).
