.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GROUPDEL" "8" "09/20/2005" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
groupdel \- Delete a group
.SH "SYNOPSIS"
.HP 9
\fBgroupdel\fR \fIgroup\fR
.SH "DESCRIPTION"
.PP
The
\fBgroupdel\fR
command modifies the system account files, deleting all entries that refer to
\fIgroup\fR. The named group must exist.
.PP
You must manually check all file systems to insure that no files remain with the named group as the file group ID.
.SH "CAVEATS"
.PP
You may not remove the primary group of any existing user. You must remove the user before you remove the group.
.SH "FILES"
.TP
\fI/etc/group\fR
group account information
.TP
\fI/etc/gshadow\fR
secure group account information
.SH "EXIT VALUES"
.PP
The
\fBgroupdel\fR
command exits with the following values:
.TP
\fI0\fR
success
.TP
\fI2\fR
invalid command syntax
.TP
\fI8\fR
can't remove user's primary group
.TP
\fI10\fR
can't update group file
.SH "SEE ALSO"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupmod\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)
.SH "AUTHOR"
.PP
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
