.\"     Title: grpck
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/30/2006
.\"    Manual: System Management Commands
.\"    Source: System Management Commands
.\"
.TH "GRPCK" "8" "07/30/2006" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
grpck \- verify integrity of group files
.SH "SYNOPSIS"
.HP 6
\fBgrpck\fR [\-r] [\fIgroup\fR\ \fIshadow\fR]
.SH "DESCRIPTION"
.PP

\fBgrpck\fR
verifies the integrity of the system authentication information. All entries in the
\fI/etc/group\fR
and
\fI/etc/gshadow\fR
are checked to see that the entry has the proper format and valid data in each field. The user is prompted to delete entries that are improperly formatted or which have other uncorrectable errors.
.PP
Checks are made to verify that each entry has:
.TP 3n
\(bu
the correct number of fields
.TP 3n
\(bu
a unique group name
.TP 3n
\(bu
a valid list of members and administrators
.sp
.RE
.PP
The checks for correct number of fields and unique group name are fatal. If the entry has the wrong number of fields, the user will be prompted to delete the entire line. If the user does not answer affirmatively, all further checks are bypassed. An entry with a duplicated group name is prompted for deletion, but the remaining checks will still be made. All other errors are warnings and the user is encouraged to run the
\fBgroupmod\fR
command to correct the error.
.PP
The commands which operate on the
\fI/etc/group\fR
file are not able to alter corrupted or duplicated entries.
\fBgrpck\fR
should be used in those circumstances to remove the offending entry.
.SH "OPTIONS"
.PP
By default,
\fBgrpck\fR
operates on the files
\fI/etc/group\fR
and
\fI/etc/gshadow\fR. The user may select alternate files with the
\fIgroup\fR
and
\fIshadow\fR
parameters. Additionally, the user may execute the command in read\-only mode by specifying the
\fB\-r\fR
flag. This causes all questions regarding changes to be answered
\fIno\fR
without user intervention.
\fBgrpck\fR
can also sort entries in
\fI/etc/group\fR
and
\fI/etc/gshadow\fR
by GID. To run it in sort mode pass it
\fB\-s\fR
flag. No checks are performed then, it just sorts.
.SH "FILES"
.TP 3n
\fI/etc/group\fR
Group account information.
.TP 3n
\fI/etc/gshadow\fR
Secure group account information.
.TP 3n
\fI/etc/passwd\fR
User account information.
.SH "SEE ALSO"
.PP

\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBgroupmod\fR(8).
.SH "EXIT VALUES"
.PP
The
\fBgrpck\fR
command exits with the following values:
.TP 3n
\fI0\fR
success
.TP 3n
\fI1\fR
invalid command syntax
.TP 3n
\fI2\fR
one or more bad group entries
.TP 3n
\fI3\fR
can't open group files
.TP 3n
\fI4\fR
can't lock group files
.TP 3n
\fI5\fR
can't update group files

