.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "ID" "1" "09/30/2005" "User Commands" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
id \- Display current user and group ID names
.SH "SYNOPSIS"
.HP 3
\fBid\fR [\-a]
.SH "DESCRIPTION"
.PP
\fBid\fR
displays the current real and effective user and group ID names or values. If the value does not have a corresponding entry in
\fI/etc/passwd\fR
or
\fI/etc/group\fR, the value will be displayed without the corresponding name. The optional
\fB\-a\fR
flag will display the group set on systems which support multiple concurrent group membership.
.SH "FILES"
.TP
\fI/etc/group\fR
group account information
.TP
\fI/etc/passwd\fR
user account information
.SH "SEE ALSO"
.PP
\fBgetgid\fR(2),
\fBgetgroups\fR(2),
\fBgetuid\fR(2)
.SH "AUTHOR"
.PP
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
