.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "LOGOUTD" "8" "11/05/2005" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
logoutd \- Enforce login time restrictions
.SH "SYNOPSIS"
.HP 8
\fBlogoutd\fR
.SH "DESCRIPTION"
.PP
\fBlogoutd\fR
enforces the login time and port restrictions specified in
\fI/etc/porttime\fR.
\fBlogoutd\fR
should be started from
\fI/etc/rc\fR. The
\fI/var/run/utmp\fR
file is scanned periodically and each user name is checked to see if the named user is permitted on the named port at the current time. Any login session which is violating the restrictions in
\fI/etc/porttime\fR
is terminated.
.SH "FILES"
.TP
\fI/etc/porttime\fR
login and port permissions
.TP
\fI/var/run/utmp\fR
list of current login sessions
