.\"     Title: nologin
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/30/2006
.\"    Manual: System Management Commands
.\"    Source: System Management Commands
.\"
.TH "NOLOGIN" "8" "07/30/2006" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
nologin \- politely refuse a login
.SH "SYNOPSIS"
.HP 8
\fBnologin\fR
.SH "DESCRIPTION"
.PP

\fBnologin\fR
displays a message that an account is not available and exits non\-zero. It is intended as a replacement shell field for accounts that have been disabled.
.PP
To disable all logins, investigate
\fBnologin\fR(5).
.SH "SEE ALSO"
.PP

\fBlogin\fR(1),
\fBnologin\fR(5).
.SH "HYSTORY"
.PP
The
\fBnologin\fR
command appeared in BSD 4.4.
