.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "PASSWD" "5" "01/22/2006" "File Formats and Conversions" "File Formats and Conversions"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
passwd \- the password file
.SH "DESCRIPTION"
.PP
\fI/etc/passwd\fR
contains one line for each user account, with seven fields delimited by colons (\(lq:\(rq). These fields are:
.TP 3
\(bu
login name
.TP
\(bu
optional encrypted password
.TP
\(bu
numerical user ID
.TP
\(bu
numerical group ID
.TP
\(bu
user name or comment field
.TP
\(bu
user home directory
.TP
\(bu
optional user command interpreter
.PP
The encrypted password field may be blank, in which case no password is required to authenticate as the specified login name. However, some applications which read the
\fI/etc/passwd\fR
file may decide not to permit
\fIany\fR
access at all if the
\fIpassword\fR
field is blank. If the
\fIpassword\fR
field is a lower\-case
\(lqx\(rq, then the encrypted password is actually stored in the
\fBshadow\fR(5)
file instead; there
\fImust\fR
be a corresponding line in the
\fIshadow\fR
file, or else the user account is invalid. If the
\fIpassword\fR
field is any other string, then it will be treated as an encrypted password, as specified by
\fBcrypt\fR(3).
.PP
The comment field is used by various system utilities, such as
\fBfinger\fR(1).
.PP
The home directory field provides the name of the initial working directory. The
\fBlogin\fR
program uses this information to set the value of the
\fB$HOME\fR
environmental variable.
.PP
The command interpreter field provides the name of the user's command language interpreter, or the name of the initial program to execute. The
\fBlogin\fR
program uses this information to set the value of the
\fB$SHELL\fR
environmental variable. If this field is empty, it defaults to the value
\fI/bin/sh\fR.
.SH "FILES"
.TP
\fI/etc/passwd\fR
user account information
.TP
\fI/etc/shadow\fR
optional encrypted password file
.SH "SEE ALSO"
.PP
\fBgetent\fR(1),
\fBlogin\fR(1),
\fBpasswd\fR(1),
\fBsu\fR(1),
\fBcrypt\fR(3),
\fBgetpwnam\fR(3),
\fBshadow\fR(5),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBsulogin\fR(8).
