.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "PASSWD" "1" "12/03/2005" "User Commands" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
passwd \- change user password
.SH "SYNOPSIS"
.HP 7
\fBpasswd\fR [\-x\ \fImax\fR] [\-n\ \fImin\fR] [\-w\ \fIwarn\fR] [\-i\ \fIinact\fR] \fIlogin\fR
.HP 7
\fBpasswd\fR [\-l \-u \-d \-S \-e] \fIlogin\fR
.SH "DESCRIPTION"
.PP
\fBpasswd\fR
changes passwords for user accounts. A normal user may only change the password for his/her own account, the super user may change the password for any account.
\fBpasswd\fR
also changes account information, such as the full name of the user, user's login shell, or password expiry date and interval.
.SS "Password Changes"
.PP
The user is first prompted for his/her old password, if one is present. This password is then encrypted and compared against the stored password. The user has only one chance to enter the correct password. The super user is permitted to bypass this step so that forgotten passwords may be changed.
.PP
After the password has been entered, password aging information is checked to see if the user is permitted to change the password at this time. If not,
\fBpasswd\fR
refuses to change the password and exits.
.PP
The user is then prompted for a replacement password. This password is tested for complexity. As a general guideline, passwords should consist of 6 to 8 characters including one or more from each of following sets:
.TP 3
\(bu
lower case alphabetics
.TP
\(bu
digits 0 thru 9
.TP
\(bu
punctuation marks
.PP
Care must be taken not to include the system default erase or kill characters.
\fBpasswd\fR
will reject any password which is not suitably complex.
.PP
If the password is accepted,
\fBpasswd\fR
will prompt again and compare the second entry against the first. Both entries are required to match in order for the password to be changed.
.SS "Hints for user passwords"
.PP
The security of a password depends upon the strength of the encryption algorithm and the size of the key space. The
\fIUNIX\fR
System encryption method is based on the NBS DES algorithm and is very secure. The size of the key space depends upon the randomness of the password which is selected.
.PP
Compromises in password security normally result from careless password selection or handling. For this reason, you should not select a password which appears in a dictionary or which must be written down. The password should also not be a proper name, your license number, birth date, or street address. Any of these may be used as guesses to violate system security.
.PP
Your password must easily remembered so that you will not be forced to write it on a piece of paper. This can be accomplished by appending two small words together and separating each with a special character or digit. For example, Pass%word.
.PP
Other methods of construction involve selecting an easily remembered phrase from literature and selecting the first or last letter from each word. An example of this is:
.TP 3
\(bu
Ask not for whom the bell tolls
.TP
\(bu
which produces
.TP
\(bu
An4wtbt
.PP
You may be reasonably sure few crackers will have included this in their dictionaries. You should, however, select your own methods for constructing passwords and not rely exclusively on the methods given here.
.SH "OPTIONS"
.PP
The options which apply to the
\fBpasswd\fR
command are:
.TP
\fB\-a\fR, \fB\-\-all\fR
This option can be used only with
\fB\-S\fR
and causes show status for all users.
.TP
\fB\-d\fR, \fB\-\-delete\fR
Delete a user's password (make it empty). This is a quick way to disable a password for an account. It will set the named account passwordless.
.TP
\fB\-e\fR, \fB\-\-expire\fR
Immediately expire an account\(cqs password. This in effect can force a user to change his/her password at the user\(cqs next login.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help message and exit.
.TP
\fB\-i\fR, \fB\-\-inactive\fR \fIINACTIVE\fR
This option is used to disable an account after the password has been expired for a number of days. After a user account has had an expired password for
\fIINACTIVE\fR
days, the user may no longer sign on to the account.
.TP
\fB\-k\fR, \fB\-\-keep\-tokens\fR
Indicate change password should be performed only for expired authentication tokens (passwords). The user wishes to keep their non\-expired tokens as before.
.TP
\fB\-l\fR, \fB\-\-lock\fR
Lock the named account. This option disables an account by changing the password to a value which matches no possible encrypted value.
.TP
\fB\-n\fR, \fB\-\-mindays\fR \fIMIN_DAYS\fR
Set the minimum number of days between password changes. A value of zero for this field indicates that the user may change her password at any time.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Quiet mode.
.TP
\fB\-r\fR, \fB\-\-repository\fR \fIREPOSITORY\fR
change password in
\fIREPOSITORY\fR
repository
.TP
\fB\-S\fR, \fB\-\-status\fR
Display account status information. The status information consists of 7 fields. The first field is the user\(cqs login name. The second field indicates if the user account is locked (L), has no password (NP), or has a usable password (P). The third field gives the date of the last password change. The next four fields are the minimum age, maximum age, warning period, and inactivity period for the password. These ages are expressed in days.
.TP
\fB\-u\fR, \fB\-\-unlock\fR
Unlock the named account. This option re\-enables an account by changing the password back to its previous value (to value before using
\fB\-l\fR
option).
.TP
\fB\-w\fR, \fB\-\-warndays\fR \fIWARN_DAYS\fR
Set the number of days of warning before a password change is required. The
\fIWARN_DAYS\fR
option is the number of days prior to the password expiring that a user will be warned her password is about to expire.
.TP
\fB\-x\fR, \fB\-\-maxdays\fR \fIMAX_DAYS\fR
Set the maximum number of days a password remains valid. After
\fIMAX_DAYS\fR, the password is required to be changed.
.SH "CAVEATS"
.PP
Not all options may be supported. Password complexity checking may vary from site to site. The user is urged to select a password as complex as he feels comfortable with. Users may not be able to change their password on a system if NIS is enabled and they are not logged into the NIS server.
.SH "FILES"
.TP
\fI/etc/passwd\fR
user account information
.TP
\fI/etc/shadow\fR
secure user account information
.SH "EXIT VALUES"
.PP
The
\fBpasswd\fR
command exits with the following values:
.TP
\fI0\fR
success
.TP
\fI1\fR
permission denied
.TP
\fI2\fR
invalid combination of options
.TP
\fI3\fR
unexpected failure, nothing done
.TP
\fI4\fR
unexpected failure, passwd file missing
.TP
\fI5\fR
passwd file busy, try again
.TP
\fI6\fR
invalid argument to option
.SH "SEE ALSO"
.PP
\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5).
