.\"     Title: porttime
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/20/2006
.\"    Manual: File Formats and Conversions
.\"    Source: File Formats and Conversions
.\"
.TH "PORTTIME" "5" "06/20/2006" "File Formats and Conversions" "File Formats and Conversions"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
porttime \- port access time file
.SH "DESCRIPTION"
.PP

\fIporttime\fR
contains a list of tty devices, user names, and permitted login times.
.PP
Each entry consists of three colon separated fields. The first field is a comma separated list of tty devices, or an asterisk to indicate that all tty devices are matched by this entry. The second field is a comma separated list of user names, or an asterisk to indicated that all user names are matched by this entry. The third field is a comma separated list of permitted access times.
.PP
Each access time entry consists of zero or more days of the week, abbreviated
\fISu\fR,
\fIMo\fR,
\fITu\fR,
\fIWe\fR,
\fITh\fR,
\fIFr\fR, and
\fISa\fR, followed by a pair of times separated by a hyphen. The abbreviation
\fIWk\fR
may be used to represent Monday thru Friday, and
\fIAl\fR
may be used to indicate every day. If no days are given,
\fIAl\fR
is assumed.
.SH "EXAMPLES"
.PP
The following entry allows access to user
\fBjfh\fR
on every port during weekdays from 9am to 5pm.
.PP
*:jfh:Wk0900\-1700
.PP
The following entries allow access only to the users
\fIroot\fR
and
\fIoper\fR
on
\fI/dev/console\fR
at any time. This illustrates how the
\fI/etc/porttime\fR
file is an ordered list of access times. Any other user would match the second entry which does not permit access at any time.
.sp
.RS 3n
.nf
      console:root,oper:Al0000\-2400
      console:*:
    
.fi
.RE
.PP
The following entry allows access for the user
\fIgames\fR
on any port during non\-working hours.
.PP
*:games:Wk1700\-0900,SaSu0000\-2400
.SH "FILES"
.TP 3n
\fI/etc/porttime\fR
File containing port access.
.SH "SEE ALSO"
.PP

\fBlogin\fR(1).
