.\"$Id: pwconv.8,v 1.9 2001/01/25 10:43:51 kloczek Exp $
.TH PWCONV 8 "26 Sep 1997"
.SH NAME
pwconv, pwunconv, grpconv, grpunconv \- convert to and from shadow passwords and groups.
.SH SYNOPSIS
.B pwconv
.br
.B pwunconv
.br
.B grpconv
.br
.B grpunconv
.SH DESCRIPTION
These four programs all operate on the normal and shadow password and
group files:
.IR /etc/passwd ", " /etc/group ", " /etc/shadow ", and " /etc/gshadow .

.B pwconv
.RI "creates " shadow " from " passwd " and an optionally existing " shadow .
.B pwunconv
.RI "creates " passwd " from " passwd " and " shadow " and then removes " shadow .
.B grpconv
.RI "creates " gshadow " from " group " and an optionally existing " gshadow .
.B grpunconv
.RI "creates " group " from " group " and " gshadow " and then removes " gshadow .

Each program acquires the necessary locks before conversion.

.BR pwconv " and " grpconv
are similiar.  First, entries in the shadowed file which don't exist
in the main file are removed.  Then, shadowed entries which don't have
`x' as the password in the main file are updated.  Any missing
shadowed entries are added.  Finally, passwords in the main file are
replaced with `x'.  These programs can be used for initial conversion
as well to update the shadowed file if the main file is edited by
hand.

.B pwconv
will use the values of
.BR PASS_MIN_DAYS ", " PASS_MAX_DAYS ", and " PASS_WARN_AGE
from
.I /etc/login.defs
when adding new entries to
.IR /etc/shadow .

.RB "Likewise, " pwunconv " and " grpunconv
are similiar.  Passwords in the main file are updated from the
shadowed file.  Entries which exist in the main file but not in the
shadowed file are left alone.  Finally, the shadowed file is removed.

Some password aging information is lost by
.BR pwunconv .
It will convert what it can.
.SH "BUGS"
Errors in the password or group files (such as invalid or duplicate
entries) may cause these programs to loop forever or fail in other
strange ways.  Please run \fBpwck\fR and \fBgrpck\fR to correct any
such errors before converting to or from shadow passwords or groups.
.SH "SEE ALSO"
.BR login.defs (5),
.BR pwck (8),
.BR grpck (8),
.BR shadowconfig (8)
