.\"$Id: shadowconfig.8,v 1.6 2003/05/01 18:17:39 kloczek Exp $
.TH SHADOWCONFIG 8 "19 Apr 1997" "Debian GNU/Linux"
.SH NAME
shadowconfig \- toggle shadow passwords on and off
.SH SYNOPSIS
.B "shadowconfig"
.IR on " | " off
.SH DESCRIPTION
.PP

\fBshadowconfig on\fR will turn shadow passwords on; \fBshadowconfig off\fR
will turn shadow passwords off. \fBshadowconfig\fR will print an error
message and exit with a nonzero code if it finds anything awry. If that
happens, you should correct the error and run it again. Turning shadow
passwords on when they are already on, or off when they are already off, is
harmless.
.P
Read \fI/usr/share/doc/passwd/README.debian.gz\fR for a brief introduction
to shadow passwords and related features.
.P
Note that turning shadow passwords off and on again will lose all password
aging information.
