.\"     Title: su
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/30/2006
.\"    Manual: User Commands
.\"    Source: User Commands
.\"
.TH "SU" "1" "07/30/2006" "User Commands" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
su \- change user ID or become super\-user
.SH "SYNOPSIS"
.HP 3
\fBsu\fR [\fIoptions\fR] [\fILOGIN\fR]
.SH "DESCRIPTION"
.PP

\fBsu\fR
is used to become another user during a login session. Invoked without a
\fBusername\fR,
\fBsu\fR
defaults to becoming the super user. The optional argument
\fB\-\fR
may be used to provide an environment similar to what the user would expect had the user logged in directly.
.PP
Additional arguments may be provided after the username, in which case they are supplied to the user's login shell. In particular, an argument of
\fB\-c\fR
will cause the next argument to be treated as a command by most command interpreters. The command will be executed by the shell specified in
\fI/etc/passwd\fR
for the target user.
.PP
You can use the
\fB\-\-\fR
argument to separate
\fBsu\fR
options from the arguments supplied to the shell.
.PP
The user will be prompted for a password, if appropriate. Invalid passwords will produce an error message. All attempts, both valid and invalid, are logged to detect abuse of the system.
.PP
The current environment is passed to the new shell. The value of
\fB$PATH\fR
is reset to
\fI/bin:/usr/bin\fR
for normal users, or
\fI/sbin:/bin:/usr/sbin:/usr/bin\fR
for the super user. This may be changed with the
\fIENV_PATH\fR
and
\fIENV_SUPATH\fR
definitions in
\fI/etc/login.defs\fR.
.PP
A subsystem login is indicated by the presence of a "*" as the first character of the login shell. The given home directory will be used as the root of a new file system which the user is actually logged into.
.SH "OPTIONS"
.PP
The options which apply to the
\fBsu\fR
command are:
.TP 3n
\fB\-c\fR, \fB\-\-command\fR \fISHELL\fR
Specify a command that will be invoked by the shell using its
\fB\-c\fR.
.TP 3n
\fB\-\fR, \fB\-l\fR, \fB\-\-login\fR
Provide an environment similar to what the user would expect had the user logged in directly.
.sp
When
\fB\-\fR
is used, it must be specified as the last
\fBsu\fR
option. The other forms (\fB\-l\fR
and
\fB\-\-login\fR) do not have this restriction.
.TP 3n
\fB\-s\fR, \fB\-\-shell\fR \fISHELL\fR
The shell that will be invoked.
.sp
The invoked shell is choosen among (higest priority first):
.RS 3n
.TP 3n
\(bu
The shell specified with \-\-shell
.TP 3n
\(bu
If
\fB\-\-preserve\-environment\fR
is used, the shell specified by the
\fB$SHELL\fR
environment variable.
.TP 3n
\(bu
The shell indicated in the
\fI/etc/passwd\fR
entry for the target user.
.TP 3n
\(bu

\fI/bin/sh\fR
if a shell could not be found by any above method.
.RE
.IP "" 3n
.sp
If the target user has a restricted shell (i.e. the shell field of this user's entry in
\fI/etc/passwd\fR
is not specified in
\fI/etc/shell\fR), then the
\fB\-\-shell\fR
option or the
\fB$SHELL\fR
environment variable won't be taken into account unless
\fBsu\fR
is called by the root.
.TP 3n
\fB\-m\fR, \fB\-p\fR, \fB\-\-preserve\-environment\fR
Preserve the current environment.
.sp
If the target user has a restricted shell, this option has no effect (unless
\fBsu\fR
is called by root).
.SH "CAVEATS"
.PP
This version of
\fBsu\fR
has many compilation options, only some of which may be in use at any particular site.
.SH "FILES"
.TP 3n
\fI/etc/passwd\fR
User account information.
.TP 3n
\fI/etc/shadow\fR
Secure user account information.
.SH "SEE ALSO"
.PP
\fBlogin\fR(1),
\fBlogin.defs\fR(5),
\fBsh\fR(1)
