.\"     Title: sulogin
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: System Management Commands
.\"    Source: System Management Commands
.\"
.TH "SULOGIN" "8" "06/24/2006" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sulogin \- Single\-user login
.SH "SYNTAX"
.PP
\fBsulogin\fR
[\fItty\-device\fR]
.SH "DESCRIPTION"
.PP

\fBsulogin\fR
is invoked by
\fBinit\fR
prior to allowing the user access to the system when in single user mode. This feature may only be available on certain systems where
\fBinit\fR
has been modified accordingly, or where the
\fI/etc/inittab\fR
has an entry for a single user login.
.PP
The user is prompted
.PP
Type control\-d to proceed with normal startup,
(or give root password for system maintenance):
.PP
Input and output will be performed with the standard file descriptors unless the optional device name argument is provided.
.PP
If the user enters the correct root password, a login session is initiated. When
\fIEOF\fR
is pressed instead, the system enters multi\-user mode.
.PP
After the user exits the single\-user shell, or presses
\fIEOF\fR, the system begins the initialization process required to enter multi\-user mode.
.SH "CAVEATS"
.PP
This command can only be used if
\fBinit\fR
has been modified to call
\fBsulogin\fR
instead of
\fI/bin/sh\fR, or if the user has set the
\fIinittab\fR
to support a single user login. For example, the line:
.PP
co:s:respawn:/etc/sulogin /dev/console
.PP
should execute the sulogin command in single user mode.
.PP
As complete an environment as possible is created. However, various devices may be unmounted or uninitialized and many of the user commands may be unavailable or nonfunctional as a result.
.SH "FILES"
.TP 3n
\fI/etc/passwd\fR
User account information.
.TP 3n
\fI/etc/shadow\fR
Secure user account information.
.SH "SEE ALSO"
.PP

\fBlogin\fR(1),
\fBsh\fR(1),
\fBinit\fR(8).
