.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: useradd.8,v 1.6 1999/03/07 19:14:47 marekm Exp $
.\"
.TH USERADD 8
.SH NAME
useradd \- Create a new user or update default new user information
.SH SYNOPSIS
.TP 8
.B useradd
.\" .RB [ -A
.\" .RI { method | \fBDEFAULT\fR "},... ]"
.RB [ -c
.IR comment ]
.RB [ -d
.IR home_dir ]
.br
.RB [ -e
.IR expire_date ]
.RB [ -f
.IR inactive_time ]
.br
.RB [ -g
.IR initial_group ]
.RB [ -G
.IR group [,...]]
.br
.RB [ -m " [" -k
.IR skeleton_dir ]]
.RB [ -p
.IR passwd ]
.br
.RB [ -s
.IR shell ]
.RB [ -u
.IR uid " ["
.BR -o ]]
.I login
.TP 8
.B useradd
\fB-D\fR
[\fB-g\fI default_group\fR]
[\fB-b\fI default_home\fR]
.br
[\fB-f\fI default_inactive\fR]
[\fB-e\fI default_expire_date\fR]
.br
[\fB-s\fI default_shell\fR]
.SH DESCRIPTION
.SS Creating New Users
When invoked without the \fB-D\fR option, the \fBuseradd\fR command
creates a new user account using the values specified on the
command line and the default values from the system.
The new user account will be entered into the system files as needed,
the home directory will be created, and initial files copied, depending
on the command line options.
The options which apply to the \fBuseradd\fR command are
.\" .IP "\fB-A {\fImethod\fR|\fBDEFAULT\fR},..."
.\" The value of the user's authentication method.
.\" The authentication method is the name of a program which is responsible
.\" for validating the user's identity.
.\" The string \fBDEFAULT\fR may be used to change the user's authentication
.\" method to the standard system password method.
.\" This is a comma-separated list of program names.
.\" It may include \fBDEFAULT\fR exactly once.
.IP "\fB-c \fIcomment\fR"
The new user's password file comment field.
.IP "\fB-d \fIhome_dir\fR"
The new user will be created using \fIhome_dir\fR as the value for
the user's login directory.
The default is to append the \fIlogin\fR name to \fIdefault_home\fR
and use that as the login directory name.
.IP "\fB-e \fIexpire_date\fR"
The date on which the user account will be disabled.
The date is specified in the format \fIYYYY-MM-DD\fR.
.IP "\fB-f \fIinactive_days\fR"
The number of days after a password expires until the account
is permanently disabled.
A value of 0 disables the account as soon as the password has
expired, and a value of -1 disables the feature.
The default value is -1.
.IP "\fB-g \fIinitial_group\fR"
The group name or number of the user's initial login group.
The group name must exist.  A group number must refer to an
already existing group.
The default group number is 1.
.IP "\fB-G \fIgroup,[...]\fR"
A list of supplementary groups which the user is also a member
of.
Each group is separated from the next by a comma, with no
intervening whitespace.
The groups are subject to the same restrictions as the group
given with the \fB-g\fR option.
The default is for the user to belong only to the initial group.
.IP \fB-m\fR
The user's home directory will be created if it does not exist.
The files contained in \fIskeleton_dir\fR will be copied to the
home directory if the \fB-k\fR option is used, otherwise the
files contained in \fI/etc/skel\fR will be used instead.
Any directories contained in \fIskeleton_dir\fR or \fI/etc/skel\fR
will be created in the user's home directory as well.
The \fB-k\fR option is only valid in conjunction with the \fB-m\fR
option.
The default is to not create the directory and to not copy any
files.
.IP "\fB-p \fIpasswd\fR"
The encrypted password, as returned by \fBcrypt\fR(3).
The default is to disable the account.
.IP "\fB-s \fIshell\fR"
The name of the user's login shell.
The default is to leave this field blank, which causes the system
to select the default login shell.
.IP "\fB-u \fIuid\fR"
The numerical value of the user's ID.
This value must be unique, unless the \fI-o\fR option is used.
The value must be non-negative.
The default is to use the smallest ID value greater than 99 and
greater than every other user.
Values between 0 and 99 are typically reserved for system accounts.
.SS Changing the default values
When invoked with the \fB-D\fR option, \fBuseradd\fR will either
display the current default values, or update the default values
from the command line.
The valid options are
.IP "\fB-b \fIdefault_home\fR"
The initial path prefix for a new user's home directory.
The user's name will be affixed to the end of \fIdefault_home\fR
to create the new directory name if the \fB-d\fI option is not
used when creating a new account.
.IP "\fB-e \fIdefault_expire_date\fR"
The date on which the user account is disabled.
.IP "\fB-f \fIdefault_inactive\fR"
The number of days after a password has expired before the
account will be disabled.
.IP "\fB-g \fIdefault_group\fR"
The group name or ID for a new user's initial group.
The named group must exist, and a numerical group ID must have
an existing entry .
.IP "\fB-s \fIdefault_shell\fR"
The name of the new user's login shell.
The named program will be used for all future new user accounts.
.PP
If no options are specified, \fBuseradd\fR displays the current
default values.
.SH NOTES
The system administrator is responsible for placing the default
user files in the \fI/etc/skel\fR directory.
.SH CAVEATS
You may not add a user to an NIS group.
This must be performed on the NIS server.
.SH FILES
/etc/passwd \- user account information
.br
/etc/shadow \- secure user account information
.br
/etc/group \- group information
.br
/etc/default/useradd \- default information
.br
/etc/skel \- directory containing default files
.SH SEE ALSO
.BR chfn (1),
.BR chsh (1),
.BR crypt (3),
.BR groupadd (8),
.BR groupdel (8),
.BR groupmod (8),
.BR passwd (1),
.BR userdel (8),
.BR usermod (8)
.SH AUTHOR
Julianne Frances Haugh (jfh@bga.com)
