.\"     Title: vipw
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/06/2006
.\"    Manual: System Management Commands
.\"    Source: System Management Commands
.\"
.TH "VIPW" "8" "06/06/2006" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
vipw, vigr \- edit the password, group, shadow\-password or shadow\-group file
.SH "SYNOPSIS"
.HP 5
\fBvipw\fR [options]
.HP 5
\fBvigr\fR [options]
.SH "DESCRIPTION"
.PP

\fBvipw\fR
and
\fBvigr\fR
will edit the files
\fI/etc/passwd\fR
and
\fI/etc/group\fR, respectively. With the
\fB\-s\fR
flag, they will edit the shadow versions of those files,
\fI/etc/shadow\fR
and
\fI/etc/gshadow\fR, respectively. The programs will set the appropriate locks to prevent file corruption. When looking for an editor, the programs will first try the environment variable
\fB$VISUAL\fR, then the environment variable
\fB$EDITOR\fR, and finally the default editor,
\fBvi\fR(1).
.SH "OPTIONS"
.PP
The options which apply to the
\fBvipw\fR
and
\fBvigr\fR
commands are:
.TP 3n
\fB\-g\fR, \fB\-\-group\fR
Edit group database.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Display help message and exit.
.TP 3n
\fB\-p\fR, \fB\-\-passwd\fR
Edit passwd database.
.TP 3n
\fB\-q\fR, \fB\-\-quiet\fR
Quiet mode.
.TP 3n
\fB\-s\fR, \fB\-\-shadow\fR
Edit shadow or gshadow database.
.SH "FILES"
.TP 3n
\fI/etc/group\fR
Group account information.
.TP 3n
\fI/etc/gshadow\fR
Secure group account information.
.TP 3n
\fI/etc/passwd\fR
User account information.
.TP 3n
\fI/etc/shadow\fR
Secure user account information.
.SH "SEE ALSO"
.PP

\fBvi\fR(1),
\fBgroup\fR(5),
\fBgshadow\fR(5)
\fBpasswd\fR(5),
\fBshadow\fR(5).
