.\" $Id: vipw.8,v 1.2 1997/12/14 20:07:22 marekm Exp $
.TH VIPW 8 "26 Sep 1997"
.SH NAME
vipw, vigr \- edit the password, group, shadow-password, or shadow-group file.
.SH SYNOPSIS
.BR vipw " [-s]"
.br
.BR vigr " [-s]"
.SH DESCRIPTION
.BR vipw " and " vigr
will edit the files
.IR /etc/passwd " and " /etc/group ", respectively."
With the
.B -s
flag, they will edit the shadow versions of those files,
.IR /etc/shadow " and " /etc/gshadow ", respectively.
The programs will set the appropriate locks to prevent file corruption.

When looking for an editor, the programs will first try the
environment variable
.BR VISUAL ,
then the environment variable
.BR EDITOR ,
and finally the default editor,
.BR vi .
.SH "SEE ALSO"
.BR passwd (5),
.BR group (5),
.BR shadow (5)
