.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: groupmod.8,v 1.1 2002/03/10 07:41:06 kloczek Exp $
.\"
.\" Traduzione in italiano a cura di Isabella Ruocco <isacher@nettaxi.com>
.\" luglio 1999
.\"
.TH GROUPMOD 8
.SH NOME
groupmod \- Modifica un gruppo
.SH SINTASSI
.B groupmod
[\fB-g\fI gid \fR[\fB-o\fR]]
[\fB-n\fI nome_gruppo \fR]
.I gruppo
.SH DESCRIZIONE
Il comando \fBgroupmod\fR modifica i file di account del sistema in modo
da riflettere i cambiamenti che sono specificati sulla linea di comando.
Le opzioni che si applicano al comando \fIgroupmod\fR sono
.IP "\fB-g \fIgid\fR"
Il valore numerico dell'identificatore (ID) del gruppo.
Questo valore deve essere univoco, a meno che non venga usata l'opzione
\fB-o\fR.
Il valore deve essere non-negativo.
Valori tra 0 e 99 sono tipicamente riservati per gruppi di sistema.
Occorre modificare manualmente l'ID di gruppo di tutti i file
il cui ID di gruppo è quello vecchio.
.IP "\fB-n \fInome_gruppo\fR"
Il nome del gruppo verrà modificato da \fIgruppo\fR a \fInome_gruppo\fR.
.SH FILE
/etc/group \- informazioni sui gruppi
.br
/etc/gshadow \- informazioni sicure sui gruppi
.SH VEDERE ANCHE
.BR chfn (1),
.BR chsh (1),
.BR useradd (8),
.BR userdel (8),
.BR usermod (8),
.BR passwd (1),
.BR groupadd (8),
.BR groupdel (8)
.SH AUTORE
Julianne Frances Haugh (jfh@tab.com)
