.\" $Id: groups.1,v 1.1 2002/03/10 07:41:06 kloczek Exp $
.\" Italian manpages for GNU sh-utils-1.16.
.\" Copyright (C) 1997 Free Software Foundation, Inc.
.\" Giovanni Bortolozzo <borto@dei.unipd.it>, 1997.
.\"
.\" Traduzione di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Maggio 1997
.\"
.\"" for hilit19
.TH GROUPS 1 "GNU Shell Utilities" "FSF"
.SH NOME
groups \- mostra i gruppi in cui è presente l'utente
.SH SINTASSI
.B groups
[nomeutente...]
.br
.B groups
{\-\-help,\-\-version}
.SH DESCRIZIONE
Questa documentazione non è mantenuta da lungo tempo e potrebbe essere
inaccurata o incompleta. La documentazione in Texinfo è ora la fonte
autorevole. 
.PP
Questa pagina di manuale documenta la versione GNU di
.BR groups .
.B groups
mostra i nomi dei gruppi supplementari in cui è presente ogni 
.I nomeutente
dato, o del processo corrente se non ne è dato nessuno. Se sono dati
dei nomi di utenti, il nome di ogni utente è stampato prima della
lista dei gruppi dell'utente.
.PP
La lista dei gruppi è equivalente all'output del comando `id \-Gn'.
.SS OPZIONI
Quando GNU
.B groups
è chiamato con un solo argomento sono riconosciute le seguenti
opzioni: 
.TP
.I "\-\-help"
Mostra nello standard output un messaggio d'aiuto ed esce con successo.
.TP
.I "\-\-version"
Mostra nello standard output informazioni sulla versione ed esce con
successo.

