.\" Copyright 1992, Phillip Street and Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)lastlog.8	3.3	08:24:58	29 Sep 1993 (National Guard Release)
.\"	$Id: lastlog.8,v 1.5 2003/04/28 06:38:54 kloczek Exp $
.\"
.\" Traduzione in italiano a cura di Isabella Ruocco <isacher@nettaxi.com>
.\" luglio 1999
.\"
.TH LASTLOG 8
.SH NOME
lastlog \- esamina il file lastlog 
.SH SINTASSI
.TP 8
\fBlastlog\fR [(\fB-u\fR|\fB--user\fR) \fIutente\fR]
[(\fB-t\fR|\fB--time\fR) \fIdays\fR] [(\fB-h\fR|\fB--help\fR)]
.SH DESCRIZIONE
\fBlastlog\fR formatta e stampa il contenuto dell'ultimo log di login,
\fI/var/log/lastlog\fR.  Verranno stampati \fBnome-login\fR, \fBporta\fR,
e \fBdata_ultima_connessione\fR.
Il comportamento predefinito (senza opzioni) è quello di stampare le voci di
lastlog in ordine di UID.
Digitando l'opzione \fB-u \fInome-login\fR verrà stampato solo il
record di \fInome-login\fR.
Digitando \fB-t \fIgiorni\fR verranno stampate solo le ultime connessioni
più recenti di \fIgiorni\fR.
L'opzione \fB-t\fR sovrascrive l'uso di \fB-u\fR.
.PP
Se l'utente non si è mai connesso verrà mostrato, al posto della porta e della
data, il messaggio \fB"**Never logged in**"\fR (**Mai connesso**).
.SH FILE
\fI/var/log/lastlog\fR \- file di connessione lastlog 
.SH CAVEAT
Grandi lacune nei numeri di uid provocheranno una prolungata esecuzione del
programma lastlog senza alcun output sullo schermo (i.e. se mmdf=800 e l'ultimo
uid=170, sembrerà che il programma rimanga appeso mentre elabora gli uid 171-799).
.SH AUTORI
Julianne Frances Haugh (jfh@tab.com)
.br
Phillip Street
