.\" $Id: newgrp.1,v 1.1 2002/03/10 07:41:06 kloczek Exp $
.\" Original author unknown.  This man page is in the public domain.
.\" Modified Sat Oct  9 17:46:48 1993 by faith@cs.unc.edu
.\"
.\" Traduzione in italiano di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Agosto 1996
.\"
.\" " for hilit19
.TH NEWGRP 1 "9 ottobre 1993" "Linux 1.2" "Linux Programmer's Manual"
.SH NOME
newgrp \- logga in un nuovo gruppo
.SH SINTASSI
.BI "newgrp [ " gruppo " ]"
.SH DESCRIZIONE
.B Newgrp
cambia l'identificatico del gruppo (GID) del suo chiamante, in modo analogo a 
.BR login (1).
La stessa persona rimane loggata, e non è cambiata la directory corrente,
ma i calcoli sui permessi d'accesso ai file sono fatti rispetto a nuovo 
group ID.
.LP
Se non è specificato alcun gruppo, il GID è posto pari al GID di login.
.LP
.SH FILE
.I /etc/group
.br
.I /etc/passwd

.SH "VEDERE ANCHE"
.BR login "(1), " group (5)

.SH AUTORE
All'inizio era Michael Haardt. Attualmente mantenuto da
Peter Orbaek (poe@daimi.aau.dk).
