.\"$Id$
.\" Copyright 1989 - 1990, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Modified Tue 18 Sep 2002 by NAKNAO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH SHADOW 5
.SH 名前
shadow \- 暗号化されたパスワードファイル
.SH 説明
.I shadow
にはユーザのアカウントに対する暗号化されたパスワード情報、
およびオプションとしてパスワードの有効期限の情報が記されている。
含まれている内容は
.IP "" .5i
ログイン名
.IP "" .5i
暗号化されたパスワード
.IP "" .5i
1970 年 1 月 1 日から、最後にパスワードが変更された日までの日数
.IP "" .5i
パスワードが変更可能となるまでの日数
.IP "" .5i
パスワードを変更しなくてはならなくなる日までの日数
.IP "" .5i
パスワード有効期限が来る前に、ユーザが警告を受ける日数
.IP "" .5i
パスワード有効期限が過ぎてからアカウントが使用不能になるまでの日数
.IP "" .5i
1970 年 1 月 1 日からアカウントが使用不能になる日までの日数
.IP "" .5i
予約フィールド
.PP
パスワードフィールドは必ず記入されていなくてはならない。
暗号化されたパスワードは、
a から z、A から Z のアルファベット、
0 から 9 までの数字、 \. と / の 64 文字のうちの、
13 文字以上 24 文字以下である。
この文字列がどのように解釈されるかの詳細は \fBcrypt\fR(3) を参照せよ。
.PP
最後にパスワードを変更した日時は
1970 年 1 月 1 日からの日数として記述される。
パスワードは十分な日数が経過してからでないと変更できず、
また最大日数が経過した後は必ず変更しなければならない。
変更可能となるまでに要する日数が有効期限よりも大きい場合は、
ユーザがパスワードを変更することは出来ない。
.PP
パスワードの有効期限が過ぎてから、
指定日数のうちにパスワードを変更しなかった場合は、
そのアカウントは無効になり、使えなくなる。
また、アカウントを指定した期日に、
(その他のパスワード有効期限情報にはよらず)
使用不能とすることもできる。
.PP
この情報は、\fI/etc/passwd\fR 中の
あらゆるパスワード情報・有効期限情報よりも優先される。
.PP
パスワードの安全性を保つためには、
このファイルを一般ユーザが読めるようにしてはならない。
.SH ファイル
\fI/etc/passwd\fR \- ユーザアカウント情報
.br
\fI/etc/shadow\fR \- 暗号化されたユーザパスワード
.SH 関連項目
.BR chage (1),
.BR login (1),
.BR passwd (1),
.BR su (1),
.BR passwd (5),
.BR pwconv (8),
.BR pwunconv (8),
.BR sulogin (8)
.SH 著者
Julianne Frances Haugh (julie78787@gmail.com)
