.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "CHAGE" "1" "12/07/2005" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
chage \- Modifier les informations de validité d'un mot de passe
.SH "SYNOPSIS"
.HP 6
\fBchage\fR [\fIoptions\fR] \fIutilisateur\fR
.SH "DESCRIPTION"
.PP
\fBChage\fR
modifie le nombre de jours entre les changements de mot de passe et la date du dernier changement. Ces informations sont utilisées par le système pour déterminer si un utilisateur doit changer son mot de passe.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBchage\fR
sont\ :
.TP
\fB\-d\fR, \fB\-\-lastday\fR \fIDERNIER_JOUR\fR
Fixe le numéro du jour depuis le 1er janvier 1970, où le mot de passe a été changé la dernière fois. La date peut aussi être exprimée dans le format AAAA\-MM\-JJ (ou le format utilisé plus communément dans votre région).
.TP
\fB\-E\fR, \fB\-\-expiredate\fR \fIDATE_FIN_VALIDITÉ\fR
Fixe la date à partir de laquelle le compte de l'utilisateur ne sera plus accessible. La date est le numéro du jour depuis le 1er janvier 1970 après lequel le compte sera bloqué. La date peut aussi être exprimée dans un format AAAA\-MM\-JJ (ou le format plus communément utilisé dans votre région). Un utilisateur dont le compte est bloqué doit contacter l'administrateur système pour pouvoir utiliser le système à nouveau.
.sp
Une valeur de
\fI\-1\fR
pour
\fIDATE_FIN_VALIDITÉ\fR
aurra pour effet de supprimer la date de fin de validité.
.TP
\fB\-h\fR, \fB\-\-help\fR
Affiche un message d'aide et quitte.
.TP
\fB\-I\fR, \fB\-\-inactive\fR \fIDURÉE_INACTIVITÉ\fR
Fixe le nombre de jours d'inactivité, après qu'un mot de passe ait dépassé la date de fin de validité, avant que le compte ne soit bloqué. La valeur
\fIDURÉE_INACTIVITÉ\fR
est le nombre de jours d'inactivité. Un utilisateur dont le compte est bloqué doit contacter l'administrateur système avant de pouvoir utiliser le système à nouveau.
.sp
Une valeur de
\fI\-1\fR
pour
\fIDURÉE_INACTIVITÉ\fR
supprime la durée d'inactivité pour un compte.
.TP
\fB\-l\fR, \fB\-\-list\fR
Affiche les informations sur les âges des comptes.
.TP
\fB\-m\fR, \fB\-\-mindays\fR \fIJOURS_MIN\fR
Fixe le nombre minimum de jours entre chaque changement de mot de passe. Une valeur de zéro pour ce champ indique que l'utilisateur peut changer son mot de passe n'importe quand.
.TP
\fB\-M\fR, \fB\-\-maxdays\fR \fIJOURS_MAX\fR
Fixe le nombre maximum de jours pendant lesquels un mot de passe est valable. Quand
\fIJOURS_MAX\fR
plus
\fIDERNIER_JOUR\fR
est inférieur à la date courante, l'utilisateur est obligé de changer son mot de passe avant de pouvoir utiliser son compte. Cet événement peut être déclenché plus tôt grâce à l'option
\fB\-W\fR
qui prévient l'utilisateur à l'avance avec un message d'alerte.
.sp
Une valeur de
\fI\-1\fR
pour
\fIJOURS_MAX\fR
supprime cette fonctionnalité.
.TP
\fB\-W\fR, \fB\-\-warndays\fR \fIDURÉE_AVERTISSEMENT\fR
Fixe le nombre de jours d'avertissement avant que le changement de mot de passe ne soit obligatoire. La valeur
\fIDURÉE_AVERTISSEMENT\fR
est le nombre de jours précédant la fin de validité pendant lesquels un utilisateur sera prévenu que son mot de passe est sur le point d'arriver en fin de validité.
.PP
Si aucune de ces options n'est donnée,
\fBchage\fR
utilise un mode interactif, demandant confirmation à l'utilisateur pour les valeurs de tous les champs. Entrez la nouvelle valeur pour changer la valeur du champ, ou laissez la ligne vide pour conserver la valeur actuelle. La valeur actuelle est affichée entre crochets.
.SH "NOTE"
.PP
Le programme
\fBchage\fR
nécessite l'utilisation d'un fichier de mots de passe cachés (\(Fo\ shadow password file\ \(Fc). Ces fonctionnalités ne sont pas disponibles quand les mots de passe sont enregistrés dans un fichier de mots de passe simple (\(Fo\ passwd file\ \(Fc).
.PP
La commande
\fBchage\fR
est réservée à l'utilisateur root, sauf pour l'option
\fB\-l\fR, qui peut être utilisée par un utilisateur non privilégié pour savoir quand son mot de passe ou son compte arrivera en fin de validité.
.SH "FICHIERS"
.TP
\fI/etc/passwd\fR
informations sur les comptes des utilisateurs
.TP
\fI/etc/shadow\fR
informations sécurisées sur les comptes utilisateurs
.SH "VALEUR DE RETOUR"
.PP
La commande
\fBchage\fR
retourne les valeurs suivantes en quittant\ :
.TP
\fI0\fR
succès
.TP
\fI1\fR
permission refusée
.TP
\fI2\fR
erreur de syntaxe
.TP
\fI15\fR
impossible de trouver le fichier des mots de passe cachés
.SH "VOIR AUSSI"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5).
