.\"     Title: chfn
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes utilisateur
.\"    Source: Commandes utilisateur
.\"
.TH "CHFN" "1" "30/07/2006" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
chfn \- Modifier le nom complet et les informations associées à un utilisateur
.SH "SYNOPSIS"
.HP 5
\fBchfn\fR [\-f\ \fInom_complet\fR] [\-r\ \fIno_bureau\fR] [\-w\ \fItel_bureau\fR] [\-h\ \fItel_perso\fR] [\-o\ \fIautre\fR] [\fIutilisateur\fR]
.SH "DESCRIPTION"
.PP
\fBChfn\fR
modifie le nom complet d'un utilisateur, son numéro de bureau, son numéro de téléphone professionnel, et son numéro de téléphone personnel. Ces informations sont généralement affichées par
\fBfinger\fR(1)
ou d'autres programmes similaires. Un utilisateur normal ne peut modifier que les informations associées à son propre compte, avec les restrictions spécifiées dans
\fI/etc/login.defs\fR. (Par défaut, les utilisateurs ne peuvent pas modifier leur nom complet). Le superutilisateur peut modifier n'importe quel champ pour n'importe quel compte. De plus, seul le superutilisateur peut utiliser l'option
\fB\-o\fR
pour modifier les parties non spécifiées du champ GECOS.
.PP
La seule restriction pour le contenu des champs est qu'ils ne doivent contenir aucun caractère de contrôle, ni aucune virgule, deux\-points ou signe égal. Le champ
\fIautre\fR
n'a pas cette limitation et peut être utilisé pour enregistrer des informations sur le compte pour d'autres applications.
.PP
Si aucune option n'est sélectionnée,
\fBchfn\fR
opère de manière interactive, demandant à l'utilisateur d'entrer les valeurs actuelles de chacun des champs. Entrer une nouvelle valeur pour la modifier, ou de laisser une ligne blanche pour conserver la valeur actuelle. La valeur actuelle est indiquée entre crochets (\fB[ ]\fR). En l'absence d'option,
\fBchfn\fR
opère sur l'utilisateur actuel.
.SH "FICHIERS"
.TP 3n
\fI/etc/login.defs\fR
Configuration de la suite des mots de passe cachés \(Fo\ shadow password\ \(Fc.
.TP 3n
\fI/etc/passwd\fR
Informations sur les comptes des utilisateurs.
.SH "VOIR AUSSI"
.PP
\fBchsh\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5).
