.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "CHPASSWD" "8" "12/07/2005" "Commandes pour la gestion du système" "Commandes pour la gestion du s"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
chpasswd \- Mettre à jour des mots de passe par lot
.SH "SYNOPSIS"
.HP 9
\fBchpasswd\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
\fBChpasswd\fR
lit une liste de paires de noms d'utilisateurs et de mots de passe depuis l'entrée standard et utilise ces informations pour mettre à jour un groupe d'utilisateurs existants. Chaque ligne est au format suivant\ :
.PP
\fInom_utilisateur\fR:\fImot_de_passe\fR
.PP
Par défaut, le mot de passe doit être fourni en clair. L'algorithme de chiffrement par défaut est le chiffrement DES. L'âge du mot de passe sera également mis à jour, s'il est présent.
.PP
Cette commande est destinée aux gros systèmes pour lesquels un nombre importants de comptes sont créés en une seule fois.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBchpasswd\fR
sont\ :
.TP
\fB\-e\fR, \fB\-\-encrypted\fR
Indique que les mots de passe fournis sont chiffrés.
.TP
\fB\-h\fR, \fB\-\-help\fR
Affiche un message d'aide et quitte.
.TP
\fB\-m\fR, \fB\-\-md5\fR
Permet d'utiliser le chiffrement MD5, plutôt que DES, lorsque les mots de passe fournis ne sont pas chiffrés.
.SH "AVERTISSEMENTS"
.PP
Veuillez veiller à éviter que le fichier utilisé par la commande
\fBchpasswd\fR
soit accessible en lecture s'il contient des mots de passe non chiffrés.
.SH "VOIR AUSSI"
.PP
\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBuseradd\fR(8).
