.\"     Title: chpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes de gestion du système
.\"    Source: Commandes de gestion du système
.\"
.TH "CHPASSWD" "8" "30/07/2006" "Commandes de gestion du systèm" "Commandes de gestion du systèm"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
chpasswd \- Mettre à jour des mots de passe par lot
.SH "SYNOPSIS"
.HP 9
\fBchpasswd\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
\fBChpasswd\fR
lit une liste de paires de noms d'utilisateurs et de mots de passe depuis l'entrée standard et utilise ces informations pour mettre à jour un groupe d'utilisateurs existants. Chaque ligne est au format suivant\ :
.PP
\fInom_utilisateur\fR:\fImot_de_passe\fR
.PP
Par défaut, le mot de passe doit être fourni en clair. L'algorithme de chiffrement par défaut est le chiffrement DES. L'âge du mot de passe sera également mis à jour, s'il est présent.
.PP
Cette commande est destinée aux gros systèmes pour lesquels un nombre importants de comptes sont créés en une seule fois.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBchpasswd\fR
sont\ :
.TP 3n
\fB\-e\fR, \fB\-\-encrypted\fR
Indique que les mots de passe fournis sont chiffrés.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Afficher un message d'aide et quitter.
.TP 3n
\fB\-m\fR, \fB\-\-md5\fR
Permettre d'utiliser le chiffrement MD5, plutôt que DES, lorsque les mots de passe fournis ne sont pas chiffrés.
.SH "AVERTISSEMENTS"
.PP
Pensez à fixer les permissions ou umask afin d'empêcher la lecture par les autres utilisateurs des fichiers non chiffrés.
.SH "VOIR AUSSI"
.PP
\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBuseradd\fR(8).
