.\"
.\"  chsh.1 -- change your login shell
.\"  (c) 1994 by salvatore valente <svalente@athena.mit.edu>
.\"
.\"  this program is free software.  you can redistribute it and
.\"  modify it under the terms of the gnu general public license.
.\"  there is no warranty.
.\"
.\"  $Author: kloczek $
.\"  $Revision: 1.2 $
.\"  $Date: 2004/08/04 13:02:24 $
.\"
.\" Traduction 22/04/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.TH CHSH 1 "22 Avril 1997" Linux "Manuel de l'utilisateur Linux"
.SH NOM
chsh \- Changer le shell appelé à la connexion.
.SH SYNOPSIS
.B chsh
[\ \-s\ shell\ ] [\ \-l\ ] [\ \-u\ ] [\ \-v\ ] [\ utilisateur\ ]
.SH DESCRIPTION
.B chsh
est invoqué pour changer le shell qui est appelé lors de la connexion de
l'utilisateur.
Si aucun shell n'est mentionné sur la ligne de commande,
.B chsh
va en réclamer un.
.SH SHELLS VALIDES
.B chsh
acceptera le nom complet (avec chemin d'accès) de tout fichier exécutable
sur le système. Néanmoins, il affichera un message d'avertissement si le
shell n'est pas mentionné dans le fichier
.IR /etc/shells .
.SH OPTIONS
.TP
.I "\-l, \-\-list-shells"
Afficher la liste des shells mentionnés dans
.I /etc/shells
puis quitter.
.TP
.I "\-s, \-\-shell"
Indiquer le shell de connexion désiré.
.TP
.I "\-u, \-\-help"
Afficher un message d'aide puis quitter.
.TP
.I "-v, \-\-version"
Afficher un numéro de version, puis quitter.
.SH "VOIR AUSSI"
.BR login (1),
.BR passwd (5),
.BR shells (5)
.SH AUTEURS
Salvatore Valente <svalente@mit.edu>

.SH TRADUCTION
Christophe Blaess, 1997.
