.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "FAILLOG" "5" "12/07/2005" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
faillog \- Journal des échecs de connexion
.SH "DESCRIPTION"
.PP
\fI/var/log/faillog\fR
maintient un compteur des échecs de connexion ainsi que les limites associées à chaque compte. Le fichier contient un nombre fixe d'enregistrements, indexés par un identifiant numérique. Chaque enregistrement comprend le nombre d'échecs de connexion depuis la dernière connexion réussie, le nombre maximal d'échecs avant que le compte ne soit désactivé, la ligne du dernier échec de connexion, et la date du dernier échec.
.PP
La structure du fichier est la suivante\ :
.sp
.nf
struct	faillog {
	short   fail_cnt;      /* compteur des échecs */
	short   fail_max;      /* nb max avant désactivation */
	char    fail_line[12]; /* ligne du dernier échec */
	time_t  fail_time;     /* date du dernier échec */
};
.fi
.SH "FICHIERS"
.TP
\fI/var/log/faillog\fR
journal des échecs de connexion
.SH "VOIR AUSSI"
.PP
\fBfaillog\fR(8)
