.\"     Title: faillog
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes de gestion du système
.\"    Source: Commandes de gestion du système
.\"
.TH "FAILLOG" "8" "30/07/2006" "Commandes de gestion du systèm" "Commandes de gestion du systèm"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
faillog \- Examiner le fichier faillog, et fixer les limites d'échecs de connexion
.SH "SYNOPSIS"
.HP 8
\fBfaillog\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
\fBFaillog\fR
affiche le contenu du journal des échecs de connexion (\fI/var/log/faillog\fR), et maintient le décompte et les limitations de ces échecs. Exécuter
\fBfaillog\fR
sans argument n'affiche que la liste des échecs des utilisateurs qui ont déjà eu un échec de connexion.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBfaillog\fR
sont\ :
.TP 3n
\fB\-a\fR, \fB\-\-all\fR
Afficher les échecs de tous les utilisateurs.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Afficher un message d'aide et quitter.
.TP 3n
\fB\-l\fR, \fB\-\-lock\-time\fR \fISEC\fR
Verrouiller le compte pendant
\fISEC\fR
secondes après un échec de connexion.
.TP 3n
\fB\-m\fR, \fB\-\-maximum\fR \fIMAX\fR
Fixer le nombre maximum d'échecs de connexion après lesquels le compte sera désactivé à
\fIMAX\fR. Une limite
\fIMAX\fR
de 0 aura pour effet de ne pas placer de limite d'échec. La limite pour l'utilisateur
\fIroot\fR
devrait toujours être 0 pour éviter tout risque de déni de service contre le système.
.TP 3n
\fB\-r\fR, \fB\-\-reset\fR
Réinitialiser les compteurs (ou un compteur, si l'option
\fB\-u\fR
\fIIDENTIFIANT\fR
est utilisée) des échecs de connexion. L'accès en écriture sur
\fI/var/log/faillog\fR
est nécessaire pour cette option.
.TP 3n
\fB\-t\fR, \fB\-\-time\fR \fIJOURS\fR
Afficher les entrées de faillog plus récentes que
\fIJOURS\fR. L'option
\fB\-t\fR
surcharge l'utilisation de l'option
\fB\-u\fR.
.TP 3n
\fB\-u\fR, \fB\-\-user\fR \fIIDENTIFIANT\fR
Afficher l'entrée de faillog ou maintient le décompte et les limitations (suivant que l'option
\fB\-l\fR,
\fB\-m\fR
ou
\fB\-r\fR
est utilisée) seulement pour l'utilisateur
\fIIDENTIFIANT\fR.
.SH "AVERTISSEMENTS"
.PP
\fBFaillog\fR
n'affiche que les utilisateurs n'ayant pas eu de connexion réussie depuis leur dernier échec. Pour afficher un utilisateur ayant eu une connexion réussie depuis son dernier échec, vous devez explicitement demander cet utilisateur avec l'option
\fB\-u\fR, ou demander l'affichage de tous les utilisateurs avec l'option
\fB\-a\fR.
.SH "FICHIERS"
.TP 3n
\fI/var/log/faillog\fR
Journal des échecs de connexion.
.SH "VOIR AUSSI"
.PP
\fBlogin\fR(1),
\fBfaillog\fR(5).
