.\"     Title: faillog
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Formats et conversions de fichiers
.\"    Source: Formats et conversions de fichiers
.\"
.TH "FAILLOG" "5" "30/07/2006" "Formats et conversions de fich" "Formats et conversions de fich"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
faillog \- journal des échecs de connexion
.SH "DESCRIPTION"
.PP
\fI/var/log/faillog\fR
maintient un compteur des échecs de connexion ainsi que les limites associées à chaque compte. Le fichier est constitué d'enregistrements de longueur fixe, indexés par l'identifiant numérique des utilisateurs (UID). Chaque enregistrement comprend le nombre d'échecs de connexion depuis la dernière connexion réussie, le nombre maximal d'échecs avant que le compte ne soit désactivé, la ligne correspondant au dernier échec de connexion, la date du dernier échec, et le temps en secondes après lequel le compte sera bloqué après un échec.
.PP
La structure du fichier est la suivante\ :
.sp
.RS 3n
.nf
struct	faillog {
	short   fail_cnt;      /* compteur des échecs */
	short   fail_max;      /* nb max avant désactivation */
	char    fail_line[12]; /* ligne du dernier échec */
	time_t  fail_time;     /* date du dernier échec */
	long    fail_locktime;};
.fi
.RE
.SH "FICHIERS"
.TP 3n
\fI/var/log/faillog\fR
Journal des échecs de connexion.
.SH "VOIR AUSSI"
.PP

\fBfaillog\fR(8)
