.\"     Title: gpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes utilisateur
.\"    Source: Commandes utilisateur
.\"
.TH "GPASSWD" "1" "30/07/2006" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
gpasswd \- Administrer le fichier
.SH "SYNOPSIS"
.HP 8
\fBgpasswd\fR \fIgroupe\fR
.HP 8
\fBgpasswd\fR \-a\ \fIutilisateur\fR \fIgroupe\fR
.HP 8
\fBgpasswd\fR \-d\ \fIutilisateur\fR \fIgroupe\fR
.HP 8
\fBgpasswd\fR \-R\ \fIgroupe\fR
.HP 8
\fBgpasswd\fR \-r\ \fIgroupe\fR
.HP 8
\fBgpasswd\fR [\-A\ \fIutilisateur,\fR...] [\-M\ \fIutilisateur,\fR...] \fIgroupe\fR
.SH "DESCRIPTION"
.PP
\fBGpasswd\fR
est utilisé pour administrer le fichier
\fI/etc/group\fR
(ainsi que le fichier
\fI/etc/gshadow\fR
si l'option SHADOWGRP a été définie lors de la compilation). Chaque groupe peut avoir des administrateurs, des membres ainsi qu'un mot de passe. L'administrateur système peut utiliser l'option
\fB\-A\fR
pour définir le(s) administrateur(s) de groupe et l'option
\fB\-M\fR
pour en définir les membres. Il possède également tous les droits des administrateurs et des membres du groupe.
.SS "Notes sur les mots de passe de groupe"
.PP
Les mots de passe de groupe représentent naturellement un risque en matière de sécurité, puisque plusieurs personnes ont connaissance du mot de passe. Cependant, les groupes sont utiles pour permettre la coopération entre différents utilisateurs.
.\" end of SS subsection "Notes sur les mots de passe de groupe"
.SH "OPTIONS"
.PP
Un administrateur de groupe peut ajouter ou supprimer des utilisateurs en utilisant respectivement les options
\fB\-a\fR
et
\fB\-d\fR. Les administrateurs peuvent utiliser l'option
\fB\-r\fR
pour supprimer le mot de passe d'un groupe. Lorsqu'aucun mot de passe n'est défini, seuls les membres d'un groupe peuvent utiliser
\fBnewgrp\fR
pour utiliser ce groupe. L'option
\fB\-R\fR
désactive l'accès au groupe via la commande
\fBnewgrp\fR
(sauf pour les membres du groupe).
.PP
\fBGpasswd\fR
exécuté par un administrateur de groupe suivi d'un nom de groupe, affiche simplement l'invite de mot de passe du groupe. Si un mot de passe est défini alors les membres du groupe pourront utiliser
\fBnewgrp\fR(1)
sans mot de passe, tandis que les utilisateurs n'étant pas membre du groupe devront fournir le mot de passe.
.SH "FICHIERS"
.TP 3n
\fI/etc/group\fR
Informations sur les groupes.
.TP 3n
\fI/etc/gshadow\fR
Informations sécurisées sur les groupes.
.SH "VOIR AUSSI"
.PP
\fBnewgrp\fR(1),
\fBgshadow\fR(5),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBgrpck\fR(8),
\fBgroup\fR(5).
