.\" Traduction 09/01/1997 par Christophe Blaess (ccb@club-internet.fr)
.\"
.TH GROUPS 1L "9 Janvier 1997" FSF "Manuel de l'utilisateur Linux"
.SH NOM
groups \- Afficher les groupes auxquels appartient un utilisateur.
.SH SYNOPSIS
.B groups
[utilisateur...]
.br
.B groups
{\-\-help,\-\-version}
.SH DESCRIPTION
Cette page de manuel documente la version GNU de
.BR groups .

.B groups
affiche le noms des groupes supplémentaires de chaque
.IR utilisateur 
indiqué, ou ceux du processus en cours si rien n'est précisé.

Si plusieurs utilisateurs sont mentionnés, le nom de chacun d'entre
eux est affiché avant la liste de ses groupes.
.PP
La liste des groupes est équivalente au résultat de la commande `id \-Gn'.
.SS OPTIONS
Quand la version GNU de
.B groups
est invoquée avec un seul argument, les options suivantes sont reconnues :
.TP
.I "\-\-help"
Afficher un message d'aide sur la sortie standard et terminer normalement.
.TP
.I "\-\-version"
Afficher un numéro de version sur la sortie standard et terminer normalement.

.SH TRADUCTION
Christophe Blaess, 1997.
