.\"     Title: groups
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes utilisateur
.\"    Source: Commandes utilisateur
.\"
.TH "GROUPS" "1" "30/07/2006" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
groups \- Afficher la liste des groupes auxquels appartient l'utilisateur
.SH "SYNOPSIS"
.HP 7
\fBgroups\fR [\fIutilisateur\fR]
.SH "DESCRIPTION"
.PP
\fBGroups\fR
affiche la liste des noms de groupe (ou leur identifiant numérique) de l'utilisateur. Si une valeur n'a pas d'entrée correspondante dans
\fI/etc/group\fR, l'identifiant numérique du groupe est affiché. Le paramètre optionnel
\fIutilisateur\fR
permet d'afficher la liste des groupes pour cet utilisateur.
.SH "NOTE"
.PP
Sur les systèmes qui ne gèrent pas l'appartenance à plusieurs groupes, seules les informations contenues dans
\fI/etc/group\fR
sont affichées. L'utilisateur doit utiliser
\fBnewgrp\fR
ou
\fBsg\fR
pour modifier l'identifiant de groupe réel et effectif.
.SH "FICHIERS"
.TP 3n
\fI/etc/group\fR
Informations sur les groupes.
.SH "VOIR AUSSI"
.PP
\fBnewgrp\fR(1),
\fBgetgid\fR(2),
\fBgetgroups\fR(2),
\fBgetuid\fR(2).
