.\"     Title: groupdel
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes de gestion du système
.\"    Source: Commandes de gestion du système
.\"
.TH "GROUPDEL" "8" "30/07/2006" "Commandes de gestion du systèm" "Commandes de gestion du systèm"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
groupdel \- Supprimer un groupe
.SH "SYNOPSIS"
.HP 9
\fBgroupdel\fR \fIgroupe\fR
.SH "DESCRIPTION"
.PP
La commande
\fBgroupdel\fR
modifie les fichiers d'administration des comptes du système, en supprimant les entrées qui se réfèrent à
\fIgroupe\fR. Le groupe indiqué doit exister.
.PP
Vous devez vérifier vous\-même qu'aucun fichier possédé par le groupe ne subsiste sur tous les systèmes de fichiers.
.SH "AVERTISSEMENTS"
.PP
Vous ne pouvez pas supprimer le groupe primaire d'un utilisateur existant. Vous devez supprimer l'utilisateur auparavant.
.SH "FICHIERS"
.TP 3n
\fI/etc/group\fR
Informations sur les groupes.
.TP 3n
\fI/etc/gshadow\fR
Informations sécurisées sur les groupes.
.SH "VALEURS DE RETOUR"
.PP
La commande
\fBgroupdel\fR
retourne les valeurs suivantes en quittant\ :
.TP 3n
\fI0\fR
succès
.TP 3n
\fI2\fR
erreur de syntaxe
.TP 3n
\fI8\fR
impossible de supprimer le groupe primaire d'un utilisateur existant
.TP 3n
\fI10\fR
impossible de mettre à jour le fichier des groupes
.SH "VOIR AUSSI"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupmod\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)
