.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GROUPS" "1" "12/07/2005" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
groups \- Afficher la liste des groupes auxquels appartient l'utilisateur
.SH "SYNOPSIS"
.HP 7
\fBgroups\fR [\fIutilisateur\fR]
.SH "DESCRIPTION"
.PP
\fBGroups\fR
affiche la liste des noms de groupe (ou leur identifiant numérique) de l'utilisateur. Si une valeur n'a pas d'entrée correspondante dans
\fI/etc/group\fR, l'identifiant numérique du groupe est affiché. L'argument optionnel
\fIutilisateur\fR
permet d'afficher la liste des groupes pour cet utilisateur.
.SH "NOTE"
.PP
Sur les systèmes ne supportant pas l'appartenance à plusieurs groupes, seules les informations contenues dans
\fI/etc/group\fR
sont affichées. L'utilisateur doit utiliser
\fBnewgrp\fR
ou
\fBsg\fR
pour modifier l'identifiant de groupe réel et effectif.
.SH "FICHIERS"
.TP
\fI/etc/group\fR
informations sur les groupes
.SH "VOIR AUSSI"
.PP
\fBnewgrp\fR(1),
\fBgetgid\fR(2),
\fBgetgroups\fR(2),
\fBgetuid\fR(2).
