.\"     Title: lastlog
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes de gestion du système
.\"    Source: Commandes de gestion du système
.\"
.TH "LASTLOG" "8" "30/07/2006" "Commandes de gestion du systèm" "Commandes de gestion du systèm"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
lastlog \- signaler les connexions les plus récentes de tous les utilisateurs ou d'un utilisateur donné
.SH "SYNOPSIS"
.HP 8
\fBlastlog\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
\fBLastlog\fR
affiche le contenu du journal des dernières connexions (\fI/var/log/lastlog\fR). Les champs
\fIUtilisateur\fR,
\fIPort\fR, date de
\fIDernière\fR
connexion sont affichés. Par défaut (aucune option de spécifiée), les entrées de laslog sont affichées triées par ordre d'apparition dans
\fI/etc/passwd\fR.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBlastlog\fR
sont\ :
.TP 3n
\fB\-b\fR, \fB\-\-before\fR \fIJOURS\fR
N'affiche que les entrées du fichier lastlog plus anciennes que
\fIJOURS\fR.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Afficher un message d'aide et quitter.
.TP 3n
\fB\-t\fR, \fB\-\-time\fR \fIJOURS\fR
Affiche les entrées du fichier lastlog plus récentes que
\fIJOURS\fR.
.TP 3n
\fB\-u\fR, \fB\-\-user\fR \fIIDENTIFIANT\fR
N'affiche que les entrées correspondant à l'utilisateur
\fIIDENTIFIANT\fR.
.TP 3n
L'utilisation de l'option \fB\-t\fR supplante l'option \fB\-u\fR.
.PP
Dans le cas où l'utilisateur ne s'est jamais connecté, le message \(Fo\ \fI**Never logged in**\fR\ \(Fc (\(Fo\ \fI**Jamais connecté**\fR\ \(Fc) est affiché à la place des champs
\fIPort\fR
et date de
\fIDernière\fR
connexion.
.SH "NOTE"
.PP
Le fichier
\fIlastlog\fR
est une base de données qui contient des informations concernant la dernière connexion de chaque utilisateur. Vous n'avez pas à faire de rotation (avec rotate) sur ce fichier. C'est un fichier \(Fo\ creux\ \(Fc, donc sa taille sur le disque est bien plus petite que celle affichée par \(Fo\ \fBls \-l\fR\ \(Fc (qui peut indiquer un très gros fichier si vous avez des utilisateurs avec des UID élevés). Vous pouvez afficher sa taille réelle avec \(Fo\ \fBls \-s\fR\ \(Fc.
.SH "FICHIERS"
.TP 3n
\fI/var/log/lastlog\fR
Base de données de l'heure des connexions précédentes des utilisateurs.
.SH "AVERTISSEMENTS"
.PP
S'il y a des trous importants dans les valeurs des UID, lastlog s'exécutera plus lentement, sans affichage à l'écran (par exemple, s'il n'y a pas d'entrée pour les utilisateurs ayant un UID compris entre 170 et 800 dans base de données lastlog, le programme lastlog semblera bloqué comme s'il traitait les entrées correspondant aux UID 171 à 799).
