.\"     Title: limits
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Formats et conversions de fichiers
.\"    Source: Formats et conversions de fichiers
.\"
.TH "LIMITS" "5" "30/07/2006" "Formats et conversions de fich" "Formats et conversions de fich"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
limits \- définition des limites de ressources
.SH "DESCRIPTION"
.PP
Le fichier
\fIlimits\fR
(\fI/etc/limits\fR
par défaut ou LIMITS_FILE définit dans
\fIconfig.h\fR) décrit les limites de ressource que vous voulez imposer. Il doit être possédé et ne doit être lisible que par le compte root.
.PP
Par défaut, aucun quota (aucune limite) n'est imposé à \(Fo\ root\ \(Fc. En fait, il n'est pas possible d'imposer de cette façon de limite aux comptes root ou équivalents (comptes ayant un UID de 0).
.PP
Chaque ligne décrit une limite pour un utilisateur, elle est de la forme suivante\ :
.PP

\fIutilisateur LISTE_DE_LIMITES\fR
.PP
Où
\fILISTE_DE_LIMITES\fR
est une chaîne construite par la concaténation d'une liste de limites de ressource. Chaque limite consiste en une lettre (identifiant le type de limite) et une valeur numérique.
.PP
Les identifiants possibles sont\ :
.TP 3n
\(bu
A\ : espace d'adressage maximal (en kilo octets)
.TP 3n
\(bu
C\ : taille maximale d'un fichier image de la mémoire (\(Fo\ core\ \(Fc, en kilo octets)
.TP 3n
\(bu
D\ : taille maximale du segment de données d'un programme (en kilo octets)
.TP 3n
\(bu
F\ : taille maximale des fichiers (en kilo octets)
.TP 3n
\(bu
M\ : taille maximale de mémoire verrouillée (\(Fo\ locked\-in\-memory\ \(Fc, en kilo octets)
.TP 3n
\(bu
N\ : nombre maximal de fichiers ouverts
.TP 3n
\(bu
R\ : taille maximale de la mémoire résidente (\(Fo\ resident set size\ \(Fc, en kilo octets)
.TP 3n
\(bu
S\ : taille maximale de la pile (en kilo octets)
.TP 3n
\(bu
T\ : temps processeur maximal consommé (en minutes)
.TP 3n
\(bu
U\ : nombre maximal de processus
.TP 3n
\(bu
K\ : masque de création de fichier, positionné par
\fBumask\fR(2).
.TP 3n
\(bu
L\ : nombre maximal de connexions simultanées pour cet utilisateur
.TP 3n
\(bu
P\ : priorité des processus, positionné par
\fBsetpriority\fR(2).
.sp
.RE
.PP
Par exemple,
\fIL2D2048N5\fR
est une chaîne
\fILISTE_DE_LIMITES\fR
valable. Pour faciliter la lecture, les entrées suivantes sont équivalentes\ :
.sp
.RS 3n
.nf
      utilisateur L2D2048N5
      utilisateur L2 D2048 N5
    
.fi
.RE
.PP
Attention\ : tout ce qui suit
\fIutilisateur\fR
est considéré comme une limite de chaîne. Les commentaires ne sont pas autorisés. Une chaîne de limites non valable sera rejetée (non utilisée) par le programme
\fBlogin\fR.
.PP
L'entrée par défaut est représentée par un utilisateur dénommé \(Fo\ \fI*\fR\ \(Fc. Si plusieurs entrées par défaut sont présentes dans le fichier de limites, alors seule la dernière sera prise en compte.
.PP
Un simple tiret \(Fo\ \fI\-\fR\ \(Fc sera suffisant pour désactiver toute limite à un utilisateur,
.PP
Notez également que les limites ne sont spécifiées que PAR CONNEXION. Il n'y a pas de limite globale ou permanente. Des limites globales pourraient voir le jour, mais pour l'instant, il faut faire sans.
.SH "FICHIERS"
.TP 3n
\fI/etc/limits\fR
.SH "VOIR AUSSI"
.PP
\fBlogin\fR(1),
\fBsetpriority\fR(2),
\fBsetrlimit\fR(2).
