.\"     Title: login
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes utilisateur
.\"    Source: Commandes utilisateur
.\"
.TH "LOGIN" "1" "30/07/2006" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
login \- Démarrer une session sur le système
.SH "SYNOPSIS"
.HP 6
\fBlogin\fR [\-p] [\fInom_utilisateur\fR] [\fIENV=VAR\fR...]
.HP 6
\fBlogin\fR [\-p] [\-h\ \fIhôte\fR] [\-f\ \fInom_utilisateur\fR]
.HP 6
\fBlogin\fR [\-p] \-r\ \fIhôte\fR
.SH "DESCRIPTION"
.PP
\fBLogin\fR
permet d'établir une nouvelle session sur le système. Elle est généralement invoquée après avoir répondu à l'invite de login
\fIlogin:\fR
sur le terminal de l'utilisateur.
\fBLogin\fR
peut être spécifique à l'interpréteur de commandes (\(Fo\ shell\ \(Fc) et ne devrait pas être invoqué comme un sous\-processus. En général,
\fBlogin\fR
est traité comme
\fB>exec login\fR, ce qui entraîne la sortie de l'interpréteur de commandes en cours. L'exécution de
\fBlogin\fR
depuis un interpréteur de commandes (\(Fo\ shell\ \(Fc) autre qu'un interpréteur de commandes initial (\(Fo\ login shell\ \(Fc) produira un message d'erreur.
.PP
Un mot de passe est ensuite demandé à l'utilisateur. L'affichage du mot de passe est désactivé pour éviter de révéler le mot de passe. Seul un petit nombre d'échecs est permis avant que
\fBlogin\fR
ne quitte et que la liaison ne soit interrompue.
.PP
Si une date de fin de validité du mot de passe a été définie pour ce compte, un nouveau mot de passe pourra vous être demandé. Votre ancien mot de passe et votre nouveau mot de passe vous seront alors demandés avant de pouvoir continuer. Veuillez lire la page de manuel
\fBpasswd\fR(1)
pour plus d'informations.
.PP
Après une connexion réussie, vous serez informé des messages du système et de la présence de courrier. Vous pouvez désactiver l'affichage du message du système (\fI/etc/motd\fR), en créant un fichier vide
\fI.hushlogin\fR
dans le répertoire de votre compte. Le message concernant les courriers sera \(Fo\ \fIYou have new mail.\fR\ \(Fc, \(Fo\ \fIYou have mail.\fR\ \(Fc, ou \(Fo\ \fINo Mail.\fR\ \(Fc suivant l'état de votre boîte aux lettres.
.PP
Vos identifiants d'utilisateur et de groupe seront définis en fonction des valeurs spécifiées dans le fichier
\fI/etc/passwd\fR. Les valeurs des variables d'environnement
\fI$HOME\fR,
\fI$SHELL\fR,
\fI$PATH\fR,
\fI$LOGNAME\fR, et
\fI$MAIL\fR
seront définies en fonction des champs appropriés de l'entrée qui vous correspond. Les valeurs d'ulimit, d'umask et de nice pourront également être affectées en fonction des entrées du champ GECOS.
.PP
Sur certains systèmes, la variable d'environnement
\fI$TERM\fR
sera initialisée au type de terminal de votre tty, comme spécifié dans
\fI/etc/ttytype\fR.
.PP
Un script d'initialisation pour votre interpréteur de commandes pourra également être exécuté. Veuillez vous référer à la section de manuel appropriée pour plus d'informations sur cette fonctionnalité.
.PP
Une connexion à un sous\-système est indiquée par la présence d'un \(Fo\ *\ \(Fc comme premier caractère de l'interpréteur de commandes initial. Le répertoire personnel sera utilisé comme racine d'un nouveau système de fichiers dans lequel l'utilisateur sera connecté.
.PP
Le programme
\fBlogin\fR
n'est PAS responsable de la suppression d'utilisateurs dans le fichier utmp. Les responsables du nettoyage de l'appartenance des sessions de terminal sont
\fBgetty\fR(8)
et
\fBinit\fR(8). Si vous utilisez
\fBlogin\fR
depuis un interpréteur de commandes sans
\fBexec\fR, l'utilisateur que vous utilisez continuera à apparaître comme étant connecté même après s'être déconnecté de cette \(Fo\ sous\-session\ \(Fc.
.SH "OPTIONS"
.TP 3n
\fB\-f\fR
Ne pas réaliser d'authentification. L'utilisateur est pré\-authentifié.
.TP 3n
\fB\-h\fR
Nom de l'hôte distant pour cette connexion.
.TP 3n
\fB\-p\fR
Préserver l'environnement.
.TP 3n
\fB\-r\fR
Exécuter le protocole de connexion automatique (autologin) pour rlogin.
.PP
Les options
\fB\-r\fR,
\fB\-h\fR
et
\fB\-f\fR
ne peuvent être utilisées que par root.
.SH "AVERTISSEMENTS"
.PP
Cette version de
\fBlogin\fR
comporte de nombreuses options de compilation. Seules certaines d'entre elles peuvent avoir été activées sur votre site.
.PP
L'emplacement des fichiers peut varier suivant la configuration du système.
.PP
Le programme
\fBlogin\fR
n'est PAS responsable de la suppression d'utilisateurs dans le fichier utmp. Les responsables du nettoyage de l'appartenance des sessions de terminal sont
\fBgetty\fR(8)
et
\fBinit\fR(8). Si vous utilisez
\fBlogin\fR
depuis un interpréteur de commandes sans
\fBexec\fR, l'utilisateur que vous utilisez continuera à apparaître comme étant connecté même après s'être déconnecté de cette \(Fo\ sous\-session\ \(Fc.
.PP
Comme pour n'importe quel programme, l'apparence de
\fBlogin\fR
peut être imitée. Si des utilisateurs non sûrs ont un accès physique à la machine, un attaquant pourrait utiliser cet accès pour obtenir le mot de passe de la personne qui s'assiérait ensuite face à l'écran. Sous Linux, le mécanisme SAK peut être utilisé par les utilisateurs pour initier un chemin de confiance et prévenir ce genre d'attaques.
.SH "FICHIERS"
.TP 3n
\fI/var/run/utmp\fR
Liste des sessions de connexion en cours.
.TP 3n
\fI/var/log/wtmp\fR
Liste des sessions de connexion précédentes.
.TP 3n
\fI/etc/passwd\fR
Informations sur les comptes des utilisateurs.
.TP 3n
\fI/etc/shadow\fR
Informations sécurisées sur les comptes utilisateurs.
.TP 3n
\fI/etc/motd\fR
Fichier contenant le message du système.
.TP 3n
\fI/etc/nologin\fR
Empêcher les utilisateurs non\-root de se connecter.
.TP 3n
\fI/etc/ttytype\fR
Liste des types de terminaux.
.TP 3n
\fI$HOME/.hushlogin\fR
Supprimer l'affichage des messages du système.
.SH "VOIR AUSSI"
.PP
\fBmail\fR(1),
\fBpasswd\fR(1),
\fBsh\fR(1),
\fBsu\fR(1),
\fBlogin.defs\fR(5),
\fBnologin\fR(5),
\fBpasswd\fR(5),
\fBsecuretty\fR(5),
\fBgetty\fR(8).
