.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "PASSWD" "5" "12/07/2005" "Formats de fichiers et conversions" "Formats de fichiers et convers"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
passwd \- Le fichier des mots de passe
.SH "DESCRIPTION"
.PP
\fI/etc/passwd\fR
contient différentes informations sur les comptes utilisateurs. Ces informations consistent en sept champs séparés par des deux\-points (\(Fo\ :\ \(Fc)\ :
.TP 3
\(bu
nom de connexion de l'utilisateur (\(Fo\ login\ \(Fc)
.TP
\(bu
un mot de passe chiffré optionnel
.TP
\(bu
l'identifiant numérique de l'utilisateur
.TP
\(bu
l'identifiant numérique du groupe de l'utilisateur
.TP
\(bu
le nom complet de l'utilisateur ou un champ de commentaires
.TP
\(bu
le répertoire personnel de l'utilisateur
.TP
\(bu
l'interpréteur de commandes de l'utilisateur (optionel)
.PP
Le champ du mot de passe chiffré peut être vide. Dans ce cas, aucun mot de passe n'est nécessaire pour s'identifier comme le login donné. Cependant, certaines applications qui lisent le fichier
\fI/etc/passwd\fR
peuvent décider de ne donner aucun accès si le
\fImot de\fR
passe est vide. Si le mot de passe est un
\(lqx\(rq
minuscule, alors le mot de passe chiffré est enregistré dans le fichier
\fBshadow\fR(5)\ ; il
\fIdoit\fR
y avoir une ligne correspondante dans le fichier
\fIshadow\fR, sinon le compte de l'utilisateur n'est pas valide. Si le mot de passe est une autre chaîne, alors il est considéré comme un mot de pass chiffré, comme indiqué dans
\fBcrypt\fR(3).
.PP
Le champ de commentaire est utilisé par différents utilitaires système, tels que
\fBfinger\fR(1).
.PP
Le champ du répertoire personnel de l'utilisateur correspond au nom du répertoire de travail initial.
\fBLogin\fR
utilise cette information pour définir la valeur de la variable d'environnement
\fBHOME\fR.
.PP
Le champ de l'interpréteur de commandes correspond au nom de l'interpréteur de commandes de l'utilisateur, ou au nom d'un programme initial à exécuter.
\fBLogin\fR
utilise cette information pour définir la valeur de la variable d'environnement
\fB$SHELL\fR. Si ce champ est vide,
\fI/bin/sh\fR
est utilisé par défaut.
.SH "FICHIERS"
.TP
\fI/etc/passwd\fR
informations sur les comptes des utilisateurs
.TP
\fI/etc/shadow\fR
un mot de passe chiffré optionnel
.SH "VOIR AUSSI"
.PP
\fBgetent\fR(1),
\fBlogin\fR(1),
\fBpasswd\fR(1),
\fBsu\fR(1),
\fBcrypt\fR(3),
\fBgetpwnam\fR(3),
\fBshadow\fR(5),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBsulogin\fR(8).
