.\"     Title: passwd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes utilisateur
.\"    Source: Commandes utilisateur
.\"
.TH "PASSWD" "1" "30/07/2006" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
passwd \- Modifier le mot de passe d'un utilisateur
.SH "SYNOPSIS"
.HP 7
\fBpasswd\fR [\fIoptions\fR] [\fILOGIN\fR]
.SH "DESCRIPTION"
.PP
\fBPasswd\fR
modifie les mots de passe des comptes d'utilisateurs. Un utilisateur normal ne peut changer que son propre mot de passe, le superutilisateur peut changer le mot de passe associé à n'importe quel compte.
\fBPasswd\fR
modifie également les informations associées au compte, telles que le nom complet de l'utilisateur, son interpréteur de commandes de connexion (\(Fo\ login shell\ \(Fc), la date de fin de validité du mot de passe, ou sa durée de validité.
.SS "Modifications du mot de passe"
.PP
Dans un premier temps, l'utilisateur doit fournir son ancien mot de passe, s'il en avait un. Ce mot de passe est ensuite chiffré puis comparé avec le mot de passe enregistré. L'utilisateur n'a droit qu'à un seul essai pour entrer le mot de passe correct. Le superutilisateur peut contourner cette première étape de manière à changer les mots de passe ayant été oubliés.
.PP
Une fois que le mot de passe a été entré, les informations de limite de validité du mot de passe sont vérifiées pour s'assurer que l'utilisateur est autorisé à modifier son mot de passe à cet instant. Dans le cas contraire,
\fBpasswd\fR
refuse de changer le mot de passe, et quitte.
.PP
Le nouveau mot de passe sera demandé deux fois à l'utilisateur. Le second mot de passe est comparé avec le premier. Ces deux mots de passe devront être identiques pour que le mot de passe soit changé.
.PP
La complexité de ce mot de passe est alors testée. Comme ligne de conduite générale, un mot de passe doit toujours être constitué de 6 à 8 caractères en en choisissant un ou plus parmi chacun des ensembles suivants\ :
.TP 3n
\(bu
caractères alphabétiques minuscules
.TP 3n
\(bu
chiffres de 0 à 9
.TP 3n
\(bu
marques de ponctuation
.sp
.RE
.PP
Il faudra faire attention à ne pas utiliser les caractères de suppression ou d'effacement.
\fBPasswd\fR
rejettera tout mot de passe dont la complexité ne sera pas suffisante.
.\" end of SS subsection "Modifications du mot de passe"
.SS "Astuces pour les mots de passe"
.PP
La sécurité d'un mot de passe repose sur la force de l'algorithme de chiffrement et sur la taille de l'espace de clés utilisé. La méthode de chiffrement des systèmes
\fIUNIX\fR
est basée sur l'algorithme NBS DES, elle est très sûre. La taille de l'espace de clés dépend de l'aléa du mot de passe utilisé.
.PP
Les compromissions de la sécurité des mots de passe résultent le plus souvent d'une négligence dans le choix du mot de passe, ou lors de son utilisation. Pour cette raison, vous ne devez pas sélectionner de mot de passe apparaissant dans un dictionnaire ou devant être écrit. Le mot de passe ne doit pas non plus être un nom propre, un numéro minéralogique, une date de naissance, ou une adresse. En effet ceux\-ci pourraient être devinés pour violer la sécurité du système.
.PP
Vous devez pouvoir vous souvenir facilement de votre mot de passe, afin de ne pas avoir à le noter sur un morceau de papier. Pour ce faire, on peut choisir d'accoler deux mots en les séparant avec un caractère spécial ou un chiffre. Par exemple, Mot2passe.
.PP
D'autres méthodes de construction utilisent une phrase facile à se rappeler, et consistent à sélectionner la première ou la dernière lettre de chaque mot. Voici un exemple [\ NdT\ : en anglais\ ]\ :
.TP 3n
\(bu
Ask not for whom the bell tolls.
.TP 3n
\(bu
Ce qui donne\ :
.TP 3n
\(bu
An4wtbt.
.sp
.RE
.PP
Vous pouvez raisonnablement être assuré que quelques crackers ont désormais inclus ces mots de passe dans leurs dictionnaires. Vous pouvez également utiliser votre propre méthode de construction de mots de passe et ne pas compter exclusivement sur les méthodes proposées ici.
.\" end of SS subsection "Astuces pour les mots de passe"
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBpasswd\fR
sont\ :
.TP 3n
\fB\-a\fR, \fB\-\-all\fR
Cette option ne peut être utilisée qu'avec
\fB\-S\fR
et permet d'afficher l'état des mots de passe pour tous les utilisateurs.
.TP 3n
\fB\-d\fR, \fB\-\-delete\fR
Supprime le mot de passe (le rend vide) d'un utilisateur. C'est une façon rapide de supprimer l'authentification par mot de passe pour un compte. Il rend compte indiqué sans mot de passe.
.TP 3n
\fB\-e\fR, \fB\-\-expire\fR
Annule immédiatement la validité du mot de passe d'un compte. Ceci permet d'obliger un utilisateur à changer son mot de passe lors de sa prochaine connexion.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Afficher un message d'aide et quitter.
.TP 3n
\fB\-i\fR, \fB\-\-inactive\fR \fIDURÉE_INACTIVITÉ\fR
Cette option permet de désactiver un compte un certain nombre de jours après que son mot de passe soit arrivé en fin de validité. Après qu'un mot de passe soit arrivé en fin de validité depuis plus de
\fIDURÉE_INACTIVITÉ\fR
jours, l'utilisateur ne pourra plus se connecter avec ce compte.
.TP 3n
\fB\-k\fR, \fB\-\-keep\-tokens\fR
Indique que seuls les mots de passe arrivés en fin de validité doivent être modifié. C'est utile quand l'utilisateur ne veut pas modifier un mot de passe qui serait toujours valable.
.TP 3n
\fB\-l\fR, \fB\-\-lock\fR
Verrouille le compte indiqué. Cette option désactive un compte en modifiant son mot de passe pour une valeur qui ne peut pas correspondre à un mot de passe chiffré possible.
.TP 3n
\fB\-m\fR, \fB\-\-mindays\fR \fIJOURS_MIN\fR
Définit le nombre minimum de jours entre chaque changement de mot de passe à
\fIMIN_DAYS\fR. Une valeur de zéro pour ce champ indique que l'utilisateur peut changer son mot de passe quand il le souhaite.
.TP 3n
\fB\-q\fR, \fB\-\-quiet\fR
Mode silencieux.
.TP 3n
\fB\-r\fR, \fB\-\-repository\fR \fIREPOSITORY\fR
Change le mot de passe de la base
\fIREPOSITORY\fR
.TP 3n
\fB\-S\fR, \fB\-\-status\fR
Afficher l'état d'un compte. Cet état est constitué de 7 champs. Le premier champ est le nom du compte. Le second champ indique si le compte est bloqué (L), n'a pas de mot de passe (NP) ou a un mot de passe utilisable (P). Le troisième champ donne la date de dernière modification du mot de passe. Les quatre champs suivants sont\ : la durée minimum avant modification, la durée maximum de validité, la durée d'avertissement, et la durée d'inactivité autorisée pour le mot de passe. Les durées sont exprimées en jours.
.TP 3n
\fB\-u\fR, \fB\-\-unlock\fR
Déverrouille le compte indiqué. Cette option réactive un compte en changeant un mot de passe à sa valeur précédente (la valeur présente avant l'utilisation de l'option
\fB\-l\fR).
.TP 3n
\fB\-w\fR, \fB\-\-warndays\fR \fIDURÉE_AVERTISSEMENT\fR
Fixe le nombre de jours d'avertissement avant que le changement de mot de passe ne soit obligatoire. La valeur
\fIDURÉE_AVERTISSEMENT\fR
est le nombre de jours précédant la fin de validité pendant lesquels un utilisateur sera prévenu que son mot de passe est sur le point d'arriver en fin de validité.
.TP 3n
\fB\-x\fR, \fB\-\-maxdays\fR \fIJOURS_MAX\fR
Fixe le nombre maximum de jours pendant lesquels un mot de passe reste valable. Après
\fIJOURS_MAX\fR, le mot de passe devra être modifié.
.SH "AVERTISSEMENTS"
.PP
Toutes les options ne sont pas forcément gérées. La vérification de la complexité des mots de passe peut varier d'un site à l'autre. Il est vivement conseillé aux utilisateurs de choisir un mot de passe aussi complexe que possible dans la limite de ce qu'il est capable de mémoriser. Il se peut que les utilisateurs ne puisse pas changer leur mot de passe sur un système si NIS est activé et qu'ils ne sont pas connectés au serveur NIS.
.SH "FICHIERS"
.TP 3n
\fI/etc/passwd\fR
Informations sur les comptes des utilisateurs.
.TP 3n
\fI/etc/shadow\fR
Informations sécurisées sur les comptes utilisateurs.
.SH "VALEURS DE RETOUR"
.PP
La commande
\fBpasswd\fR
retourne les valeurs suivantes en quittant\ :
.TP 3n
\fI0\fR
succès
.TP 3n
\fI1\fR
permission refusée
.TP 3n
\fI2\fR
combinaison d'options non valable
.TP 3n
\fI3\fR
échec inattendu, rien n'a été fait
.TP 3n
\fI4\fR
échec inattendu, le fichier
\fIpasswd\fR
est manquant
.TP 3n
\fI5\fR
fichier
\fIpasswdw/filename> en cours d'utilisation, veuillez réessayer plus tard 6 param \fR
.SH "VOIR AUSSI"
.PP
\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5).
