.\"     Title: porttime
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Formats et conversions de fichiers
.\"    Source: Formats et conversions de fichiers
.\"
.TH "PORTTIME" "5" "30/07/2006" "Formats et conversions de fich" "Formats et conversions de fich"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
porttime \- Fichier de configuration des droits d'accès en fonction de la date et de l'heure
.SH "DESCRIPTION"
.PP
\fIporttime\fR
contient une liste de tty, noms d'utilisateurs, et horaires d'accès autorisés.
.PP
Chaque entrée consiste en trois champs séparés par un caractère deux\-points \(Fo\ :\ \(Fc. Le premier champ est une liste de tty séparés par des virgules, ou un astérisque \(Fo\ *\ \(Fc pour indiquer que l'entrée correspond à toutes les tty. Le second champ est une liste de noms d'utilisateurs, ou un astérisque pour indiquer que cette entrée correspond à n'importe quel utilisateur. Le troisième champ est une liste d'horaires d'accès autorisés.
.PP
Chaque horaire d'accès consiste en zéro ou plusieurs abréviations de jours de la semaine\ :
\fISu\fR
(dimanche),
\fIMo\fR
(lundi),
\fITu\fR
(mardi),
\fIWe\fR
(mercredi),
\fITh\fR
(jeudi),
\fIFr\fR
(vendredi),
\fISa\fR
(samedi), suivi d'un couple d'horaires séparés par un tiret. L'abréviation
\fIWk\fR
peut être utilisée pour représenter les jours de la semaine du lundi au vendredi, et
\fIAl\fR
permet de spécifier l'ensemble des jours de la semaine. Par défaut, si aucun jour n'est spécifié,
\fIAl\fR
est utilisé.
.SH "EXEMPLES"
.PP
L'entrée suivante autorise l'accès à l'utilisateur
\fBjfh\fR
sur n'importe quel port pendant la semaine de 9 heures à 17 heures.
.PP
*:jfh:Wk0900\-1700
.PP
L'entrée suivante autorise l'accès à /dev/console uniquement aux utilisateurs
\fIroot\fR
et
\fIoper\fR
à n'importe quelle heure. Ceci permet de montrer l'importance de l'ordre des entrées dans le fichier
\fI/etc/porttime\fR. Les autres utilisateurs ne satisferont que la deuxième entrée, qui n'autorise aucun accès.
.sp
.RS 3n
.nf
      console:root,oper:Al0000\-2400
      console:*:
    
.fi
.RE
.PP
L'entrée suivante autorise l'accès à tous les ports pour l'utilisateur
\fIgames\fR, en dehors des heures de travail.
.PP
*:games:Wk1700\-0900,SaSu0000\-2400
.SH "FICHIERS"
.TP 3n
\fI/etc/porttime\fR
Fichier contenant le port d'accès.
.SH "VOIR AUSSI"
.PP
\fBlogin\fR(1).
