.\"     Title: pwck
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes de gestion du système
.\"    Source: Commandes de gestion du système
.\"
.TH "PWCK" "8" "30/07/2006" "Commandes de gestion du systèm" "Commandes de gestion du systèm"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
pwck \- Vérifier l'intégrité des fichiers de mots de passe
.SH "SYNOPSIS"
.HP 5
\fBpwck\fR [\-q] [\-s] [\fIpasswd\fR\ \fIshadow\fR]
.HP 5
\fBpwck\fR [\-q] [\-r] [\fIpasswd\fR\ \fIshadow\fR]
.SH "DESCRIPTION"
.PP
\fBPwck\fR
vérifie l'intégrité des informations d'authentification du système. Toutes les entrées des fichiers
\fI/etc/passwd\fR
et
\fI/etc/shadow\fR
sont vérifiées afin de s'assurer qu'elles ont le bon format et qu'elles contiennent des données valables dans chaque champ. Une confirmation de l'utilisateur sera demandée pour détruire les entrées mal formatées ou ayant d'autres erreurs non récupérables.
.PP
Voici les vérifications effectuées\ :
.TP 3n
\(bu
nombre correct de champs
.TP 3n
\(bu
unicité des noms d'utilisateur
.TP 3n
\(bu
validité des identifiants d'utilisateur et de groupe
.TP 3n
\(bu
validité du groupe primaire
.TP 3n
\(bu
validité du répertoire personnel
.TP 3n
\(bu
validité de l'interpréteur de commandes initial (\(Fo\ login shell\ \(Fc)
.sp
.RE
.PP
Une erreur dans le nombre de champs ou la non unicité d'un nom d'utilisateur sera fatale. Si le nombre de champs n'est pas correct, il sera demandé à l'utilisateur de supprimer la ligne. Si l'utilisateur ne répond pas par l'affirmative, les vérifications suivantes ne seront pas effectuées. Il sera également demandé de supprimer les entrées correspondant aux noms d'utilisateur redondants, mais dans ce cas, les autres vérifications seront effectuées. Toutes les autres erreurs ne sont que des avertissements et l'utilisateur est encouragé à utiliser
\fBusermod\fR
pour les corriger.
.PP
Les commandes qui opèrent sur le fichier
\fI/etc/passwd\fR
ne peuvent pas modifier les entrées corrompues ou redondantes.
\fBPwck\fR
doit être utilisé dans ce cas pour retirer ces entrées.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBpwck\fR
sont\ :
.TP 3n
\fB\-q\fR
Ne signaler que les erreurs. Les avertissements qui ne nécessite pas une action de la part de l'utilisateur ne seront pas affichés.
.TP 3n
\fB\-r\fR
Permet d'exécuter
\fBpwck\fR
dans le mode lecture seule.
.TP 3n
\fB\-s\fR
Trie les entrées de
\fI/etc/passwd\fR
et
\fI/etc/shadow\fR
par UID.
.PP
Par défaut,
\fBpwck\fR
opère sur les fichiers
\fI/etc/passwd\fR
et
\fI/etc/shadow\fR. L'utilisateur peut spécifier d'autres fichiers avec les paramètres
\fIfichier_passwd\fR
et
\fIfichier_shadow\fR.
.SH "FICHIERS"
.TP 3n
\fI/etc/group\fR
Informations sur les groupes.
.TP 3n
\fI/etc/passwd\fR
Informations sur les comptes des utilisateurs.
.TP 3n
\fI/etc/shadow\fR
Informations sécurisées sur les comptes utilisateurs.
.SH "VOIR AUSSI"
.PP
\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBusermod\fR(8).
.SH "VALEURS DE RETOUR"
.PP
La commande
\fBpwck\fR
retourne les valeurs suivantes en quittant\ :
.TP 3n
\fI0\fR
succès
.TP 3n
\fI1\fR
erreur de syntaxe
.TP 3n
\fI2\fR
une entrée de mot de passe ou plus est incorrecte
.TP 3n
\fI3\fR
impossible d'ouvrir les fichiers de mots de passe
.TP 3n
\fI4\fR
impossible de verrouiller les fichiers de mots de passe
.TP 3n
\fI5\fR
impossible de mettre à jour les fichiers des mots de passe

