.\"     Title: shadow
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Appels de bibliothèque
.\"    Source: Appels de bibliothèque
.\"
.TH "SHADOW" "3" "30/07/2006" "Appels de bibliothèque" "Appels de bibliothèque"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
shadow, getspnam \- routines d'utilisation des mots de passe cachés
.SH "SYNTAX"
.PP

\fI#include <shadow.h>\fR
.PP

\fIstruct spwd *getspent();\fR
.PP

\fIstruct spwd *getspnam(char\fR
\fI*nom\fR\fI);\fR
.PP

\fIvoid setspent();\fR
.PP

\fIvoid endspent();\fR
.PP

\fIstruct spwd *fgetspent(FILE\fR
\fI*fp\fR\fI);\fR
.PP

\fIstruct spwd *sgetspent(char\fR
\fI*cp\fR\fI);\fR
.PP

\fIint putspent(struct spwd\fR
\fI*p,\fR
\fIFICHIER\fR
\fI*fp\fR\fI);\fR
.PP

\fIint lckpwdf();\fR
.PP

\fIint ulckpwdf();\fR
.SH "DESCRIPTION"
.PP
\fIshadow\fR
manipule le contenu du fichier des mots de passe cachés,
\fI/etc/shadow\fR. La structure définie dans le fichier inclus est\ :
.sp
.RS 3n
.nf
struct spwd {
      char		*sp_namp; /* nom de connexion de l'utilisateur */
      char		*sp_pwdp; /* mot de passe chiffré */
      long int		sp_lstchg; /* dernier changement de mot de passe */
      long int		sp_min; /* jours avant de pouvoir changer de mot de passe */
      long int		sp_max; /* jours avant l'obligation de changer de mot de passe */
      long int		sp_warn; /* jours d'avertissement avant la fin de validité */
      long int		sp_inact; /* jours avant que le compte soit inactif */
      long int		sp_expire; /* date de fin de validité du compte */
      unsigned long int	sp_flag; /* réservé pour une utilisation future */
}
    
.fi
.RE
.PP
La signification de chaque champ est la suivante\ :
.TP 3n
\(bu
sp_namp \- pointeur vers le nom d'utilisateur terminé par un zéro binaire (\(Fo\ null\-terminated\ \(Fc)
.TP 3n
\(bu
sp_pwdp \- pointeur vers le mot de passe terminé par un zéro binaire ( \(Fo\ null\-terminated\ \(Fc)
.TP 3n
\(bu
sp_lstchg \- nombre de jours, comptés à partir du 1er janvier 1970, depuis la dernière modification du mot de passe
.TP 3n
\(bu
sp_min \- nombre de jours pendant lesquels le mot de passe ne peut pas être changé
.TP 3n
\(bu
sp_max \- nombre maximal de jours avant que le mot de passe doive être changé
.TP 3n
\(bu
sp_warn \- nombre de jours avant que le mot de passe n'arrive en fin de validité pendant lesquels l'utilisateur est averti de la fin prochaine de la validité de son mot de passe
.TP 3n
\(bu
sp_inact \- nombre de jours après la fin de validité du mot de passe avant de considérer que le compte est inactif et soit désactivé
.TP 3n
\(bu
sp_expire \- nombre de jours, comptés à partir du 1er janvier 1970, après lesquels le compte sera désactivé
.TP 3n
\(bu
sp_flag \- réservé pour une utilisation future
.SH "DESCRIPTION"
.PP
\fIGetspent\fR,
\fIgetspname\fR,
\fIfgetspent\fR, et
\fIsgetspent\fR
renvoient tous un pointeur vers une structure
\fIstruct spwd\fR.
\fIGetspent\fR
renvoie l'entrée suivante du fichier, et
\fIfgetspent\fR
renvoie l'entrée suivante du flux qui est considéré comme étant un fichier au format correct.
\fISgetspent\fR
renvoie un pointeur vers une structure
\fIstruct spwd\fR
en utilisant la chaîne de caractère fournie en entrée.
\fIGetspnam\fR
cherche à partir de la position courante une entrée correspondant à
\fInom\fR
dans le fichier fourni en entrée.
.PP
\fISetspent\fR
et
\fIendspent\fR
peuvent être utilisés pour débuter et terminer l'accès au fichier de mots de passe cachés.
.PP
Les fonctions
\fIlckpwdf\fR
et
\fIulckpwdf\fR
doivent être utilisées pour garantir un accès exclusif au fichier
\fI/etc/shadow\fR.
\fILckpwdf\fR
essaie de placer un verrou avec
\fIpw_lock\fR
pendant 15 secondes. Il essaie ensuite de placer un second verrou en utilisant
\fIspw_lock\fR
pendant le reste de ces 15 secondes. Si un de ces verrous ne peut être placé,
\fIlckpwdf\fR
renvoie \-1. Quand les deux verrous peuvent être placés, la valeur 0 est renvoyée.
.SH "DIAGNOSTICS"
.PP
Les fonctions renvoient NULL si plus aucune entrée n'est disponible ou si une erreur est survenue lors du traitement. Les fonctions dont la valeur de retour est un
\fIint\fR
renvoient 0 en cas de succès et \-1 en cas d'échec.
.SH "AVERTISSEMENTS"
.PP
Ces fonctions peuvent n'être disponibles que pour le superutilisateur car l'accès au fichier de mots de passe cachés est restreint.
.SH "FICHIERS"
.TP 3n
\fI/etc/shadow\fR
Informations sécurisées sur les comptes utilisateurs.
.SH "VOIR AUSSI"
.PP
\fBgetpwent\fR(3),
\fBshadow\fR(5).
