.\"     Title: su
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes utilisateur
.\"    Source: Commandes utilisateur
.\"
.TH "SU" "1" "30/07/2006" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
su \- Changer d'identifiant d'utilisateur ou devenir superutilisateur
.SH "SYNOPSIS"
.HP 3
\fBsu\fR [\fIoptions\fR] [\fILOGIN\fR]
.SH "DESCRIPTION"
.PP
\fBSu\fR
permet de devenir un autre utilisateur pour la durée d'une session. Invoqué sans nom d'utilisateur, le comportement par défaut est de devenir superutilisateur. Le paramètre optionnel
\fB\-\fR
permet d'obtenir un environnement similaire à celui que l'utilisateur aurait obtenu lors d'une connexion directe.
.PP
Des paramètres supplémentaires peuvent être fournis après le nom de l'utilisateur. Dans ce cas, ils sont donnés à l'interpréteur de commandes de connexion de l'utilisateur. En particulier, le paramètre \(Fo\ \fB\-c\fR\ \(Fc considère que le paramètre suivant est une commande pour la plupart des interpréteurs de commandes. La commande sera exécutée par l'interpréteur indiqué dans
\fI/etc/passwd\fR
pour l'utilisateur cible.
.PP
Vous pouvez utiliser le paramètre
\fB\-\-\fR
pour séparer les options de
\fBsu\fR
des paramètres fournis par l'interpréteur de commandes.
.PP
Un mot de passe sera demandé à l'utilisateur, si nécessaire. Les mots de passe incorrects produisent un message d'erreur. Toutes les tentatives, réussies ou non, sont enregistrées afin de détecter tout abus du système.
.PP
L'environnement actuel est fourni au nouvel interpréteur de commandes. La valeur de
\fB$PATH\fR
est réinitialisée à
\fI/bin:/usr/bin\fR
pour les utilisateurs normaux, ou à
\fI/sbin:/bin:/usr/sbin:/usr/bin\fR
pour le superutilisateur. Ce comportement peut être modifié avec les paramètres
\fIENV_PATH\fR
et
\fIENV_SUPATH\fR
de
\fI/etc/login.defs\fR.
.PP
Une connexion à un sous\-système est indiquée par la présence d'un \(Fo\ *\ \(Fc comme premier caractère de l'interpréteur de commandes initial. Le répertoire personnel sera utilisé comme racine d'un nouveau système de fichiers dans lequel l'utilisateur sera connecté.
.SH "OPTIONS"
.PP
Les options applicables à la commande
\fBsu\fR
sont\ :
.TP 3n
\fB\-c\fR, \fB\-\-command\fR\fIINTERPRÉTEUR_COMMANDES\fR
Indiquer une commande qui sera invoquée par l'interpréteur de commandes en utilisant son option
\fB\-c\fR
.TP 3n
\fB\-\fR, \fB\-l\fR, \fB\-\-login\fR
Fournir à l'utilisateur un environnement similaire à celui qu'il aurait obtenu s'il s'était connecté directement.
.sp
Lorsque
\fB\-\fR
est utilisé, il doit être indiqué comme dernier paramètre de
\fBsu\fR
option. Les autres formes (\fB\-l\fR
et
\fB\-\-login\fR) ne présentent pas cette restriction.
.TP 3n
\fB\-s\fR, \fB\-\-shell\fR \fIINTERPRÉTEUR\fR
Interpréteur de commande devant être appelé.
.sp
L'interpréteur de commandes est choisi parmi (celui de plus haute priorité en tête)\ :
.RS 3n
.TP 3n
\(bu
Interpréteur de commande indiqué par \-\-shell
.TP 3n
\(bu
Si
\fB\-\-preserve\-environment\fR
est utilisé, l'interpréteur de commandes indiqué par la variable d'environnement
\fB$SHELL\fR
sera utilisé.
.TP 3n
\(bu
Interpréteur de commandes indiqué dans
\fI/etc/passwd\fR
pour l'utilisateur cible.
.TP 3n
\(bu
\fI/bin/sh\fR
si aucun interpréteur de commandes ne peut être trouvé par l'une des méthodes ci\-dessus.
.RE
.IP "" 3n
.sp
Si l'utilisateur cible possède un interpréteur de commande restreint (par exemple, le champ de l'interpréteur de commande dans
\fI/etc/passwd\fR
n'est pas renseigné dans
\fI/etc/shell\fR), alors, l'option
\fB\-\-shell\fR
de la variable d'environnement
\fB$SHELL\fR
ne sera pas prise en compte à moins que
\fBsu\fR
ne soit appelé par le superutilisateur.
.TP 3n
\fB\-m\fR, \fB\-p\fR, \fB\-\-preserve\-environment\fR
Préserver l'environnement actuel.
.sp
Si l'utilisateur cible possède un interpréteur de commandes restreint, cette option n'a aucun effet (à moins que
\fBsu\fR
ne soit appelé par le superutilisateur).
.SH "AVERTISSEMENTS"
.PP
Cette version de
\fBsu\fR
a de nombreuses options de compilation. Seules certaines d'entre elles peuvent avoir été activées sur votre site.
.SH "FICHIERS"
.TP 3n
\fI/etc/passwd\fR
Informations sur les comptes des utilisateurs.
.TP 3n
\fI/etc/shadow\fR
Informations sécurisées sur les comptes utilisateurs.
.SH "VOIR AUSSI"
.PP
\fBlogin\fR(1),
\fBlogin.defs\fR(5),
\fBsh\fR(1)
