.\"     Title: suauth
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Formats et conversions de fichiers
.\"    Source: Formats et conversions de fichiers
.\"
.TH "SUAUTH" "5" "30/07/2006" "Formats et conversions de fich" "Formats et conversions de fich"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
suauth \- Fichier de contrôle détaillé de su
.SH "SYNOPSIS"
.HP 12
\fB/etc/suauth\fR
.SH "DESCRIPTION"
.PP
Le fichier
\fI/etc/suauth\fR
est lu chaque fois que su est exécuté. Il permet de modifier le comportement de la commande su, en fonction de\ :
.sp
.RS 3n
.nf
      1) l'utilisateur cible de su
    
.fi
.RE
.sp
.PP
2) l'utilisateur qui exécute la commande su (ou un groupe dont il est membre)
.PP
Le fichier est formaté de la façon suivante (les lignes commençant par un \(Fo\ #\ \(Fc sont des commentaires, et sont ignorées)\ :
.sp
.RS 3n
.nf
      vers\-id:par\-id:ACTION
    
.fi
.RE
.PP
Où vers\-id peut être le mot
\fIALL\fR, une liste de noms d'utilisateurs séparés par une virgule ou
\fIALL EXCEPT\fR
suivi d'une liste d'utilisateurs séparés par une virgule.
.PP
par\-id utilise le même format que vers\-id, mais accepte également le mot\-clé
\fIGROUP\fR.
\fIALL EXCEPT GROUP\fR
est également accepté.
\fIGROUP\fR
est suivi d'un ou plusieurs noms de groupes, séparés par une virgule. Il n'est pas suffisant d'avoir comme groupe primaire le groupe approprié\ : une entrée dans
\fB/etc/group\fR(5)
est nécessaire.
.PP
Les valeurs d'ACTION valables sont\ :
.TP 3n
\fIDENY\fR
La tentative de changement d'utilisateur s'est arrêtée avant que le mot de passe ne soit demandé.
.TP 3n
\fINOPASS\fR
La tentative est automatiquement réussie. Aucun mot de passe n'est demandé.
.TP 3n
\fIOWNPASS\fR
Pour que la commande su soit réussie, l'utilisateur doit entrer son propre mot de passe. Ceci lui est demandé.
.PP
Notez qu'il y a trois champs séparés par un \(Fo\ deux\-points\ \(Fc. Ne pas accoler d'espace à ce \(Fo\ deux\-points\ \(Fc. Notez aussi que le fichier est examiné séquentiellement ligne par ligne, et que la première règle applicable est utilisée sans que le reste du fichier ne soit examiné. Ceci permet à l'administrateur système de définir un contrôle aussi fin qu'il le souhaite.
.SH "EXEMPLE"
.sp
.RS 3n
.nf
      # exemple de fichier /etc/suauth
      #
      # Deux utilisateurs privilégiés peuvent
      # devenir root avec leur propre mot de passe.
      #
      root:chris,birddog:OWNPASS
      #
      # Les autres ne peuvent pas de venir root avec
      # su, à l'exception des membres du groupe wheel.
      # Ceci correspond au comportement des BSD.
      #
      root:ALL EXCEPT GROUP wheel:DENY
      #
      # terry et birddog sont des comptes possédés
      # par la même personne.
      # Un accès sans mot passe est aménagé
      # entre ces deux comptes.
      #
      terry:birddog:NOPASS
      birddog:terry:NOPASS
      #
    
.fi
.RE
.sp
.SH "FICHIERS"
.TP 3n
\fI/etc/suauth\fR
.SH "BOGUES"
.PP
Il en reste sans doute beaucoup. L'analyseur du fichier est particulièrement impitoyable avec les erreurs de syntaxe. Il n'autorise d'espace qu'en début et fin de ligne, et seul le délimiteur spécifique doit être utilisé.
.SH "DIAGNOSTICS"
.PP
Une erreur dans l'analyse du fichier est reportée via
\fBsyslogd\fR(8)
au niveau ERR dans la catégorie AUTH.
.SH "VOIR AUSSI"
.PP
\fBsu\fR(1).
