.\"     Title: useradd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes de gestion du système
.\"    Source: Commandes de gestion du système
.\"
.TH "USERADD" "8" "30/07/2006" "Commandes de gestion du systèm" "Commandes de gestion du systèm"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
useradd \- créer un nouvel utilisateur ou modifier les informations par défaut appliquées aux nouveaux utilisateurs
.SH "SYNOPSIS"
.HP 8
\fBuseradd\fR [\fIoptions\fR] \fILOGIN\fR
.HP 8
\fBuseradd\fR \-D
.HP 8
\fBuseradd\fR \-D [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
Quand elle est invoquée sans l'option
\fB\-D\fR, la commande
\fBuseradd\fR
crée un nouveau compte utilisateur qui utilise les valeurs indiquées sur la ligne de commande et les valeurs par défaut du système. En fonction des options de la ligne de commande, la commande useradd fera la mise à jour des fichiers du système, elle pourra créer le répertoire personnel et copier les fichiers initiaux.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBuseradd\fR
sont\ :
.TP 3n
\fB\-c\fR, \fB\-\-comment\fR \fICOMMENTAIRE\fR
Toute chaîne de texte. C'est généralement une description courte du compte, elle est actuellement utilisée comme champ pour le nom complet de l'utilisateur.
.TP 3n
\fB\-b\fR, \fB\-\-base\-dir\fR \fIRÉP_BASE\fR
Répertoire de base par défaut du système si l'option
\fB\-d\fR
rép n'est pas spécifiée.
\fIRÉP_BASE\fR
est concaténé avec le nom du compte pour définir le répertoire personnel. Quand l'option
\fB\-m\fR
n'est pas utilisée,
\fIRÉP_BASE\fR
doit exister.
.TP 3n
\fB\-d\fR, \fB\-\-home\fR \fIRÉP_PERSO\fR
Le nouvel utilisateur sera créé en utilisant
\fIRÉP_PERSO\fR
comme valeur de répertoire de connexion de l'utilisateur. Le comportement par défaut est de concaténer
\fIUTILISATEUR\fR
au répertoire
\fIRÉP_BASE\fR, et de l'utiliser en tant que nom de répertoire de connexion. Il n'est pas nécessaire que le répertoire
\fIRÉP_PERSO\fR
existe mais il ne sera pas créé s'il n'existe pas.
.TP 3n
\fB\-e\fR, \fB\-\-expiredate\fR \fIDATE_FIN_VALIDITÉ\fR
Date à laquelle le compte utilisateur sera désactivé. La date est indiquée dans le format
\fIAAAA\-MM\-JJ\fR.
.TP 3n
\fB\-f\fR, \fB\-\-inactive\fR \fIDURÉE_INACTIVITÉ\fR
Nombre de jours suivant la fin de validité d'un mot de passe après lequel le compte est définitivement désactivé. Une valeur de 0 désactive le compte dès que le mot de passe a dépassé sa fin de validité, et une valeur de \-1 désactive cette fonctionnalité. La valeur par défaut est de \-1.
.TP 3n
\fB\-g\fR, \fB\-\-gid\fR \fIGROUPE\fR
Nom ou ou numéro du groupe de connexion initial de l'utilisateur. Le nom du groupe doit exister. Un numéro de groupe doit se référer à un groupe existant. Le numéro de groupe par défaut est de 1, ou la valeur indiquée dans
\fI/etc/default/useradd\fR.
.TP 3n
\fB\-G\fR, \fB\-\-groups\fR \fIGROUPE1\fR[\fI,GROUPE2,...\fR[\fI,GROUPEN\fR]]]
Liste de groupes supplémentaires auxquels appartient également l'utilisateur. Chaque groupe est séparé du suivant par une virgule, sans espace entre eux. Les groupes sont soumis aux mêmes restrictions que celles de l'option
\fB\-g\fR. Le comportement par défaut pour l'utilisateur est de n'appartenir qu'au groupe initial.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Afficher un message d'aide et quitter.
.TP 3n
\fB\-m\fR, \fB\-\-create\-home\fR
Le répertoire personnel de l'utilisateur sera créé s'il n'existe pas déjà. Les fichiers contenus dans
\fIrép_squelette\fR
seront copiés dans le répertoire personnel si l'option
\fB\-k\fR
est employée\ ; sinon, les fichiers contenus dans
\fI/etc/skel\fR
seront utilisés à la place. Tous les répertoires contenus dans
\fIrép_squelette\fR
ou dans
\fI/etc/skel\fR
seront également créés dans le répertoire personnel de l'utilisateur. L'option
\fB\-k\fR
n'est valable qu'en conjonction avec l'option
\fB\-m\fR. Le comportement par défaut est de ne pas créer le répertoire, et de ne copier aucun fichier.
.TP 3n
\fB\-K\fR, \fB\-\-key\fR \fICLÉ\fR=\fIVALEUR\fR
Surcharge les valeurs par défaut du fichier
\fI/etc/login.defs\fR
(UID_MIN, UID_MAX, UMASK, PASS_MAX_DAYS et autres).

Par exemple\ :
\fB\-K\fR
\fIPASS_MAX_DAYS\fR=\fI\-1\fR
peut être utilisé pour la création de comptes système pour désactiver la gestion de la durée de validité des mots de passe, même si les comptes système n'ont pas de mot de passe. Plusieurs options
\fB\-K\fR
peuvent être spécifiées, comme par exemple\ :
\fB\-K\fR
\fIUID_MIN\fR=\fI100\fR
\fB\-K\fR
\fIUID_MAX\fR=\fI499\fR
.sp
Note\ :
\fB\-K\fR
\fIUID_MIN\fR=\fI10\fR,\fIUID_MAX\fR=\fI499\fR
ne fonctionne pas pour l'instant.
.TP 3n
\fB\-o\fR, \fB\-\-non\-unique\fR
Permet de créer un compte d'utilisateur avec un identifiant (\(Fo\ UID\ \(Fc) dupliqué (non unique).
.TP 3n
\fB\-p\fR, \fB\-\-password\fR \fIMOT_DE_PASSE\fR
Le mot de passe chiffré, comme renvoyé par
\fBcrypt\fR(3). Le comportement par défaut est de désactiver le compte.
.TP 3n
\fB\-s\fR, \fB\-\-shell\fR \fIINTERPRÉTEUR\fR
Le nom de l'interpréteur de commandes initial de l'utilisateur (\(Fo\ login shell\ \(Fc). Le comportement par défaut est de laisser ce champ vide. Le système sélectionnera alors l'interpréteur par défaut.
.TP 3n
\fB\-u\fR, \fB\-\-uid\fR \fIUID\fR
La valeur numérique de l'identifiant de l'utilisateur. Cette valeur doit être unique, à moins que l'option
\fB\-o\fR
ne soit utilisée. La valeur ne doit pas être négative. Le comportement par défaut est d'utiliser la plus petite valeur d'identifiant plus grande que 999, et plus grande que celle des identifiants de tous les autres utilisateurs. Les valeurs comprises entre 0 et 999 sont généralement réservées pour les comptes systèmes.
.SS "Modifier les valeurs par défaut"
.PP
Quand il est invoqué avec l'option
\fB\-D\fR,
\fBuseradd\fR
affichera soit les valeurs actuelles par défaut, soit mettra à jour les valeurs par défaut via la ligne de commande. Les options valables sont\ :
.TP 3n
\fB\-b\fR, \fB\-\-base\-dir\fR \fIRÉP_BASE\fR
Préfixe du chemin des répertoires personnels pour les nouveaux utilisateurs. Le nom de l'utilisateur sera attaché à la fin de
\fIRÉP_PERSO\fR
pour créer le nom du nouveau répertoire si l'option
\fB\-d\fR
n'est pas utilisée pendant la création d'un nouveau compte.
.TP 3n
\fB\-e\fR, \fB\-\-expiredate\fR \fIDATE_FIN_VALIDITÉ\fR
Date à laquelle le compte utilisateur sera désactivé.
.TP 3n
\fB\-f\fR, \fB\-\-inactive\fR \fIDURÉE_INACTIVITÉ\fR
Nombre de jours après la fin de validité d'un mot de passe avant que le compte ne soit désactivé.
.TP 3n
\fB\-g\fR, \fB\-\-gid\fR \fIGROUPE\fR
Nom de groupe ou identifiant numérique du groupe initial d'un nouvel utilisateur. Le groupe spécifié doit exister, et un identifiant de groupe numérique doit déjà exister.
.TP 3n
\fB\-s\fR, \fB\-\-shell\fR \fIINTERPRÉTEUR\fR
Nom de l'interpréteur de commandes initial (\(Fo\ login shell\ \(Fc) d'un nouvel utilisateur. Le programme nommé sera utilisé pour tous les futurs nouveaux comptes utilisateur.
.PP
Si aucune option n'est spécifiée,
\fBuseradd\fR
affiche les valeurs par défaut du moment.
.\" end of SS subsection "Modifier les valeurs par défaut"
.SH "NOTES"
.PP
L'administrateur système doit se charger de placer les fichiers par défaut dans le répertoire
\fI/etc/skel\fR.
.SH "AVERTISSEMENTS"
.PP
Vous ne pouvez pas ajouter d'utilisateur à un groupe NIS. Cela doit être effectué sur le serveur NIS.
.PP
De la même façon, si le nom de l'utilisateur existe dans une base de données externe, telle que NIS,
\fBuseradd\fR
refusera de créer le compte d'utilisateur.
.PP
Les noms d'utilisateur doivent commencer par une lettre minuscule ou un tiret bas (\(Fo\ underscore\ \(Fc), et seuls des lettres minuscules, des chiffres, des \(Fo\ underscore\ \(Fc, des tirets ou un dollar peuvent suivre. Soit, sous la forme d'une expression rationnelle\ : [a\-z_][a\-z0\-9_\-]*[$]
.SH "FICHIERS"
.TP 3n
\fI/etc/passwd\fR
Informations sur les comptes des utilisateurs.
.TP 3n
\fI/etc/shadow\fR
Informations sécurisées sur les comptes utilisateurs.
.TP 3n
\fI/etc/group\fR
Informations sur les groupes.
.TP 3n
\fI/etc/default/useradd\fR
Valeurs par défaut pour la création de comptes.
.TP 3n
\fI/etc/skel/\fR
Répertoire contenant les fichiers par défaut.
.TP 3n
\fI/etc/login.defs\fR
Configuration de la suite des mots de passe cachés \(Fo\ shadow password\ \(Fc.
.SH "VALEURS DE RETOUR"
.PP
La commande
\fBuseradd\fR
retourne les valeurs suivantes en quittant\ :
.TP 3n
\fI0\fR
succès
.TP 3n
\fI1\fR
impossible de mettre à jour le fichier des mots de passe
.TP 3n
\fI2\fR
erreur de syntaxe
.TP 3n
\fI3\fR
paramètre non valable pour l'option
.TP 3n
\fI4\fR
UID déjà utilisé (et pas d'option
\fB\-o\fR)
.TP 3n
\fI6\fR
le groupe spécifié n'existe pas
.TP 3n
\fI9\fR
nom d'utilisateur déjà utilisé
.TP 3n
\fI10\fR
impossible de mettre à jour le fichier des groupes
.TP 3n
\fI12\fR
impossible de créer le répertoire personnel
.TP 3n
\fI13\fR
impossible de créer le répertoire d'attente des courriels
.SH "VOIR AUSSI"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBcrypt\fR(3),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBnewusers\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8).
