.\" Copyright 1991 \- 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: userdel.8,v 1.3 2005/04/05 19:08:53 kloczek Exp $
.\"
.\" Traduction 27/09/2000 par Frédéric Delanoy (fdelanoy@info.fundp.ac.be)
.\"
.TH USERDEL 8
.SH NOM
userdel \- Effacer un compte utilisateur et les fichiers associés
.SH SYNOPSIS
.B userdel
[\fB\-r\fR]
.I login
.SH DESCRIPTION
La commande \fBuserdel\fR modifie les fichiers des comptes du système, en supprimant toutes les entrées qui se réfèrent à \fIlogin\fR.  L'utilisateur nommé doit exister.
.SH OPTIONS
.IP \fB\-r\fR
Les fichiers présents dans le répertoire personnel de l'utilisateur seront supprimés en même temps que le répertoire lui\-même.  Les fichiers situés dans d'autres systèmes de fichiers devront être recherchés et éliminés manuellement.
.SH FICHIERS
\fI/etc/passwd\fR \- information sur les comptes utilisateurs
.br
\fI/etc/shadow\fR \- information sécurisée sur les comptes utilisateurs
.br
\fI/etc/group\fR \- information de groupes
.SH INCONVÉNIENTS
\fBuserdel\fR ne vous permet pas de supprimer un compte si l'utilisateur en question est actuellement connecté.  Vous devez tuer tous les processus en cours d'exécution appartenant à l'utilisateur possédant le compte que vous êtes en train de supprimer.  Vous ne pouvez pas supprimer d'attribut NIS d'un client NIS.  Cela doit être effectué sur le serveur NIS.
.SH "VOIR AUSSI"
.BR chfn (1),
.BR chsh (1),
.BR groupadd (8),
.BR groupdel (8),
.BR groupmod (8),
.BR passwd (1),
.BR useradd (8),
.BR usermod (8)
.SH AUTEUR
Julianne Frances Haugh (jfh@bga.com)
.SH TRADUCTION
Frédéric Delanoy, 2000.
