.\"     Title: vipw
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 30/07/2006
.\"    Manual: Commandes de gestion du système
.\"    Source: Commandes de gestion du système
.\"
.TH "VIPW" "8" "30/07/2006" "Commandes de gestion du systèm" "Commandes de gestion du systèm"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
vipw, vigr \- éditer les fichiers passwd, group, shadow ou gshadow
.SH "SYNOPSIS"
.HP 5
\fBvipw\fR [\fIoptions\fR]
.HP 5
\fBvigr\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
\fBVipw\fR
et
\fBvigr\fR
permettent d'éditer les fichiers
\fI/etc/passwd\fR
et
\fI/etc/group\fR, respectivement. Avec l'option
\fB\-s\fR, ils permettent d'éditer les versions cachées de ces fichiers\ :
\fI/etc/shadow\fR
et
\fI/etc/gshadow\fR, respectivement. Ces programmes placent les verrous nécessaires afin d'éviter toute corruption des fichiers. L'éditeur utilisé est choisi d'abord en fonction de la variable d'environnement
\fB$VISUAL\fR, puis de la variable d'environnement
\fB$EDITOR\fR, et enfin l'éditeur par défaut,
\fBvi\fR(1).
.SH "OPTIONS"
.PP
Les options applicables aux commandes
\fBvipw\fR
et
\fBvigr\fR
sont\ :
.TP 3n
\fB\-g\fR, \fB\-\-group\fR
Éditer la base de données de groupes.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Afficher un message d'aide et quitter.
.TP 3n
\fB\-p\fR, \fB\-\-passwd\fR
Éditer la base de données de mots de passe.
.TP 3n
\fB\-q\fR, \fB\-\-quiet\fR
Mode silencieux.
.TP 3n
\fB\-s\fR, \fB\-\-shadow\fR
Éditer les bases de données shadow ou gshadow.
.SH "FICHIERS"
.TP 3n
\fI/etc/group\fR
Informations sur les groupes.
.TP 3n
\fI/etc/gshadow\fR
Informations sécurisées sur les groupes.
.TP 3n
\fI/etc/passwd\fR
Informations sur les comptes des utilisateurs.
.TP 3n
\fI/etc/shadow\fR
Informations sécurisées sur les comptes utilisateurs.
.SH "VOIR AUSSI"
.PP
\fBvi\fR(1),
\fBgroup\fR(5),
\fBgshadow\fR(5)\fBpasswd\fR(5),
\fBshadow\fR(5).
