dist: bionic
sudo: false

language: c

compiler:
 - gcc
 - clang

arch:
 - amd64
 - arm64
 - ppc64le
 - s390x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install -qq automake autopoint xsltproc libselinux1-dev gettext expect
  - sudo apt-get -y install -qq byacc libtool
script:
 - ./autogen.sh --without-selinux --disable-man
 - grep ENABLE_ config.status
 - make

env:
  global:
   - secure: "G47VYFrtzqalrVjixTqBG9Qsa8EZRcaqsh1k6fq5JgEyHmMQActpvTUDs9FXf1MEqiY5XX3VDVfBsZgKPHgmHsMzD1bX11xpnpGByB8g7gr8I3u2ZkCREqgi77a5l3LeBh+seWiambe/DYOgvPCNa6pCynLgR9advqtgKhpCruU="

addons:
  coverity_scan:

    project:
      name: "shadow-maint/shadow"
      description: "Upstream shadow utils tree"

    notification_email: christian.brauner@ubuntu.com,serge@hallyn.com

    build_command_prepend: "./autogen.sh --without-selinux --disable-man"
    build_command: "make -kj4 || make"
    branch_pattern: master

script:
 - cat /proc/self/uid_map
 - cat /proc/self/status
 - systemd-detect-virt
 - ./autogen.sh --without-selinux --disable-man
 - grep ENABLE_ config.status
 - make
 - sudo make install
 - (cd tests; sudo ./run_some; cat testsuite.log)

# vim:et:ts=2:sw=2
