.\" Copyright 1990, John F. Haugh II
.\" All rights reserved.
.\"
.\" Use, duplication, and disclosure prohibited without
.\" the express written permission of the author.
.\"
.\"	@(#)chfn.1	3.1	09:34:16	21 Nov 1990
.\"
.TH CHFN 1
.SH NAME
chfn \- change user name and information
.SH SYNOPSIS
\fBchfn\fR [ \fB-f \fIfull_name\fR ] [ \fB-r \fIroom_no\fR ]
.br
[ \fB-w \fIwork_ph\fR ] [ \fB-h \fIhome_ph\fR ] [ \fB-o \fIother\fR ]
[ \fIuser\fR ]
.SH DESCRIPTION
\fIchfn\f changes user fullname, office number, office extension, and home
phone number information for a user's account. 
This information is typically printed by \fIfinger(1)\f and similiar
programs.
A normal user may only change the fields for their own account,
the super user may change the fields for any account.
Also, only the super user may use the \fB-o\f option to change the
undefined portions of the GCOS field.
.PP
The only restrictions placed on the contents of the fields is that no
control characters may be present, nor any of comma, colon, or equal sign.
The \fIother\f field does not have this restriction, and is used to
store accounting information used by other applications.
.PP
If none of the options are selected, \fIchfn\f operates in an interactive
fashion, prompting the user with the current values for all of the fields.
Enter the new value to change the field, or leave the line blank to use
the current value.
The current value is displayed between a pair of \fB[ ]\f marks.
Without options, chfn prompts for the current user account.
.SH Files
/etc/passwd \- user account information
.SH See Also
passwd(4)
