.\" Copyright 1989, 1990, John F. Haugh II
.\" All rights reserved.
.\"
.\" Use, duplication, and disclosure prohibited without
.\" the express written permission of the author.
.\"
.\"	@(#)porttime.4	3.2	08:36:07	08 Feb 1991
.\"
.TH PORTTIME 4
.SH NAME
porttime \- port access time file
.SH DESCRIPTION
.I porttime
contains a list of tty devices, user names, and permitted login times.
.PP
Each entry consists of three colon separated fields.
The first field is a comma separated list of tty devices,
or an asterisk to indicate that all tty devices are matched by this entry.
The second field is a comma separated list of user names, or an
asterisk to indicated that all user names are matched by this entry.
The third field is a comma separated list of permitted access times.
.PP
Each access time entry consists of zero or more days of the week,
abbreviated \fBSu\fR, \fBMo\fR, \fBTu\fR, \fBWe\fR, \fBTh\fR,
\fBFr\fR, and \fBSa\fR, followed by a pair of times separated by
a hyphen.
The abbreviation \fBWk\fR may be used to represent Monday thru Friday,
and \fBAl\fR may be used to indicate every day.
If no days are given, \fBAl\fR is assumed.
.SH Examples
The following entry allows access to user \fBjfh\fR on every port
during weekdays from 9am to 5pm.
.br
.sp 1
*:jfh:Wk0900-1700
.br
.sp 1
The following entries allow access only to the users \fBroot\fR and
\fBoper\fR on /dev/console at any time.
This illustrates how the
\fB/etc/porttime\fR file is an ordered list of access times.
Any other user would match the second entry which does not permit
access at any time.
.br
.sp 1
console:root,oper:Al0000-2400
.br
console:*:
.br
.sp 1
The following entry allows access for the user \fBgames\fR on any
port during non-working hours.
.br
.sp 1
*:games:Wk1700-0900,SaSu0000-2400
.br
.sp 1
.SH Files
/etc/porttime \- file containing port access times
.SH See Also
login(1)
