.\" Copyright 1991, 1992, 1993, John F. Haugh II
.\" All rights reserved.
.\"
.\" Permission is granted to copy and create derivative works for any
.\" non-commercial purpose, provided this copyright notice is preserved
.\" in all copies of source code, or included in human readable form
.\" and conspicuously displayed on all copies of object code or
.\" distribution media.
.\"
.\" This software is provided on an AS-IS basis and the author makes
.\" no warrantee of any kind.
.\"
.\"	@(#)usermod.1	3.4	08:10:31	07 May 1993
.\"
.TH USERMOD 1M
.SH NAME
usermod \- Modify a user account
.SH SYNOPSIS
.B usermod
[ \fB-A\fI method\fR | \fBDEFAULT\fR ]
[ \fB-c\fI comment\fR ]
[ \fB-d\fI home_dir \fR[ \fB-m\fR ] ]
[ \fB-e\fI expire_date\fR ]
[ \fB-f\fI inactive_time\fR ]
[ \fB-g\fI initial_group\fR ]
[ \fB-G\fI group[,...]\fR ]
[ \fB-l\fI login_name \fR ]
[ \fB-s\fI shell\fR ]
[ \fB-u\fI uid \fR[ \fB-o\fR ]
.I login
.SH DESCRIPTION
The \fIusermod\fR command modifies the system account files to reflect
the changes that are specified on the command line.
The options which apply to the \fIusermod\fR command are
.IP "\fB-A \fImethod\fR|\fBDEFAULT\fR"
The new value of the user's authentication method.
The authentication method is the name of a program which is responsible
for validating the user's identity.
The string \fBDEFAULT\fR may be used to change the user's authentication
method to the standard system password method.
.IP "\fB-c \fIcomment\fR"
The new value of the user's password file comment field.
It is normally modified using the \fBchfn(1)\fR utility.
.IP "\fB-d \fIhome_dir\fR"
The user's new login directory.
If the \fB-m\fR option is given the contents of the current home directory
will be moved to the new home directory, which is created if it does not
already exist.
.IP "\fB-e \fIexpire_date\fR"
The date on which the user account will be disabled.
The date is specified in the format \fIMM/DD/YY\fR.
.IP "\fB-f \fIinactive_days\fR"
The number of days after a password expires until the account
is permanently disabled.
A value of 0 disables the account as soon as the password has
expired, and a value of -1 disables the feature.
The default value is -1.
.IP "\fB-g \fIinitial_group\fR"
The group name or number of the user's new initial login group.
The group name must exist.  A group number must refer to an
already existing group.
The default group number is 1.
.IP "\fB-G \fIgroup,[...]\fR"
A list of supplementary groups which the user is also a member
of.
Each group is separated from the next by a comma, with no
intervening whitespace.
The groups are subject to the same restrictions as the group
given with the \fB-g\fR option.
If the user is currently a member of a group which is not listed,
the user will be removed from the group
.IP "\fB-l \fIlogin_name\fR"
The name of the user will be changed from \fIlogin\fR to
\fIlogin_name\fR.
Nothing else is changed.
In particular, the user's home directory name should probably
be changed to reflect the new login name.
.IP "\fB-s \fIshell\fR"
The name of the user's new login shell.
Setting this field to blank causes the system
to select the default login shell.
.IP "\fB-u \fIuid\fR"
The numerical value of the user's ID.
This value must be unique, unless the \fI-o\fR option is used.
The value must be non-negative.
Values between 0 and 99 are typically reserved for system accounts.
Any files which the user owns and which are located in the directory
tree rooted at the user's home directory will have the file user ID
changed automatically.
Files outside of the user's home directory must be altered manually.
.SH CAVEATS
\fBusermod\fB will not allow you to change the name of a user who is
logged in.
You must make certain that the named user is not executing any processes
when this command is being executed if the user's numerical user ID is
being changed.
You must change the owner of any crontab files manually.
You must change the owner of any at jobs manually.
.SH Files
/etc/passwd \- user account information
.br
/etc/shadow \- secure user account information
.br
/etc/group \- group information
.SH SEE ALSO
\fBchfn(1), chsh(1), groupadd(1M), groupdel(1M), groupmod(1M),
passwd(1), useradd(1M), userdel(1M)
