.\"     Title: chage
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 10/30/2006
.\"    Manual: Polecenia użytkowników
.\"    Source: Polecenia użytkowników
.\"
.TH "CHAGE" "1" "10/30/2006" "Polecenia użytkowników" "Polecenia użytkowników"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAZWA"
chage \- zmiana informacji o terminie ważności hasła użytkownika
.SH "SKŁADNIA"
.HP 6
\fBchage\fR [\fIopcje\fR] [\fILOGIN\fR]
.SH "OPIS"
.PP
Polecenie
\fBchage\fR
zmienia liczbę dni pomiędzy zmianami hasła i datę ostatniej zmiany hasła. Informację tę system wykorzystuje do ustalenia, kiedy użytkownik musi zmienić hasło.
.SH "OPCJE"
.PP
Polecenie
\fBchage\fR
posiada następujące opcje:
.PP
\fB\-d\fR, \fB\-\-lastday\fR\fIOSTATNI\fR
.RS 3n
Ustawia ilość dni od 1 stycznia 1970 kiedy hało było ostani raz zmieniane. Data ważności może być takze prezekazana w formacie RRRR\-MM\-DD (lub formacie używanym lokalnie).
.RE
.PP
\fB\-E\fR, \fB\-\-expiredate\fR\fIDATA_WAŻN\fR
.RS 3n
Ustawia datę, począwszy od której konto użytkownika nie będzie już dostępne.
\fIDATA_WAŻN\fR
jest liczbą dni od 1 stycznia 1970, od której konto jest blokowane. Data może być też wyrażona w formacie RRRR\-MM\-DD (lub innej, powszechniej używanej w danym regionie). Użytkownik, którego konto jest zablokowane musi skontaktować się z administratorem systemu zanim będzie mógł z niego ponownie skorzystać.
.sp
Przekazanie
\fI\-1\fR
jako
\fIDATA_WAŻN\fR
usuwa ograniczenie ważności konta użytkownika.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
Wyświetlenie komunikatu pomocy i zakończenie działania.
.RE
.PP
\fB\-I\fR, \fB\-\-inactive\fR\fINIEAKTYWNE\fR
.RS 3n
Opcja ta służy do ustawiania czasu nieaktywności konta po wygaśnięciu ważności hasła, po którym to czasie konto jest blokowane. Parametr
\fINIEAKTYWNE\fR
jest liczbą dni nieaktywności. Użytkownik, którego konto jest zablokowane musi skontaktować się z administratorem systemu zanim będzie mógł z niego ponownie skorzystać.
.sp
Przekazanie
\fI\-1\fR
jako
\fINIEAKTYWNE\fR
usuwa ograniczenie nieaktywniści konta użytkownika.
.RE
.PP
\fB\-l\fR, \fB\-\-list\fR
.RS 3n
Wyświetlenie informacji o terminach ważności konta i hasła.
.RE
.PP
\fB\-m\fR, \fB\-\-mindays\fR\fIMIN_DNI\fR
.RS 3n
Utawia minimalną liczbę dni pomiędzy zmianami hasła na
\fIMIN_DAYS\fR. Wartość zerowa oznacza, że użytkownik może je zmieniać w dowolnym czasie.
.RE
.PP
\fB\-M\fR, \fB\-\-maxdays\fR\fIMAX_DNI\fR
.RS 3n
Ustawia maksymalną liczbę dni, przez jakie hasło jest ważne. Gdy
\fIMAX_DNI\fR
plus
\fIOSTATNI\fR
jest mniejsze niż bieżący dzień, użytkownik musi zmienić swoje hasła, zanim będzie mógł skorzystać z konta. Zdarzenie to może być zaplanowane z wyprzedzeniem przez wykorzystanie opcji
\fB\-W\fR, ostrzegającej zawczasu użytkownika o zbliżającym się terminie zmiany.
.sp
Przekazanie
\fI\-1\fR
jako
\fIMAX_DAYS\fR
usuwa sprawdzanie wazności hasła.
.RE
.PP
\fB\-W\fR, \fB\-\-warndays\fR\fIDNI_OSTRZ\fR
.RS 3n
Ustawia na
\fIDNI_OSTRZ\fR
liczbę dni przed upływem ważności hasła. Od tego dnia użytkownik będzie ostrzegany o nadchodzącym terminie zmiany hasła.
.RE
.PP
Jeśli nie podano żadnej opcji, to
\fBchage\fR
działa w trybie interaktywnym, proponując użytkownikowi wartości bieżące dla każdego z pól. Wprowadzenie nowej wartości powoduje zmianę wartości pola, a podanie wartości pustej pozostawia wartość bieżącą. Bieżąca wartość pola wyświetlana jest w nawiasach
\fI[ ]\fR.
.SH "UWAGI"
.PP
Program
\fBchage\fR
wymaga do działania chronionego pliku haseł użytkowników (shadow).
.PP
Polecenia chage może użyć tylko użytkownik root, za wyjątkiem opcji
\fB\-l\fR. Może się nią posłużyć się użytkownik nieuprzywilejowany do stwierdzenia, kiedy wygasa jego własne hasło lub konto.
.SH "PLIKI"
.PP
\fI/etc/passwd\fR
.RS 3n
Informacja o kontach użytkowników.
.RE
.PP
\fI/etc/shadow\fR
.RS 3n
Informacje chronione o użytkownikach.
.RE
.SH "KOD ZAKOŃCZENIA"
.PP
Polecenie
\fBchage\fR
kończy działanie z następującymi wartościami kodów zakończenia:
.PP
\fI0\fR
.RS 3n
poprawne zakończenie działania programu
.RE
.PP
\fI1\fR
.RS 3n
brak dostępu
.RE
.PP
\fI2\fR
.RS 3n
niepoprawna składnia polecenia
.RE
.PP
\fI15\fR
.RS 3n
nie można znaleźć pliku shadow
.RE
.SH "ZOBACZ TAKŻE"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5).
