.\" $Id: chage.1,v 1.8 2004/08/04 13:02:25 kloczek Exp $
.\" {PTM/WK/1999-09-16}
.\" Copyright 1990 - 1994 Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH CHAGE 1
.SH NAZWA
chage \- zmiana informacji o terminie wa¿no¶ci has³a u¿ytkownika
.SH SK£ADNIA
.TP 6
\fBchage\fR
[\fB-m \fImindni\fR] [\fB-M \fImaxdni\fR]
[\fB-d \fIostatni\fR] [\fB-I \fInieaktywne\fR]
.br
[\fB-E \fIdata_wa¿no¶ci\fR] [\fB-W \fIdni_ostrzegania\fR] \fIu¿ytkownik\fR
.TP 6
\fBchage\fR
\fB-l \fIu¿ytkownik\fR
.SH OPIS
\fBchage\fR zmienia liczbê dni pomiêdzy zmianami has³a i datê ostatniej
zmiany has³a. Informacjê tê system wykorzystuje do ustalenia, kiedy
u¿ytkownik musi zmieniæ has³o.
Polecenia \fBchage\fR mo¿e u¿yæ tylko u¿ytkownik root, za wyj±tkiem
opcji \fB-l\fR. Mo¿e siê ni± pos³u¿yæ siê u¿ytkownik nieuprzywilejowany
do stwierdzenia, kiedy wygasa jego w³asne has³o lub konto.
Polecenie \fBchage\fR posiada nastêpuj±ce opcje:
.IP "\fB-E\fR \fIdata_wa¿no¶ci\fR"
Ustawia datê, pocz±wszy od której konto u¿ytkownika nie bêdzie ju¿ dostêpne.
\fIdata_wa¿no¶ci\fR jest liczb± dni od 1 stycznia 1970, od której konto jest
blokowane. Data mo¿e byæ te¿ wyra¿ona w postaci RRRR-MM-DD (lub innej,
powszechniej u¿ywanej w danym regionie).
U¿ytkownik, którego konto jest zablokowane musi skontaktowaæ siê
z administratorem systemu zanim bêdzie móg³ z niego ponownie skorzystaæ.
.IP "\fB-I\fR \fInieaktywne\fR"
Opcja \fB-I\fR s³u¿y do ustawiania czasu nieaktywno¶ci po wyga¶niêciu
has³a, po którym konto jest blokowane. Parametr \fInieaktywne\fR podaje
liczbê dni nieaktywno¶ci. Warto¶æ 0 wy³±cza tê funkcjê.
U¿ytkownik, którego konto jest zablokowane musi skontaktowaæ siê
z administratorem systemu zanim bêdzie móg³ z niego ponownie skorzystaæ.
.IP "\fB-m\fR \fImindni\fR"
Utawia minimaln± liczbê dni pomiêdzy zmianami has³a na warto¶æ fImindni\fR.
Warto¶æ zerowa oznacza, ¿e u¿ytkownik mo¿e je zmieniaæ w dowolnym czasie.
.IP "\fB-M\fR \fImaxdni\fR"
Ustawia maksymaln± liczbê dni, przez jakie has³o jest wa¿ne na warto¶æ
\fImaxdni\fR. Gdy \fImaxdni\fR plus \fIostatni\fR jest mniejsze ni¿ bie¿±cy
dzieñ, u¿ytkownik musi zmieniæ swoje has³a, zanim bêdzie móg³ skorzystaæ z
konta. Zdarzenie to mo¿e byæ zaplanowane z wyprzedzeniem przez wykorzystanie
opcji \fB-W\fR, ostrzegaj±cej zawczasu u¿ytkownika o zbli¿aj±cym siê
terminie zmiany.
.IP "\fB-M\fR \fIostatni\fR"
Ustawia liczbê dni od 1 stycznia 1970 do dnia kiedy ostatnio zmieniono has³o
na \fIostatni\fR. Data mo¿e równie¿ zostaæ podana w postaci RRRR-MM-DD (lub
postaci powszechniej u¿ywanej w danym regionie).
.IP "\fB-W\fR \fIdni_ostrzegania\fR"
Ustawia na \fIdni_ostrzegania\fR liczbê dni przed up³ywem wa¿no¶ci has³a.
Od tego dnia u¿ytkownik bêdzie ostrzegany o nadchodz±cym terminie zmiany
has³a.
.PP
Je¶li nie podano ¿adnej opcji, to \fBchage\fR dzia³a w trybie interaktywnym,
proponuj±c u¿ytkownikowi warto¶ci bie¿±ce dla ka¿dego z pól. Wprowadzenie
nowej warto¶ci powoduje zmianê warto¶ci pola, a podanie warto¶ci pustej
pozostawia warto¶æ bie¿±c±.
Bie¿±ca warto¶æ pola wy¶wietlana jest w nawiasach \fB[ ]\fR.
.SH UWAGA
Program \fBchage\fR wymaga do dzia³ania chronionego pliku hase³ u¿ytkowników
(shadow). Je¶li has³a u¿ytkowników s± przechowywane w pliku passwd,
funkcjonalno¶æ programu \fBchage\fR jest niedostêpna.
.SH PLIKI
\fI/etc/passwd\fR \- informacje o kontach u¿ytkowników
.br
\fI/etc/shadow\fR \- chronione informacje o kontach u¿ytkowników
.SH ZOBACZ TAK¯E
.BR passwd (5),
.BR shadow (5)
.SH AUTOR
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
