.\"     Title: chpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 11/19/2006
.\"    Manual: Polecenia Zarządzania Systemem
.\"    Source: Polecenia Zarządzania Systemem
.\"
.TH "CHPASSWD" "8" "11/19/2006" "Polecenia Zarządzania Systemem" "Polecenia Zarządzania Systemem"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAZWA"
chpasswd \- wsadowa aktualizacja haseł użytkowników
.SH "SKŁADNIA"
.HP 9
\fBchpasswd\fR [\fIopcje\fR]
.SH "OPIS"
.PP
Polecenie
\fBchpasswd\fR
czyta pary danych (użytkownik i hasło) ze standardowego wejścia. Odczytane informacje wykorzystywane są do aktualizacji danych o grupie istniejących użytkowników. Każdy wiersz przekazywanych danych ma postać:
.PP
\fInazwa_użytkownika\fR:\fIhasło\fR
.PP
Domyślnie dostarczane hasła muszą być w postaci jawnej. Podczas kodowania haseł używany jest domyślnie algorytm DES. W trakcie zmiany hasła aktualizowany jest także wiek hasła.
.PP
Polecenie to przeznaczone jest do użytku w dużych systemach, gdzie aktualizuje się wiele kont naraz.
.SH "OPCJE"
.PP
Polecenie
\fBchpasswd\fR
posiada następujące opcje:
.PP
\fB\-e\fR, \fB\-\-encrypted\fR
.RS 3n
Dostarczone na standardowe wejście hasła są traktowane jako już zakodowane.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
Wyświetlenie komunikatu pomocy i zakończenie działania.
.RE
.PP
\fB\-m\fR, \fB\-\-md5\fR
.RS 3n
Jeżeli dpostarczane hasła są w postaci jawnej użyj kodowania MD5 zamiast domyślnego DES.
.RE
.SH "OSTRZEŻENIA"
.PP
Pamiętaj żeby zabezpieczyć przed odczytem plik przekazywany na standardowe wejście polecenia.
.SH "ZOBACZ TAKŻE"
.PP
\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBuseradd\fR(8).
