.\" {PTM/WK/1999-09-16}
.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH CHPASSWD 8
.SH NAZWA
chpasswd - wsadowa aktualizacja pliku hase³
.SH SK£ADNIA
.B chpasswd
.RB [ -e ]
.SH OPIS
\fBchpasswd\fR odczytuje ze standardowego wej¶cia plik zawieraj±cy pary:
nazwa u¿ytkownika i has³o. Odczytan± informacje wykorzystuje do aktualizacji
grupy istniej±cych u¿ytkowników.
Bez prze³±cznika -e, has³a traktowane s± jako podane jawnie. Z prze³±cznikiem
-e has³a powinny byæ dostarczone w postaci zakodowanej (encrypted).
Ka¿dy wiersz ma postaæ
.sp 1
	  \fInazwa_U¿ytkownika\fR:\fIhas³o\fR
.sp 1
Dany u¿ytkownik musi istnieæ.
Je¿eli bêdzie to konieczne, podane has³o zostanie zakodowane a wiek has³a,
je¶li wystêpuje, zaktualizowany.
.PP
Polecenie to przeznaczone jest do u¿ytku w du¿ych systemach, gdzie aktualizuje
siê wiele kont naraz.
.SH PRZESTROGI
.\" Po u¿yciu \fBchpasswd\fR musi zostaæ wykonane polecenie \fImkpasswd\fR,
.\" aktualizuj±ce pliki DBM hase³ (DBM password files).
Plik ¼ród³owy, je¶li zawiera niezakodowane has³a, musi byæ chroniony.
.\" Polecenie to mo¿e byæ zaniechane na rzecz polecenia newusers(8).
.SH ZOBACZ TAK¯E
.\" mkpasswd(8), passwd(1), useradd(1)
.BR passwd (1),
.BR useradd (8),
.BR newusers (8)
.SH AUTOR
Julianne Frances Haugh (jfh@austin.ibm.com)
