.\"     Title: chsh
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 10/30/2006
.\"    Manual: Polecenia użytkowników
.\"    Source: Polecenia użytkowników
.\"
.TH "CHSH" "1" "10/30/2006" "Polecenia użytkowników" "Polecenia użytkowników"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAZWA"
chsh \- zmiana powłoki zgłoszeniowej
.SH "SKŁADNIA"
.HP 5
\fBchsh\fR [\fIopcje\fR] [\fILOGIN\fR]
.SH "OPIS"
.PP
Polecenie
\fBchsh\fR
zmienia powłokę zgłoszeniową użytkownika. Określa nazwę początkowego polecenia zgłoszeniowego użytkownika. Zwykły użytkownik może zmienić wyłącznie powłokę zgłoszeniową własnego konta, superużytkownik może zmienić powłokę zgłoszeniową dla dowolnego konta.
.SH "OPCJE"
.PP
Polecenie
\fBchsh\fR
posiada następujące opcje:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 3n
Wyświetlenie komunikatu pomocy i zakończenie działania.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR\fISHELL\fR
.RS 3n
Nazwa nowej powłoki (shell) użytkownika. Ustawienie tego pola na puste powoduje, że system wybierze domyślną powłokę logowania.
.RE
.PP
Jeżeli nie podano opcji
\fB\-s\fR, to polecenie
\fBchsh\fR
działa w trybie interaktywnym, proponując użytkownikowi bieżącą powłokę logowania. Wprowadzenie nowej wartości powoduje zmianę powłoki, a podanie wartości pustej pozostawia bieżącą powłokę. Bieżąca powłoka wyświetlana jest w nawiasach
\fI[ ]\fR
.SH "UWAGI"
.PP
Jedynym ograniczeniem nałożonym na powłokę zgłoszeniową jest to, że jej nazwa musi być wymieniona w
\fI/etc/shells\fR, chyba że polecenie chsh zostało uruchomione przez superużytkownika wówczas może być podana dowolna nazwa. Użytkownicy kont z ograniczoną powłoką logowania nie mogą jej zmieniać. Odradza się z tego powodu umieszczanie
\fI/bin/rsh\fR
w pliku
\fI/etc/shells\fR, gdyż przypadkowa zmiana na powłokę ograniczoną uniemożliwi użytkownikowi jakąkolwiek zmianę powłoki logowania, nawet z powrotem na dotychczasową.
.SH "PLIKI"
.PP
\fI/etc/passwd\fR
.RS 3n
Informacja o kontach użytkowników.
.RE
.PP
\fI/etc/shells\fR
.RS 3n
Lista dozwolonych powłok zgłoszeniowych.
.RE
.PP
\fI/etc/login.defs\fR
.RS 3n
Konfiguracja pakietu shadow.
.RE
.SH "ZOBACZ TAKŻE"
.PP
\fBchfn\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5).
