.\" $Id: dialups.5,v 1.2 2001/01/25 10:43:54 kloczek Exp $
.\" {PTM/WK/1999-09-22}
.TH DIALUPS
.SH NAZWA
dialups - plik terminalowych linii telefonicznych
.SH OPIS
Z dostêpem do systemu przez liniê telefoniczn± zwi±zane s± dwa pliki
konfiguracyjne: \fI/etc/d_passwd\fR, zawieraj±cy has³a i \fI/etc/dialups\fR,
zawieraj±cy linie. W ka¿dym wierszu pliku \fIdialups\fR zawarta jest nazwa
pliku specjalnego linii terminalowej, do której pod³±czony jest modem:
.br
.sp 1
         /dev/tty12
         /dev/tty13
.br
.sp 1
Warto jest uj±æ w nim \fBwszystkie\fR linie z dostêpem modemowym.
Po³±czenie z linii pominiêtej nie bêdzie dodatkowo weryfikowane - u¿ytkownicy
³±cz±cy siê ni± nie bêd± musieli podawaæ has³a telefonicznego.
.SH ZOBACZ TAK¯E
.BR dpasswd (1),
.BR login (1),
.BR d_passwd (5).
