.\" {PTM/WK/1999-09-17}
.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH DPASSWD 8
.SH NAZWA
\fBdpasswd\fR - zmieñ has³o telefoniczne
.SH SK£ADNIA
.B dpasswd
.RB [ - ( a | d )]
.I pow³oka
.SH OPIS
\fBdpasswd\fR dodaje, usuwa i aktualizuje has³a telefoniczne (dialup
passwords) dla pow³ok logowania u¿ytkowników.
Ka¿dorazowo, gdy u¿ytkownik loguje siê przez liniê telefoniczn±,
¿±dane jest od niego has³o telefoniczne (po poprawnym uwierzytelnieniu
jego w³asnego has³a).
.PP
\fBdpasswd\fR bêdzie prosiæ o podanie nowego has³a dwukrotnie, by upewniæ
siê, ¿e zosta³o ono poprawnie wprowadzone.
.PP
Argument \fIpow³oka\fR musi byæ pe³n±, ¶cie¿kow± nazw± programu zg³oszenia
(logowania).
.SH PLIKI
.br
.I /etc/d_passwd
.br
.I /etc/dialups
.SH ZOBACZ TAK¯E
.BR login (1)
.SH AUTOR
Julianne Frances Haugh (jfh@austin.ibm.com)
