.\"     Title: groupmod
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 12/07/2006
.\"    Manual: Polecenia Zarządzania Systemem
.\"    Source: Polecenia Zarządzania Systemem
.\"
.TH "GROUPMOD" "8" "12/07/2006" "Polecenia Zarządzania Systemem" "Polecenia Zarządzania Systemem"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAZWA"
groupmod \- modyfikuj definicję grupy systemowej
.SH "SKŁADNIA"
.HP 9
\fBgroupmod\fR [\fIopcje\fR] \fIGRUPA\fR
.SH "OPIS"
.PP
Polcenie
\fBgroupmod\fR
modifikuje definicję grupy\fIGRUPA\fR
poprzez modifikację stosownego wpisu w bazie grup.
.SH "OPCJE"
.PP
Polecenie
\fBgroupmod\fR
posiada następujące opcje:
.TP 3n
\fB\-g\fR, \fB\-\-gid\fR\fIGID\fR
Nowa wartość ID grupy
\fIGRUPA\fR. Numeryczna wartość
\fIGID\fR
musi mieć nieujemną wartość całkowitą. Wartość ta musi być unikalna chyba że użyto opcji
\fB\-o\fR. Wartości pomiędzy 0 a 999 są zwykle zarezerwowane dla grup systemowych. Pliki, dla których stary identyfikator jest identyfikatorem grupy pliku, wymagają ręcznej zmiany ID grupy.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Wyświetlenie komunikatu pomocy i zakończenie działania.
.TP 3n
\fB\-a\fR, \fB\-\-append\fR\fINOWA_GRUPA\fR
Nazwa grupy zostanie zmieniona z
\fIGRUPA\fR
na nazwę
\fINOWA_GRUPA\fR.
.TP 3n
\fB\-o\fR, \fB\-\-non\-unique\fR
Użyte z opcją
\fB\-g\fR
umożliwia zmiane
\fIGID\fR
grupy na wartość nieunikalną.
.SH "PLIKI"
.TP 3n
\fI/etc/group\fR
Informacje o grupach użytkowników.
.TP 3n
\fI/etc/gshadow\fR
Informacje chronione o grupach użytkowników.
.SH "KOD ZAKOŃCZENIA"
.PP
Polecenie
\fBgroupmod\fR
kończy działanie z następującymi wartościami kodów zakończenia:
.TP 3n
\fI0\fR
poprawne zakończenie działania programu
.TP 3n
\fI2\fR
niepoprawna składnia polecenia
.TP 3n
\fI3\fR
nieprawidłowy argument opcji
.TP 3n
\fI4\fR
specified group doesn't exist
.TP 3n
\fI6\fR
specified group doesn't exist
.TP 3n
\fI9\fR
nazwa grupy już jest w użyciu
.TP 3n
\fI10\fR
nie można zaktualizować pliku z grupami
.SH "ZOBACZ TAKŻE"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8).
