.\" $Id$
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH GROUPS 1
.SH NAZWA
groups \- wyświetlenie nazw bieżących grup
.SH SKŁADNIA
\fBgroups\fR [\fBużytkownik\fR]
.SH OPIS
\fBgroups\fR wyświetla nazwy lub wartości identyfikatorów grup.
Jeżeli wartość nie posiada odpowiedniego wpisu w \fI/etc/group\fR, to
zostanie wyświetlona jako numeryczny identyfikator grupy. Opcjonalny
parametr \fIużytkownik\fR powoduje wyświetlenie grup dla danego
\fIużytkownika\fR.
.SH UWAGA
Systemy nie obsługujące równoczesnych grup (tj. takie, w których użytkownik
może w danej być członkiem tylko jednej grupy, grupy aktywnej) będą wyświetlać
informację z \fI/etc/group\fR.
Do zmiany bieżącego rzeczywistego i efektywnego identyfikatora grupy użytkownik
musi użyć polecenia \fBnewgrp\fR lub \fBsg\fR.
.SH PLIKI
\fI/etc/group\fR \- informacja o grupach
.SH ZOBACZ TAKŻE
.BR newgrp (1),
.BR getgid (2),
.BR getgroups (2),
.BR getuid (2)
.SH AUTOR
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
