.\" $Id: groupadd.8,v 1.6 2002/03/09 11:16:18 ankry Exp $
.\" {PTM/WK/0.1/VIII-1999}
.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH GROUPADD 8
.SH NAZWA
groupadd - twórz now± grupê
.SH SK£ADNIA
\fBgroupadd\fR [\fB-g\fR \fIgid\fR [\fB-o\fR]] \fIgrupa\fR
.SH OPIS
Polecenie \fBgroupadd\fR tworzy nowe konto grupy pos³uguj±c siê
warto¶ciami podanymi w wierszu poleceñ i domy¶lnymi warto¶ciami z systemu.
W razie potrzeby zostanie wprowadzona do systemu nowa grupa.
Polecenie \fBgroupadd\fR posiada opcje:
.TP
.BI -g " gid"
Numeryczna warto¶æ identyfikatora grupy. Warto¶æ ta musi byæ niepowtarzalna,
chyba ¿e u¿yto opcji \fB-o\fR. Warto¶æ ID grupy nie mo¿e byæ ujemna. Domy¶lnie
u¿ywana jest najmniejsza warto¶æ identyfikatora wiêksza ni¿ 99 a wiêksza ni¿
jakiejkolwiek innej grupy.
Warto¶ci miêdzy 0 a 99 s± zwykle zarezerwowane dla kont systemowych.
.SH PLIKI
.IR /etc/group "   - informacja o kontach grup"
.br
.IR /etc/gshadow " - bezpieczna informacja o kontach grup"
.SH ZOBACZ TAK¯E
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR groupdel (8),
.BR groupmod (8).
.BR useradd (8),
.BR userdel (8),
.BR usermod (8),
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
.SH OD T£UMACZA
Niniejsza dokumentacja opisuje polecenie wchodz±ce w sk³ad pakietu shadow.
Istnieje wiele programów i skryptów do zarz±dzania kontami u¿ytkowników czy
grup. Z uwagi na powtarzaj±ce siê nazwy poleceñ, upewnij siê, ¿e korzystasz
z w³a¶ciwej dokumentacji.
