.\" $Id: groupmod.8,v 1.11 2004/12/12 20:58:26 kloczek Exp $
.\" {PTM/WK/0.1/VIII-1999}
.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH GROUPMOD 8
.SH NAZWA
groupmod - zmieñ dane grupy
.SH SK£ADNIA
\fBgroupmod\fR [\fB-g\fR \fIGID\fR [\fB-o\fR]] [\fB-n\fR \fINOWA_NAZWA_GRUPY\fR]
\fIGRUPA\fR
.SH OPIS
Polecenie \fBgroupmod\fR modyfikuje systemowe pliki kont tak, by
odzwierciedliæ w nich zmiany grup podane w wierszu poleceñ.
.SH OPCJE
Polecenie \fBgroupmod\fR posiada nastêpuj±ce opcje:
.IP "\fB-g\fR \fIGID\fR"
Numeryczna warto¶æ identyfikatora grupy (group ID). Warto¶æ ta musi byæ
niepowtarzalna, chyba ¿e u¿yto opcji \fB-o\fR. Nie mo¿e byæ ujemna.
Warto¶ci pomiêdzy 0 a 999 s± zwykle zarezerwowane dla grup systemowych. 
Pliki, dla których stary identyfikator jest identyfikatorem
grupy pliku, wymagaj± rêcznej zmiany ID grupy.
.IP "\fB-n\fR \fINOWA_NAZWA_GRUPY\fR"
Nazwa grupy zostanie zmieniona z \fIGRUPA\fR na \fINOWA_NAZWA_GRUPY\fR.
.SH PLIKI
\fI/etc/group\fR	\- informacja o grupach
.br
\fI/etc/gshadow\fI	\- bezpieczna informacja o grupach
.SH KOD ZAKOÑCZENIA
.TP 2
Polecenie \fBgroupmod\fR koñczy dzia³anie z nastêpuj±cymi warto¶ciami kodów zakoñczenia:
.br
\fB0\fR	\- powodzenie
.br
\fB2\fR	\- niew³a¶ciwa sk³adnia parametrów polecenia
.br
\fB3\fR	\- niew³a¶ciwe parametry opcji
.br
\fB4\fR	\- gid jest ju¿ u¿ywany (i nie u¿yto opcji -o)
.br
\fB6\fR	\- podana grupa nie istnieje
.br
\fB9\fR	\- grupa jest ju¿ u¿ywana
.br
\fB10\fR	\- niemo¿liwa aktualizacja plików grup
.SH ZOBACZ TAK¯E
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR groupadd (8),
.BR groupdel (8),
.BR useradd (8),
.BR userdel (8),
.BR usermod (8)
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
