.\" {PTM/WK/1999-09-18}
.\" Copyright 1992, Phillip Street and Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)lastlog.8	3.3	08:24:58	29 Sep 1993 (National Guard Release)
.\"
.TH LASTLOG 8
.SH NAZWA
lastlog \- sprawd¼ plik ostatnich logowañ (lastlog)
.SH SK£ADNIA
.B lastlog
.RB [ -u
.IR uid ]
.RB [ -t
.IR dni
.SH OPIS
\fBlastlog\fR formatuje i wy¶wietla zawarto¶æ dziennika ostatnich logowañ,
\fI/var/log/lastlog\fR.  Wy¶wietlone zostan± \fBnazwa u¿ytkownika\fR,
\fBport\fR i \fBczas ostatniego logowania\fR.
Domy¶lnie (bez flag) pozycje pliku wy¶wietlane s± w kolejno¶ci identyfikatorów
u¿ytkowników (UID).
Wprowadzenie opcji \fB-u \fInazwa_u¿ytkownika\fR spowoduje wy¶wietlenie
pozycji opisuj±cej ostatnie rozpoczêcie sesji tylko dla tego u¿ytkownika.
U¿ycie \fB-t \fIdni\fR powoduje, ¿e bêd± wy¶wietlone ostatnie logowania
u¿ytkowników nowsze ni¿ sprzed zadanej liczby \fIdni\fR.
Opcja \fB-t\fR przes³ania u¿ycie opcji \fB-u\fR.
.PP
Je¿eli u¿ytkownik nigdy siê nie logowa³ to zamiast portu i czasu logowania
zostanie wy¶wietlony komunikat \fB"**Never logged in**"\fR (nigdy siê nie
logowa³).
.SH PLIKI
.IR /var/log/lastlog " - dziennik ostatnich logowañ"
.SH PRZESTROGI
Du¿e luki w numeracji UID powoduj±, ¿e program bêdzie pracowa³ d³u¿ej, nie
wy¶wietlaj±c wyników (np. je¶li mmdf=800, za¶ ostatni uid=170, to program
bêdzie sprawia³ wra¿enie zawieszonego w trakcie przetwarzania uid 171-799).
.SH AUTORZY
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
.br
Phillip Street
