.\" $Id: login.1,v 1.9 2003/04/26 13:24:15 kloczek Exp $
.\" {PTM/WK/1999-09-25}
.\" Copyright 1989 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH LOGIN 1
.SH NAZWA
login \- rozpocznij sesjê pracy w systemie
.SH SK£ADNIA
\fBlogin\fR [\fB-p\fR] [\fIu¿ytkownik\fR] [\fIZMIENNA=WARTO¦Æ\fR ...]
.br
\fBlogin\fR [\fB-p\fR] [\fB-h \fIhost\fR] [\fB-f \fIu¿ytkownik\fR]
.br
\fBlogin\fR [\fB-p\fR] \fB-r \fIhost\fR
.SH OPIS
.B login
s³u¿y do utworzenia nowej sesji pracy z systemem. Zwykle wywo³ywane jest
automatycznie w odpowiedzi na zachêtê
.I login:
na terminalu u¿ytkownika.
.B login
mo¿e byæ specyficzne dla pow³oki i nie mo¿e zostaæ wywo³ane jako podproces.
Najczê¶ciej,
.B login
traktowane jest przez pow³okê jako \fBexec login\fR, co powoduje opuszczenie
przez u¿ytkownika bie¿±cej pow³oki.
Próba wykonania \fBlogin\fR z pow³oki innej ni¿ zg³oszeniowa powoduje
wypisanie komunikatu o b³êdzie.
.PP
Przy wywo³aniu polecenia z zachêty \fIlogin:\fR, u¿ytkownik mo¿e po swojej
nazwie wprowadziæ zmienne ¶rodowiska. Zmienne te wprowadzane s± w postaci:
\fBNAZWA=WARTO¦Æ\fR. Nie wszystkie zmienne mog± jednak byæ ustawione w ten
sposób, szczególnie \fBPATH\fR, \fBHOME\fR i \fBSHELL\fR.
Dodatkowo, zakazane mo¿e byæ \fBIFS\fR (input field separator: separator pól
wej¶ciowych), je¿eli pow³ok± zg³oszeniow± u¿ytkownika jest \fB/bin/sh\fR.
.PP
U¿ytkownik pytany jest o has³o, je¶li takowe istnieje.
Dla zapobie¿enia ujawnieniu has³a wy¶wietlanie wprowadzanych znaków jest
w trakcie jego wprowadzania wy³±czone. Dozwolona jest jedynie niewielka liczba
nieudanych prób podania has³a. Po wyczerpaniu limitu prób \fBlogin\fR koñczy
pracê za¶ po³±czenie komunikacyjne jest zrywane.
.PP
Je¿eli dla konta u¿ytkownika w³±czona jest kontrola wa¿no¶ci has³a, mo¿e on
byæ poproszony o podanie nowego has³a przed kontynuacj±. Bêdzie wówczas musia³
podaæ stare i nowe has³o. Wiêcej informacji na ten temat znajduje siê
w \fBpasswd\fR(1).
.PP
Po poprawnym rozpoczêciu sesji (zalogowaniu siê), zostanie wy¶wietlona
wiadomo¶ci dnia (je¶li jest) i informacja o stanie skrzynki pocztowej.
Mo¿na wy³±czyæ wy¶wietlanie zawarto¶ci pliku wiadomo¶ci dnia,
\fI/etc/motd\fR, tworz±c w swoim katalogu domowym plik \fI.hushlogin\fR
o zerowej d³ugo¶ci.
Informacja o stanie skrzynki pocztowej jest jedn± z:
"\fBMasz now± pocztê.\fR" (You have new mail.),
"\fBMasz pocztê.\fR" (You have mail.) lub "\fBNie masz poczty.\fR" (No Mail.)
\- stosownie do stanu skrzynki.
.PP
Identyfikator u¿ytkownika i grupy (UID i GID) zostan± ustawione wed³ug
warto¶ci w pliku \fI/etc/passwd\fR.
Warto¶ci \fB$HOME\fR, \fB$SHELL\fR, \fB$PATH\fR, \fB$LOGNAME\fR i \fB$MAIL\fR
ustawiane s± stosownie do odpowiednich pól danego wpisu pliku hase³.
Mog± byæ równie¿ ustawiane warto¶ci ulimit, umask oraz nice wed³ug wpisów
w polu GECOS.
.PP
W niektórych systemach zostanie ustawiona zmienna ¶rodowiskowa \fB$TERM\fR,
wskazuj±ca na typ terminala na linii tty, jak podano w \fI/etc/ttytype\fR.
.PP
Mo¿e tak¿e zostaæ wykonany skrypt startowy (inicjacyjny) odpowiedniego
interpretatora poleceñ.
Bardziej szczegó³owe informacje na ten temat mo¿na znale¼æ w odpowiednim
rozdziale podrêcznika man.
.PP
Logowanie do podsystemu jest wykazywane przez obecno¶æ "*" jako pierwszego
znaku pow³oki zg³oszeniowej. Podany katalog domowy zostanie potraktowany jako
katalog g³ówny nowego systemu plików, do którego u¿ytkownik siê zaloguje.
.SH OPCJE
.TP
.B -p
Zachowanie ¶rodowiska.
.TP
.B -f
Nie przeprowadzanie autentykacji, u¿ytkownik ju¿ zosta³ zautentykowany.
.TP
.B -h
Name zdalnego hosta dla tego logowania.
.TP
.B -r
Przeprowadzenie procedury automatycznego logowania dla rlogin.
.PP
Opcje \fB-r\fP, \fB-h\fP i \fB-f\fP mog± byæ u¿ywane tylko w przypadku
wywo³ania \fBlogin\fP przez roota.
.SH PRZESTROGI
Niniejsza wersja \fBlogin\fR posiada wiele opcji kompilacji, z których tylko
czê¶æ bêdzie mieæ zastosowanie w danej instalacji.
.PP
Po³o¿enie plików mo¿e byæ ró¿ne w zale¿no¶ci od konfiguracji systemu.
.SH PLIKI
.br
\fI/var/run/utmp\fR \- lista bie¿±cych sesji pracy
.br
\fI/var/log/wtmp\fR \- lista poprzednich sesji pracy
.br
\fI/etc/passwd\fR \- informacje o kontach u¿ytkowników
.br
\fI/etc/shadow\fR \- zakodowane has³a i informacje o ich wa¿no¶ci
.br
\fI/etc/motd\fR \- plik 'wiadomo¶ci dnia'
.br
\fI/etc/nologin\fR \- zapobiega logowaniu innych ni¿ root
.br
\fI/etc/ttytype\fR \- lista typów terminali
.br
.br
\fI$HOME/.hushlogin\fR \- zapobiega wy¶wietlaniu wiadomo¶ci dnia
.SH ZOBACZ TAK¯E
.BR mail (1),
.BR passwd (1),
.BR sh (1),
.BR su (1),
.BR login.defs (5),
.BR nologin (5),
.BR passwd (5),
.BR getty (8)
.SH AUTOR
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
