.\" $Id: login.access.5,v 1.4 2005/12/01 20:38:27 kloczek Exp $
.TH LOGIN.ACCESS 5
.\" .Dt SKEY.ACCESS 5
.\" .Os FreeBSD 1.2
.SH NAZWA
login.access \- tabela kontroli dostępu logowania
.SH OPIS
Plik
.I login.access
określa kombinacje (użytkownik, host) i/lub (użytkownik, tty) 
dla których logowanie będzie albo przyjęte albo odrzucone.
.PP
Gdy ktoś się loguje, plik
.I login.access
przeszukiwany jest do znalezienia pierwszej pozycji pasującej do danej
kombinacji (użytkownik, host), lub, w przypadku logowań nie\-sieciowych
kombinacji (użytkownik, tty). Pole zezwolenia w tej tablicy pozycji określa
czy logowanie będzie przyjęte czy odrzucone.
.PP
Każdy wiersz tabeli kontroli dostępu logowania posiada trzy, oddzielone
znakiem dwukropka, pola:
.sp 1
.IR 	zezwolenie : użytkownicy : pochodzenie
.sp 1
Pierwsze pole powinno zawierać znak "\fB+\fR" (dostęp zapewniony) lub "\fB\-\fR"
(zakaz dostępu). Drugie z pól powinno zawierać listę jednego lub więcej nazw
użytkowników, grup lub słowo
.B ALL
(zawsze pasuje do wszystkich). Trzecie pole powinno być listą jednej lub więcej
nazw tty (dla logowań nie\-sieciowych), nazw hostów, domen (rozpoczynających się
od kropki), adresów hostów, internetowych numerów sieci (kończących się
kropką), słowem
.B ALL
(wszystkie \- zawsze pasuje) lub
.B LOCAL
(dopasowuje dowolny łańcuch nie zawierający kropki).
Jeżeli uruchomisz NIS możesz użyć @nazwagrupysieciowej we wzorcu hosta
lub użytkownika.
.\" @netgroupname
.PP
Operator
.B EXCEPT
(oprócz) umożliwia pisanie złożonych reguł.
.PP
Plik grup przeszukiwany jest wyłącznie wtedy, gdy nazwa nie pasuje do
logującego się użytkownika. Dopasowywane są tylko te grupy, w których
użytkownik jest jawnie wymieniony: program nie sprawdza wartości
identyfikatora grupy głównej użytkownika.
.SH PLIKI
.I /etc/login.access
.SH ZOBACZ TAKŻE
.BR login (1)
.SH AUTOR
Guido van Rooij
