.\" $Id: newusers.8,v 1.4 2001/01/27 02:55:54 kloczek Exp $
.\" {PTM/WK/1999-09-15}
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH NEWUSERS 8
.SH NAZWA
newusers - wsadowa aktualizacja i tworzenie nowych u¿ytkowników
.SH SK£ADNIA
\fBnewusers\fR [\fInowi_u¿ytkownicy\fR]
.SH OPIS
\fBnewusers\fR odczytuje plik zawieraj±cy pary: nazwa u¿ytkownika i podane
jawnym tekstem has³o. Odczytan± informacjê wykorzystuje do aktualizacji grupy
istniej±cych u¿ytkowników  lub utworzenia nowych.
Ka¿dy wiersz pliku posiada taki sam format jak standardowy plik hase³ (patrz
\fBpasswd\fR(5)), z nastêpuj±cymi wyj±tkami:
.IP "\fIpw_passwd\fR" 10
To pole zostanie zakodowane i u¿yte jako nowa warto¶æ zakodowanego has³a.
.IP "\fIpw_age\fR"
Dla chronionych hase³ (shadow) pole zostanie zignorowane je¶li u¿ytkownik ju¿
istnieje.
.IP "\fIpw_gid\fR"
Pole to mo¿e zawieraæ nazwê istniej±cej grupy. Dany u¿ytkownik zostanie
wówczas dodany do jej cz³onków. Je¿eli podano numeryczny identyfikator
nieistniej±cej grupy, to zostanie za³o¿ona nowa grupa o tym identyfikatorze.
.IP "\fIpw_dir\fR"
Zostanie wykonane sprawdzenie czy istnieje katalog o tej nazwie. Je¿eli nie,
to bêdzie on utworzony. W³a¶cicielem zostanie ustanowiony tworzony
(lub aktualizowany) u¿ytkownik. Grupa katalogu zostanie ustawiona na grupê
u¿ytkownika.
.PP
Polecenie to przeznaczone jest do u¿ytku w du¿ych systemach, gdzie aktualizuje
siê wiele kont naraz.
.SH PRZESTROGI
.\" Po u¿yciu \fBnewusers\fR musi zostaæ wykonane polecenie \fImkpasswd\fR,
.\" aktualizuj±ce pliki DBM hase³ (DBM password files).
Plik ¼ród³owy, zawieraj±cy niezakodowane has³a, musi byæ chroniony.
.SH ZOBACZ TAK¯E
.\" mkpasswd(8), passwd(1), useradd(1)
.BR passwd (1),
.BR useradd (8)
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
