.\" $Id: passwd.5,v 1.4 2005/04/05 18:47:51 kloczek Exp $
.\" Copyright 1989 - 1990, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH PASSWD 5 "24 Czerwiec 1993" "Linux" "Podrêcznik programisty linuxowego"
.SH NAZWA
passwd \- plik passwd definiuj±cy u¿ytkowników systemu
.SH OPIS
Plik 
.B passwd
jest plikiem tekstowym ASCII, który zawiera listê u¿ytkowników systemu
oraz has³a jakich musz± u¿ywaæ aby otrzymaæ dostêp do systemu.
Ka¿dy powinien móc odczytaæ informacje z pliku passwd (poniewa¿ has³a
w tym pliku s± zakodowane jest to poprawne) lecz prawo do modyfikacji
pliku powinien mieæ tylko administrator.
Dodaj±c nowego u¿ytkownika nale¿y pole przeznaczone na has³o pozostawiæ puste
i u¿yæ programu \fBpasswd\fP(1). Gwiazdka lub inny pojedynczy znak w polu
has³a oznacza, ze u¿ytkownik nie mo¿e dostaæ siê do systemu przez \fBlogin\fP(1). 
Je¶li g³ówny system plików jest na ram dysku (/dev/ram) nale¿y
plik passwd skopiowaæ na dyskietkê przechowuj±c± g³ówny system plików
przed zamkniêciem systemu. Trzeba równie¿ sprawdziæ prawa dostêpu do.
Je¶li trzeba utworzyæ grupê u¿ytkowników, ich identyfikatory grupy
GID musz± byæ równe oraz musi istnieæ odpowiednia pozycja w pliku
\fI/etc/group\fP, lub grupa nie bêdzie istnia³a.  
.PP
Ka¿da pozycja zajmuje jeden wiersz w formacie:
.sp
login_name:has³o:UID:GID:imie_nazwisko:katalog:pow³oka
.RS
.RE
.sp
Krótki opis poszczególnych pól:
.sp
.RS
.TP 1.0in
.I login_name
nazwa u¿ytkownika w systemie (radzê u¿ywaæ ma³ych liter).
.TP
.I has³o
zakodowane has³o u¿ytkownika.
.TP
.I UID
identyfikator u¿ytkownika (liczbowo).
.TP
.I GID
identyfikator grupy (liczbowo).
.TP
.I imiê_nazwisko
Opisowa nazwa u¿ytkownika, zwykle imiê i nazwisko (wykorzystywane
przez programy pocztowe).
.TP
.I katalog
katalog macierzysty ($HOME) u¿ytkownika.
.TP
.I pow³oka
program jaki uruchomiæ po wej¶ciu u¿ytkownika do systemu.
(je¶li pusty u¿yj /bin/sh, je¶li istnieje /etc/shells i
dana pow³oka nie jest tam wymieniona, u¿ytkownik nie bêdzie móg³
dostaæ siê do systemu wykorzystuj±c protokó³ ftp).
.RE
.SH PLIKI
.I /etc/passwd
.SH "ZOBACZ TAK¯E"
.BR login (1),
.BR passwd (1),
.BR group (5)
