.\" $Id: passwd.1,v 1.16 2005/12/01 20:38:27 kloczek Exp $
.\" Copyright 1989 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH PASSWD 1
.SH NAZWA
passwd \- zmiana hasła użytkownika
.SH SKŁADNIA
\fBpasswd\fR [\fB\-f\fR|\fB\-s\fR] [\fInazwa\fR]
.br
\fBpasswd\fR [\fB\-g\fR] [\fB\-r\fR|\fB\-R\fR] \fIgrupa\fR
.br
\fBpasswd\fR [\fB\-x\fR \fImax\fR] [\fB\-n\fR \fImin\fR]
[\fB\-w\fR \fIostrzeż\fR] [\fB\-i\fR \fInieakt\fR] \fIlogin\fR
.br
\fBpasswd\fR {\fB\-l\fR|\fB\-u\fR|\fB\-d\fR|\fB\-S\fR|\fB\-e\fR} \fIlogin\fR
.SH OPIS
\fBpasswd\fR zmienia hasła kont użytkowników i grup.
Zwykły użytkownik może zmienić wyłącznie hasło własnego konta, superużytkownik
może zmieniać hasła dowolnych kont.
Administrator grupy może zmienić hasło tej grupy.
\fBpasswd\fR zmienia także informacje o koncie, takie jak pełna nazwa
użytkownika, jego powłoka zgłoszeniowa (logowania) czy daty i interwały dotyczące
ważności hasła.
.PP
Użycie opcji \fB\-s\fR powoduje wywołanie przez \fBpasswd\fR programu \fBchsh\fR
w celu zmiany powłoki użytkownika, użycie opcji \fB\-f\fR powoduje wywołanie
przez passwd programu chfn w celu zmiany infirmacji o użytkowniku. Te dwie opcje
istnieją jedynie dla zgodności, gdyż wymienione programy mogą być wywoływane
bezpośrednio.
.SS Zmiany hasła
Na początku użytkownik pytany jest o stare, dotychczasowe hasło, jeśli takie
istnieje. Hasło to jest kodowane i porównywane z przechowywanym hasłem.
Użytkownik ma tylko jedną próbę na wprowadzenie poprawnego hasła.
Superużytkownikowi zezwala się na pominięcie tego kroku, aby mogły być
zmienione hasła, których zapomniano.
.PP
Po wprowadzeniu hasła, sprawdzana jest informacja o jego wieku, by stwierdzić
czy użytkownikowi wolno w danym czasie zmienić hasło.
Jeżeli nie, to \fBpasswd\fR odmawia zmiany hasła i kończy pracę.
.PP
Następnie użytkownik proszony jest o nowe hasło, zastępujące dotychczasowe.
Hasło podlega sprawdzeniu jego zawiłości. Jako ogólną wskazówkę można podać,
że hasła powinny składać się z 6 do 8 znaków, zawierając po jednym lub więcej
znaków z każdej z poniższych kategorii:
.IP "" .5i
małe litery alfabetu
.IP "" .5i
duże litery alfabetu
.IP "" .5i
cyfry od 0 do 9
.IP "" .5i
znaki interpunkcyjne
.PP
Należy uważać, by nie użyć domyślnych systemowych znaków akcji erase lub kill.
\fBpasswd\fR odrzuci każde niedostatecznie skomplikowane hasło.
.PP
Jeśli hasło zostanie przyjęte, to \fBpasswd\fR prosi o jego powtórzenie
i porównuje drugi wpis z pierwszym.
Oba wpisy muszą być takie same, by hasło zostało zmienione.
.SS Hasła grup
Jeżeli posłużono się opcją \fB\-g\fR, to zmieniane jest hasło podanej grupy.
Użytkownik powinien być albo superużytkownikiem albo administratorem tej grupy.
Nie występuje pytanie o bieżące hasło grupy.
Do usuwania bieżącego hasła danej grupy służy opcja \fB\-g\fR w połączeniu
z \fB\-r\fR. Pozwala to na dostęp do grupy tylko jej członkom.
Opcja \fB\-R\fR w połączeniu z \fR\-g\fR ogranicza dostęp do grupy wszystkim
użytkownikom.
.SS Informacja o ważności konta
Superużytkownik może zmieniać informację o wieku konta posługując się opcjami
\fB\-x\fR, \fB\-n\fR, \fB\-w\fR oraz \fB\-i\fR.
Opcja \fB\-x\fR służy do ustawiania maksymalnej liczby dni, przez jakie hasło
pozostaje ważne.
Po upływie \fImax\fR dni, hasło musi być zmienione.
Opcja \fB\-n\fR ustawia minimalną liczbę dni, jakie muszą upłynąć zanim hasło
będzie mogło być zmienione.
Użytkownik nie otrzyma zezwolenia na zmianę hasła przed upływem \fImin\fR dni.
Opcja \fB\-w\fR służy do ustawienia liczby dni przed upływem terminu ważności
hasła, przez które użytkownik będzie otrzymywał ostrzeżenie mówiące mu, ile dni
pozostało do tej daty. Ostrzeżenia zaczną pojawiać się \fIostrzeż\fR dni przed
upływem ważności hasła.
Opcja \fB\-i\fR (nieaktywność) służy do wyłączania konta po upływie zadanej
liczby dni po wygaśnięciu hasła.
Po upływie \fInieakt\fR dni od przeterminowania hasła użytkownik nie może już
korzystać z konta.
.PP
Jeśli istnieje potrzeba natychmiastowego przeterminowania hasła dla danego
konta, można posłużyć się opcją \fB\-e\fR. Spowoduje to zmuszenie użytkownika
do zmiany hasła przy najbliższym logowaniu. Za pomocą opcji \fB\-d\fR można
skasować hasło użytkownika (uczynić je pustym). Należy zachować szczególną
ostrożność używając tej opcji, gdyż może ona spowodować, że do zalogowania
się na konto nie będzie w ogóle potrzebne hasło, pozostawiając system otwartym
dla nieproszonych gości.
.SS Utrzymywanie i konserwacja konta
Konta użytkowników mogą być blokowane i odblokowywane przy pomocy opcji
\fB\-l\fR i \fB\-u\fR.
Opcja \fB\-l\fR wyłącza konto zmieniając jego hasło na wartość nieodpowiadającą
żadnemu możliwemu zakodowanemu hasłu.
Opcja \fB\-u\fR ponownie udostępnia konto przywracając uprzednią wartość hasła.
.PP
Stan konta można uzyskać przy pomocy opcji \fB\-S\fR.
Informacja o stanie składa się z 6 części.
Pierwsza wskazuje, czy konto użytkownika jest zablokowane (L) (locked),
nie posiada hasła (NP) (no password) lub ma funkcjonalne hasło (P) (password).
Druga część podaje datę ostatniej zmiany hasła.
następne cztery to minimalny wiek, maksymalny wiek, okres ostrzegania i okres
nieaktywności hasła.
.SS Podpowiedzi dotyczące haseł użytkownika
Bezpieczeństwo hasła zależy od siły algorytmu kodującego oraz rozmiaru
przestrzeni kluczy. Metoda kodowania używana w Systemie \fB\s\-2UNIX\s+2\fR
oparta jest o algorytm NBS DES i jest bardzo bezpieczna. Rozmiar przestrzeni
kluczy zależy od losowości wybranego hasła.
.PP
Naruszenia bezpieczeństwa haseł wynikają zwykle z beztroski przy wyborze lub
przechowywaniu hasła. Z tego powodu nie należy wybierać hasła występującego
w słowniku ani takiego, które wymaga zanotowania. Hasło nie powinno też być
poprawną nazwą, imieniem, nazwiskiem, numerem prawa jazdy, datą urodzenia czy
elementem adresu. Wszystkie z powyższych mogą być użyte do odgadnięcia hasła
i naruszenia bezpieczeństwa systemu.
.PP
Hasło musi być łatwe do zapamiętania, tak by nie być zmuszonym do jego
zapisywania na kartce. Można to osiągnąć sklejając ze sobą dwa krótkie słowa,
ze wstawionym pomiędzy nie znakiem specjalnym lub cyfrą.
Na przykład, Pass%word, Lew7konia.
.PP
Inna metoda konstrukcji hasła polega na wyborze łatwego do zapamiętania zdania
(np. z literatury) i wyborze pierwszej bądź ostatniej litery każdego wyrazu.
Przykładem tego jest
.IP "" .5i
Ask not for whom the bell tolls.
.PP
co daje
.IP "" .5i
An4wtbt,
.PP
albo też
.IP "" .5i
A czy znasz Ty, bracie młody
.PP
co daje
.IP "" .5i
A3zTbm.
.PP
W zasadzie można być pewnym, że niewielu crackerów będzie mieć takie hasło
w swoich słownikach. Należy jednak wybierać własne metody konstrukcji haseł
a nie polegać wyłącznie na opisanych tutaj.
.SS Uwagi o hasłach grup
Hasła grup są nieodłącznym problemem bezpieczeństwa, gdyż do ich znajomości
uprawniona jest więcej niż jedna osoba.
Grupy są jednak użytecznym narzędziem pozwalającym na współpracę między
różnymi użytkownikami.
.SH PRZESTROGI
Niektóre opcje mogą nie być obsługiwane. 
Sprawdzanie złożoności hasła może różnić się w różnych instalacjach. Zachęca
się użytkownika do wyboru tak skomplikowanego hasła, z jakim będzie mu
wygodnie.
Użytkownicy mogą nie móc zmienić hasła w systemie przy włączonym NIS, jeśli
nie są zalogowani do serwera NIS.
.SH PLIKI
\fI/etc/passwd\fR	\- informacja o kontach użytkowników
.br
\fI/etc/shadow\fR	\- zakodowane hasła użytkowników
.SH KOD ZAKOŃCZENIA
.TP 2
Polecenie \fBpasswd\fR kończy działanie z następującymi wartościami kodów zakończenia:
.br
\fB0\fR	\- powodzenie
.br
\fB1\fR	\- permission denied
.br
\fB2\fR	\- niewłaściwa składnia parametrów polecenia
.br
\fB3\fR	\- nieoczekiwanie niepowodzenie, nic nie zostało wykonane
.br
\fB4\fR	\- nieoczekiwanie niepowodzenie, brakuje pliku passwd
.br
\fB5\fR	\- passwd file busy, try again later
.br
\fB6\fR	\- niewłaściwe parametry opcji
.SH "ZOBACZ TAKŻE"
.BR group (5),
.BR passwd (5),
.BR shadow (5)
.SH AUTOR
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
