.\" $Id$
.\" Copyright 1992, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH PWCK 8
.SH NAZWA
pwck \- weryfikacja spójności plików haseł
.SH OPIS
\fBpwck\fR [\fB\-r\fR] [\fIpasswd\fR \fIshadow\fR]
.SH OPIS
\fBpwck\fR weryfikuje integralność informacji autentykacji systemowej.
W plikach \fI/etc/passwd\fR i \fI/etc/shadow\fR sprawdzane są wszystkie
pozycje, by upewnić się, że każda z nich posiada właściwy format
i poprawne dane w każdym z pól. Użytkownik monitowany jest o usunięcie
pozycji, które są sformatowane niepoprawnie lub posiadają inne nie dające
się skorygować błędy.
.P
Kontrolowane jest czy każda pozycja posiada:
.sp
.in +.5i
\- właściwą liczbę pól
.br
\- unikalną nazwę użytkownika
.br
\- poprawny identyfikator użytkownika i grupy
.br
\- poprawną grupę główną
.br
\- poprawny katalog domowy
.br
\- poprawną powłokę zgłoszeniową (startową)
.in -.5i
.sp
.P
Kontrola właściwej liczby pól i niepowtarzalnej nazwy użytkownika jest
decydująca. Jeżeli pozycja posiada błędną liczbę pól, to użytkownik jest
proszony o usunięcie całej pozycji (wiersza).
Jeżeli użytkownik nie potwierdzi decyzji o usunięciu, to pomijane są wszelkie
dalsze sprawdzenia.
Pozycja z powtórzoną nazwą użytkownika powoduje monit o usunięcie, ale nadal
będą wykonywane pozostałe sprawdzenia.
Wszystkie inne błędy dają ostrzeżenia a użytkownik jest zachęcany
do uruchomienia polecenia \fBusermod\fR, by je poprawić.
.P
Polecenia działające na pliku \fI/etc/passwd\fR nie potrafią zmieniać
uszkodzonych lub powielonych pozycji. W takich okolicznościach powinien być
używany \fBpwck\fR, by usunąć nieprawidłową pozycję.
.SH OPCJE
Domyślnie \fBpwck\fR działa na plikach \fI/etc/passwd\fR oraz \fI/etc/shadow\fR.
Przy pomocy parametrów \fIpasswd\fR i \fIshadow\fR użytkownik może wybrać inne
pliki.
Dodatkowo, użytkownik może wykonać polecenie w trybie tylko\-do\-odczytu, poprzez
podanie flagi \fB\-r\fR.
Powoduje to, że na wszystkie pytania dotyczące zmian zostanie, bez ingerencji
użytkownika, użyta odpowiedź \fBnie\fR.
\fBpwck\fR może być również użyty do sortowania pozycji w plikach \fI/etc/passwd\fR 
oraz \fI/etc/shadow\fR według UID. By włączyć tryb sortowania należy przekazać
opcję \fB\-s\fR. Nie są wtedy przeprowadzane żadne kontrole, tylko sortowanie.
.SH PLIKI
\fI/etc/passwd\fR	\- informacja o kontach użytkowników
.br
\fI/etc/shadow\fR	\- zakodowana informacja o hasłach
.br
\fI/etc/group\fR	\- informacja o grupach
.SH KOD ZAKOŃCZENIA
.TP 2
Polecenie \fBpwck\fR kończy działanie z następującymi wartościami kodów zakończenia:
.br
\fB0\fR	\- powodzenie
.br
\fB1\fR	\- niewłaściwa składnia parametrów polecenia
.br
\fB2\fR	\- jedna lub więcej złych pozycji pliku haseł
.br
\fB3\fR	\- niemożliwe otwarcie plików haseł
.br
\fB4\fR	\- niemożliwa blokada plików haseł
.br
\fB5\fR	\- niemożliwa aktualizacja plików haseł
.SH ZOBACZ TAKŻE
.BR usermod (8),
.BR group (5),
.BR passwd (5),
.BR shadow (5)
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
