.\" $Id: pwconv.8,v 1.5 2005/12/01 20:38:27 kloczek Exp $
.TH PWCONV 8 "26 września 1997"
.SH NAZWA
pwconv, pwunconv, grpconv, grpunconv \- konwersja dot. chronionych plików haseł i grup
.SH SKŁADNIA
.B pwconv
.br
.B pwunconv
.br
.B grpconv
.br
.B grpunconv
.SH OPIS
Wszystkie te cztery programy działają na zwykłych i dodatkowych (shadow)
plikach haseł i grup:
.IR /etc/passwd ", " /etc/group ", " /etc/shadow " i " /etc/gshadow .

.B pwconv
.RI "tworzy " shadow " z " passwd " i opcjonalnie istniejącego " shadow .
.B pwunconv
.RI "tworzy " passwd " z " passwd " i " shadow " a następnie usuwa " shadow .
.B grpconv
.RI "tworzy " gshadow " z " group " i opcjonalnie istniejącego " gshadow .
.B grpunconv
.RI "tworzy " group " z " group " i " gshadow " a następnie usuwa " gshadow .

Każdy z programów zdobywa niezbędne blokady przed konwersją.

.BR pwconv " i " grpconv
są podobne. Po pierwsze, z pliku dodatkowego usuwane są pozycje, które
nie istnieją w pliku głównym. Następnie, w pliku dodatkowym aktualizowane są
pozycje nie posiadające 'x' jako hasła w pliku głównym. Dodawane są pozycje
brakujące w stosunku do pliku głównego. Na koniec, hasła w pliku głównym
zastępowane są przez 'x'. Programy te mogą służyć zarówno do początkowej
konwersji jak i do aktualizacji dodatkowego pliku haseł jeśli plik główny
zmieniany był ręcznie.

Przy dodawaniu nowych wpisów do
.IR /etc/shadow
.B pwconv
użyje wartości
.BR PASS_MIN_DAYS ", " PASS_MAX_DAYS " i " PASS_WARN_AGE
z pliku
.IR /etc/login.defs .

.RB "Podobnie, " pwunconv " oraz " grpunconv
są zbliżone.  Hasła w pliku głównym aktualizowane są na podstawie pliku
dodatkowego (shadow). Wpisy istniejące w pliku głównym, a nie posiadające
odpowiedników w dodatkowym są pozostawiane bez zmian. Na koniec usuwany
jest plik dodatkowy.

Część informacji o ważności haseł jest tracona przez
.BR pwunconv .
Przeprowadza on konwersję tego, co potrafi.
.SH BŁĘDY
Błędy w plikach haseł czy grup (takie jak nieprawidłowe czy powtórzone
pozycje) mogą spowodować zapętlenie się omawianych programów lub różnego
rodzaju inne błędne zachowanie. Przed konwersją na lub z dodatkowych plików
haseł lub grup proszę uruchomić \fBpwck\fR i \fBgrpck\fR, by poprawić tego
rodzaju błędy.
.SH ZOBACZ TAKŻE
.BR login.defs (5),
.BR grpck (8),
.BR pwck (8),
.BR shadowconfig (8)
