.\" $Id: shadowconfig.8,v 1.4 2005/04/05 18:47:51 kloczek Exp $
.TH SHADOWCONFIG 8 "19 kwietnia 1997" "Debian GNU/Linux"
.SH NAZWA
shadowconfig \- prze³±cza ochronê hase³ i grup przez pliki shadow
.SH SK£ADNIA
.B "shadowconfig"
.IR on " | " off
.SH OPIS
.PP
.B shadowconfig on
w³±cza ochronê hase³ i grup przez dodatkowe, przes³aniane pliki (shadow);
.B shadowconfig off
wy³±cza dodatkowe pliki hase³ i grup.
.B shadowconfig
wy¶wietla komunikat o b³êdzie i koñczy pracê z niezerowym kodem je¶li
znajdzie co¶ nieprawid³owego. W takim wypadku powiniene¶ poprawiæ b³±d
.\" if it finds anything awry.
i uruchomiæ program ponownie.

W³±czenie ochrony hase³, gdy jest ona ju¿ w³±czona lub jej wy³±czenie,
gdy jest wy³±czona jest nieszkodliwe.

Przeczytaj
.IR /usr/share/doc/passwd/README.debian.gz ,
gdzie znajdziesz krótkie wprowadzenie do ochrony hase³ z u¿yciem dodatkowych
plików hase³ przes³anianych (shadow passwords) i zwi±zanych tematów.
