.\" $Id: su.1,v 1.7 2002/03/09 19:24:25 ankry Exp $
.\" {PTM/WK/1999-09-25}
.\" Copyright 1989 - 1990, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH SU 1
.SH NAZWA
su \- zmiana identyfikatora u¿ytkownika lub uzyskanie praw superu¿ytkownika
.SH SK£ADNIA
\fBsu\fR [\fB-\fR] [\fInazwa_u¿ytkownika\fR [\fIargumenty\fR]]
.SH OPIS
.B su
s³u¿y do stawania siê innym u¿ytkownikiem w trakcie w³asnej sesji.
Wywo³anie bez nazwy u¿ytkownika, domy¶lnie oznacza dla \fBsu\fR
próbê stania siê superu¿ytkownikiem.
Opcjonalnym argumentem \fB\-\fR mo¿na pos³u¿yæ siê do zasymulowania
rzeczywistego rozpoczynania sesji pracy. Pozwala to na utworzenie ¶rodowiska
u¿ytkownika. podobnego do tego, jakie wystêpuje przy bezpo¶rednim zg³oszeniu
u¿ytkownika w systemie.
.PP
Po nazwie u¿ytkownika mog± wyst±piæ dodatkowe argumenty. Zostan± one
dostarczone pow³oce zg³oszeniowej u¿ytkownika. W szczególno¶ci, argument
\fB-c\fR spowoduje, ¿e nastêpny argument zostanie potraktowany jak polecenie
przez wiêkszo¶æ interpretatorów poleceñ.
Polecenie zostanie wykonane przez pow³okê wymienion± w \fI/etc/passwd\fR dla
docelowego u¿ytkownika.
.PP
U¿ytkownik pytany jest o odpowiednie has³o, je¶li takowe istnieje.
Nieprawid³owe has³o spowoduje wypisanie komunikatu o b³êdzie. Wszystkie próby,
udane i nieudane, s± rejestrowane do celów wykrywania nadu¿yæ w systemie.
.PP
Nowej pow³oce przekazywane jest bie¿±ce ¶rodowisko. Warto¶æ \fB$PATH\fR dla
zwyk³ych u¿ytkowników ustawiana jest na \fB/bin:/usr/bin\fR, za¶ dla
superu¿ytkownika na \fB/sbin:/bin:/usr/sbin:/usr/bin\fR.
Mo¿na to zmieniæ przy pomocy definicji \fBENV_PATH\fR i \fBENV_SUPATH\fR
w \fI/etc/login.defs\fR.
Logowanie do podsystemu jest wykazywane przez obecno¶æ "*" jako pierwszego
znaku pow³oki zg³oszeniowej. Podany katalog domowy zostanie potraktowany jako
katalog g³ówny nowego systemu plików, do którego u¿ytkownik siê zaloguje.
.SH PRZESTROGI
Niniejsza wersja \fBsu\fR posiada wiele opcji kompilacji, z których tylko
czê¶æ bêdzie mieæ zastosowanie w danej instalacji.
.SH PLIKI
/etc/passwd \- informacje o kontach u¿ytkowników
.br
/etc/shadow \- zakodowane has³a i informacje o ich wa¿no¶ci
.br
$HOME/.profile \- plik startowy dla domy¶lnej pow³oki
.SH ZOBACZ TAK¯E
.BR login (1),
.BR sh (1),
.BR login.defs (5),
.BR suauth (5)
.SH AUTOR
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
