.\" $Id$
.\" Copyright 1989 - 1990, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH SU 1
.SH NAZWA
su \- zmiana identyfikatora użytkownika lub uzyskanie praw superużytkownika
.SH SKŁADNIA
\fBsu\fR [\fB\-\fR] [\fInazwa_użytkownika\fR [\fIargumenty\fR]]
.SH OPIS
.B su
służy do stawania się innym użytkownikiem w trakcie własnej sesji.
Wywołanie bez nazwy użytkownika, domyślnie oznacza dla \fBsu\fR
próbę stania się superużytkownikiem.
Opcjonalnym argumentem \fB\-\fR można posłużyć się do zasymulowania
rzeczywistego rozpoczynania sesji pracy. Pozwala to na utworzenie środowiska
użytkownika. podobnego do tego, jakie występuje przy bezpośrednim zgłoszeniu
użytkownika w systemie.
.PP
Po nazwie użytkownika mogą wystąpić dodatkowe argumenty. Zostaną one
dostarczone powłoce zgłoszeniowej użytkownika. W szczególności, argument
\fB\-c\fR spowoduje, że następny argument zostanie potraktowany jak polecenie
przez większość interpretatorów poleceń.
Polecenie zostanie wykonane przez powłokę wymienioną w \fI/etc/passwd\fR dla
docelowego użytkownika.
.PP
Użytkownik pytany jest o odpowiednie hasło, jeśli takowe istnieje.
Nieprawidłowe hasło spowoduje wypisanie komunikatu o błędzie. Wszystkie próby,
udane i nieudane, są rejestrowane do celów wykrywania nadużyć w systemie.
.PP
Nowej powłoce przekazywane jest bieżące środowisko. Wartość \fB$PATH\fR dla
zwykłych użytkowników ustawiana jest na \fB/bin:/usr/bin\fR, zaś dla
superużytkownika na \fB/sbin:/bin:/usr/sbin:/usr/bin\fR.
Można to zmienić przy pomocy definicji \fBENV_PATH\fR i \fBENV_SUPATH\fR
w \fI/etc/login.defs\fR.
Logowanie do podsystemu jest wykazywane przez obecność "*" jako pierwszego
znaku powłoki zgłoszeniowej. Podany katalog domowy zostanie potraktowany jako
katalog główny nowego systemu plików, do którego użytkownik się zaloguje.
.SH PRZESTROGI
Niniejsza wersja \fBsu\fR posiada wiele opcji kompilacji, z których tylko
część będzie mieć zastosowanie w danej instalacji.
.SH PLIKI
\fI/etc/passwd\fR	\- informacje o kontach użytkowników
.br
\fI/etc/shadow\fR	\- zakodowane hasła i informacje o ich ważności
.SH ZOBACZ TAKŻE
.BR login (1),
.BR sh (1),
.BR login.defs (5),
.BR suauth (5)
.SH AUTOR
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
