.\" $Id: suauth.5,v 1.3 2005/04/05 18:47:51 kloczek Exp $
.TH SUAUTH 5 "14 lutego 1996"
.UC 5
.SH NAZWA
suauth \- plik szczegó³owej kontroli su
.\" detailed su control file
.SH SK£ADNIA
.B /etc/suauth
.SH OPIS
Plik
.I /etc/suauth
przeszukiwany jest przy ka¿dym wywo³aniu polecenia su. Mo¿e on zmieniaæ
zachowanie siê polecenia su, w oparciu o
.PP
.RS
.nf
1) u¿ytkownika, na którego konto wykonywane jest su
.fi
2) u¿ytkownika wykonuj±cego polecenie su (lub dowoln± z grup, której mo¿e
on byæ cz³onkiem)
.RE
.PP
Plik sformatowany jest jak poni¿ej. Wiersze rozpoczynaj±ce siê od # s±
traktowane jak wiersze komentarza i ignorowane.
.PP
.RS
na\-ID:z\-ID:AKCJA
.RE
.PP
Gdzie na\-ID jest albo s³owem
.B ALL
(wszyscy), albo list± nazw u¿ytkowników rozdzielonych "," albo te¿ s³owami
.B ALL EXCEPT
(wszyscy oprócz), po których nastêpuje lista nazw u¿ytkowników
rozdzielonych przecinkiem.
.PP
z\-ID jest formatowane w taki sam sposób jak na\-ID, z wyj±tkiem tego, ¿e
rozpoznawane jest dodatkowe s³owo
.BR GROUP.
Zapis 
.B ALL EXCEPT GROUP
(wszyscy za wyj±tkiem grupy) jest równie¿ ca³kowicie poprawny.
Po s³owie
.B GROUP
powinna wyst±piæ jedna lub wiêcej rozdzielonych przecinkiem nazw grup.
Niewystarczaj±ce jest podanie g³ównego ID danej grupy \- niezbêdny jest
wpis w 
.BR /etc/group (5).
.PP
Akcja mo¿e byæ tylko jedn± z obecnie obs³ugiwanych opcji:
.TP 10
.B DENY
(zakaz) Próba wykonania su jest zatrzymywana jeszcze przed pytaniem o has³o.
.TP 10
.B NOPASS
(bez has³a) Próba wykonania su jest automatycznie pomy¶lna; brak pytania
o has³o.
.TP 10
.B OWNPASS
(w³asne has³o) U¿ytkownik wywo³uj±cy su musi wprowadziæ w³asne has³o, by
polecenie zosta³o pomy¶lnie wykonane. Jest on powiadamiany o konieczno¶ci
podania w³asnego has³a.
.PP
Zauwa¿, ¿e istniej± trzy odrêbne pola rozdzielone dwukropkiem. Bia³e znaki
wokó³ dwukropka nie s± dozwolone. Zauwa¿ te¿, ¿e plik analizowany jest
sekwencyjnie, wiersz po wierszu, i stosowana jest pierwsza pasuj±ca regu³a
bez analizy reszty pliku. Umo¿liwia to administratorowi systemu precyzyjn±
kontrolê wed³ug w³asnych upodobañ.
.SH PRZYK£AD
.PP
.nf
# przyk³adowy plik /etc/suauth
#
# para uprzywilejowanych u¿ytkowników
# mo¿e wykonaæ su na konto root
# przy pomocy w³asnych hase³
#
root:chris,birddog:OWNPASS
# 
# Nikt inny nie mo¿e wykonaæ su na konto root,
# chyba ¿e jest cz³onkiem grupy wheel.
# Tak to robi BSD.
#
root:ALL EXCEPT GROUP wheel:DENY
#
# Byæ mo¿e terry i birddog s± kontami,
# których u¿ywa ta sama osoba.
# Mo¿na zrobiæ wzajemny dostêp
# pomiêdzy nimi bez hase³.
#
terry:birddog:NOPASS
birddog:terry:NOPASS
#
.fi
.SH PLIKI
.I /etc/suauth
.SH B£ÊDY
Mo¿e byæ sporo ukrytych. Analizator pliku jest szczególnie wra¿liwy
na b³êdy sk³adniowe. Zak³ada on, ¿e nie bêdzie zbêdnych bia³ych znaków
(za wyj±tkiem pocz±tków i koñców wierszy), a ró¿ne elementy bêd± separowane
konkretnym znakiem ogranicznika.
.SH DIAGNOSTYKA
B³±d analizy pliku zg³aszany jest przy u¿yciu
.BR syslogd (8)
jako zagro¿enie o poziomie ERR (b³±d) w podsystemie AUTH (identyfikacji
u¿ytkownika przy zg³oszeniu).
.\" as level ERR on facility AUTH.
.SH ZOBACZ TAK¯E
.BR su (1)
.SH AUTOR
.nf
Chris Evans (lady0110@sable.ox.ac.uk)
Lady Margaret Hall
Oxford University
England
