.\" $Id: sulogin.8,v 1.5 2003/04/26 13:24:15 kloczek Exp $
.\" {PTM/WK/1999-09-14}
.\" Copyright 1989 - 1992, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH SULOGIN 8
.SH NAZWA
sulogin - login w trybie jednou¿ytkownikowym
.SH SK£ADNIA
\fBsulogin\fR [\fIurz±dzenie-tty\fR]
.SH OPIS
.B sulogin
wywo³ywane jest przez \fBinit\fR przed zezwoleniem u¿ytkownikowi
na dostêp do systemu w trybie jednou¿ytkownikowym (single user mode).
Funkcja ta mo¿e byæ dostêpna tylko w niektórych systemach, w których
odpowiednio zmieniono \fBinit\fR lub plik \fB/etc/inittab\fR posiada
pozycjê dla logowania siê w trybie jednou¿ytkownikowym.
.PP
Wy¶wietlany jest symbol zachêty
.IP "" .5i
Type control-d to proceed with normal startup,
.br
(or give root password for system maintenance):
.br
Naci¶nij control-d by kontynuowaæ zwyk³y start,
.br
(lub podaj has³o u¿ytkownika root do konserwacji systemu):
.PP
Wej¶cie i wyj¶cie bêd± obs³ugiwane przy u¿yciu standardowych deskryptorów
plików, chyba ¿e u¿yto opcjonalnego argumentu - nazwy urz±dzenia.
.PP
Je¶li u¿ytkownik wprowadzi poprawne has³o superu¿ytkownika root,
to rozpoczynana jest sesja pracy na koncie root.
Je¿eli natomiast naci¶niêto \fBEOF\fR, to system przechodzi
do wielou¿ytkownikowego trybu pracy.
.PP
Po opuszczeniu przez u¿ytkownika pow³oki przypisanej do
jednou¿ytkownikowego trybu pracy lub po naci¶niêciu \fBEOF\fR, system
wykonuje proces inicjacji wymagany do przej¶cia w tryb wielou¿ytkownikowy.
.SH OSTRZE¯ENIA
.PP
Polecenie to mo¿e byæ u¿ywane wy³±cznie wtedy, gdy \fBinit\fR zosta³ zmieniony
tak, by wywo³ywaæ \fBsulogin\fR zamiast \fB/bin/sh\fR,
albo gdy u¿ytkownik skonfigurowa³ plik \fIinittab\fR tak, by obs³ugiwa³
logowanie w trybie jednou¿ytkownikowym.
Na przyk³ad, wiersz
.br
.sp 1
co:s:respawn:/etc/sulogin /dev/console
.br
.sp 1
powinien wykonaæ polecenie sulogin w trybie jednou¿ytkownikowym.
.PP
Na ile jest to mo¿liwe, tworzone jest pe³ne ¶rodowisko.
Jednak¿e w efekcie mog± nie byæ do³±czone czy zainicjowane ró¿ne
urz±dzenia, za¶ wiele poleceñ u¿ytkownika mo¿e byæ niedostêpnych lub
nie funkcjonowaæ.
.SH PLIKI
.IR /etc/passwd " - informacja o kontach u¿ytkowników"
.br
.IR /etc/shadow " - zakodowane has³a i informacja o ich wa¿no¶ci"
.SH ZOBACZ TAK¯E
.BR login (1),
.BR sh (1),
.BR init (8)
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
