.\" $Id: useradd.8,v 1.18 2004/11/04 03:06:32 kloczek Exp $
.\" {PTM/WK/0.1/VIII-1999}
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH USERADD 8
.SH NAZWA
useradd - twórz nowego u¿ytkownika lub zmieñ domy¶ln± informacjê o nowym
.SH SK£ADNIA
.TP 8
\fBuseradd\fR [\fB-c\fR \fIkomentarz\fR] [\fB-d\fR \fIkatalog_domowy\fR]
.br
[\fB-e\fR \fIdata_wa¿no¶ci\fR] [\fB-f\fR \fIdni_nieaktywno¶ci\fR]
.br
[\fB-g\fR \fIgrupa_pocz±tkowa\fR] [\fB-G\fR \fIgrupa\fR[,...]]
.br
[[\fB-M\fR] \fB-m\fR [\fB-k\fR \fIkatalog_wzorców\fR]] [\fB-o\fR] [\fB-p\fR \fIhas³o\fR]
.br
[\fB-s\fR \fIpow³oka\fR] [\fB-u\fR \fIuid\fR] \fIlogin\fR
.TP 8
\fBuseradd\fR \fB-D\fR [\fB-g\fI domy¶lna_grupa\fR] [\fB-b\fI katalog_bazowy\fR]
.br
[\fB-f\fI domy¶lne_dni_nieaktywno¶ci\fR]
.br
[\fB-e\fI domy¶lna_data_wa¿no¶ci\fR]
.br
[\fB-s\fI domy¶lna_pow³oka\fR]
.SH OPIS
.SS Tworzenie nowych u¿ytkowników
.\" .SS Creating New Users
Wywo³ane bez opcji \fB-D\fR, polecenie \fBuseradd\fR tworzy nowe konto
u¿ytkownika pos³uguj±c siê warto¶ciami podanymi w wierszu poleceñ i domy¶lnymi
warto¶ciami z systemu.
W zale¿no¶ci od potrzeb i opcji wiersza poleceñ, do plików systemowych
zostanie wprowadzone nowe konto u¿ytkownika, utworzony bêdzie jego katalog
domowy, do którego przekopiowane zostan± pliki startowe.
.SH OPCJE
Polecenie \fBuseradd\fR posiada nastêpuj±ce opcje:
.\" .IP "\fB-A {\fImetoda\fR|\fBDEFAULT\fR},..."
.\" Okre¶la metodê autentykacji u¿ytkownika.
.\" Metoda autentykacji jest nazw± programu odpowiedzialnego za weryfikacjê
.\" to¿samo¶ci u¿ytkownika.
.\" Mo¿e zostaæ u¿yty ³añcuch \fBDEFAULT\fR w celu zmiany metody autentykacji
.\" u¿ytkownika na standardow± metodê has³a systemowego.
.\" Argumentem tej opcji jest lista oddzielonych przecinkami nazw programów.
.\" Mo¿e ona zawieraæ ³añcuch \fBDEFAULT\fR tylko jednokrotnie.
.IP "\fB-c \fIkomentarz\fR"
Pole komentarza dla zak³adanego u¿ytkownika w pliku hase³.
.IP "\fB-d \fIkatalog_domowy\fR"
Warto¶æ \fIkatalog_domowy\fR zostanie u¿yta do okre¶lenia katalogu logowania
nowotworzonego u¿ytkownika.
Domy¶lnie do \fIdomy¶lny_domowy\fR dodawana jest nazwa u¿ytkownika
(\fIlogin\fR) tworz±c pe³n± nazwê katalogu logowania.
.IP "\fB-e \fIdata_wa¿no¶ci\fR"
Data, od której konto u¿ytkownika zostanie wy³±czone.
Data podawana jest w formacie \fIMM/DD/YY\fR.
.IP "\fB-f \fIdni_nieaktywno¶ci\fR"
Liczba dni po wyga¶niêciu has³a do sta³ego wy³±czenia konta.
Warto¶æ 0 wy³±cza konto natychmiast po przeterminowaniu has³a, za¶ warto¶æ
-1 wy³±cza tê cechê. Domy¶ln± warto¶ci± jest -1.
.IP "\fB-g \fIgrupa_pocz±tkowa\fR"
Nazwa lub numer pocz±tkowej grupy logowania u¿ytkownika. Nazwa grupy musi
istnieæ. Numer grupy musi odnosiæ siê do ju¿ istniej±cej grupy.
Domy¶lnym numerem grupy jest 1.
.IP "\fB-G \fIgrupa,[...]\fR"
Lista dodatkowych grup, do których równie¿ nale¿y u¿ytkownik.
Ka¿da grupa oddzielona jest od nastêpnej przecinkiem, bez wtr±conej spacji.
Do grup odnosz± siê te same ograniczenia, które obowi±zuj± przy grupie podanej
w opcji \fB-g\fR.
Domy¶lnie u¿ytkownik nale¿y tylko do grupy pocz±tkowej.
.IP \fB-M\fR
RedHat doda³ opcjê CREATE_HOME w pliku login.defs w swojej wersji shadow-utils,
która powodowa³a domy¶lne u¿ycie \fB-m\fR - ta opcja wy³±cza to. U¿ywanie jej 
znajduje zastosowanie np. w skryptach, lecz mo¿e byæ powodem niezgodno¶ci
z innymi wersjami shadow-utils.
.IP \fB-m\fR
Je¶li nie istnieje katalog domowy u¿ytkownika, to zostanie on utworzony.
Je¶li pos³u¿ono siê opcj± \fB-k\fR, to bêd± do niego przekopiowane wzorcowe
pliki startowe zawarte w \fIkatalogu_wzorców\fR. W przeciwnym przypadku,
zamiast nich zostan± u¿yte pliki zawarte w \fI/etc/skel\fR.
W katalogu domowym u¿ytkownika zostan± równie¿ utworzone
podkatalogi zawarte w \fIkatalogu_wzorców\fR lub \fI/etc/skel\fR.
Opcja \fB-k\fR jest dozwolona tylko w po³±czeniu z opcj± \fB-m\fR.
Domy¶lnym dzia³aniem jest nie tworzenie katalogu i nie kopiowanie
jakichkolwiek plików.
.IP "\fB-o\fR"
Umo¿liwia utworzenie u¿ytkownaika z nieunikalnym UID (takim samym jak ju¿
istniej±cy).
.IP "\fB-p \fIpasswd\fR"
Zakodowane has³o w postaci zwracanej przez \fBcrypt\fR(3).
Domy¶lnym dzia³aniem jest blokowanie konta.
.\" .IP \fB-r\fR
.\" Tworzenie konta systemowego. Ta opcja pozwala na utworzenie konta o UID
.\" ni¿szym ni¿ UID_MIN zdefiniowane w fI/etc/login.defs\fR. O ile nie poda siê
.\" dodatkowo opcji \fB-m\fR nie jest tworzony katalog domowy dla tak tworzonego
.\" u¿ytkownika niezale¿nie od tego czy tworzenie katalogu jest ustawione czy
.\" nie w \fI/etc/login.defs\fR.
.IP "\fB-s \fIpow³oka\fR"
Nazwa pow³oki (shell) u¿ytkownika. Ustawienie tego pola na puste
powoduje, ¿e system wybierze domy¶ln± pow³okê logowania.
.IP "\fB-u \fIuid\fR"
Numeryczna warto¶æ identyfikatora u¿ytkownika (user's ID). Warto¶æ ta musi
byæ niepowtarzalna, chyba ¿e u¿yto opcji \fI-o\fR. Warto¶æ musi byæ nieujemna.
Domy¶lnie u¿ywana jest tu najmniejsza warto¶æ identyfikatora wiêksza od 999
i wiêksza od identyfikatorów pozosta³ych u¿ytkowników.
Warto¶ci od 0 do 999 s± zwykle zarezerwowane dla kont systemowych.
.SS Zmiana warto¶ci domy¶lnych
Wywo³ane z opcj± \fB-D\fR, polecenie \fBuseradd\fR albo wy¶wietli bie¿±ce
warto¶ci domy¶lne, albo zaktualizuje domy¶lne warto¶ci z wiersza poleceñ.
Dozwolonymi opcjami s±:
.IP "\fB-b \fIkatalog_bazowy\fR"
Pocz±tkowy przedrostek ¶cie¿ki dla katalogu domowego nowego u¿ytkownika.
Je¶li przy tworzeniu nowego konta nie u¿yto opcji \fB-d\fR, to
na koniec \fIkatalogu_bazowego\fR zostanie dodana nazwa u¿ytkownika, tworz±c
now± nazwê katalogu.
.IP "\fB-e \fIdomy¶lna_data_wa¿no¶ci\fR"
Data, od której konto u¿ytkownika zostanie wy³±czone.
.IP "\fB-f \fIdomy¶lne_dni_nieaktywno¶ci\fR"
Liczba dni po wyga¶niêciu has³a do sta³ego wy³±czenia konta.
.IP "\fB-g \fIdomy¶lna_grupa\fR"
Nazwa lub numer pocz±tkowej grupy logowania u¿ytkownika. Nazwa grupy musi
istnieæ. Numer grupy musi odnosiæ siê do ju¿ istniej±cej grupy.
.IP "\fB-s \fIdomy¶lna_pow³oka\fR"
Nazwa pow³oki (shell) dla nowych u¿ytkowników. Podany program bêdzie u¿yty
dla wszystkich przysz³ych nowych kont u¿ytkowników.
.PP
Bez podania opcji \fBuseradd\fR wy¶wietla bie¿±ce ustawienia domy¶lne.
.SH UWAGI
Administrator systemu odpowiedzialny jest za umieszczenie domy¶lnych
plików u¿ytkownika w katalogu \fI/etc/skel\fR.
.SH OSTRZE¯ENIA
Nie mo¿esz dodaæ u¿ytkownika do grupy NIS. Musi to zostaæ wykonane
na serwerze NIS.
.SH PLIKI
\fI/etc/passwd\fR			\- informacja o kontach u¿ytkowników
.br
\fI/etc/shadow\fR			\- bezpieczna informacja o kontach u¿ytkowników
.br
\fI/etc/group\fR			\- informacja o grupach
.br
\fI/etc/default/useradd\fR	\- informacja o ustawieniach domy¶lnych
.br
\fI/etc/skel/\fR			\- katalog zawieraj±cy pliki domy¶lne
.SH KOD ZAKOÑCZENIA
.TP 2
Polecenie \fBuseadd\fR koñczy dzia³anie z nastêpuj±cymi warto¶ciami kodów zakoñczenia:
.br
\fB0\fR	\- powodzenie
.br
\fB1\fR	\- nie mo¿na zaktualizowaæ pliku z has³ami
.br
\fB2\fR	\- niew³a¶ciwa sk³adnia parametrów polecenia
.br
\fB3\fR	\- niew³a¶ciwe parametry opcji
.br
\fB4\fR	\- uid jest ju¿ u¿ywany (i nie u¿yto opcji -o)
.br
\fB6\fR	\- podana grupa nie istnieje
.br
\fB9\fR	\- podany login jest ju¿ u¿ywany
.br
\fB10\fR	\- nie mo¿na zaktualizowaæ pliku z grupami
.br
\fB12\fR	\- nie mo¿na utworzyæ katalogu domowego
.br
\fB13\fR	\- nie mo¿na utworzyæ spoola pocztowego
.SH ZOBACZ TAK¯E
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR crypt (3),
.BR groupadd (8),
.BR groupdel (8),
.BR groupmod (8),
.BR userdel (8),
.BR usermod (8)
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
