.\" $Id: usermod.8,v 1.7 2002/03/09 11:16:24 ankry Exp $
.\" {PTM/WK/0.1/VIII-1999}
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH USERMOD 8
.SH NAZWA
usermod \- zmiana danych konta u¿ytkownika
.SH SK£ADNIA
.TP 8
.B usermod
.\" .RB [ -A
.\" .RI { metoda | \fBDEFAULT\fR "},... ]"
.RB [ -c
.IR komentarz ]
.RB [ -d
.IR katalog_domowy " ["
.BR -m ]]
.br
.RB [ -e
.IR data_wa¿no¶ci ]
.RB [ -f
.IR dni_nieaktywno¶ci ]
.br
.RB [ -g
.IR grupa_pocz±tkowa ]
.RB [ -G
.IR grupa [,...]]
.br
.RB [ -l
.IR login_name ]
.RB [ -s
.IR pow³oka ]
.br
.RB [ -u
.IR uid " ["
.BR -o ]]
.I login
.SH OPIS
Polecenie \fBusermod\fR zmienia systemowe pliki kont, odzwierciedlaj±c zmiany
podane w wierszu poleceñ. Posiada ono nastêpuj±ce opcje:
.\" .IP "\fB-A \fImetoda\fR|\fBDEFAULT\fR"
.\" Nowa warto¶æ metody autentykacji u¿ytkownika. Metoda autentykacji jest
.\" nazw± programu odpowiedzialnego za weryfikacjê to¿samo¶ci u¿ytkownika.
.\" Mo¿e zostaæ u¿yty ³añcuch \fBDEFAULT\fR w celu zmiany metody autentykacji
.\" u¿ytkownika na standardow± metodê has³a systemowego.
.\" method to the standard system password method.
.IP "\fB-c \fIkomentarz\fR"
Nowa warto¶æ pola komentarza dla danego u¿ytkownika w pliku hase³.
Zwykle jest zmieniana przy pomocy narzêzia \fBchfn\fR(1).
.IP "\fB-d \fIkatalog_domowy\fR"
Nowy katalog logowania u¿ytkownika. Je¿eli podano opcjê \fB-m\fR, to zawarto¶æ
aktualnego katalogu domowego zostanie przesuniêta do nowego katalogu. Nowy
katalog domowy jest tworzony je¶li nie istnieje.
.IP "\fB-e \fIdata_wa¿no¶ci\fR"
Data, od której konto danego u¿ytkownika zostanie wy³±czone.
.\" disabled
Data podawana jest w formacie \fIMM/DD/YY\fR.
.IP "\fB-f \fIdni_nieaktywno¶ci\fR"
Liczba dni po wyga¶niêciu has³a do sta³ego wy³±czenia konta.
Warto¶æ 0 wy³±cza konto natychmiast po przeterminowaniu has³a, za¶ warto¶æ
-1 wy³±cza tê cechê. Domy¶ln± warto¶ci± jest -1.
.IP "\fB-g \fIgrupa_pocz±tkowa\fR"
Nazwa lub numer pocz±tkowej grupy logowania u¿ytkownika. Nazwa grupy musi
istnieæ. Numer grupy musi odnosiæ siê do ju¿ istniej±cej grupy.
Domy¶lnym numerem grupy jest 1.
.IP "\fB-G \fIgrupa,[...]\fR"
Lista dodatkowych grup, do których równie¿ nale¿y u¿ytkownik.
Ka¿da grupa oddzielona jest od nastêpnej przecinkiem, bez wtr±conej spacji.
Do grup odnosz± siê te same ograniczenia, które obowi±zuj± przy grupie podanej
w opcji \fB-g\fR.
Je¿eli u¿ytkownik jest obecnie cz³onkiem grupy, której nie podano na li¶cie,
to zostanie z niej usuniêty.
.IP "\fB-l \fIlogin_name\fR"
Nazwa u¿ytkownika zostanie zmieniona z \fIlogin\fR na \fIlogin_name\fR.
Nic wiêcej nie jest zmieniane. W szczególno¶ci, prawdopodobnie powinna zostaæ
zmieniona nazwa katalogu domowego u¿ytkownika, tak by odzwierciedla³a now±
nazwê u¿ytkownika.
.IP "\fB-s \fIpow³oka\fR"
Nazwa nowej pow³oki (shell) u¿ytkownika. Ustawienie tego pola na puste
powoduje, ¿e system wybierze domy¶ln± pow³okê logowania.
.IP "\fB-u \fIuid\fR"
Numeryczna warto¶æ identyfikatora u¿ytkownika (user's ID). Warto¶æ ta musi
byæ niepowtarzalna, chyba, ¿e u¿yto opcji \fI-o\fR. Warto¶æ musi byæ nieujemna.
Warto¶ci od 0 do 99 s± zwykle zarezerwowane dla kont systemowych.
Wszystkim plikom posiadanym przez u¿ytkownika, a po³o¿onym w drzewie katalogowym
rozpoczynaj±cym siê od jego katalogu domowego zostanie automatycznie zmieniony
identyfikator u¿ytkownika pliku.
Pliki poza katalogiem domowym u¿ytkownika musz± zostaæ zmienione rêcznie.
.SH OSTRZE¯ENIA
\fBusermod\fR nie pozwoli na zmianê nazwy zalogowanego u¿ytkownika.
Je¶li zmieniany jest numeryczny identyfikator u¿ytkownika procesu, to musisz
siê upewniæ, ¿e w trakcie wykonywania tego polecenia u¿ytkownik nie
wykonuje ¿adnego procesu.
W³a¶niciela plików crontab musisz zmieniæ rêcznie.
W³a¶niciela zadañ at musisz zmieniæ rêcznie.
Jakiekolwiek zmiany dotycz±ce NIS musisz wykonaæ na serwerze NIS.
.SH PLIKI
.IR /etc/passwd " - informacja o kontach u¿ytkowników"
.br
.IR /etc/shadow " - bezpieczna informacja o kontach u¿ytkowników"
.br
.IR /etc/group "  - informacja o grupach"
.SH ZOBACZ TAK¯E
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR groupadd (8),
.BR groupdel (8),
.BR groupmod (8),
.BR useradd (8),
.BR userdel (8)
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
.SH OD T£UMACZA
Niniejsza dokumentacja opisuje polecenie wchodz±ce w sk³ad pakietu shadow.
Istnieje wiele programów i skryptów do zarz±dzania kontami u¿ytkowników czy
grup. Z uwagi na powtarzaj±ce siê nazwy poleceñ, upewnij siê, ¿e korzystasz
z w³a¶ciwej dokumentacji.
