.\" $Id: userdel.8,v 1.9 2003/04/28 17:52:15 kloczek Exp $
.\" {PTM/WK/0.1/VIII-1999}
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH USERDEL 8
.SH NAZWA
userdel \- usuñ konto u¿ytkownika i powi±zane pliki
.SH SK£ADNIA
\fBuserdel\fR [\fB-r\fR] \fIlogin\fR
.SH OPIS
Polecenie \fBuserdel\fR zmienia systemowe pliki kont, usuwaj±c wszystkie
zapisy odnosz±ce siê do \fIlogin\fR.
Podany u¿ytkownik musi istnieæ. Polecenie \fBuserdel\fR posiada
nastêpuj±ce opcje:
.TP
.B -r
Zostan± usuniête zarówno pliki w katalogu domowym u¿ytkownika jak
i sam ten katalog.
Pliki po³o¿one w innym systemie plików musz± byæ odszukane i usuniête rêcznie.
.SH PLIKI
\fI/etc/passwd\fR	\- informacja o kontach u¿ytkowników
.br
\fI/etc/shadow\fR	\- bezpieczna informacja o kontach u¿ytkowników
.br
\fI/etc/group\fR	\- informacja o grupach
.SH KOD ZAKOÑCZENIA
.TP 2   
Polecenie \fBuserdel\fR koñczy dzia³anie z nastêpuj±cymi warto¶ciami kodów zakoñczenia:
.br
\fB0\fR	\- powodzenie
.br
\fB1\fR	\- nie mo¿na zaktualizowaæ pliku z has³ami
.br
\fB2\fR	\- niew³a¶ciwa sk³adnia parametrów polecenia
.br
\fB6\fR	\- podany u¿ytkownik nie istnieje
.br
\fB8\fR	\- u¿ytkownik jest aktualnie zalogowany
.br
\fB10\fR	\- nie mo¿na zaktualizowaæ pliku z grupami
.br
\fB12\fR	\- nie mo¿na usun±æ katalogu domowego
.SH PRZESTROGI
\fBuserdel\fR nie pozwoli na usuniêcie konta aktualnie zalogowanego
u¿ytkownika. Musisz usun±æ wszystkie uruchomione procesy nale¿±ce
do usuwanego konta. 
Nie mo¿esz usun±æ ¿adnych atrybutów NIS klienta NIS.
Musi to zostaæ wykonane na serwerze NIS.
.SH ZOBACZ TAK¯E
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR groupadd (8),
.BR groupdel (8),
.BR groupmod (8),
.BR useradd (8),
.BR usermod (8)
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
