.\" $Id$
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.TH USERADD 8
.SH NAZWA
useradd \- twórz nowego użytkownika lub zmień domyślną informację o nowym
.SH SKŁADNIA
.TP 8
\fBuseradd\fR [\fB\-c\fR \fIkomentarz\fR] [\fB\-d\fR \fIkatalog_domowy\fR]
.br
[\fB\-e\fR \fIdata_ważności\fR] [\fB\-f\fR \fIdni_nieaktywności\fR]
.br
[\fB\-g\fR \fIgrupa_początkowa\fR] [\fB\-G\fR \fIgrupa\fR[,...]]
.br
[[\fB\-M\fR] \fB\-m\fR [\fB\-k\fR \fIkatalog_wzorców\fR]] [\fB\-o\fR] [\fB\-p\fR \fIhasło\fR]
.br
[\fB\-s\fR \fIpowłoka\fR] [\fB\-u\fR \fIuid\fR] \fIlogin\fR
.TP 8
\fBuseradd\fR \fB\-D\fR [\fB\-g\fR \fIdomyślna_grupa\fR] [\fB\-b\fR \fIkatalog_bazowy\fR]
.br
[\fB\-f\fR \fIdomyślne_dni_nieaktywności\fR]
.br
[\fB\-e\fR \fIdomyślna_data_ważności\fR]
.br
[\fB\-s\fR \fIdomyślna_powłoka\fR]
.SH OPIS
.SS Tworzenie nowych użytkowników
.\" .SS Creating New Users
Wywołane bez opcji \fB\-D\fR, polecenie \fBuseradd\fR tworzy nowe konto
użytkownika posługując się wartościami podanymi w wierszu poleceń i domyślnymi
wartościami z systemu.
W zależności od potrzeb i opcji wiersza poleceń, do plików systemowych
zostanie wprowadzone nowe konto użytkownika, utworzony będzie jego katalog
domowy, do którego przekopiowane zostaną pliki startowe.
.SH OPCJE
Polecenie \fBuseradd\fR posiada następujące opcje:
.IP "\fB\-c\fR \fIkomentarz\fR"
Pole komentarza dla zakładanego użytkownika w pliku haseł.
.IP "\fB\-d\fR \fIkatalog_domowy\fR"
Wartość \fIkatalog_domowy\fR zostanie użyta do określenia katalogu logowania
nowotworzonego użytkownika.
Domyślnie do \fIdomyślny_domowy\fR dodawana jest nazwa użytkownika
(\fIlogin\fR) tworząc pełną nazwę katalogu logowania.
.IP "\fB\-e\fR \fIdata_ważności\fR"
Data, od której konto użytkownika zostanie wyłączone.
Data podawana jest w formacie \fIMM/DD/YY\fR.
.IP "\fB\-f\fR \fIdni_nieaktywności\fR"
Liczba dni po wygaśnięciu hasła do stałego wyłączenia konta.
Wartość 0 wyłącza konto natychmiast po przeterminowaniu hasła, zaś wartość
\-1 wyłącza tę cechę. Domyślną wartością jest \-1.
.IP "\fB\-g\fR \fIgrupa_początkowa\fR"
Nazwa lub numer początkowej grupy logowania użytkownika. Nazwa grupy musi
istnieć. Numer grupy musi odnosić się do już istniejącej grupy.
Domyślnym numerem grupy jest 1.
.IP "\fB\-G\fR \fIgrupa,[...]\fR"
Lista dodatkowych grup, do których również należy użytkownik.
Każda grupa oddzielona jest od następnej przecinkiem, bez wtrąconej spacji.
Do grup odnoszą się te same ograniczenia, które obowiązują przy grupie podanej
w opcji \fB\-g\fR.
Domyślnie użytkownik należy tylko do grupy początkowej.
.IP \fB\-m\fR
Jeśli nie istnieje katalog domowy użytkownika, to zostanie on utworzony.
Jeśli posłużono się opcją \fB\-k\fR, to będą do niego przekopiowane wzorcowe
pliki startowe zawarte w \fIkatalogu_wzorców\fR. W przeciwnym przypadku,
zamiast nich zostaną użyte pliki zawarte w \fI/etc/skel\fR.
W katalogu domowym użytkownika zostaną również utworzone
podkatalogi zawarte w \fIkatalogu_wzorców\fR lub \fI/etc/skel\fR.
Opcja \fB\-k\fR jest dozwolona tylko w połączeniu z opcją \fB\-m\fR.
Domyślnym działaniem jest nie tworzenie katalogu i nie kopiowanie
jakichkolwiek plików.
.IP "\fB\-o\fR"
Umożliwia utworzenie użytkownaika z nieunikalnym UID (takim samym jak już
istniejący).
.IP "\fB\-p\fR \fIpasswd\fR"
Zakodowane hasło w postaci zwracanej przez \fBcrypt\fR(3).
Domyślnym działaniem jest blokowanie konta.
.IP "\fB\-s\fR \fIpowłoka\fR"
Nazwa powłoki (shell) użytkownika. Ustawienie tego pola na puste
powoduje, że system wybierze domyślną powłokę logowania.
.IP "\fB\-u\fR \fIuid\fR"
Numeryczna wartość identyfikatora użytkownika (user's ID). Wartość ta musi
być niepowtarzalna, chyba że użyto opcji \fI\-o\fR. Wartość musi być nieujemna.
Domyślnie używana jest tu najmniejsza wartość identyfikatora większa od 999
i większa od identyfikatorów pozostałych użytkowników.
Wartości od 0 do 999 są zwykle zarezerwowane dla kont systemowych.
.SS Zmiana wartości domyślnych
Wywołane z opcją \fB\-D\fR, polecenie \fBuseradd\fR albo wyświetli bieżące
wartości domyślne, albo zaktualizuje domyślne wartości z wiersza poleceń.
Dozwolonymi opcjami są:
.IP "\fB\-b\fR \fIkatalog_bazowy\fR"
Początkowy przedrostek ścieżki dla katalogu domowego nowego użytkownika.
Jeśli przy tworzeniu nowego konta nie użyto opcji \fB\-d\fR, to
na koniec \fIkatalogu_bazowego\fR zostanie dodana nazwa użytkownika, tworząc
nową nazwę katalogu.
.IP "\fB\-e\fR \fIdomyślna_data_ważności\fR"
Data, od której konto użytkownika zostanie wyłączone.
.IP "\fB\-f\fR \fIdomyślne_dni_nieaktywności\fR"
Liczba dni po wygaśnięciu hasła do stałego wyłączenia konta.
.IP "\fB\-g\fR \fIdomyślna_grupa\fR"
Nazwa lub numer początkowej grupy logowania użytkownika. Nazwa grupy musi
istnieć. Numer grupy musi odnosić się do już istniejącej grupy.
.IP "\fB\-s\fR \fIdomyślna_powłoka\fR"
Nazwa powłoki (shell) dla nowych użytkowników. Podany program będzie użyty
dla wszystkich przyszłych nowych kont użytkowników.
.PP
Bez podania opcji \fBuseradd\fR wyświetla bieżące ustawienia domyślne.
.SH UWAGI
Administrator systemu odpowiedzialny jest za umieszczenie domyślnych
plików użytkownika w katalogu \fI/etc/skel\fR.
.SH OSTRZEŻENIA
Nie możesz dodać użytkownika do grupy NIS. Musi to zostać wykonane
na serwerze NIS.
.SH PLIKI
\fI/etc/passwd\fR			\- informacja o kontach użytkowników
.br
\fI/etc/shadow\fR			\- bezpieczna informacja o kontach użytkowników
.br
\fI/etc/group\fR			\- informacja o grupach
.br
\fI/etc/default/useradd\fR	\- informacja o ustawieniach domyślnych
.br
\fI/etc/skel/\fR			\- katalog zawierający pliki domyślne
.SH KOD ZAKOŃCZENIA
.TP 2
Polecenie \fBuseadd\fR kończy działanie z następującymi wartościami kodów zakończenia:
.br
\fB0\fR	\- powodzenie
.br
\fB1\fR	\- nie można zaktualizować pliku z hasłami
.br
\fB2\fR	\- niewłaściwa składnia parametrów polecenia
.br
\fB3\fR	\- niewłaściwe parametry opcji
.br
\fB4\fR	\- uid jest już używany (i nie użyto opcji \-o)
.br
\fB6\fR	\- podana grupa nie istnieje
.br
\fB9\fR	\- podany login jest już używany
.br
\fB10\fR	\- nie można zaktualizować pliku z grupami
.br
\fB12\fR	\- nie można utworzyć katalogu domowego
.br
\fB13\fR	\- nie można utworzyć spoola pocztowego
.SH ZOBACZ TAKŻE
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR crypt (3),
.BR groupadd (8),
.BR groupdel (8),
.BR groupmod (8),
.BR userdel (8),
.BR usermod (8)
.SH AUTOR
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
