.\" $Id: vipw.8,v 1.7 2005/12/01 20:38:27 kloczek Exp $
.TH VIPW 8 "26 września 1997"
.SH NAZWA
vipw, vigr \- edycja plików haseł, grup i ich wersji dodatkowych (shadow)
.SH SKŁADNIA
\fBvipw\fR [\fB\-s\fR]
.br
\fBvigr\fR [\fB\-s\fR]
.SH OPIS
.BR vipw " i " vigr
umożliwiają modyfikację plików odpowiednio
.IR /etc/passwd " i " /etc/group .
Przy zastosowaniu flagi
.BR \-s,
modyfikują także dodatkowe wersje chronione (shadow) tych plików \- odpowiednio
.IR /etc/shadow " i " /etc/gshadow " .
Dla ochrony przed uszkodzeniem plików programy te ustawiają odpowiednie
blokady.

Szukając edytora, programy
.BR vipw " i " vigr
używają w pierwszej kolejności zmiennej środowiskowej
.BR VISUAL ,
następnie zmiennej
.BR EDITOR ,
a na końcu domyślnego edytora,
.BR vi .
.SH ZOBACZ TAKŻE
.BR passwd (5),
.BR group (5),
.BR shadow (5)
