#!/usr/bin/expect

set timeout 2
expect_after default {puts "\nFAIL"; exit 1}

spawn /bin/sh
send "if \[ \$(id -u) -eq 0 \]; then PS1='# '; else PS1='$ '; fi\r"
expect "# "

send "LD_PRELOAD=../../../common/time_0.so pwck\r"
expect "no matching password file entry in /etc/shadow"
expect "add user 'bar' in /etc/shadow? "
send "yes\r"
expect "pwck: the files have been updated"
expect "# "
send "echo \$?\r"
expect "2"
send "exit\r"
puts "OK\n"
exit 0
