#!/usr/bin/expect

set timeout 2
expect_after default {puts "\nFAIL"; exit 1}

spawn /bin/sh
send "if \[ \$(id -u) -eq 0 \]; then PS1='# '; else PS1='$ '; fi\r"
expect "# "

send "pwck tmp/passwd tmp/shadow\r"
expect "invalid password file entry"
expect "delete line 'foo:x:1000:1000::'? "
send "yes\r"
expect "no matching password file entry in tmp/passwd"
expect "delete line 'foo:!:12977:0:99999:7:::'? "
send "yes\r"
expect "pwck: the files have been updated"
expect "# "
send "echo \$?\r"
expect "2"
send "exit\r"
puts "OK\n"
exit 0
