.\" $Id$
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Fri Jan 12 JST 2000 by Kentaro Shirakata <argrath@ub32.org>
.\" Updated Fri Mar  1 JST 2002 by Kentaro Shirakata <argrath@ub32.org>
.\" Modified Sun 22 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH USERDEL 8
.SH 名前
userdel \- ユーザのアカウントと関連ファイルを削除する
.SH 書式
.B userdel
[\fB\-r\fR]
.I login
.SH 説明
\fBuserdel\fR コマンドは、システムアカウントファイルを修正し、
ユーザ \fIlogin\fR に対応するすべてのエントリを削除する。
削除されるユーザは存在していなければならない。
\fBuserdel\fR コマンドに適用できるオプションは以下の通り。
.IP \fB\-r\fR
ユーザのホームディレクトリ中のファイルを削除する。
ホームディレクトリ自体とユーザのメールスプールも消去する。
ファイルシステム中のほかの場所にあるそのユーザのファイルは、
手作業で探し出して削除しなければならない。
.SH ファイル
\fI/etc/passwd\fR \- ユーザアカウント情報
.br
\fI/etc/shadow\fR \- 安全なユーザアカウント情報
.br
\fI/etc/group\fR \ \- グループ情報
.SH 警告
\fBuserdel\fR は、削除されるユーザが現在ログインしている場合は、
そのアカウントの削除を許可しない。
削除しようとしているアカウントに属する実行中のプロセスは、
すべて kill しなければならない。
NIS のクライアントからは、NIS の属性値は削除できない。
削除は NIS のサーバで行わなければならない。
.SH 関連項目
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR groupadd (8),
.BR groupdel (8),
.BR groupmod (8),
.BR useradd (8),
.BR usermod (8)
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
