.\"$Id: chage.1,v 1.4 2003/04/28 02:14:00 kloczek Exp $
.\" Copyright 1990 - 1994 Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Modified Tue 16 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH CHAGE 1
.SH 名前
chage \- ユーザパスワードの有効期限情報を変更する。
.SH 書式
.TP 6
\fBchage\fR
[\fB-m \fImindays\fR] [\fB-M \fImaxdays\fR]
[\fB-d \fIlastday\fR] [\fB-I \fIinactive\fR]
.br
[\fB-E \fIexpiredate\fR] [\fB-W \fIwarndays\fR] \fIuser\fR
.TP 6
\fBchage\fR
\fB-l \fIuser\fR
.SH 説明
\fBchage\fR は、
パスワードを最後に更新してから、
次に変更しなければならない期日までの日数を変更する。
システムはこの情報を用いて、
ユーザがいつパスワードを変更しなければならないかを決定する。
\fBchage\fR コマンドを使えるのは root ユーザのみに限られている。
ただし一般ユーザも \fB-l\fR オプションを指定すればこのコマンドを利用でき、
自分のパスワードまたはアカウントがいつ切れるかを知ることができる。
.PP
\fB-m\fR オプションを指定した場合、
\fImindays\fR の値はパスワード変更の間隔の最短日数になる。
このフィールドをゼロとした時は、ユーザはいつでもパスワードを変更できる。
.PP
\fB-M\fR オプションを指定すると、
\fImaxdays\fR の値はパスワードが有効な最長日数となる。
\fImaxdays\fR と \fIlastday\fR を足した値が現在の日付より小さい場合、
ユーザはアカウントを使用する前にパスワードを変更しなければならない。
\fB-W\fR オプションを使えばこの期日がいつ来るかが分かるようにできる。
この場合はユーザに事前に警告が与えられる。
.PP
\fB-d\fR オプションを用いると、
パスワードの最終更新日を設定できる。
\fIlastday\fR の値は
1970 年 1 月 1 日からパスワード最終更新日までの日数である。
日付は YYYY-MM-DD という書式
(もしくはあなたの地域でもっとよく用いられている書式)
で指定する事もできる。
.PP
\fB-E\fR オプションは、
それ以降ユーザがアカウントにアクセスできなくなる日付を設定するのに用いられる。
\fIexpiredate\fR は 1970 年 1 月 1 日から
アカウントがロックされる日までの日数である。
日付は YYYY-MM-DD という書式
(もしくはあなたの地域でもっとよく用いられているもの)
で指定することもできる。
アカウントをロックされたユーザが再びそのシステムを使うには、
システム管理者と連絡を取る必要がある。
.PP
\fB-I\fR オプションは、
パスワードの期限が切れてからアカウントがロックされるまでの
放置日数を設定するために用いる。
アカウントをロックされたユーザが再びそのシステムを使うためには、
システム管理者に連絡しなければならない。
\fIinactive\fR は使用不能期間の日数である。
0 にすればこの機能を無効にできる。
.PP
\fB-W\fR オプションは、
パスワードの変更が必要となる前に警告を行う期間の日数を設定するために用いる。
\fIwarndays\fR は、
パスワードの期限切れに先だって、
ユーザに期限が切れかかっていることを警告する日数である。
.PP
いずれのオプションも指定されないと
\fBchage\fR は対話的に動作する。
全てのフィールドに対して各々現在の設定値を表示し、
新しい値の入力を促す。
新しい値を設定する場合はそれを入力し、
現在の値を使うなら空行のままリターンキーを押せばよい。
現在の値は \fB[ ]\fR の間に表示される。
.SH 注意
\fBchage\fR プログラムを用いるには shadow パスワードファイルが必要である。
この機能は、passwd ファイルにパスワードが保存されているときには
利用できない。
.SH ファイル
\fI/etc/passwd\fR \- ユーザアカウント情報
.br
\fI/etc/shadow\fR \- shadow 化されたユーザアカウント情報
.SH 関連項目
.BR passwd (5),
.BR shadow (5)
.SH 著者
Julianne Frances Haugh <jockgrrl@ix.netcom.com>
