.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: chpasswd.8,v 1.2 2001/11/16 17:01:32 ankry Exp $
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Wed Apr 26 18:06:10 JST 2000
.\"         by Kentaro Shirakata <argrath@ub32.org>
.\"
.TH CHPASSWD 8
.SH 名前
\fBchpasswd\fR \- パスワードファイルをバッチ処理で更新する
.SH 書式
\fBchpasswd [-e]\fR
.SH 説明
\fBchpasswd\fRコマンドは標準入力からユーザ名とパスワード
の組が記されているファイルを読み込み、その情報を用いて既存のユーザ群の
パスワード情報を更新する。
-e オプションがない場合は、パスワードは平文と見なされる。
-e オプションがある場合は、パスワードは暗号化されていると見なされる。
各行は
.sp 1
	  \fIuser_name\fR:\fIpassword\fR
.sp 1
という書式である。
指定したユーザは既に存在していなくてはならない。
与えられたパスワードは必要に応じて暗号化され、パスワードの有効期限が存在するなら
それも更新される。
.PP
このコマンドは、同時に大量のアカウントを作成する様な大規模なシステム環境
で使用することを意図している。
.SH 警告
入力ファイルに暗号化されていないパスワードが記されている場合は、
プロテクトをかけておかなくてはならない。
.SH 関連項目
.BR passwd (1),
.BR useradd (8),
.BR newusers (8)
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
