.\"$Id: groupmod.8,v 1.8 2004/11/04 03:06:32 kloczek Exp $
.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated & Modified Sat 21 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH GROUPMOD 8
.SH 名前
groupmod \- グループを修正する
.SH 書式
\fBgroupmod\fR [\fB-g\fI gid \fR[\fB-o\fR]] [\fB-n\fI group_name \fR]
\fIgroup\fR
.SH 説明
\fBgroupmod\fR コマンドは、
コマンドラインからの指定によって、
システムアカウントファイルを修正する。
\fIgroupmod\fR コマンドに指定できるオプションは次の通り。
.IP "\fB-g \fIgid\fR"
変更を受けるグループの ID 番号。
この値は、\fB-o\fR オプションを用いる場合を除き、他と重複してはならない。
また非負値でなくてはならない。
デフォルトは、999 および他のあらゆる既存グループの ID よりも大きい、
最小の数値となる。
変更前のグループ ID を持つ全てのファイルは、
手作業で新しいグループ ID へと変更しなければならない。
.IP "\fB-n \fIgroup_name\fR"
グループの名前が \fIgroup\fR から \fIgroup_name\fR に変更される。
.SH ファイル
\fI/etc/group\fR \- グループ情報
.br
\fR/etc/gshadow\I \- 安全なグループ情報
.SH 関連項目
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR groupadd (8),
.BR groupdel (8),
.BR useradd (8),
.BR userdel (8),
.BR usermod (8)
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
