.\"$Id: grpck.8,v 1.7 2005/12/01 20:38:26 kloczek Exp $
.\" Copyright 1992 - 1993, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated & Modified Sat 21 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH GRPCK 8
.SH 名前
grpck \- グループファイルが正しいかどうか検査する
.SH 書式
\fBgrpck\fR [\fB\-r\fR] [\fIgroup\fR \fIshadow\fR]
.SH 説明
\fBgrpck\fR コマンドはシステムの認証情報が正しいかどうか検査する。
\fI/etc/group\fR と \fI/etc/gshadow\fR
各ファイルの全てのエントリに対し、
各フィールドの書式が正しいか、
そのデータが有効なものかどうかを検証する。
書式が正しくないエントリや、
修正不能な誤りを含むエントリは削除するようプロンプトを出す。
.P
各々のエントリに対して
.sp
.in +.5i
\- フィールドの数が正しいか
.br
\- グループ名に重複がないか
.br
\- メンバーのリストと管理者のリストが正しいか
.in \-.5i
.sp
がチェックされる。
.P
フィールドの数が間違っていたり、
グループ名が重複しているのは致命的なエラーである。
フィールドの数が正しくない場合、
ユーザーはそのエントリ行を削除するよう促される。
削除に同意しなかった場合は、それ以降のチェックは行われない。
重複したグループ名があった場合も削除を促されるが、
この場合は削除しなくてもそれ以降のチェックは続行される。
他の全てのエラーに対しては警告がなされる。
\fBgroupmod\fR コマンドを実行してそのエラーを修正すると良いだろう。
.P
\fI/etc/group\fR ファイルを操作するコマンドは、
壊れたエントリや重複したエントリを変更できない。
そのような際に誤りのあるエントリを削除するには
\fBgrpck\fR を用いるとよい。
.SH オプション
デフォルトでは \fBgrpck\fR は \fI/etc/group\fR ファイルと
\fI/etc/gshadow\fR に対して動作する。
\fIgroup\fR パラメータと \fIshadow\fR パラメータを用いて、
別のファイルを選択することもできる。
さらに \fB\-r\fR フラグを指定すれば、
リードオンリーモードでコマンドを実行することもできる。
この場合、変更を行うかどうかはユーザへ問い合わされず、
自動的に \fBno\fR と回答される。
.B grpck
は
\fI/etc/group\fR と \fI/etc/gshadow\fR
のエントリを GID でソートすることもできる。
ソートモードで動作させるには \fB\-s\fR フラグを与える。
この場合チェックは行われず、単にソートするだけである。
.SH ファイル
\fI/etc/group\fR \  \- グループアカウント情報
.br
\fI/etc/gshadow\fR \- 暗号化されたパスワードとグループ管理者情報
.br
\fI/etc/passwd\fR \ \- ユーザー情報
.SH 関連項目
.BR group (5),
.BR passwd (5),
.BR shadow (5),
.BR groupmod (8)
.SH 返り値
\fBgrpck\fR コマンドは終了時に以下の値を返す:
.IP 0 5
成功
.IP 1 5
構文エラー
.IP 2 5
誤ったグループエントリが存在する
.IP 3 5
グループファイルをオープンできない
.IP 4 5
グループファイルをロックできない
.IP 5 5
グループファイルを更新できない
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
