.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: id.1,v 1.1 2001/11/16 17:00:53 ankry Exp $
.\"
.\" Japanese Version Copyright (c) 2000 ISHIKAWA Keisuke
.\"         all rights reserved.
.\" Translated Thu Nov  9 23:17:10 JST 2000
.\"         by ISHIKAWA Keisuke
.\"
.TH ID 1
.SH 名前
id \- 現在のユーザ ID 名とグループ ID 名を表示する
.SH 書式
.B id
.RB [ -a ]
.SH 説明
.B id
は、現在の実ユーザ ID、実効ユーザ ID、実グループ ID、実効グループ ID の名前または値を表示する。
\fI/etc/passwd\fR に、その値に対応するエントリが存在しない場合は、対応する名前は表示されずに値だけが表示される。
\fB-a\fR フラグ (オプション) を指定すると、ユーザを複数のグループのメンバーにできるシステムでのグループ・セットが表示される。
.SH ファイル
/etc/passwd \- ユーザーアカウント情報
.br
/etc/group \- グループ情報
.SH 関連項目
.BR getuid (2),
.BR getgid (2),
.BR getgroups (2)
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)


