.\" Copyright 1992, Phillip Street and Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)lastlog.8	3.3	08:24:58	29 Sep 1993 (National Guard Release)
.\"	$Id: lastlog.8,v 1.2 2001/11/16 17:01:32 ankry Exp $
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated & Modified Thu Oct 14 1997 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" Updated Fri Jan 12 2001 by Kentaro Shirakata <argrath@ub32.org>
.\"
.TH LASTLOG 8
.SH 名前
lastlog \- lastlog ファイルを調べる
.SH 書式
.B lastlog
.RB [ \-u
.IR login-name ]
.RB [ \-t
.IR days ]
.SH 説明
\fBlastlog\fR は最終ログインの記録ファイル
\fI/var/log/lastlog\fR の内容を整形して表示する。
\fBlogin-name\fR, \fBport\fR, \fBlast login time\fR が表示される。
デフォルトでは (フラグを指定しなかった場合は) lastlog エントリを
UID の数値でソートして表示する。
\fB\-u \fIlogin-name\fR フラグを指定すると
\fIlogin-name\fR の記録だけが表示される。
\fB\-t \fIdays\fR と入力すると最近
\fIdays\fR 日以内の最終ログインを表示する。
\fB\-t\fR フラグを用いると \fB\-u\fR フラグの指定は無視される。
.PP
一度もログインしていないユーザに対しては、
ポートと時刻の代わりに
\fB"**Never logged in**"\fR
というメッセージが表示される。
.SH ファイル
/var/log/lastlog \- lastlog 記録ファイル
.SH 警告
uid 番号に大きな飛びがあると、
lastlog プログラムは長時間スクリーンに何も出力しないまま
実行を続ける (つまり mmdf=800 で最後の uid=170の場合、
uid 171-799 の間プログラムは何も出力しないので、
ハングしたように見える)。
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
.br
Phillip Street


