.\"
.\" Japanese Version Copyright (c) 2001 Maki KURODA
.\"     all right reserved,
.\" Translated Mon Nov  5 18:12:16 JST 2001
.\" by Maki KURODA <mkuroda@aisys-jp.com>
.\"
.TH LIMITS 5
.SH 名前
limits \- 資源制限の定義
.SH 説明
.I limits
ファイル (デフォルトでは /etc/limits 、config.h に定義されている LIMITS_FILE) は
強制したい資源の制限を記述する。
このファイルは root が所有し、 root アカウントのみ読み込み可能であるべきである．
.PP
デフォルトでは root に対する割り当ては行われない。実際、root と同等のアカウント ( UID 0 を備えたアカウント)
へのこの手続きによって制限する方法はない。
.PP
各行には以下の形式でユーザに対する制限を記述する：
.sp
.I	user LIMITS_STRING
.PP
\fBLIMITS_STRING\fP は資源制限の定義をつなげた文字列である。
各制限の定義は、1 文字の識別子と、それに続く数字で表した制限値で構成される。
.PP
有効な識別子は以下である：
A: 最大アドレススペース (KB)
.br
C: 最大コアファイルサイズ (KB)
.br
D: 最大データサイズ (KB)
.br
F: 最大ファイルサイズ (KB)
.br
M: メモリ上に確保される最大アドレススペース (KB)
.br
N: 最大オープンファイル数
.br
R: 最大レジデント設定サイズ (KB)
.br
S: 最大スタックサイズ (KB)
.br
T: 最大 CPU 時間 (MIN)
.br
U: 最大プロセス数
.br
K: \fBumask\fR(2) による設定される、ファイル作成時の mask
.br
L: ユーザの最大ログイン数
.br
P: \fBsetpriority\fR(2) によって設定されるプロセス優先度
.PP
例えば、\fIL2D2048N5\fP は有効な \fBLIMITS_STRING\fP である。読みやすさを考えて、
2 番目の例のような書き方をすることもできる：
.sp
username L2D2048N5
.br
username L2 D2048 N5
.PP
\fIusername\fP の後の行の残りが制限された文字列として扱われるので、
コメントが許可されないことに注意すること。
無効な制限文字列は、login プログラムによって拒絶される(無視される)だろう。
.PP
デフォルトの指定はユーザ名 "\fB*\fP" によって表示される。
\fBLIMITS_FILE\fP に多数の \fIdefault\fP を登録している場合、
最後のものがデフォルト指定として使用される。
.PP
あるユーザへの制限を完全に無効にするには、シングルダッシュ "\fB-\fP" を使用する。
.PP
さらに、全ての制限の設定は「ログイン毎」で設定されていることに注意すること。
それらはグローバルではなくまた、永久ではない。グローバルな制限が可能になるときが
来るだろうが、今のところは「しなければならないこと」である。;)
.SH ファイル
/etc/limits
.SH 関連項目
.BR login (1),
.BR setpriority (2),
.BR setrlimit (2)
.SH 著者
Cristian Gafton (gafton@sorosis.ro)
