.\" This page is originally in the shadow package.
.\"
.\" Translated Fri 14 Feb 1997 by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\"
.\" this is comment
.TH LOGIN.ACCESS 5
.\" .Dt SKEY.ACCESS 5
.\" .Os FreeBSD 1.2
.SH 名前
login.access \- ログインアクセスをコントロールするテーブル
.SH 説明
.I login.access
ファイルには、ログインを許可又は拒絶する(ユーザ, ホスト)の組及び/又は
(ユーザ, tty)の組みあわせを指定する。
.PP
誰かがログインした際は、
.I login.access
ファイルがスキャンされ、最初に符合する(ユーザ,ホスト)の組合せ、もしくは
ネットワーク経由のログインでない場合は最初に符合する(ユーザ, tty)の組み
合わせを探す。
このテーブルの許可欄によってログインが許可されるか拒絶されるかが決まる。
.PP
ログインアクセス制御表の各行には3つの欄があり、文字":"で分割されている:
.sp 1
.IR 	許可 : ユーザ : 接続元
.sp 1
最初の欄は"\fB+\fR"(アクセスを許可する)もしくは"\fB-\fR"(アクセスを拒否する)でなくては
ならない。
二番目の欄は一つ以上のログイン名またはグループ名、もしくは
.B ALL
(必ず符合する)
でなくてはならない。
三番目の欄は、一つ以上のtty名(ネットワーク経由でないログインの場合)、
ホスト名、("\fB.\fR"で始まる)ドメイン名、ホストアドレス、または("\fB.\fR"で終わる)
インターネットのネットワーク番号からなるリスト、
.B ALL
(必ず符合する)又は
.B LOCAL
("\fB.\fR"を全く含まない文字列全てに符合する)でなくてはならない。
NISを運用している場合は、ホスト又はユーザのパターン中に@netgroupname
を指定することが出来る。
.PP
.B EXCEPT
オペレータを用いることにより、とても簡略にルールを指定することが出来る。
.PP
ログインするユーザ名がいずれの名前とも符合しない場合のみ、groupファイル
を検索する。
ユーザ名が陽に記されているグループにのみ符合する: プログラムはユーザの
主グループのid番号迄は見ない。
.SH ファイル
/etc/login.access
.SH 関連項目
.BR login (1)
.SH 著者
Guido van Rooij
