.\" Copyright 1991, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: newgrp.1,v 1.3 2002/03/09 11:16:16 ankry Exp $
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\"
.TH NEWGRP 1
.SH 名前
newgrp \- グループIDを変更する
.br
sg \- 異なるグループIDでコマンドを実行する
.SH 書式
.BR newgrp " [" - ]
[\fIgroup\fR]
.br
.BR sg " [" - ]
[\fIgroup\fR [[\fB-c\fR] \fIcommand\fR]]
.SH 説明
.B newgrp
はログインセッション中に現在のグループIDを変更するために用いられる。
オプションとして\fB\-\fRフラグを与えた場合は、
新たにログインしたのと同じ様に環境が再初期化される。
そうでない場合は、作業ディレクトリを含めて、現在の環境は変化しない。
.PP
.B newgrp
は、現在の実際のグループIDを、指定したグループに、
またグループ名を指定しなかった場合は\fI/etc/passwd\fRに記載された
ディフォルトのグループに、変更する。
ユーザにはパスワードがなくグループにはある場合、
もしくは、メンバーであると設定されておらず、
しかもグループにはパスワードがある場合には、
パスワードの入力を求められる。
グループのパスワードが設定されておらず、かつユーザがメンバーとして
設定されていない場合は、アクセスを拒否される。
.PP
.B sg
コマンドは\fBnewgrp\fRと同様な働きをするが、
ユーザのシェルは置き換わらない。
従って、\fBsg\fRコマンドから抜けた場合は以前のグループIDに戻る。
.B sg
はコマンドも受け付ける。
コマンドはBourneシェルで実行され、引用符で囲まなくてはならない。
.SH 警告
この版の\fBnewgrp\fRには多くのコンパイル時オプションがあるが、
サイトによっては、そのうちのいくつかしか設定されていないこともある。
.SH ファイル
/etc/passwd \- ユーザのアカウント情報
.br
/etc/group \- グループ情報
.SH 関連項目
.BR id (1),
.BR login (1),
.BR su (1)
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
