.\"$Id$
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Japanese Version Copyright (c) 1996 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated Wed Nov 20 17:42:39 JST 1996
.\"         by HANATAKA Shinya
.\" Modified Sun 22 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH NEWUSERS 8
.SH 名前
newusers \- ユーザの新規作成や情報更新をバッチ処理で行う
.SH 書式
\fBnewusers\fR [\fInew_users\fR]
.SH 説明
\fBnewusers\fR はユーザ名と平文パスワードとの組を記したファイルを読み、
その情報をもとに既存のユーザ情報の変更や新規ユーザの作成を行う。
このファイルの書式は、
下記の点を除き標準的なパスワードファイル
(\fBpasswd\fR(5) 参照) と同じである。
.IP "\fIpw_passwd\fR" 10
このフィールドが暗号化され、新しい暗号化パスワードとなる。
.IP "\fIpw_age\fR"
このフィールドは shadow ファイル向けの情報であるが、
ユーザがすでに存在する場合は無視される。
.IP "\fIpw_gid\fR"
このフィールドに既存のグループを指定した場合は、
ユーザはそのグループに加えられる。
存在しないグループ ID を指定した場合は、
そのグループ ID で新たなグループが作成される。
.IP "\fIpw_dir\fR"
このフィールドで指定したディレクトリがすでに存在するかチェックし、
もし存在しなければ新たにディレクトリが作られる。
このディレクトリの所有者は、
新規作成されたユーザ、あるいは情報が変更されたユーザとなる。
.PP
このコマンドは、同時に大量のアカウントを作成するような、
大規模なシステム環境で用いるために作られた。
.SH 警告
入力ファイルには暗号化されていないパスワードが含まれるため、
適切に保護しておかなければならない。
.SH 関連項目
.BR passwd (1),
.BR useradd (8)
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
