.\"
.\" Japanese Version Copyright (c) 2001 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sat Dec  1 20:09:17 JST 2001
.\"         by Yuichi SATO <ysato@h4.dion.ne.jp>
.\"
.\" $Id: pwconv.8,v 1.2 2001/12/20 14:02:38 ankry Exp $
.TH PWCONV 8 "26 Sep 1997"
.SH 名前
pwconv, pwunconv, grpconv, grpunconv \- shadow パスワードと shadow グループへの変換、および通常のファイルへの逆変換
.SH 書式
.B pwconv
.br
.B pwunconv
.br
.B grpconv
.br
.B grpunconv
.SH 説明
これら 4 つのプログラムは、通常のパスワード・グループファイル
および shadow パスワード・グループファイル
.IR /etc/passwd ", " /etc/group ", " /etc/shadow ", " /etc/gshadow
を操作する。

\fBpwconv\fR は \fIpasswd\fR と \fIshadow\fR (既に存在する場合) から
\fIshadow\fR を作成する。
\fBpwunconv\fR は \fIpasswd\fR と \fIshadow\fR から \fIpasswd\fR を作成し、
\fIshadow\fR を削除する。
\fBgrpconv\fR は \fIgroup\fR と \fIgshadow\fR (既に存在する場合) から
\fIgshadow\fR を作成する。
\fBgrpunconv\fR は \fIgroup\fR と \fIgshadow\fR から \fIgroup\fR を作成し、
\fIgshadow\fR を削除する。

各プログラムは必要とされるロックを変換の前に取得する。

.B pwconv 
と
.B grpconv
は類似している。
1 つ目は、通常のファイルにエントリがない場合、
そのエントリは shadow 化されたファイルでは削除されるという点である。
2 つ目は、通常のファイルでパスワードが `x' になっていない場合、
shadow 化されたファイルにおいて、
それに対応するエントリが更新されるという点である。
3 つ目は、通常のファイルに書かれたパスワードが `x' に置き換えられる点である。
これらのプログラムは、初めて変換を行うときに使える。
また、通常のファイルを手動で編集した場合に
shadow 化されたファイルを更新するのに使うこともできる。

.I /etc/shadow
に新しいエントリを追加する場合、
.B pwconv
は
.I /etc/login.defs
にある
.BR PASS_MIN_DAYS ", " PASS_MAX_DAYS ", " PASS_WARN_AGE
の値を使う。

同様に、
.B pwunconv
と
.B grpunconv
は類似している。
通常のファイルのパスワードは、
shadow 化されたファイルを使って更新される。
エントリが通常のファイルには存在するが
shadow 化されたファイルには存在しないという場合、
そのエントリはそのままにされる。
最終的に shadow 化されたファイルは削除される。

.B pwunconv 
は期限の切れたパスワードを破棄し、変換できるもののみを変換する。

.SH バグ
(不正なエントリや重複したエントリといった) エラーが
パスワードファイルやグループファイルにあると、
プログラムは永遠にループして、おかしな形で失敗する。
shadow パスワード・グループへの変換や
shadow 化ファイルからの逆変換を行う前に、
\fBpwck\fR と \fBgrpck\fR を実行してエラーを修正すること。
.SH 関連項目
.BR login.defs (5),
.BR pwck (8),
.BR grpck (8),
.BR shadowconfig (8)
