.\"$Id: shadowconfig.8,v 1.4 2003/04/28 02:14:00 kloczek Exp $
.\"
.\" Japanese Version Copyright (c) 2001 Maki KURODA
.\"     all right reserved,
.\" Translated Tue Oct 30 11:59:11 JST 2001
.\"     by Maki KURODA <mkuroda@aisys-jp.com>
.\" Modified Sun 22 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH SHADOWCONFIG 8 "19 Apr 1997" "Debian GNU/Linux"
.SH 名前
shadowconfig \- shadow パスワードを有効・無効にする
.SH 書式
.B "shadowconfig"
.IR on " | " off
.SH 説明
.B shadowconfig on
は shadow パスワードを有効にする。
.B shadowconfig off
は shadow パスワードを無効にする。
何か間違いがあると、
.B shadowconfig
はエラーメッセージを表示し、ゼロ以外の返り値を返す。
そのようなことが起こった場合は、
エラーを修正して再度実行しなければならない。

shadow パスワードがすでに有効になっているときに再度有効にしたり、
無効になっているときに再度無効にしても、何の影響もない。

\fI/usr/share/doc/passwd/README.debian.gz\fR
には shadow パスワードや関連機能に関する
簡単な説明が書かれている。
