.\" This page is originally in the shadow package.
.\"
.\" Translated Fri 14 Feb 1997 by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\"
.TH SUAUTH 5 "Feb 14, 1996"
.UC 5
.SH 名前
suauth \- suを詳細にコントロールするためのファイル
.SH 書式
.B /etc/suauth
.SH 説明
.I /etc/suauth
ファイルは、
suコマンドを実行した時に必ず参照される。
このファイルによって、
.PP
.RS
.nf
1) suが対象とするユーザ
.fi
2)suコマンドを実行しているユーザ(もしくはそのユーザが属するグループ)
.RE
に基づいてsuコマンドの振舞が変更される。
.PP
このファイルは以下の様な書式をしており、
#で始まる行はコメントとして扱われ、無視される;
.PP
.RS
to-id:from-id:ACTION
.RE
.PP
ここで、to-idは
.B ALL
という語、コンマで区切られたユーザ名のリスト
もしくは
.B ALL EXCEPT
という語とそれに続く","で区切られたユーザ名のリスト
のいずれかである。
.PP
from-idはto-idと同じ書式であり、更に
.B GROUP
という語も使用できる。
.B ALL EXCEPT GROUP
という使い方も全く正しい。
.B GROUP
の後には一つ以上のグループ名を","で区切って記す。
関連するグループの主グループidを記すだけでは十分ではなく、
.B /etc/group (5)
中のエントリを記す必要がある。
.PP
ACTIONには、現在サポートされている以下のオプションのいずれか一つ
を指定できる。
.TP 20
.B DENY
パスワードを聞く前にsuを停止する。
.TP 20
.B NOPASS
自動的にsuすることが出来、パスワードは尋ねて来ない。
.TP 20
.B OWNPASS
su出来るためには、ユーザが自分のパスワードを入力しなくては
ならない。パスワードを入力するように要求される。
.PP
コロンによって区切られた別々の欄が三つあることに注意。
コロンの隣に空白があってはならない。
ファイルは一行毎に順番に吟味されること及び、最初に適合した規則を用い、
ファイルの残りは吟味されないことにも注意せよ。
したがって、システム管理者は必要とするだけ微調整を行うことが出来る。
.SH 例
.PP
.nf
# /etc/suauthファイルの例
#
# 数名の特権ユーザは自分のパスワードを
# 用いてrootにsu出来る。
#
root:chris,birddog:OWNPASS
# 
# 他のユーザはwheelグループに属していない限り
# rootにsuすることは出来ない。
# BSDと同じ振舞。
#
root:ALL EXCEPT GROUP wheel:DENY
#
# おそらくterryとbirddogは同じ人間が
# 所有するアカウントである。
# パスワード無しで互いに
# 他方にsu出来る。
#
terry:birddog:NOPASS
birddog:terry:NOPASS
#
.fi
.SH ファイル
/etc/suauth
.SH バグ
多くのバグが潜んでいる可能性がある。
とりわけ、ファイルパーサは書式エラーに寛大ではなく、
(行の始め及び終わり以外に)見かけの空白はあってはならないし、
特定のトークンにより全く別の区切り方になってしまう事もある。
.SH 返り値
ファイルをパースする際のエラーは
.B syslogd (8)
を用いてAUTH機能のレベルERR
として通知される。
.SH 関連項目
.BR su (1)
.SH 著者
.nf
Chris Evans (lady0110@sable.ox.ac.uk)
Lady Margaret Hall
Oxford University
England
