.\"$Id: usermod.8,v 1.8 2004/11/04 03:06:32 kloczek Exp $
.\" Copyright 1991 - 1994, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Tue Jan 23 17:21:08 JST 2001
.\"         by Kentaro Shirakata <argrath@ub32.org>
.\" Modified Sun 22 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.\"WORD:        initial group           主グループ
.\"WORD:        supplementary group     補助グループ
.\"
.TH USERMOD 8
.SH 名前
usermod \- ユーザアカウントを修正する
.SH 書式
\fBusermod\fR [\fB-c\fR \fIcomment\fR] [\fB-d\fR \fIhome_dir\fR [\fB-m\fR]]
.br
[\fB-e\fR \fIexpire_date\fR] [\fB-f\fR \fIinactive_time\fR]
.br
[\fB-g\fR \fIinitial_group\fR] [\fB-G\fR \fIgroup\fR [,...]]
.br
[\fB-l\fR \fIlogin_name\fR] [\fB-p\fR \fIpasswd\fR]
.br
[\fB-s\fR \fIshell\fR] [\fB-u\fR \fIuid\fR [\fB-o\fR]] [\fB-L\fR|\fB-U\fR]
\fIlogin\fR
.SH 説明
\fBusermod\fR コマンドは、
コマンドライン上での指定によって、
システムアカウントファイルを修正する。
\fBusermod\fR コマンドに指定できるオプションは次の通り。
.IP "\fB-c \fIcomment\fR"
パスワードファイルのコメントフィールドに与える新しい値。
通常は
.BR chfn (1)
ユーティリティによって変更される。
.IP "\fB-d \fIhome_dir\fR"
新しいログインディレクトリ。
\fB-m\fR オプションを用いると、
現在のホームディレクトリの中身が新しいホームディレクトリに移動される
(後者が存在しない場合は新たに作成される)。
.IP "\fB-e \fIexpire_date\fR"
そのユーザアカウントが使用不能になる日付。
日付は \fIYYYY-MM-DD\fR という書式で指定する。
.IP "\fB-f \fIinactive_days\fR"
パスワードの使用期限が切れてからアカウントが永久に使用不能になるまでの日数。
0 にすると、
パスワードの期限が切れると同時にこのアカウントは使用不能になる。
-1 にするとこの機能が無効になる。デフォルト値は -1。
.IP "\fB-g \fIinitial_group\fR"

新たにそのユーザのログイン時初期グループとするグループ名または ID。
グループ名は既に存在していなければならない。
グループ番号は既存のグループを参照していなければならない。
デフォルトのグループ番号は 1。
.IP "\fB-G \fIgroup,[...]\fR"
ユーザが属する補助グループ (supplementary groups) のリスト。
グループはコンマで区切り、間に空白文字を入れてはならない。
指定できるグループには \fB-g\fR オプションと同様の制限がある。
現在そのユーザが、
新しいリストにないグループのメンバーになっている場合は、
そのグループから削除される。
.IP "\fB-l \fIlogin_name\fR"
ユーザのログイン名を \fIlogin\fR から \fIlogin_name\fR に変更する。
他は何も変更しないので、
おそらく新しいログイン名に合わせて
ホームディレクトリの名前を変更する必要があるだろう。
.IP "\fB-p \fIpasswd\fR"                                                
\fBcrypt\fR(3) の返り値である暗号化パスワード。
.IP "\fB-s \fIshell\fR"
ユーザの新しいログインシェルの名前。
このフィールドを空白にした場合は、
システムがデフォルトのログインシェルを選択する。
.IP "\fB-u \fIuid\fR"
ユーザの ID 番号。
この値は、\fB-o\fR オプションを用いる場合を除き、他と重複してはならない。
また非負値でなくてはならない。
0 から 999 までの値は、通常システムアカウント用に予約されている。
ホームディレクトリ以下の、
そのユーザ所有のすべてのファイルのユーザ ID は、
自動的に新しい値に変更される。
ホームディレクトリ以下にないファイルは手作業で変更しなければならない。
.IP "\fB-L\fR"
ユーザのパスワードをロックする。
これは暗号化されたパスワードの前に '!' を追加し、
実質的にパスワードを無効にする。
このオプションを \fI-p\fR や \fI-U\fR と同時に用いることはできない。
.IP "\fB-U\fR"
ユーザのパスワードをアンロックする。
これは暗号化されたパスワードの先頭の '!' を取り除く。
このオプションを \fI-p\fR や \fI-L\fR と同時に用いることはできない。
.SH 警告
\fBusermod\fR
は現在ログインしているユーザの名前を変更できない。
このコマンドを使用してユーザの ID 番号を変更する際には、
指定したユーザのプロセスが一つも実行されていないことを
事前に確認しなければならない。
crontab ファイルの所有者は手作業で変更しなければならない。
at ジョブの所有者は手作業で変更しなければならない。
NIS に関する作業は NIS サーバ上で行なわなければならない。
.SH ファイル
\fI/etc/passwd\fR \- ユーザアカウント情報
.br
\fI/etc/shadow\fR \- 安全なユーザアカウント情報
.br
\fI/etc/group\fR \ - グループ情報
.SH 関連項目
.BR chfn (1),
.BR chsh (1),
.BR passwd (1),
.BR crypt (3),
.BR groupadd (8),
.BR groupdel (8),
.BR groupmod (8),
.BR useradd (8),
.BR userdel (8)
.SH 著者
Julianne Frances Haugh (jockgrrl@ix.netcom.com)
