.\" $Id: chsh.1,v 1.4 2005/12/01 20:38:29 kloczek Exp $
.\"  (c) 1994 by salvatore valente <svalente@athena.mit.edu>
.\"
.\"  this program is free software.  you can redistribute it and
.\"  modify it under the terms of the gnu general public license.
.\"  there is no warranty.
.TH CHSH 1 "October 13 1994" "chsh" "Linux Reference Manual"
.SH 名稱
chsh \- 更換你登入時所用的shell
.SH 語法
.B chsh
[\ \-s\ shell\ ] [\ \-l\ ] [\ \-u\ ] [\ \-v\ ] [\ username\ ]
.SH 描述
.B chsh
用來更換你登入時所用的shell
。在命令列沒指定shell。
.B chsh
會提示一個給你。
.SS 有效的shell
.B chsh
可用指定路徑全名的方式來指定任何一個可執行的檔案。
然而，如果此 shell並沒紀錄在
.I /etc/shells
檔上，則chsh會提出警告訊息。
.SH 選項
.TP
.I "\-l, \-\-list\-shells"
列出紀錄在
.I /etc/shells
的shell。
.TP
.I "\-s, \-\-shell"
變更你的登入shell.
.TP
.I "\-u, \-\-help"
使用短訊。
.TP
.I "\-v, \-\-version"
版本資訊
.SH "相關文件"
.BR login (1),
.BR passwd (5),
.BR shells (5)
.SH 作者
Salvatore Valente <svalente@mit.edu>
