.\" {PTM/WK/1999-09-17}
.\" Copyright 1992 - 1993, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.TH GRPCK 1
.SH NAZWA
grpck \- weryfikacja spójno¶ci plików grup
.SH SK£ADNIA
.B grpck
.RB [ -r ]
.RI [ group
.IR shadow ]
.SH OPIS
\fBgrpck\fR weryfikuje integralno¶æ informacji autentykacji systemowej.
Sprawdzane s± wszystkie pozycje w plikach \fI/etc/group\fR
i \fI/etc/gshadow\fR, by upewniæ siê, ¿e ka¿da z nich posiada w³a¶ciwy format
i poprawne dane w ka¿dym z pól. U¿ytkownik monitowany jest o usuniêcie
pozycji, które s± sformatowane niepoprawnie lub posiadaj± inne nie daj±ce
siê skorygowaæ b³êdy.
.P
Kontrolowane jest czy ka¿da pozycja posiada
.sp
.in +.5i
- w³a¶ciw± liczbê pól
.br
- unikaln± nazwê grupy
.br
- poprawn± listê cz³onków i administratorów
.in -.5i
.sp
.P
Kontrola w³a¶ciwej liczby pól i niepowtarzalnej nazwy grupy jest
decyduj±ca. Je¿eli pozycja posiada b³êdn± liczbê pól, to u¿ytkownik jest
proszony o usuniêcie ca³ej pozycji (wiersza).
Je¿eli u¿ytkownik nie potwierdzi decyzji o usuniêciu, to pomijane s± wszelkie
dalsze sprawdzenia.
Pozycja z powtórzon± nazw± grupy powoduje monit o usuniêcie, ale nadal
bêd± wykonywane pozosta³e sprawdzenia.
Wszystkie inne b³êdy daj± ostrze¿enia a u¿ytkownik jest zachêcany
do uruchomienia polecenia \fBgroupmod\fR, by je poprawiæ.
.P
Polecenia dzia³aj±ce na pliku \fI/etc/group\fR nie potrafi± zmieniaæ
uszkodzonych lub powielonych pozycji. W takich okoliczno¶ciach powinien byæ
u¿ywany \fBgrpck\fR, by usun±æ nieprawid³ow± pozycjê.
.SH OPCJE
Domy¶lnie \fBgrpck\fR dzia³a na plikach \fI/etc/group\fR oraz \fI/etc/gshadow\fR.
Przy pomocy parametrów \fIgroup\fR i \fIshadow\fR u¿ytkownik mo¿e wybraæ inne
pliki.
Dodatkowo, u¿ytkownik mo¿e wykonaæ polecenie w trybie tylko-do-odczytu, poprzez
podanie flagi \fB-r\fR.
Powoduje to, ¿e na wszystkie pytania dotycz±ce zmian zostanie, bez ingerencji
u¿ytkownika, u¿yta odpowied¼ \fBnie\fR.
.SH PLIKI
.IR /etc/group " - informacja o kontach grup"
.br
.IR /etc/gshadow " - zakodowana informacja o has³ach i administratorach grup"
.br
.IR /etc/passwd " -informacja o u¿ytkownikach"
.SH ZOBACZ TAK¯E
.BR groupmod (8),
.BR group (5),
.BR passwd (5),
.BR shadow (5)
.SH DIAGNOSTYKA
Polecenie \fBgrpck\fR koñczy pracê z nastêpuj±cymi warto¶ciami kodów:
.IP 0 5
Powodzenie
.IP 1 5
B³±d sk³adni
.IP 2 5
Jedna lub wiêcej z³ych pozycji pliku grup
.IP 3 5
Niemo¿liwe otwarcie plików grup
.IP 4 5
Niemo¿liwa blokada plików grup
.IP 5 5
Niemo¿liwa aktualizacja plików grup
.SH AUTOR
Julianne Frances Haugh (jfh@austin.ibm.com)
