.\"     Title: chage
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/11/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "chage" "1" "07/11/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
chage \- изменяет информацию об устаревании пароля пользователя
.SH "СИНТАКСИС"
.HP 6
\fBchage\fR [\fIпараметры\fR] [\fILOGIN\fR]
.SH "ОПИСАНИЕ"
.PP
Программа The
\fBchage\fR
изменяет количество дней между датой следующей смены пароля и датой последней смены пароля. Эта информация используется системой для определения момента, когда пользователь должен сменить свой пароль.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBchage\fR:
.TP 3n
\fB\-d\fR, \fB\-\-lastday\fR\fIПОСЛ_ДЕНЬ\fR
Установить число дней прошедших с 1 января 1970 года, когда была последняя смена пароля. Дата может быть также указана в виде ГГГГ\-ММ\-ДД (или в форме согласно региональным настройкам).
.TP 3n
\fB\-E\fR, \fB\-\-expiredate\fR\fIДАТА_УСТАРЕВАНИЯ\fR
Установить дату устаревания учётной записи пользователя, которая задаётся числом дней прошедших с 1 января 1970 года. Дата может быть также задана в виде ГГГГ\-ММ\-ДД (или в форме согласно региональным настройкам). Пользователь, чья учётная запись была заблокирована, должен обратиться к системному администратору, если хочет в дальнейшем работать с системой.
.sp
Указание значения
\fI\-1\fR
в параметре
\fIДАТА_УСТАРЕВАНИЯ\fR
отменяет устаревание учётной записи.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Показать краткую справку и закончить работу.
.TP 3n
\fB\-I\fR, \fB\-\-inactive\fR\fIДНЕЙ\fR
Установить число дней неактивности после устаревания пароля перед тем как учётная запись будет заблокирована. В параметре
\fIДНЕЙ\fR
задаётся число дней неактивности. Пользователь, чья учётная запись была заблокирована, должен обратиться к системному администратору, если хочет в дальнейшем работать с системой.
.sp
Указание значения
\fI\-1\fR
в параметре
\fIДНЕЙ\fR
отменяет неактивность учётной записи.
.TP 3n
\fB\-l\fR, \fB\-\-list\fR
Показать информацию об устаревании учётной записи.
.TP 3n
\fB\-m\fR, \fB\-\-mindays\fR\fIМИН_ДНЕЙ\fR
Задать
\fIминимальное количество дней\fR
между сменой пароля. Нулевое значение этого поля указывает на то, что пользователь может менять свой пароль когда захочет.
.TP 3n
\fB\-M\fR, \fB\-\-maxdays\fR\fIМАКС_ДНЕЙ\fR
Установить максимальное число дней работоспособности пароля. Если сумма значений
\fIМАКС_ДНЕЙ\fR
и
\fIПОСЛ_ДЕНЬ\fR
раньше текущего дня, то пользователю придётся изменить свой пароль перед использованием учётной записи. Для того, чтобы это не было неожиданностью можно воспользоваться параметром
\fB\-W\fR, который активирует выдачу предупреждения о смене пароля пользователя заранее.
.sp
Указание значения
\fI\-1\fR
в параметре
\fIМАКС_ДНЕЙ\fR
отменяет проверку пароля.
.TP 3n
\fB\-W\fR, \fB\-\-warndays\fR\fIПРЕДУП_ДНЕЙ\fR
Установить число дней выдачи предупреждения, перед тем как потребуется смена пароля. Параметр
\fIПРЕДУП_ДНЕЙ\fR
задаётся в днях, в течении которых пользователь будет получать предупреждение об устаревании пароля, перед тем как это случится.
.PP
Если ни один параметр не указан, то
\fBchage\fR
переходит в интерактивный режим, предлагая запустившему пользователю изменить значения всех полей своей учётной записи. Вводимое значение заменяет текущее значение поля; если введена пустая строка, то текущее значение остаётся неизменным. Текущее значение показано в скобках
\fI[ ]\fR.
.SH "ЗАМЕЧАНИЕ"
.PP
Программа
\fBchage\fR
требует наличия файла теневых паролей.
.PP
Программа
\fBchage\fR
работает только от суперпользователя, за исключением вызова с параметром
\fB\-l\fR, который может использоваться непривилегированным пользователем для определения даты устаревания своего пароля.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Программа
\fBchage\fR
завершая работу, возвращает следующие значения:
.TP 3n
\fI0\fR
успешное выполнение
.TP 3n
\fI1\fR
доступ запрещён
.TP 3n
\fI2\fR
ошибка в параметрах команды
.TP 3n
\fI15\fR
не удалось найти файл теневых паролей
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5).
