.\"     Title: chfn
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "chfn" "1" "06/24/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
chfn \- изменяет информацию о пользователе
.SH "СИНТАКСИС"
.HP 5
\fBchfn\fR [\-f\ \fIФИО\fR] [\-r\ \fIномер\ комнаты\fR] [\-w\ \fIрабочий\ телефон\fR] [\-h\ \fIдомашний\ телефон\fR] [\-o\ \fIдругое\fR] [\fIимя\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchfn\fR
изменяет ФИО, рабочий телефон, рабочие координаты и домашний номер телефона учётной записи пользователя. Обычно, эти данные выводятся командной
\fBfinger\fR(1)
и ей подобными программами. Обычный пользователь может изменить только определённые поля собственной учётной записи, разрешённые в файле
\fI/etc/login.defs\fR. (Настройкой по умолчанию пользователю не разрешается менять своё имя и фамилию.) Суперпользователь может изменять любое поле любой учётной записи. Кроме того, только суперпользователь может использовать параметр
\fB\-o\fR
для изменения нестандартизованной части поля GECOS.
.PP
Единственным ограничением значений полей является то, что они не должны содержать управляющих символов, запятых, двоеточий или знака равно. На поле
\fIдругое\fR
не действует это ограничение, и оно может использоваться для хранения информации об учётной записи для любых приложений.
.PP
Если ни один параметр не указан, то
\fBchfn\fR
переходит в интерактивный режим, предлагая запустившему пользователю изменить значения полей своей учётной записи. Вводимое значение заменяет текущее значение поля; если введена пустая строка, то текущее значение остаётся неизменным. Текущее значение показано в скобках
\fB[ ]\fR. Без параметров, программа
\fBchfn\fR
изменяет учётную запись запустившего пользователя.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/login.defs\fR
содержит конфигурацию подсистемы теневых паролей
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchsh\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5).
