.\"     Title: chpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "chpasswd" "8" "06/24/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
chpasswd \- обновляет пароли в пакетном режиме
.SH "СИНТАКСИС"
.HP 9
\fBchpasswd\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchpasswd\fR
читает список пар "пользователь пароль" из стандартного входного потока и обновляет информацию о существующих пользователях. Каждая строка имеет вид:
.PP
\fIимя_пользователя\fR:\fIпароль\fR
.PP
По умолчанию, передаваемый пароль должен быть в виде обычного текста. Алгоритмом шифрования по умолчанию является DES. Также, если есть срок устаревания пароля, то он будет обновлён.
.PP
Данная команда предназначена для работы в крупных системных средах, где за один раз заводится несколько учётных записей.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBchpasswd\fR:
.TP 3n
\fB\-e\fR, \fB\-\-encrypted\fR
Передаваемые пароли заданы в шифрованном виде.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Показать краткую справку и закончить работу.
.TP 3n
\fB\-m\fR, \fB\-\-md5\fR
Использовать алгоритм шифрования MD5 вместо DES, если пароли передаются не шифрованными.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Не забудьте установить права или umask, чтобы не позволить чтение нешифрованных файлов другими пользователями.
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBuseradd\fR(8).
