.\"     Title: chsh
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "chsh" "1" "06/24/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
chsh \- изменяет регистрационную оболочку пользователя
.SH "СИНТАКСИС"
.HP 5
\fBchsh\fR [\-s\ \fIрегистрационная\ оболочка\ пользователя\fR] [\fIимя\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchsh\fR
изменяет регистрационную оболочку пользователя. Она определяет какая команда будет запущена после регистрации пользователя в системе. Обычный пользователь может изменять регистрационную оболочку только для своей учётной записи, суперпользователь может изменять регистрационную оболочку любой учётной записи.
.PP
Все допустимые имена регистрационных оболочек должны быть указаны в файле
\fI/etc/shells\fR. На суперпользователя это ограничение не действует и поэтому ему разрешено указывать любое значение. Для учётной записи с ограниченной регистрационной оболочкой пользователь не может изменить свою регистрационную оболочку. Поэтому, команду
\fI/bin/rsh\fR
в файле
\fI/etc/shells\fR
лучше не указывать, так как, если пользователь случайно изменит свою регистрационную оболочку на эту ограниченную оболочку, то не сможет восстановить её первоначальное значение.
.SH "ПАРАМЕТРЫ"
.PP
Если параметр
\fB\-s\fR
не задан, то
\fBchsh\fR
переходит в интерактивный режим, предлагая пользователю изменить свою регистрационную оболочку. Вводимое значение заменяет текущее значение поля; если введена пустая строка, то текущее значение остаётся неизменным. Текущее значение регистрационной оболочки указано в скобках
\fI[ ]\fR.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shells\fR
содержит список разрешённых регистрационных оболочек
.TP 3n
\fI/etc/login.defs\fR
содержит конфигурацию подсистемы теневых паролей
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5).
