.\"     Title: expiry
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "expiry" "1" "06/24/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
expiry \- проверяет и изменяет пароль согласно срокам действия
.SH "СИНТАКСИС"
.HP 7
\fBexpiry\fR [\-c] [\-f]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBexpiry\fR
проверяет (параметр
\fB\-c\fR) сколько ещё времени будет работоспособен текущий пароль и вынуждает изменить его (параметр
\fB\-f\fR), если это требуется. Она может запускаться обычным пользователем.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5).
