.\"     Title: groups
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "groups" "1" "06/24/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
groups \- показывает имена групп запустившего программу пользователя
.SH "СИНТАКСИС"
.HP 7
\fBgroups\fR [\fIимя\fR]
.SH "ОПИСАНИЕ"
.PP
Команда
\fBgroups\fR
показывает имена групп запустившего программу пользователя или их числовые идентификаторы (ID). Если для номера группы нет соответствующей записи в файле
\fI/etc/group\fR, то отображается числовое значение без соответствующего имени. При указании необязательного параметра
\fIимя\fR
выводятся группы для учётной записи с указанным
\fIименем\fR.
.SH "ЗАМЕЧАНИЕ"
.PP
В системах, не имеющих поддержки одновременного членства в группах, используется информация из файла
\fI/etc/group\fR. Для смены своей текущей реальной или эффективной группы пользователь должен использовать команды
\fBnewgrp\fR
или
\fBsg\fR.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/group\fR
содержит информацию о группах
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBnewgrp\fR(1),
\fBgetgid\fR(2),
\fBgetgroups\fR(2),
\fBgetuid\fR(2).
