.\"     Title: groupdel
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "groupdel" "8" "06/24/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
groupdel \- удаляет группу
.SH "СИНТАКСИС"
.HP 9
\fBgroupdel\fR \fIгруппа\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBgroupdel\fR
изменяет системные файлы учётных записей, удаляя все записи, относящиеся к
\fIгруппе\fR. Группа с таким именем должна существовать.
.PP
Вы должны вручную проверить все файловые системы, чтобы убедиться, что не осталось файлов, принадлежащих удалённой группе.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Вы не можете удалить группу, если она является первичной для существующего пользователя. Вы должны удалить пользователя перед тем как удалять группу.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/group\fR
содержит информацию о группах
.TP 3n
\fI/etc/gshadow\fR
содержит защищаемую информацию о группах
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Программа
\fBgroupdel\fR
завершая работу, возвращает следующие значения:
.TP 3n
\fI0\fR
успешное выполнение
.TP 3n
\fI2\fR
ошибка в параметрах команды
.TP 3n
\fI8\fR
не удалось удалить первичную пользовательскую группу
.TP 3n
\fI10\fR
не удалось изменить файл групп
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupmod\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)
