.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "groups" "1" "11/10/2005" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
groups \- показывает имена групп запустившего программу пользователя
.SH "СИНТАКСИС"
.HP 7
\fBgroups\fR [\fIпользователь\fR]
.SH "ОПИСАНИЕ"
.PP
\fBgroups\fR
показывает имена групп запустившего команду пользователя или их числовые идентификаторы (ID). Если для номера группы нет соответствующей записи в файле
\fI/etc/group\fR, то выводится числовой идентификатор группы. Если указан необязательный параметр
\fIпользователь\fR
, то выводятся группы учётной записи
\fIпользователь\fR.
.SH "ЗАМЕЧАНИЕ"
.PP
В системах, не имеющих поддержки одновременного членства в группах, используется информация из файла
\fI/etc/group\fR. Для смены своей текущей реальной или эффективной группы пользователь должен использовать команды
\fBnewgrp\fR
или
\fBsg\fR.
.SH "ФАЙЛЫ"
.TP
\fI/etc/group\fR
содержит информацию о группах
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBnewgrp\fR(1),
\fBgetgid\fR(2),
\fBgetgroups\fR(2),
\fBgetuid\fR(2).
