.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "groupadd" "8" "03/11/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
groupadd \- создаёт новую группу
.SH "СИНТАКСИС"
.HP 9
\fBgroupadd\fR [\-g\ \fIGID\fR\ [\-o]] [\-f] [\-K\ \fIКЛЮЧ\fR=\fIЗНАЧЕНИЕ\fR] \fIgroup\fR
.SH "ОПИСАНИЕ"
.PP
\fBgroupadd\fR
создаёт новую группу, согласно указанным значениям командной строки и системным значениям по умолчанию. Новая группа будет добавлена в системные файлы.
.SH "ПАРАМЕТРЫ"
.PP
Возможные параметры команды
\fBgroupadd\fR
:
.TP
\fB\-f\fR
Вернуть статус успешного выполнения, если группа уже существует. Если используется вместе с параметром
\fB\-g\fR
и указанный GID уже существует, то выбирается другой (уникальный) GID (то есть параметр
\fB\-g\fR
игнорируется).
.TP
\fB\-g\fR \fIGID\fR
Числовое значение идентификатора группы. Значение должно быть уникальным, если не указан параметр
\fB\-o\fR. Также, оно должно быть не отрицательным. По умолчанию, берётся значение больше 999 и больше идентификатора любой другой группы. Значения от 0 и до 999 обычно зарезервированы под системные группы.
.TP
\fB\-h\fR, \fB\-\-help\fR
Показать краткую справку и закончить работу.
.TP
\fB\-K \fR\fB\fIКЛЮЧ\fR\fR\fB=\fR\fB\fIЗНАЧЕНИЕ\fR\fR
Изменить значения по умолчанию (GID_MIN, GID_MAX и другие), которые хранятся в файле /etc/login.defs. Можно указать несколько параметров
\fB\-K\fR.
.sp
Пример:
\fB\-K \fR\fIGID_MIN\fR=\fI100\fR\fB \-K \fR\fIGID_MAX\fR=\fI499\fR
.sp
Замечание:
\fB\-K \fR\fIGID_MIN\fR=\fI10\fR,
\fIGID_MAX\fR=\fI499\fR
такая форма пока не поддерживается.
.TP
\fB\-o\fR
Разрешить добавление группы с не уникальным GID.
.SH "ФАЙЛЫ"
.TP
\fI/etc/group\fR
содержит информацию о группах
.TP
\fI/etc/gshadow\fR
содержит защищаемую информацию о группах
.TP
\fI/etc/login.defs\fR
содержит конфигурацию подсистемы теневых паролей
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Имена групп должны начинаться со строчной буквы или символа подчёркивания. Они могут содержать только строчные буквы, символ подчёркивания, тире и знак доллара. Это можно описать регулярным выражением: [a\-z_][a\-z0\-9_\-]*[$]
.PP
Имена групп могут быть длиной не более 16 знаков.
.PP
Если имя группы уже существует во внешней базе данных групп, например в NIS, то
\fBgroupadd\fR
не станет создавать группу.
.PP
Имена групп могут быть длиной не более 16 знаков.
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
\fBgroupadd\fR
завершая работу, возвращает следующие значения:
.TP
\fI0\fR
успешное выполнение
.TP
\fI2\fR
ошибка в параметрах команды
.TP
\fI3\fR
недопустимое значение параметра
.TP
\fI4\fR
не уникальный GID (если не задан параметр
\fB\-o\fR
)
.TP
\fI9\fR
не уникальное имя группы
.TP
\fI10\fR
не удалось изменить файл групп
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8).
