.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "grpck" "8" "03/11/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
grpck \- проверяет корректность файлов групп
.SH "СИНТАКСИС"
.HP 6
\fBgrpck\fR [\-r] [\fIgroup\fR\ \fIshadow\fR]
.SH "ОПИСАНИЕ"
.PP
\fBgrpck\fR
проверяет корректность системных файлов учётных записей. Проверяется формат всех записей
\fI/etc/group\fR
и
\fI/etc/gshadow\fR
и допустимость данных каждого поля. В случае обнаружения ошибок пользователю предлагается подтвердить удаление записей, восстановление которых невозможно.
.PP
Выполняются следующие проверки:
.TP 3
\(bu
правильное количество полей
.TP
\(bu
уникальность имён групп
.TP
\(bu
корректный список членов и администраторов
.PP
Ошибки в количестве полей и уникальности имён групп невосстановимы. Если запись содержит неверное число полей, пользователя попросят подтвердить удаление всей записи. Если пользователь ответит отрицательно, дальнейшая проверка выполняться не будет. При ошибке повторения имени группы также возникает запрос на удаление, но в случае отказа проверка будет продолжена. Обо всех остальных ошибках выводится предупреждение и пользователю предлагается запустить команду
\fBgroupmod\fR
, чтобы исправить ошибку.
.PP
Команды, которые работают с файлом
\fI/etc/group\fR
, не могут изменять повреждённые или повторяющиеся записи. Именно в таких случаях и нужно использовать команду
\fBgrpck\fR
для удаления испорченной записи.
.SH "ПАРАМЕТРЫ"
.PP
По умолчанию, команда
\fBgrpck\fR
работает с файлами
\fI/etc/group\fR
и
\fI/etc/gshadow\fR. Пользователь может указать другие файлы с помощью параметров
\fIgroup\fR
и
\fIshadow\fR. Также, пользователь может запустить команду в режиме только для чтения, указав параметр
\fB\-r\fR. Это приведёт к автоматическому ответу
\fIнет\fR
без подтверждения пользователя.
\fBgrpck\fR
также может отсортировать записи в файле
\fI/etc/group\fR
и
\fI/etc/gshadow\fR
по номеру группы. Для запуска режима сортировки укажите параметр
\fB\-s\fR. В этом режиме проверка не выполняется, производится только сортировка.
.SH "ФАЙЛЫ"
.TP
\fI/etc/group\fR
содержит информацию о группах
.TP
\fI/etc/gshadow\fR
содержит защищаемую информацию о группах
.TP
\fI/etc/passwd\fR
содержит информацию о пользователях
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBgroupmod\fR(8).
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
\fBgrpck\fR
завершая работу, возвращает следующие значения:
.TP
\fI0\fR
успешное выполнение
.TP
\fI1\fR
ошибка в параметрах команды
.TP
\fI2\fR
есть одна или более неправильных записей групп
.TP
\fI3\fR
не удалось открыть файл групп
.TP
\fI4\fR
не удалось заблокировать файл групп
.TP
\fI5\fR
не удалось изменить файл групп

