.\"     Title: gshadow
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Форматы файлов
.\"    Source: Форматы файлов
.\"
.TH "gshadow" "5" "06/24/2006" "Форматы файлов" "Форматы файлов"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
gshadow \- файл с защищаемой информацией о группах
.SH "ОПИСАНИЕ"
.PP
Файл
\fI/etc/gshadow\fR
содержит защищаемую информацию о группах. Он состоит из строк с полями, отделёнными друг от друга двоеточием. Поля:
.TP 3n
\(bu
имя группы
.TP 3n
\(bu
шифрованный пароль
.TP 3n
\(bu
список администраторов группы, перечисленных через запятую
.TP 3n
\(bu
список членов группы, перечисленных через запятую
.sp
.RE
.PP
Поля с именем группы и пароль должны быть заполнены. Шифрованный пароль состоит из разрешённых 64 символов с a по z, с A по Z, с 0 по 9, \\. и /. Подробней о пароле смотрите на странице руководства
\fBcrypt\fR(3). Если поле пароля содержит строку, которая не удовлетворяет требованиям
\fBcrypt\fR(3), например содержит ! или *, то пользователь не сможет использовать этот unix пароль для регистрации с учётом настроек
\fBpam\fR(7).
.PP
Данная информация заменяет любой пароль файла
\fI/etc/group\fR.
.PP
Этот файл должен быть недоступен обычному пользователю, если нужно обеспечить безопасность паролей.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/group\fR
содержит информацию о группах
.TP 3n
\fI/etc/gshadow\fR
содержит защищаемую информацию о группах
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgroup\fR(5),
\fBgpasswd\fR(5),
\fBnewgrp\fR(5).
