.\"     Title: lastlog
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "lastlog" "8" "06/24/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
lastlog \- выводит отчёт о последней регистрации в системе всех или указанного пользователя
.SH "СИНТАКСИС"
.HP 8
\fBlastlog\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBlastlog\fR
упорядочивает и выводит содержимое файла
\fI/var/log/lastlog\fR, который содержит даты последнего входа пользователей систему. Выводятся
\fIимя пользователя\fR,
\fIпорт\fR
и
\fIдата последнего входа в систему\fR. По умолчанию (вызов без параметров) показываются записи файла lastlog, отсортированные согласно расположению пользователей в файле
\fI/etc/passwd\fR.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBlastlog\fR:
.TP 3n
\fB\-b\fR, \fB\-\-before\fR\fIДНЕЙ\fR
Показать записи lastlog за последние
\fIДНЕЙ\fR.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Показать краткую справку и закончить работу.
.TP 3n
\fB\-t\fR, \fB\-\-time\fR\fIДНЕЙ\fR
Показать записи lastlog новее чем
\fIДНЕЙ\fR.
.TP 3n
\fB\-u\fR, \fB\-\-user\fR\fIИМЯ\fR
Показать запись lastlog только для указанного пользователя с emphasis remap="I">ИМЕНЕМ
.TP 3n
Параметр \fB\-t\fR отменяет действие параметра \fB\-u\fR.
.PP
Если пользователь никогда не регистрировался в системе, то будет показано сообщение
\fI** Никогда не входил в систему**\fR
вместо названия порта и даты.
.SH "ЗАМЕЧАНИЕ"
.PP
Файл
\fIlastlog\fR
содержит информацию о последней регистрации в системе каждого пользователя. Вы не должны применять к нему ротацию журнальных файлов. Этот файл является разреженным, поэтому его размер на диске гораздо меньше, чем показывает команда "\fBls \-l\fR" (которая может показывать, что это очень большой файл, если значения идентификаторов пользователей в системе достигают больших значений). Чтобы увидеть реальный размер введите "\fBls \-s\fR".
.SH "ФАЙЛЫ"
.TP 3n
\fI/var/log/lastlog\fR
содержит список завершённых сеансов работы с системой
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Большие промежутки в значениях идентификаторов пользователей приводят к тому, что программа некоторое время ничего не выводит на экран (то есть, если в базе данных lastlog нет пользователей с идентификаторами с 170 по 800, то во время обработки UID с 171 по 799 программа кажется повисшей).
