.\"     Title: login
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "login" "1" "06/24/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
login \- начинает сеанс в системе
.SH "СИНТАКСИС"
.HP 6
\fBlogin\fR [\-p] [\fIимя_пользователя\fR] [\fIПЕРЕМЕННАЯ_СРЕДЫ=ЗНАЧЕНИЕ\fR...]
.HP 6
\fBlogin\fR [\-p] [\-h\ \fIхост\fR] [\-f\ \fIимя_пользователя\fR]
.HP 6
\fBlogin\fR [\-p] \-r\ \fIхост\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBlogin\fR
используется для запуска нового сеанса в системе. Как правило, эта программа вызывается автоматически и выводит приглашение
\fIlogin:\fR
на терминал пользователя. Программа
\fBlogin\fR
может восприниматься оболочкой командной строки не как простая программа и вызываться без создания нового процесса. Обычно, оболочка запускает
\fBlogin\fR
посредством вызова
\fBexec login\fR, что приводит к завершению работы пользователя в текущей оболочке. Попытка запустить
\fBlogin\fR
из любой оболочки, отличной от регистрационной, приводит к сообщению об ошибке.
.PP
В какой\-то момент пользователя попросят ввести свой пароль. Чтобы недопустить раскрытия, символы при вводе пароля не отображаются. Разрешено очень маленькое число попыток ввода неправильного пароля, перед тем как
\fBlogin\fR
закончит работу и прервёт подключение.
.PP
Если включён механизм устаревания пароля учётной записи, то перед входом в систему может потребоваться смена пароля. Для этого нужно ввести старый пароль и новый пароль. Подробней об этом написано в
\fBpasswd\fR(1).
.PP
После успешного входа в систему, будут показаны сообщения от системы и о наличии почты. Можно отключить вывод файла системных сообщений из файла
\fI/etc/motd\fR, создав в домашнем каталоге файл нулевой длины с именем
\fI.hushlogin\fR. Сообщение о наличии почты может быть одним из: "\fIУ вас есть новая почта.\fR", "\fIУ вас есть почта.\fR" или "\fIУ вас нет почты.\fR", в зависимости от наполненности почтового ящика.
.PP
Значения идентификатора учётной записи и группы будет взято из файла
\fI/etc/passwd\fR. Значения переменных
\fB$HOME\fR,
\fB$SHELL\fR,
\fB$PATH\fR,
\fB$LOGNAME\fR
и
\fB$MAIL\fR
устанавливаются согласно соответствующим полям учётной записи пользователя. Также могут быть установлены значения ulimit, umask и nice из поля GECOS.
.PP
В некоторых системах переменной среды
\fB$TERM\fR
будет присвоен тип терминала линии tty, согласно данным из файла
\fI/etc/ttytype\fR.
.PP
Также может быть выполнен сценарий инициализации пользовательского интерпретатора команд. Подробней об этой функции смотрите соответствующую страницу руководства.
.PP
Субсистемный вход в систему можно распознать по наличию символа "*" в начале регистрационной оболочки. Заданный домашний каталог будет использован как корень новой файловой системы, в которой регистрируется пользователь.
.PP
Программа
\fBlogin\fR
НЕ удаляет записи о пользователях из файла utmp. Эта задача программ
\fBgetty\fR(8)
и
\fBinit\fR(8)
удалять записи о владельце терминального сеанса. Если
\fBlogin\fR
запускается из командной строки без
\fBexec\fR, то пользователь продолжает находиться в системе даже после завершения работы в "порождённом сеансе".
.SH "ПАРАМЕТРЫ"
.TP 3n
\fB\-f\fR
Не выполнять аутентификацию, пользователь уже прошёл проверку.
.TP 3n
\fB\-h\fR
Имя удалённого хоста, на который нужно войти.
.TP 3n
\fB\-p\fR
Сохранить среду.
.TP 3n
\fB\-r\fR
Выполнить протокол autologin для rlogin.
.PP
Параметры
\fB\-r\fR,
\fB\-h\fR
и
\fB\-f\fR
используются только если
\fBlogin\fR
запускается суперпользователем.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Данная версия
\fBlogin\fR
может быть собрана с разными параметрами и только некоторые из них смогут быть использованы на любой машине.
.PP
Расположение файлов может отличаться на разных системах.
.PP
Программа
\fBlogin\fR
НЕ удаляет записи о пользователях из файла utmp. Эта задача программ
\fBgetty\fR(8)
и
\fBinit\fR(8)
удалять записи о владельце терминального сеанса. Если
\fBlogin\fR
запускается из командной строки без
\fBexec\fR, то пользователь продолжает находиться в системе даже после завершения работы в "порождённом сеансе".
.PP
Как и для любой программы, запуск
\fBlogin\fR
может быть подделан. Если неуполномоченные пользователи имеют физический доступ к машине, то атакующий может использовать это для получения пароля следующего человека, который будет работать за машиной. Под Linux пользователи могут использовать механизм SAK для установления достоверного пути и таким образом предотвращения атаки.
.SH "ФАЙЛЫ"
.TP 3n
\fI/var/run/utmp\fR
содержит список работающих сеансов в системе
.TP 3n
\fI/var/log/wtmp\fR
содержит список завершённых сеансов работы с системой
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.TP 3n
\fI/etc/motd\fR
содержит системные сообщения за день
.TP 3n
\fI/etc/nologin\fR
при существовании файла блокируется доступ в систему обычным пользователям
.TP 3n
\fI/etc/ttytype\fR
содержит список типов терминалов
.TP 3n
\fI$HOME/.hushlogin\fR
при существовании файла системные сообщения при входе в систему не выводятся
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBmail\fR(1),
\fBpasswd\fR(1),
\fBsh\fR(1),
\fBsu\fR(1),
\fBlogin.defs\fR(5),
\fBnologin\fR(5),
\fBpasswd\fR(5),
\fBsecuretty\fR(5),
\fBgetty\fR(8).
