.\"     Title: logoutd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "logoutd" "8" "06/24/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
logoutd \- контролирует временные интервалы работы в системе
.SH "СИНТАКСИС"
.HP 8
\fBlogoutd\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBlogoutd\fR
контролирует временные ограничения работы в системе и порты, заданные в файле
\fI/etc/porttime\fR. Программа
\fBlogoutd\fR
должен запускаться из сценария
\fI/etc/rc\fR. Файл
\fI/var/run/utmp\fR
периодически сканируется и для каждого имени пользователя проверяется, разрешено ли данному пользователю работать в настоящий момент на данном порту. Любая сессия, которая нарушает ограничения, описанные в файле
\fI/etc/porttime\fR, будет завершена.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/porttime\fR
содержит разрешённое время работы определённых пользователей с определённых портов
.TP 3n
\fI/var/run/utmp\fR
содержит список работающих сеансов в системе
