.\"     Title: newusers
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "newusers" "8" "06/24/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
newusers \- обновляет и создаёт новые учётные записи пользователей в пакетном режиме
.SH "СИНТАКСИС"
.HP 9
\fBnewusers\fR [\fInew_users\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBnewusers\fR
читает файл с парами имя пользователя/нешифрованный пароль и использует эту информацию для обновления группы существующих пользователей или создания новых учётных записей. Каждая строка имеет формат стандартного файла паролей (смотрите
\fBpasswd\fR(5)) за исключением:
.TP 3n
\fIpw_passwd\fR
Это поле будет зашифровано и использовано как новое значение шифрованного пароля.
.TP 3n
\fIpw_age\fR
Это поле игнорируется для теневых паролей, если пользователь уже существует.
.TP 3n
\fIpw_gid\fR
Это поле может содержать имя существующей группы, в которую будет добавлен данный пользователь. Если указан числовой идентификатор несуществующей группы, то будет создана новая группа с данным номером.
.TP 3n
\fIpw_dir\fR
Будет проверено существование каталога с именем значения данного поля и если такого каталога нет, то он будет создан. Владельцем каталога будет назначен обновляемый или создаваемый пользователь.
.PP
Данная команда предназначена для работы в крупных системных средах, где за один раз заводится несколько учётных записей.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Файл с входными данными должен быть защищён, так как в нём содержатся не шифрованные пароли.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/login.defs\fR
содержит конфигурацию подсистемы теневых паролей
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin.defs\fR(5),
\fBpasswd\fR(1),
\fBuseradd\fR(8).
