.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "nologin" "8" "03/11/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
nologin \- вежливо отказывает во входе в систему
.SH "СИНТАКСИС"
.HP 8
\fBnologin\fR
.SH "ОПИСАНИЕ"
.PP
\fBnologin\fR
выдаёт сообщение, что учётная запись недоступна и завершает работу с ненулевым кодом возврата. Она предназначена для замены оболочки командной строки в поле оболочки заблокированных учётных записей.
.PP
Чтобы заблокировать все учётные записи посмотрите страницу руководства
\fBnologin\fR(5).
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1),
\fBnologin\fR(5).
.SH "ИСТОРИЯ"
.PP
\fBnologin\fR
впервые появилась в BSD 4.4.
