.\"     Title: nologin
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "nologin" "8" "06/24/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
nologin \- вежливо отказывает во входе в систему
.SH "СИНТАКСИС"
.HP 8
\fBnologin\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBnologin\fR
выдаёт сообщение, что учётная запись недоступна и завершает работу с ненулевым кодом возврата. Она предназначена для замены оболочки командной строки в поле оболочки заблокированных учётных записей.
.PP
Чтобы заблокировать все учётные записи посмотрите страницу руководства
\fBnologin\fR(5).
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1),
\fBnologin\fR(5).
.SH "ИСТОРИЯ"
.PP
Программа
\fBnologin\fR
впервые появилась в BSD 4.4.
