.\"     Title: passwd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "passwd" "1" "06/24/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
passwd \- изменяет пароль пользователя
.SH "СИНТАКСИС"
.HP 7
\fBpasswd\fR [\fIпараметры\fR] \fIlogin\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBpasswd\fR
изменяет пароли пользовательских учётных записей. Обычный пользователь может изменить пароль только своей учётной записи, суперпользователь может изменить пароль любой учётной записи. Программа
\fBpasswd\fR
также изменяет информацию об учётной записи: полное имя пользователя, регистрационную оболочку командной строки или дату устаревания пароля и интервал.
.SS "Изменение пароля"
.PP
Сначала пользователя попросят ввести старый пароль, если он был. Этот пароль зашифровывается и сравнивается с имеющимся. У пользователя есть только одна попытка ввести правильный пароль. Для суперпользователя этот шаг пропускается, для того чтобы можно было изменить забытый пароль.
.PP
После ввода пароля проверяется информация об устаревании пароля, чтобы убедиться, что пользователю разрешено изменять пароль в настоящий момент. Если нет, то
\fBpasswd\fR
не производит изменение пароля и завершает работу.
.PP
Затем пользователю предложат дважды ввести новый пароль. Значение второго ввода сравнивается с первым и для изменения пароли из обеих попыток должны совпасть.
.PP
Затем пароль тестируется на сложность подбора. Согласно общим принципам, пароли должны быть длиной от 6 до 8 символов и включать один или более символов каждого типа:
.TP 3n
\(bu
строчные буквы
.TP 3n
\(bu
цифры от 0 до 9
.TP 3n
\(bu
знаки пунктуации
.sp
.RE
.PP
Не включайте системные символы стирания и удаления. Программа
\fBpasswd\fR
не примет пароль, который не имеет достаточной сложности.
.\" end of SS subsection "Изменение пароля"
.SS "Выбор пароля"
.PP
Безопасность пароля зависит от стойкости алгоритма шифрования и размера пространства ключа. В
\fIUNIX\fR
системах метод шифрования основан на алгоритме NBS DES и очень безопасен. Размер пространства ключа зависит от степени произвольности выбранного пароля.
.PP
Компромиссом в безопасности пароля является небрежный выбор пароля и сложность работы с ним. По этой причине, вы не должны использовать пароль, который является словом из словаря или который придётся записать из\-за его сложности. Также, пароль не должен быть названием чего\-либо, номером вашей лицензии, днём рождения и домашним адресом. Обо всём этом легко догадаться, что приведёт к нарушению безопасности системы.
.PP
Пароль должен легко запоминаться, чтобы не было необходимости записывать его на бумагу. Этого можно достичь соединив два маленьких слова в одно, разделив их специальным символом или цифрой. Например, Pass%word.
.PP
Другим методом создания является выбор легко запоминающейся фразы из литературы и взятие первой или последней буквы каждого слова. Например:
.TP 3n
\(bu
Ask not for whom the bell tolls
.TP 3n
\(bu
получается
.TP 3n
\(bu
An4wtbt
.sp
.RE
.PP
Можете быть уверены, что некоторые взломщики включат этот пароль в свои словари. Поэтому вы должны выбрать свои собственные методы создания паролей и не полагаться на методы предложенные здесь.
.\" end of SS subsection "Выбор пароля"
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBpasswd\fR:
.TP 3n
\fB\-a\fR, \fB\-\-all\fR
Этот параметр можно использовать только вместе с
\fB\-S\fR
для вывода статуса всех пользователей.
.TP 3n
\fB\-d\fR, \fB\-\-delete\fR
Удалить пароль пользователя (сделать его пустым). Это быстрый способ заблокировать пароль учётной записи. Это делает указанную учётную запись беспарольной.
.TP 3n
\fB\-e\fR, \fB\-\-expire\fR
Немедленно сделать пароль устаревшим. В результате это заставит пользователя изменить пароль при следующем входе в систему.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Показать краткую справку и закончить работу.
.TP 3n
\fB\-i\fR, \fB\-\-inactive\fR\fIДНЕЙ\fR
Этот параметр используется для блокировки учётной записи по прошествии заданного числа дней после устаревания пароля. То есть, если пароль устарел и прошло более указанных
\fIДНЕЙ\fR, то пользователь больше не сможет использовать данную учётную запись.
.TP 3n
\fB\-k\fR, \fB\-\-keep\-tokens\fR
Указывает, что изменение пароля нужно выполнить только для устаревших ключей аутентификации (паролей). Пользователи хотят оставить свои непросроченные ключи нетронутыми.
.TP 3n
\fB\-l\fR, \fB\-\-lock\fR
Заблокировать указанную учётную запись. Этот параметр блокирует учётную запись изменяя значение пароля на вариант, который не может быть шифрованным паролем.
.TP 3n
\fB\-m\fR, \fB\-\-mindays\fR\fIМИН_ДНЕЙ\fR
Задать
\fIминимальное количество дней\fR
между сменой пароля. Нулевое значение этого поля указывает на то, что пользователь может менять свой пароль когда захочет.
.TP 3n
\fB\-q\fR, \fB\-\-quiet\fR
Не выводить сообщений при работе.
.TP 3n
\fB\-r\fR, \fB\-\-repository\fR\fIРЕПОЗИТОРИЙ\fR
Изменить пароль в
\fIРЕПОЗИТОРИИ\fR.
.TP 3n
\fB\-S\fR, \fB\-\-status\fR
Показать состояние учётной записи. Информация о состоянии содержит 7 полей. Первое поле содержит имя учётной записи. Второе поле указывает, заблокирована ли учётная запись (L), она без пароля (NP) или у неё есть рабочий пароль (P). Третье поле хранит дату последнего изменения пароля. В следующих четырёх полях хранятся минимальный срок, максимальный срок, период выдачи предупреждения и период неактивности пароля. Эти сроки измеряются в днях.
.TP 3n
\fB\-u\fR, \fB\-\-unlock\fR
Разблокировать указанную учётную запись. Этот параметр активирует учётную запись изменяя пароль на прежнее значение (которое было перед использованием параметра
\fB\-l\fR).
.TP 3n
\fB\-w\fR, \fB\-\-warndays\fR\fIПРЕД_ДНЕЙ\fR
Установить число дней выдачи предупреждения, перед тем как потребуется смена пароля. В параметре
\fIПРЕД_ДНЕЙ\fR
указывается число дней перед тем как пароль устареет, в течении которых пользователю будут напоминать, что пароль скоро устареет.
.TP 3n
\fB\-x\fR, \fB\-\-maxdays\fR\fIМАКС_ДНЕЙ\fR
Установить максимальное количество дней, в течении которых пароль остаётся рабочим. После
\fIМАКС_ДНЕЙ\fR
пароль нужно изменить.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Не все параметры могут работать. Сложность пароля проверяется по разному на разных машинах. Пользователю настоятельно советуется выбирать пароль такой сложности, чтобы ему нормально работалось. Пользователи не могут изменять свои пароли в системе, если включён NIS и они не вошли на сервер NIS.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Программа
\fBpasswd\fR
завершая работу, возвращает следующие значения:
.TP 3n
\fI0\fR
успешное выполнение
.TP 3n
\fI1\fR
доступ запрещён
.TP 3n
\fI2\fR
недопустимая комбинация параметров
.TP 3n
\fI3\fR
неожиданная ошибка при работе, ничего не сделано
.TP 3n
\fI4\fR
неожиданная ошибка при работе, отсутствует файл
\fIpasswd\fR
.TP 3n
\fI5\fR
файл
\fIpasswd\fR
занят другой программой, попробуйте ещё раз
.TP 3n
\fI6\fR
недопустимое значение параметра
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5).
