.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "passwd" "5" "11/10/2005" "Форматы файлов" "Форматы файлов"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
passwd \- файл паролей
.SH "ОПИСАНИЕ"
.PP
\fI/etc/passwd\fR
содержит учётные записи пользователей, по одной в каждой строке. Строка состоит из семи полей, разделённых двоеточиями (\(Fo:\(Fc). Поля:
.TP 3
\(bu
имя пользователя для входа в систему
.TP
\(bu
необязательный зашифрованный пароль
.TP
\(bu
числовой идентификатор пользователя
.TP
\(bu
числовой идентификатор группы
.TP
\(bu
имя\-фамилия пользователя или поле комментария
.TP
\(bu
домашний каталог пользователя
.TP
\(bu
необязательный интерпретатор командной строки пользователя
.PP
Поле с зашифрованным паролем может быть пустым, и тогда для входа под этой учётной записью пароль не требуется. Однако, некоторые приложения, которые читают файл
\fI/etc/passwd\fR
, могут решить не позволять
\fIлюбой\fR
доступ, если поле
\fIпароля\fR
пустое. Если поле
\fIпароля\fR
содержит строчную
\(Fox\(Fc, то шифрованный пароль хранится в файле
\fBshadow\fR(5)
;
\fIдолжна\fR
быть соответствующая строка в файле
\fIshadow\fR
, иначе учётная запись считается недействительной. Если в поле
\fIпароля\fR
содержится какая\-то другая строка, то она воспринимается как шифрованный пароль, как определено в
\fBcrypt\fR(3).
.PP
Поле комментария используется различными системными утилитами, такими как
\fBfinger\fR(1).
.PP
В поле домашнего каталога хранится начальный рабочий каталог. Программа
\fBlogin\fR
использует эту информацию для установки значения переменной среды
\fB$HOME\fR.
.PP
В поле интерпретатора командной строки хранится имя интерпретатора командной строки пользователя или название программы, которая будет запущена первой. Программа
\fBlogin\fR
использует эту информацию для установки значения переменной среды
\fB$SHELL\fR. Если это поле пустое, то используется значение по умолчанию
\fI/bin/sh\fR.
.SH "ФАЙЛЫ"
.TP
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP
\fI/etc/shadow\fR
необязательный файл с шифрованными паролями
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgetent\fR(1),
\fBlogin\fR(1),
\fBpasswd\fR(1),
\fBsu\fR(1),
\fBcrypt\fR(3),
\fBgetpwnam\fR(3),
\fBshadow\fR(5),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBsulogin\fR(8).
