.\"     Title: sg
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "sg" "1" "06/24/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
sg \- выполняет команду с правами другой группы
.SH "СИНТАКСИС"
.HP 3
\fBsg\fR [\-] [группа\ [\-c]\ команда]
.SH "ОПИСАНИЕ"
.PP
Команда
\fBsg\fR
работает подобно команде
\fBnewgrp\fR, но в качестве параметра ожидает команду. Команда будет выполнена оболочкой
\fI/bin/sh\fR. В большинстве оболочек, откуда может запускаться
\fBsg\fR, команду из нескольких слов нужно заключать в кавычки. Другим отличием между
\fBnewgrp\fR
и
\fBsg\fR
является то, что некоторые оболочки воспринимают
\fBnewgrp\fR
особенным образом, заменяя себя новым экземпляром оболочки, которую создаёт
\fBnewgrp\fR. Этого не происходит с командой
\fBsg\fR, поэтому после завершения работы
\fBsg\fR
вы возвращаетесь в предыдущую группу.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.TP 3n
\fI/etc/group\fR
содержит информацию о группах
.TP 3n
\fI/etc/gshadow\fR
содержит защищаемую информацию о группах
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBid\fR(1),
\fBlogin\fR(1),
\fBnewgrp\fR(1),
\fBsu\fR(1),
\fBgpasswd\fR(1),
\fBgroup\fR(5),
\fBgshadow\fR(5)
