.\"     Title: shadow
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Форматы файлов
.\"    Source: Форматы файлов
.\"
.TH "shadow" "5" "06/24/2006" "Форматы файлов" "Форматы файлов"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
shadow \- файл с защищаемой информацией о пользователях
.SH "ОПИСАНИЕ"
.PP
\fIshadow\fR
содержит шифрованные пароли учётных записей пользователей и необязательную информацию об устаревании пароля. Включает в себя:
.TP 3n
\(bu
имя пользователя для входа в систему
.TP 3n
\(bu
шифрованный пароль
.TP 3n
\(bu
число дней с момента последнего изменения пароля, начиная с 1 января 1970 года
.TP 3n
\(bu
число дней, перед тем как пароль может быть изменён
.TP 3n
\(bu
число дней, после которых пароль должен быть изменён
.TP 3n
\(bu
число дней, за сколько пользователя начнут предупреждать, что пароль устаревает
.TP 3n
\(bu
число дней, после устаревания пароля для блокировки учётной записи
.TP 3n
\(bu
дней, отсчитывая с 1 января 1970 года, когда учётная запись была заблокирована
.TP 3n
\(bu
зарезервированное поле
.sp
.RE
.PP
Поле пароля должно быть заполнено. Шифрованный пароль имеет длину от 13 до 24 символов и состоит из 64 символов алфавита от a до z, от A до Z, от 0 до 9, \\. и /. Пароль может начинаться с символа "$". Это означает, что шифрованный пароль был сгенерирован с использованием другого (не DES) алгоритма. Например, если он начинается с "$1$", то это означает, что использовался алгоритм на основе MD5.
.PP
Подробней о пароле смотрите на странице руководства
\fBcrypt\fR(3).
.PP
Если поле пароля содержит строку, которая не удовлетворяет требованиям
\fBcrypt\fR(3), например содержит ! или *, то пользователь не сможет использовать этот unix пароль для регистрации с учётом настроек
\fBpam\fR(7).
.PP
Дата последнего изменения пароля задаётся в днях, прошедших с 1 января 1970 года. Пароль не может быть изменён пока не пройдёт положенное число дней, и должен быть изменён после максимального числа дней. Если обязательное минимальное число дней больше чем максимальное число дней, то такой пароль не может быть изменён пользователем.
.PP
Учётная запись считается неактивной и будет заблокирована, если пароль не был изменён за заданное число дней после устаревания пароля. Учётная запись также будет заблокирована в заданный день, независимо от другой информации об устаревании пароля.
.PP
Информация из этого файла заменяет любой пароль или информацию об устаревании, содержащуюся в файле
\fI/etc/passwd\fR.
.PP
Этот файл должен быть недоступен обычному пользователю, если нужно обеспечить безопасность паролей.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchage\fR(1),
\fBlogin\fR(1),
\fBsu\fR(1),
\fBpasswd\fR(1),
\fBpasswd\fR(5),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBsulogin\fR(8).
