.\"     Title: su
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "su" "1" "06/24/2006" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
su \- изменяет ID пользователя или делает его суперпользователем
.SH "СИНТАКСИС"
.HP 3
\fBsu\fR [\fIпараметры\fR] [\-] [\fIимя_пользователя\fR\ [\ \fIпараметры\fR\ ]]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBsu\fR
используется для того чтобы, пользователь мог стать другим пользователем в текущей сессии. Если
\fBsu\fR
вызывается без
\fBимени_пользователя\fR, то по умолчанию делает пользователя суперпользователем. Необязательный параметр
\fB\-\fR
можно использовать для воссоздания рабочей среды, такой же как если быть настоящий пользователь выполнял вход в систему.
.PP
После имени пользователя можно указать дополнительные аргументы, которые будут переданы регистрационной оболочке пользователя. В частности, аргумент
\fB\-c\fR
заставит большинство оболочек считать следующий аргумент как команду. Команда будет выполнена оболочкой, указанной в файле
\fI/etc/passwd\fR, которая является регистрационной для указываемого пользователя.
.PP
Вы можете использовать параметр
\fB\-\-\fR
чтобы отделить параметры
\fBsu\fR
от параметров передаваемых оболочке.
.PP
Пользователю предложат ввести пароль, если он задан. При неверном пароле возникает сообщение об ошибке. Все попытки, удачные и неудачные, протоколируются системой с целью обнаружения злоупотреблений.
.PP
Текущая рабочая среда передаётся оболочке. Значение
\fB$PATH\fR
устанавливается равным
\fI/bin:/usr/bin\fR
для обычных пользователей, или
\fI/sbin:/bin:/usr/sbin:/usr/bin\fR
для суперпользователя. Эти значения можно изменить в переменных
\fIENV_PATH\fR
и
\fIENV_SUPATH\fR
в файле
\fI/etc/login.defs\fR.
.PP
Субсистемный вход в систему можно распознать по наличию символа "*" в начале регистрационной оболочки. Заданный домашний каталог будет использован как корень новой файловой системы, в которой регистрируется пользователь.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBsu\fR:
.TP 3n
\fB\-c\fR, \fB\-\-command\fR\fIОБОЛОЧКА\fR
Указать команду, которая будет запущена оболочкой в виде параметра для
\fB\-c\fR.
.TP 3n
\fB\-\fR, \fB\-l\fR, \fB\-\-login\fR
Предоставляет среду, как если бы пользователь непосредственно регистрировался в системе.
.sp
Если используется
\fB\-\fR, то он должен быть задан последним параметром
\fBsu\fR. Другие формы (\fB\-l\fR
и
\fB\-\-login\fR) не имеют этого ограничения.
.TP 3n
\fB\-s\fR, \fB\-\-shell\fR\fIОБОЛОЧКА\fR
Оболочка, которая будет запущена.
.sp
Запущенная оболочка выбирается из (в порядке убывания приоритета):
.RS 3n
.TP 3n
\(bu
Оболочка указанная в параметре \-\-shell
.TP 3n
\(bu
Если используется
\fB\-\-preserve\-environment\fR, то оболочка задаётся переменной среды
\fB$SHELL\fR.
.TP 3n
\(bu
Оболочка, указанная в записи файла
\fI/etc/passwd\fR
для заданного пользователя.
.TP 3n
\(bu
\fI/bin/sh\fR, если ни одной оболочке не было найдено с помощью методов, указанных выше.
.RE
.IP "" 3n
.sp
Если заданный пользователь имеет ограниченную оболочку (то есть оболочка в поле пользовательской записи в файле
\fI/etc/passwd\fR
не прописана в файле
\fI/etc/shell\fR), то параметр
\fB\-\-shell\fR
или переменная среды
\fB$SHELL\fR
не будет взята из учётной записи, если
\fBsu\fR
не была запущена суперпользователем.
.TP 3n
\fB\-m\fR, \fB\-p\fR, \fB\-\-preserve\-environment\fR
Сохранить имеющуюся рабочую среду.
.sp
Если заданный пользователь имеет ограниченную оболочку, то этот параметр не сработает (если
\fBsu\fR
не запускается суперпользователем).
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Данная версия программы
\fBsu\fR
может быть собрана с разными параметрами и только некоторые из них смогут быть использованы на любой машине.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1),
\fBlogin.defs\fR(5),
\fBsh\fR(1)
