.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "su" "1" "11/10/2005" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
su \- изменяет ID пользователя или делает его суперпользователем
.SH "СИНТАКСИС"
.HP 3
\fBsu\fR [\-] [\fIимя_пользователя\fR\ [\ \fIпараметры\fR\ ]]
.SH "ОПИСАНИЕ"
.PP
\fBsu\fR
используется для того чтобы, пользователь мог стать другим пользователем в текущей сессии. Если
\fBsu\fR
вызывается без имени пользователя, то по умолчанию делает пользователя суперпользователем. Необязательный параметр
\fB\-\fR
можно использовать, чтобы воссоздать рабочую среду, такую же как если быть настоящий пользователь выполнял вход в систему.
.PP
После имени пользователя можно указать дополнительные аргументы, которые будут переданы регистрационной оболочке пользователя. В частности, аргумент
\fB\-c\fR
заставит считать большинство оболочек следующий аргумент как команду. Команда будет выполнена оболочкой, указанной в файле
\fI/etc/passwd\fR
, которая является регистрационной для указываемого пользователя.
.PP
Пользователю предложат ввести пароль, если он задан. Неправльный пароль вызовет сообщение об ошибке. Все попытки, удачные и неудачные, протоколируются системой с целью обнаружения злоупотреблений.
.PP
Текущая рабочая среда передаётся оболочке. Значение
\fI$PATH\fR
устанавливается равным
\fI/bin:/usr/bin\fR
для обычных пользователей, или
\fI/sbin:/bin:/usr/sbin:/usr/bin\fR
для суперпользователя. Эти значения можно изменить в переменных
\fIENV_PATH\fR
и
\fIENV_SUPATH\fR
в файле
\fI/etc/login.defs\fR.
.PP
Субсистемный вход в систему можно распознать по наличию символа "*" в начале регистрационной оболочки. Заданный домашний каталог будет использован как корень новой файловой системы, в которой регистрируется пользователь.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Данная версия программы
\fBsu\fR
имеет много параметров сборки, только некоторые из них могут быть использованы на любой машине.
.SH "ФАЙЛЫ"
.TP
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1),
\fBlogin.defs\fR(5),
\fBsh\fR(1),
\fBsuauth\fR(5).
