.\"     Title: suauth
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Форматы файлов
.\"    Source: Форматы файлов
.\"
.TH "suauth" "5" "06/24/2006" "Форматы файлов" "Форматы файлов"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
suauth \- файл управления командой su
.SH "СИНТАКСИС"
.HP 12
\fB/etc/suauth\fR
.SH "ОПИСАНИЕ"
.PP
Файл
\fI/etc/suauth\fR
проверяется каждый раз при запуске команды su. Он влияет на поведение команды su, в зависимости от:
.sp
.RS 3n
.nf
      1) пользователя, права которого нужно получить с помощью su
    
.fi
.RE
.sp
.PP
2) пользователя, запустившего команду su (или группы, членом которой он может быть)
.PP
Формат файла показан ниже, строки начинающиеся с # считаются комментарием и игнорируются;
.sp
.RS 3n
.nf
      желаемый\-id:желающий\-id:ДЕЙСТВИЕ
    
.fi
.RE
.PP
Где желаемый\-id может быть словом
\fIALL\fR, списком имён пользователей, перечисленных через запятую "," или фразы
\fIALL EXCEPT\fR
, после которой идёт список имён пользователей перечисленных через ","
.PP
желающий\-id может содержать то же, что и желательный\-id, плюс новое слово\fIGROUP\fR.
\fIALL EXCEPT GROUP\fR
тоже допустимо. После
\fIGROUP\fR
указывается одна или более названий групп, разделённых ",". Недостаточно иметь id первичной группы соответствующей группы, необходимо иметь запись в файле
\fB/etc/group\fR(5).
.PP
В поле ДЕЙСТВИЕ может быть только одно из следующих значений:
.TP 3n
\fIDENY\fR
Команда su останавливает выполнение, даже не спрашивая пароль.
.TP 3n
\fINOPASS\fR
Команда su выполняется без запроса пароля.
.TP 3n
\fIOWNPASS\fR
Чтобы успешно выполнить команду su, пользователь должен ввести свой собственный пароль.
.PP
Заметим, что тут используются три поля, разделённых двоеточиями. Никаких пробелов не допускается около двоеточий. Также заметим, что файл просматривается строка за строкой, и первое подходящее правило будет использовано без проверки оставшихся правил. Это позволяет системному администратору осуществлять любой контроль, какой он пожелает.
.SH "ПРИМЕР"
.sp
.RS 3n
.nf
      # пример файла /etc/suauth
      #
      # Пара привилегированных имён пользователей
      # могут выполнить su, чтобы получить права суперпользователя введя свой пароль.
      #
      root:chris,birddog:OWNPASS
      #
      # Все остальные не могут выполнить su для получения root, если они 
      # не члены группы wheel. Так настроено в BSD.
      #
      root:ALL EXCEPT GROUP wheel:DENY
      #
      # Возможно учётными записями terry и birddog
      # владеет один человек.
      # Переход из одной записи в другую
      # можно сделать без запроса пароля.
      #
      terry:birddog:NOPASS
      birddog:terry:NOPASS
      #
    
.fi
.RE
.sp
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/suauth\fR
.SH "ОШИБКИ РЕАЛИЗАЦИИ"
.PP
Может быть несколько кривостей. Анализатор файла, в частности, не прощает синтаксических ошибок, ожидая, что не будет недопустимых пробелов (кроме как в начале и конце строк) и специальных слов, разделяющих различные вещи.
.SH "ДИАГНОСТИКА"
.PP
Ошибки при анализе файла выводятся с помощью
\fBsyslogd\fR(8)
с уровнем ERR средства AUTH.
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBsu\fR(1).
