.\"     Title: useradd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/19/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "useradd" "8" "07/19/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
useradd \- регистрирует нового пользователя или изменяет информацию по умолчанию о новых пользователях
.SH "СИНТАКСИС"
.HP 8
\fBuseradd\fR [\fIпараметры\fR] \fILOGIN\fR
.HP 8
\fBuseradd\fR \-D
.HP 8
\fBuseradd\fR \-D [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
При запуске без параметра
\fB\-D\fR, команда
\fBuseradd\fR
создаёт новую учётную запись пользователя, используя значения из командной строки и системные значения по умолчанию. В зависимости от параметров командной строки, команда useradd обновляет системные файлы, а также может создать домашний каталог нового пользователя и скопировать файлы настроек.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBuseradd\fR:
.TP 3n
\fB\-c\fR, \fB\-\-comment\fR\fIКОММЕНТАРИЙ\fR
Любая текстовая строка. Обычно, здесь коротко описывается учётная запись, и в настоящее время используется как поле для имени и фамилии пользователя.
.TP 3n
\fB\-b\fR, \fB\-\-base\-dir\fR\fIБАЗОВЫЙ_КАТАЛОГ\fR
Базовый системный каталог по умолчанию, если другой каталог не указан с помощью параметра
\fB\-d\fR.
\fIБАЗОВЫЙ_КАТАЛОГ\fR
объединяется с именем учётной записи для определения домашнего каталога. Если не используется параметр
\fB\-m\fR, то
\fIБАЗОВЫЙ_КАТАЛОГ\fR
должен существовать.
.TP 3n
\fB\-d\fR, \fB\-\-home\fR\fIДОМАШНИЙ_КАТАЛОГ\fR
Для создаваемого пользователя будет использован каталог
\fIБАЗОВЫЙ_КАТАЛОГ\fR
в качестве начального каталога. По умолчанию, это значение получается объединением
\fIИМЕНИ\fR
пользователя с
\fIБАЗОВЫМ_КАТАЛОГОМ\fR
и используется как имя домашнего каталога. Каталог
\fIБАЗОВЫЙ_КАТАЛОГ\fR
необязательно должен существовать и не будет создан, если его нет.
.TP 3n
\fB\-e\fR, \fB\-\-expiredate\fR\fIДАТА_УСТАРЕВАНИЯ\fR
Дата, когда учётная запись пользователя будет заблокирована. Дата задаётся в формате
\fIГГГГ\-ММ\-ДД\fR.
.TP 3n
\fB\-f\fR, \fB\-\-inactive\fR\fIДНЕЙ\fR
Число дней, которые должны пройти после устаревания пароля, чтобы учётная запись заблокировалась навсегда. Если указано значение 0, то учётная запись блокируется сразу после устаревания пароля, а при значении \-1 данная возможность не используется. По умолчанию используется значение \-1.
.TP 3n
\fB\-g\fR, \fB\-\-gid\fR\fIГРУППА\fR
Имя или числовой идентификатор новой начальной группы пользователя. Группа с таким именем должна существовать. Идентификатор группы должен указывать на уже существующую группу. Идентификатор группы по умолчанию равен 1 или значению указанному в файле
\fI/etc/default/useradd\fR.
.TP 3n
\fB\-G\fR, \fB\-\-groups\fR\fIГРУППА1\fR[\fI,ГРУППА2,...\fR[\fI,ГРУППАN\fR]]]
Список дополнительных групп, в которых числится пользователь. Перечисление групп осуществляется через запятую, без промежуточных пробелов. На указанные группы действуют те же ограничения, что и для группы указанной в параметре
\fB\-g\fR. По умолчанию пользователь входит только в начальную группу.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Показать краткую справку и закончить работу.
.TP 3n
\fB\-m\fR, \fB\-\-create\-home\fR
Если домашнего каталога пользователя не существует, то он будет создан. Файлы из каталога
\fIКАТАЛОГ_ШАБЛОН\fR
будут скопированы в домашний каталог, если он указан параметр
\fB\-k\fR, иначе будут использованы файлы из каталога
\fI/etc/skel\fR. Все подкаталоги каталога
\fIКАТАЛОГ_ШАБЛОН\fR
или
\fI/etc/skel\fR
будут также созданы в домашнем каталоге пользователя. Параметр
\fB\-k\fR
можно использовать только вместе с параметром
\fB\-m\fR. По умолчанию, домашний каталог не создаётся и файлы не копируются.
.TP 3n
\fB\-K\fR, \fB\-\-key\fR\fIКЛЮЧ\fR=\fIЗНАЧЕНИЕ\fR
Используется для изменения значений по умолчанию, хранимых в файле /etc/login.defs (UID_MIN, UID_MAX, UMASK, PASS_MAX_DAYS и других).

Пример:
\fB\-K \fR\fIPASS_MAX_DAYS\fR=\fI\-1\fR
можно использовать при создании системной учётной записи, чтобы выключить устаревание пароля, даже если системная учётная запись вообще не имеет пароля. Можно указывать параметр
\fB\-K\fR
несколько раз, например:
\fB\-K \fR\fIUID_MIN\fR=\fI100\fR\fB \-K \fR\fIUID_MAX\fR=\fI499\fR
.sp
Замечание: запись вида
\fB\-K \fR\fIUID_MIN\fR=\fI10\fR,\fIUID_MAX\fR=\fI499\fR
пока не работает.
.TP 3n
\fB\-o\fR, \fB\-\-non\-unique\fR
Позволяет создать учётную запись с уже имеющимся (не уникальным) UID.
.TP 3n
\fB\-p\fR, \fB\-\-password\fR\fIПАРОЛЬ\fR
Шифрованное значение пароля, которое возвращает функция
\fBcrypt\fR(3). По умолчанию учётная запись заблокирована.
.TP 3n
\fB\-s\fR, \fB\-\-shell\fR\fIОБОЛОЧКА\fR
Имя регистрационной оболочки пользователя. Если задать пустое значение, то будет использована регистрационная оболочка по умолчанию.
.TP 3n
\fB\-u\fR, \fB\-\-uid\fR\fIUID\fR
Числовое значение идентификатора пользователя (ID). Оно должно быть уникальным, если не используется параметр
\fB\-o\fR. Значение должно быть неотрицательным. По умолчанию используется наименьшее значение ID большее 999 и большее любого другого значения пользователя. Значения от 0 до 999 обычно зарезервированы для системных учётных записей.
.SS "Изменение значений по умолчанию"
.PP
При запуске программы с параметром
\fB\-D\fR
команда
\fBuseradd\fR
показывает текущие значения по умолчанию или изменяет их, если указаны дополнительные параметры в командной строке. Допустимые параметры:
.TP 3n
\fB\-b\fR, \fB\-\-base\-dir\fR\fIБАЗОВЫЙ_КАТАЛОГ\fR
Начальная часть пути нового домашнего каталога пользователя. Имя пользователя будет добавлено в конец
\fIДОМАШНЕГО_КАТАЛОГА\fR
для создания имени нового каталога, если не задан параметр
\fB\-d\fR
при создании новой учётной записи.
.TP 3n
\fB\-e\fR, \fB\-\-expiredate\fR\fIДАТА_УСТАРЕВАНИЯ\fR
Дата, когда учётная запись пользователя заблокирована.
.TP 3n
\fB\-f\fR, \fB\-\-inactive\fR\fIДНЕЙ\fR
Число дней, которые должны пройти после устаревания пароля, перед тем как учётная запись будет заблокирована.
.TP 3n
\fB\-g\fR, \fB\-\-gid\fR\fIГРУППА\fR
Имя или числовой идентификатор новой начальной группы пользователя. Группа с таким именем должна существовать и для числового идентификатора должна быть запись.
.TP 3n
\fB\-s\fR, \fB\-\-shell\fR\fIОБОЛОЧКА\fR
Имя новой регистрационной оболочки пользователя. Данная программа будет использована для всех новых пользовательских учётных записей.
.PP
Если программа запущена без параметров,
\fBuseradd\fR
покажет текущие значения по умолчанию.
.\" end of SS subsection "Изменение значений по умолчанию"
.SH "ЗАМЕЧАНИЯ"
.PP
Системный администратор сам решает, какие файлы нужно положить в каталог
\fI/etc/skel/\fR.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Нельзя добавить пользователя в NIS группу. Это необходимо делать на NIS сервере.
.PP
Также, если имя пользователя уже существует во внешней базе данных такой как NIS, то
\fBuseradd\fR
не станет создавать учётную запись пользователя.
.PP
Имена пользователей должны начинаться со строчной буквы или символа подчёркивания, и должны состоять только из строчных букв, символов подчёркивания, тире и знака доллара. Это можно описать регулярным выражением: [a\-z_][a\-z0\-9_\-]*[$]
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.TP 3n
\fI/etc/group\fR
содержит информацию о группах
.TP 3n
\fI/etc/default/useradd\fR
содержит защищаемую информацию о пользователях
.TP 3n
\fI/etc/skel/\fR
каталог, содержащий пользовательские файлы по умолчанию
.TP 3n
\fI/etc/login.defs\fR
содержит конфигурацию подсистемы теневых паролей
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Команда
\fBuseradd\fR
завершая работу, возвращает следующие значения:
.TP 3n
\fI0\fR
успешное выполнение
.TP 3n
\fI1\fR
не удалось изменить файл паролей
.TP 3n
\fI2\fR
ошибка в параметрах команды
.TP 3n
\fI3\fR
недопустимое значение параметра
.TP 3n
\fI4\fR
такой UID уже существует (и не задан параметр
\fB\-o\fR)
.TP 3n
\fI6\fR
указанная группа не существует
.TP 3n
\fI9\fR
имя пользователя уже существует
.TP 3n
\fI10\fR
не удалось изменить файл групп
.TP 3n
\fI12\fR
не удалось создать домашний каталог
.TP 3n
\fI13\fR
не удалось создать почтовый ящик
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBcrypt\fR(3),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBnewusers\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8).
