.\"     Title: userdel
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 06/24/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "userdel" "8" "06/24/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
userdel \- удаляет учётную запись и файлы пользователя
.SH "СИНТАКСИС"
.HP 8
\fBuserdel\fR [параметры] \fILOGIN\fR
.SH "ОПИСАНИЕ"
.PP
Команда
\fBuserdel\fR
изменяет системные файлы учётных записей, удаляя все записи, относящиеся к указанному
\fIимени_пользователя\fR. Заданная учётная запись должна существовать.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBuserdel\fR:
.TP 3n
\fB\-f\fR, \fB\-\-force\fR
С этим параметром учётная запись будет удалена, даже если пользователь в этот момент работает в системе. Она также заставляет
\fBuserdel\fR
удалить домашний каталог пользователя и почтовый ящик, даже если другой пользователь использует тот же домашний каталог или если почтовый ящик не принадлежит данному пользователю. Если значение
\fIUSERGROUPS_ENAB\fR
равно
\fIyes\fR
в файле
\fI/etc/login.defs\fR
и если существует группа с именем удаляемого пользователя, то это группа будет удалена, даже если она всё ещё является первичной группой другого пользователя.
.sp
\fIПримечание:\fR
Этот параметр опасно использовать; он может привести систему в нерабочее состояние.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Показать краткую справку и закончить работу.
.TP 3n
\fB\-r\fR, \fB\-\-remove\fR
Файлы в домашнем каталоге пользователя будут удалены вместе с самим домашним каталогом и почтовым ящиком. Пользовательские файлы, расположенные в других файловых системах, нужно искать и удалять вручную.
.sp
Имя файла почтового ящика задаётся переменной
\fIMAIL_DIR\fR
в файле
\fIlogin.defs\fR.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/group\fR
содержит информацию о группах
.TP 3n
\fI/etc/login.defs\fR
содержит конфигурацию подсистемы теневых паролей
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Команда
\fBuserdel\fR
завершая работу, возвращает следующие значения:
.TP 3n
\fI0\fR
успешное выполнение
.TP 3n
\fI1\fR
не удалось изменить файл паролей
.TP 3n
\fI2\fR
ошибка в параметрах команды
.TP 3n
\fI6\fR
указанный пользователь не существует
.TP 3n
\fI8\fR
пользователь сейчас работает в системе
.TP 3n
\fI10\fR
не удалось изменить файл групп
.TP 3n
\fI12\fR
не удалось удалить домашний каталог
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Команда
\fBuserdel\fR
не будет удалять учётную запись, если пользователь в данный момент работает в системе. Вы должны завершить все запущенные процессы, принадлежащие учётной записи, которую нужно удалить.
.PP
Нельзя удалить NIS атрибуты клиента NIS. Это необходимо сделать на NIS сервере.
.PP
Если значение переменной
\fIUSERGROUPS_ENAB\fR
равно
\fIyes\fR
в файле
\fI/etc/login.defs\fR, то
\fBuserdel\fR
удалит группу с именем как у пользователя. Чтобы избежать рассогласованности в базах данных групп и паролей,
\fBuserdel\fR
проверит, что данная группа не используется в качестве первичной для другого пользователя, и выдаст предупреждение без удаления, если такое случится. Параметр
\fB\-f\fR
поможет удалить группу в любом случае.
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBlogin.defs\fR(5),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBuseradd\fR(8),
\fBusermod\fR(8).
