.\"     Title: usermod
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/19/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "usermod" "8" "07/19/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
usermod \- изменяет учётную запись пользователя
.SH "СИНТАКСИС"
.HP 8
\fBusermod\fR [\fIпараметры\fR] \fILOGIN\fR
.SH "ОПИСАНИЕ"
.PP
Команда
\fBusermod\fR
изменяет системные файлы учётных записей согласно переданным в командной строке параметрам.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBusermod\fR:
.TP 3n
\fB\-a\fR, \fB\-\-append\fR
Добавить пользователя в дополнительную группу(ы). Использовать только вместе с параметром
\fB\-G\fR.
.TP 3n
\fB\-c\fR, \fB\-\-comment\fR\fIКОММЕНТАРИЙ\fR
Новое значение поля комментария в файле пользовательских паролей. Обычно его изменяют с помощью программы
\fBchfn\fR(1).
.TP 3n
\fB\-d\fR, \fB\-\-home\fR\fIДОМАШНИЙ_КАТАЛОГ\fR
Новый домашний каталог пользователя. Если указан параметр
\fB\-m\fR, то содержимое текущего домашнего каталога будет перемещено в новый домашний каталог, который будет создан, если он ещё не существует.
.TP 3n
\fB\-e\fR, \fB\-\-expiredate\fR\fIДАТА_УСТАРЕВАНИЯ\fR
Дата, когда учётная запись пользователя будет заблокирована. Дата задаётся в формате
\fIГГГГ\-ММ\-ДД\fR.
.TP 3n
\fB\-f\fR, \fB\-\-inactive\fR\fIДНЕЙ\fR
Число дней, которые должны пройти после устаревания пароля, чтобы учётная запись заблокировалась навсегда. Если указано значение 0, то учётная запись блокируется сразу после устаревания пароля, а при значении \-1 данная возможность не используется. По умолчанию используется значение \-1.
.TP 3n
\fB\-g\fR, \fB\-\-gid\fR\fIГРУППА\fR
Имя или числовой идентификатор новой начальной группы пользователя. Группа с таким именем должна существовать. Идентификатор группы должен указывать на уже существующую группу. По умолчанию идентификатор группы установлен в 1.
.TP 3n
\fB\-G\fR, \fB\-\-groups\fR\fIГРУППА1\fR[\fI,ГРУППА2,...\fR[\fI,ГРУППАN\fR]]]
Список дополнительных групп, в которых числится пользователь. Перечисление групп осуществляется через запятую, без промежуточных пробелов. На указанные группы действуют те же ограничения, что и для группы указанной в параметре
\fB\-g\fR. Если пользователь член группы, которой в указанном списке нет, то пользователь удаляется из этой группы. Такое поведение можно изменить с помощью параметра
\fB\-a\fR, при указании которого к уже имеющемуся списку групп пользователя добавляется список указанных дополнительных групп.
.TP 3n
\fB\-l\fR, \fB\-\-login\fR\fIНОВОЕ_ИМЯ\fR
Имя пользователя будет изменено с emphasis remap="I">ИМЯ
.TP 3n
\fB\-L\fR, \fB\-\-lock\fR
Заблокировать пароль пользователя. Это делается помещением символа '!' в начало шифрованного пароля, чтобы приводит к блокировке пароля. Не используйте этот параметр вместе с
\fB\-p\fR
или
\fB\-U\fR.
.TP 3n
\fB\-o\fR, \fB\-\-non\-unique\fR
При использовании с параметром
\fB\-u\fR, этот параметр позволяет указывать не уникальный числовой идентификатор пользователя.
.TP 3n
\fB\-p\fR, \fB\-\-password\fR\fIПАРОЛЬ\fR
Шифрованное значение пароля, которое возвращает функция
\fBcrypt\fR(3).
.TP 3n
\fB\-s\fR, \fB\-\-shell\fR\fIОБОЛОЧКА\fR
Имя новой регистрационной оболочки пользователя. Если задать пустое значение, то будет использована регистрационная оболочка по умолчанию.
.TP 3n
\fB\-u\fR, \fB\-\-uid\fR\fIUID\fR
Числовое значение идентификатора пользователя (ID). Значение должно быть уникальным, если не задан параметр
\fB\-o\fR. Значение должно быть неотрицательным. Значения от 0 до 999 обычно зарезервированы для системных учётных записей. Для всех файлов, которыми владеет пользователь и которые расположены в его домашнем каталоге идентификатор владельца файла будет изменён автоматически. Для файлов, расположенных вне домашнего каталога идентификатор нужно изменять вручную.
.TP 3n
\fB\-U\fR, \fB\-\-unlock\fR
Разблокировать пароль пользователя. Это выполняется удалением символа '!' из начала шифрованного пароля. Не используйте этот параметр вместе с
\fB\-p\fR
или
\fB\-L\fR.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Команда
\fBusermod\fR
не будет изменять имя пользователя, если этот пользователь в данный момент работает в системе. Если требуется изменить числовой идентификатор пользователя, нужно проверить, что от этого пользователя нет запущенных процессов. Владельца файлов
\fBcrontab\fR
нужно изменять вручную. Владельца заданий
\fBat\fR
нужно изменять вручную. Также вручную нужно сделать все изменения связанные с NIS на сервере NIS.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/group\fR
содержит информацию о группах
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBcrypt\fR(3),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8).
