.\"     Title: vipw
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/19/2006
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"
.TH "vipw" "8" "07/19/2006" "Команды управления системой" "Команды управления системой"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
vipw, vigr \- служат для редактирования файлов паролей, групп, теневых паролей пользователей или групп.
.SH "СИНТАКСИС"
.HP 5
\fBvipw\fR [\fIпараметры\fR]
.HP 5
\fBvigr\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
\fBvipw\fR
и
\fBvigr\fR
редактируют файлы
\fI/etc/passwd\fR
и
\fI/etc/group\fR, соответственно. Если указан параметр
\fB\-s\fR, то будут редактироваться теневые версии этих файлов,
\fI/etc/shadow\fR
и
\fI/etc/gshadow\fR, соответственно. На время работы программы устанавливают блокировку для предотвращения повреждения файла. При выборе редактора программы сначала проверяют переменную среды
\fB$VISUAL\fR, затем
\fB$EDITOR\fR, и если ничего не найдено, запускают стандартный редактор
\fBvi\fR(1).
.SH "ПАРАМЕТРЫ"
.PP
Параметры команд
\fBvipw\fR
и
\fBvigr\fR:
.TP 3n
\fB\-g\fR, \fB\-\-group\fR
Редактирует базу данных групп.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Показать краткую справку и закончить работу.
.TP 3n
\fB\-p\fR, \fB\-\-passwd\fR
Редактировать базу данных passwd.
.TP 3n
\fB\-q\fR, \fB\-\-quiet\fR
Не выводить сообщений при работе.
.TP 3n
\fB\-s\fR, \fB\-\-shadow\fR
Редактировать базу данных shadow или gshadow.
.SH "ФАЙЛЫ"
.TP 3n
\fI/etc/group\fR
содержит информацию о группах
.TP 3n
\fI/etc/gshadow\fR
содержит защищаемую информацию о группах
.TP 3n
\fI/etc/passwd\fR
содержит информацию о пользователях
.TP 3n
\fI/etc/shadow\fR
содержит защищаемую информацию о пользователях
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBvi\fR(1),
\fBgroup\fR(5),
\fBgshadow\fR(5)\fBpasswd\fR(5),
\fBshadow\fR(5).
