#!/bin/sh
# This script is run from debian/rules to generate MD5 checksums
# for all files in the package.
# $Id: checksums,v 1.1 1997/12/14 21:05:37 marekm Exp $
set -e
cd $1
md5sum `find * -type f ! -regex "DEBIAN/.*"` >DEBIAN/md5sums </dev/null
