.TH "NOLOGIN" "8" "01/07/2006" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "JMÉNO"
nologin \- slušně odmítne přihlášení
.SH "PŘEHLED"
.HP 8
\fBnologin\fR
.SH "POPIS"
.PP
\fBnologin\fR
zobrazí oznámení, že účet není dostupný a skončí s nenulovým
návratovým kódem. Program je zamýšlen jako vhodná náhrada pole shell
v souboru passwd pro zablokované účty.
.PP
Pro zakázání všech přihlášení prozkoumejte
\fBnologin\fR(5).
.SH "VIZ TAKÉ"
.PP
\fBlogin\fR(1),
\fBnologin\fR(5).
.SH "HISTORIE"
.PP
Příkaz
\fBnologin\fR
se objevil v BSD 4.4.
