.TH GROUPS 1 "GNU Shell Utilities" "FSF" \" \-*\- nroff \-*\-
.do hla cs
.do hpf hyphen.cs
.SH JMÉNO
groups \- vypí¹e skupiny, jich¾ je u¾ivatel èlenem
.SH POU®ITÍ
\fBgroups\fR [\fIu¾ivatel...\fR]
.SH POPIS
Tato dokumentace není dále udr¾ována a mù¾e být nepøesná nebo neúplná.
Autoritativním zdrojem je Texinfo dokumentace.
.PP
Tato manuálová stránka popisuje GNU verzi pøíkazu
.BR groups .
Pøíkaz
.B groups
vypí¹e jména v¹ech skupin, v nich¾ je zadaný \fIu¾ivatel\fR nebo aktuální proces,
pokud u¾ivatel není zadán, èlenem. Pokud jsou zadána jména u¾ivatelù, potom bude
jméno ka¾dého z u¾ivatelù vypsáno pøed seznam skupin, jich¾ je èlenem.
.PP
Seznam skupin je ekvivalentní s výstupem pøíkazu `id \-Gn'.
.SH VOLBY
Kdy¾ je GNU pøíkaz \fBgroups\fR vyvolán právì s jedním parametrem,
jsou rozpoznávány následující volby:
.TP
.I "\-\-help"
Vypí¹e návod k pou¾ití na standardní výstup a bezchybnì skonèí.
.TP
.I "\-\-version"
Vypí¹e èíslo verze na standardní výstup a bezchybnì skonèí.
