#!/usr/bin/expect

set timeout 2
expect_after default {puts stderr "\nFAIL"; exit 1}

spawn /bin/sh
send "if \[ \$(id -u) -eq 0 \]; then PS1='# '; else PS1='$ '; fi\r"
expect "# "

send "grpck\r"
expect "invalid group file entry"
expect "delete line 'foo:x:4294967296:'? "
send "yes\r"
expect "no matching group file entry in /etc/group"
expect "delete line 'foo:*::'? "
send "yes\r"
expect "grpck: the files have been updated"
expect "# "
send "echo \$?\r"
expect "2"
send "exit\r"
puts "OK\n"
exit 0
