#!/usr/bin/expect

set timeout 2
expect_after default {puts "\nFAIL"; exit 1}

spawn /bin/sh
send "if \[ \$(id -u) -eq 0 \]; then PS1='# '; else PS1='$ '; fi\r"
expect "# "

send "pwck\r"
expect "duplicate shadow password entry"
expect "delete line 'foo:!:12977:0:99999:7:::'? "
send "no\r"
expect "duplicate shadow password entry"
expect "delete line 'foo:!:12977:0:99999:7:::'? "
send "no\r"
expect "pwck: no changes"
expect "# "
send "echo \$?\r"
expect "2"
send "exit\r"
puts "OK\n"
exit 0
