.\" Copyright 1989 - 1993, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: pwconv.8,v 1.1 1997/12/07 23:27:13 marekm Exp $
.\"
.TH PWCONV 8
.SH NAME
pwconv \- convert and update shadow password files
.SH SYNOPSIS
.B pwconv
.SH DESCRIPTION
\fBPwconv\fR copies the password file information from \fI/etc/passwd\fR
to the shadow password file, \fI/etc/shadow\fR.
If the \fI/etc/shadow\fR file does not exist, it is created with
modes which only permit read access to the owner.
Shadow entries in the System V Release 3.2 format will be silently
converted to the new System V Release 4 format.
Any entries which are missing fields will have those fields
filled in with default values where appropriate.
New entries are created with passwords which expire in 10000 days,
with a last changed date of today,
unless password aging information was already present.
Shadow entries without corresponding entries in \fI/etc/passwd\fR
are removed.
.SH FILES
/etc/passwd
.br
/etc/shadow
.SH SEE ALSO
.BR passwd (1),
.BR passwd (5),
.BR shadow (5),
.BR pwunconv (8)
.SH AUTHOR
Julianne Frances Haugh (jfh@tab.com)
