.\"$Id: groups.1,v 1.2 2005/04/05 19:08:56 kloczek Exp $
.TH GROUPS 1L "GNU 쉘 유틸리티" "FSF" \" \-*\- nroff \-*\-
.SH 이름
groups \- 사용자가 속한 그룹들을 출력한다
.SH 개요
.B groups
[사용자명...]
.br
.B groups
{\-\-help,\-\-version}
.SH 설명
이 맨페이지는 GNU 버전의
.BR groups 
를 다룬다.
.B groups
는 주어진 각 
.IR username
또는 프로세스
가 속한 추가 그룹의 이름을 출력해준다.
만약 사용자명이 주어졌다면 각 사용자명이 소속된 그룹 목록 앞에 표시된다.
.PP
그룹 목록은 `id \-Gn'의 결과와 같다.
.SS 옵션
GNU
.B groups
가 단 한 개의 인수를 가지고 실행되면 다음 옵션들을 인식한다:
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
