.TH ID 1L "GNU 쉘 유틸리티" "FSF" \" \-*\- nroff \-*\-
.SH 이름
id \- 실제, 유효 UID와 GID를 출력한다.
.SH 개요
.B id
[\-gnruG] [\-\-group] [\-\-name] [\-\-real] [\-\-user] [\-\-groups]
[\-\-help] [\-\-version] [username]
.SH 설명
이 맨페이지는 GNU 버전의
.BR id 
를 다룬다.
.B id
는 주어진 사용자, 또는 사용자가 주어지지 않는 경우 프로세스의 주인에 대한
정보를 출력한다. 기본적으로 실제 사용자 ID, 실제 그룹 ID, 만약 실제 사용자
ID와 다르다면 유효 사용자 ID를, 마찬가지로 실제 그룹 ID와 다르다면 유효 그룹
ID를 출력하고 추가 그룹 ID를 출력한다. 각 항목은 식별 문자 그리고 괄호 안에
해당하는 사용자 또는 그룹명으로 표현된다.
.PP
.B id
에 옵션을 주면 위에서 열거한 정보의 일부만 보여준다.
.SS 옵션
.TP
.I "\-g, \-\-group"
오로지 그룹 ID만 출력한다.
.TP
.I "\-G, \-\-groups"
추가 그룹만 출력한다.
.TP
.I "\-\-help"
표준출력으로 사용법을 출력하고 정상적으로 종료한다.
.TP
.I "\-n, \-\-name"
ID 번호 대신 사용자명, 그룹명을 출력한다.
.IR \-u ,
.IR \-g ,
또는
.IR \-G 
를 필요로 한다.
.TP
.I "\-r, \-\-real"
유효 사용자, 유효 그룹 ID가 아니라 실제 ID 를 출력한다.
.IR \-u ,
.IR \-g ,
또는
.IR \-G 
를 필요로 한다.
.TP
.I "\-u, \-\-user"
오로지 사용자 ID 만 출력한다.
.TP
.I "\-\-version"
표준출력으로 버전정보를 출력하고 정상적으로 종료한다.
