#!/usr/bin/expect

set timeout 2
expect_after default {puts "\nFAIL"; exit 1}

spawn /bin/sh
send "if \[ \$(id -u) -eq 0 \]; then PS1='# '; else PS1='$ '; fi\r"
expect "# "

send "grpck\r"
expect "duplicate group entry"
expect "delete line 'foo:x:1000:daemon'? "
send "no\r"
expect "'daemon' is a member of the 'foo' group in /etc/group but not in /etc/gshadow"
expect "duplicate group entry"
expect "delete line 'foo:x:1000:bin'? "
send "no \r"
expect "grpck: no changes"
expect "# "
send "echo \$?\r"
expect "2"
send "exit\r"
puts "OK\n"
exit 0
