.\" $Id$
.\" Copyright 1989 - 1990, Julianne Frances Haugh
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Julianne F. Haugh nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JULIE HAUGH AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL JULIE HAUGH OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Japanese Version Copyright (c) 1997 Kazuyoshi Furutaka
.\"         all rights reserved.
.\" Translated Fri Feb 14 23:06:00 JST 1997
.\"         by Kazuyoshi Furutaka <furutaka@Flux.tokai.jaeri.go.jp>
.\" Updated Wed Apr 26 JST 2000 by Kentaro Shirakata <argrath@ub32.org>
.\" Updated Fri Jan 12 JST 2001 by Kentaro Shirakata <argrath@ub32.org>
.\" Updated Mon Mar  4 JST 2002 by Kentaro Shirakata <argrath@ub32.org>
.\" Modified Tue 16 Sep 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH SU 1
.SH 名前
su \- ユーザIDを変更する。またはスーパーユーザになる
.SH 書式
\fBsu\fR [\fB\-\fR] [\fIusername\fR [\fIargs\fR]]
.SH 説明
\fBsu\fR はログインセッション中に別のユーザになるために用いる。
ユーザ名を指定せずに起動した場合、
デフォルトではスーパーユーザの ID に変更する。
オプション引数 \fB\-\fR を用いると、
直接ログインした場合と同じ環境に初期化される。
.PP
ユーザ名の後ろに追加の引数を与えることもでき、
その場合引数はユーザのログインシェルに渡される。
特に、その引数の一つとして \fB\-c\fR を渡した場合、
それに続く引数は大部分のコマンドインタプリタにコマンドとして解釈される。
コマンドはそのユーザに (\fI/etc/passwd\fR で)
指定されているシェルで実行される。
.PP
必要な場合には、ユーザにはパスワードの入力が促される。
間違ったパスワードが入力された場合にはエラーメッセージが出力される。
\fIsu\fRしようとした場合は、システムの濫用を検知するために、
それが正しい場合も不正な場合も常に記録が残される。
.PP
現在の環境は新しいシェルに引き継がれる。
ただし
\fB$PATH\fR の値は、
通常のユーザでは \fB/bin:/usr/bin\fR に、
スーパーユーザでは \fB/sbin:/bin:/usr/sbin:/usr/bin\fR
に再設定される。
これは \fI/etc/login.defs\fR の
\fBENV_PATH\fR と \fBENV_SUPATH\fR で変更できる。
.PP
サブシステムログインでは、
ログインシェルの最初の文字に "*" を置く。
渡されたホームディレクトリは、
ユーザが実際にログインする新しいファイルシステムのルートとして扱われる。
.SH 警告
この版の \fBsu\fR には多くのコンパイル時オプションがあるが、
サイトによってはこの一部しか設定されていないこともある。
.SH ファイル
\fI/etc/passwd\fR \- ユーザアカウント情報
.br
\fI/etc/shadow\fR \- 暗号化パスワードと有効期限情報
.SH 関連項目
.BR login (1),
.BR sh (1),
.BR login.defs (5),
.BR suauth (5)
.SH 著者
Julianne Frances Haugh <julie78787@gmail.com>
