.\" $Id: chfn.1,v 1.3 2005/04/05 19:08:57 kloczek Exp $
.\" (c) 1994 by salvatore valente <svalente@athena.mit.edu>
.\"
.\" this program is free software.  you can redistribute it and
.\" modify it under the terms of the gnu general public license.
.\"  there is no warranty.
.TH CHFN 1 "October 13 1994" "chfn" "Linux Reference Manual"
.SH 名称
chfn \- 改 变 你 的 finger 讯 息
.SH 语法
.B chfn
[\ \-f\ full\-name\ ] [\ \-o\ office\ ] [\ \-p\ office\-phone\ ]
[\ \-h\ home\-phone\ ] [\ \-u\ ] [\ \-v\ ] [\ username\ ]
.SH 描述
.B chfn
是 用 来 改 变 你 的 finger 讯 息 。 讯 息 是 存 放 在
.I /etc/passwd 档 内 。 可 藉 由
.B finger
来 显 示 你 的 讯 息 。 Linux
.B finger
命 令 会 显 示 四 段 讯 息 ， 这 些 讯 息 均 可 藉 由
.B chfn
改 变
: 真 实 姓 名 ， 工 作 地 点 电 话 ， 及 你 家 的 电 话 。
.SS 命令列
每 一 段 讯 息 均 可 在 命 令 列 上 指 定 。 如 没 有 给 定 讯 息 ，
.B chfn
进 入 交 谈 模 式
.SS INTERACTIVE MODE
交谈模式
.B chfn
会 在 每 一 栏 前 提 示 。 在 提 示 状 态 下 ， 你 就 可 输 入 新 的 讯 息 或 
是 按  return 而 不 改 变 。
输 入 "none" 则 表 示 该 栏 空 白 。
.SH 选项
.TP
.I "\-f, \-\-full\-name"
真 实 姓 名
.TP
.I "\-h, \-\-home\-phone"
家 里 的 电 话
.TP
.I "\-o, \-\-office"
办 工 室 号 码
.TP
.I "\-p, \-\-office\-phone"
办 公 室 电 话
.TP
.I "\-u, \-\-help"
秀 出 使 用 说 明 短 讯 。
.TP
.I "\-v, \-\-version"
秀 出 版 本 讯 息 。
.SH "相关文件"
.BR finger (1),
.BR passwd (5)
.SH 作者
Salvatore Valente <svalente@mit.edu>
