.\" $Id$
.\" (c) 1994 by salvatore valente <svalente@athena.mit.edu>
.\"
.\" this program is free software.  you can redistribute it and
.\" modify it under the terms of the gnu general public license.
.\" there is no warranty.
.TH CHSH 1 "October 13 1994" "chsh" "Linux Reference Manual"
.SH 名称
chsh \- 更换你登入时所用的shell
.SH 语法
.B chsh
[\ \-s\ shell\ ] [\ \-l\ ] [\ \-u\ ] [\ \-v\ ] [\ username\ ]
.SH 描述
.B chsh
用来更换你登入时所用的shell
。在命令列没指定shell。
.B chsh
会提示一个给你。
.SS 有效的shell
.B chsh
可用指定路径全名的方式来指定任何一个可执行的档案。
然而，如果此 shell并没纪录在
.I /etc/shells
档上，则chsh会提出警告讯息。
.SH 选项
.TP
.I "\-l, \-\-list\-shells"
列出纪录在
.I /etc/shells
的shell。
.TP
.I "\-s, \-\-shell"
变更你的登入shell.
.TP
.I "\-u, \-\-help"
使用短讯。
.TP
.I "\-v, \-\-version"
版本资讯
.SH "相关文件"
.BR login (1),
.BR passwd (5),
.BR shells (5)
.SH 作者
Salvatore Valente <svalente@mit.edu>
