- name: Pull container image
  containers.podman.podman_image:
    name: '{{ image[distribution] }}'

- name: "Create and start {{ 'privileged' if privileged | default(false) else 'unprivileged' }} container"
  containers.podman.podman_container:
    name: "{{ container_name | default('builder') }}"
    state: started
    image: '{{ image[distribution] }}'
    command: "sleep 1d"
    privileged: "{{ privileged | default(false) }}"

- name: Prepare source tree
  ansible.builtin.shell: |
    podman exec {{ container_name | default('builder') }} rm -rf /usr/local/src/shadow
    podman exec {{ container_name | default('builder') }} mkdir -p /usr/local/src
    podman cp ../../ {{ container_name | default('builder') }}:/usr/local/src/shadow
