#!/usr/bin/expect

set timeout 2
expect_after default {puts stderr "\nFAIL"; exit 1}

spawn /bin/sh
send "if \[ \$(id -u) -eq 0 \]; then PS1='# '; else PS1='$ '; fi\r"
expect "# "

send "pwck tmp/passwd tmp/shadow\r"
expect "no matching password file entry in tmp/shadow"
expect "add user 'foo' in tmp/shadow? "
send "yes\r"
expect "invalid shadow password file entry"
expect "delete line 'foo:*:'? "
send "yes\r"
expect "pwck: the files have been updated"
expect "# "
send "echo \$?\r"
expect "2"
send "exit\r"
puts "OK\n"
exit 0
