#!/usr/bin/expect

set timeout 2
expect_after default {puts stderr "\nFAIL"; exit 1}

spawn /bin/sh
send "if \[ \$(id -u) -eq 0 \]; then PS1='# '; else PS1='$ '; fi\r"
expect "# "

send "passwd foo\r"
expect "Enter new UNIX password: "
send "foopassword\r"
expect "Retype new UNIX password: "
send "foopassword\r"
expect "passwd: password updated successfully"
expect "# "
send "echo \$?\r"
expect "0"
expect "# "
send "exit\r"
puts "OK\n"
exit 0
