.\"     Title: chgpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "CHGPASSWD" "8" "20\-07\-2006" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
chgpasswd \- uppdatera grupplösenord i satsläge
.SH "SYNOPSIS"
.HP 10
\fBchgpasswd\fR [\fIflaggor\fR]
.SH "BESKRIVNING"
.PP
\fBchgpasswd\fR
läser en lista på gruppnamn och lösenordspar från standard in och använder denna information för att uppdatera en uppsÃ\(Csttning redan existerande grupper. Varje rad är i formatet:
.PP
\fIgruppnamn\fR:\fIlösenord\fR
.PP
Som standard måste det insända lösenordet vara i klartext. Standardkrypteringsalgoritmen är DES.
.PP
This command is intended to be used in a large system environment where many accounts are created at a single time.
.SH "FLAGGOR"
.PP
Flaggorna som gäller för kommandot
\fBchgpasswd\fR
är:
.TP 3n
\fB\-e\fR, \fB\-\-encrypted\fR
Insända lösenord är i ett krypterat format.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Visa hjälpmeddelande och avsluta.
.TP 3n
\fB\-m\fR, \fB\-\-md5\fR
Använd MD5\-kryptering istället för DES när insända lösenord inte är krypterade.
.SH "TÄNK PÅ"
.PP
Kom ihåg att ställa in rättigheter eller umask för att förhindra lÃ\(Cssning av okrypterade filer för andra användare.
.SH "SE OCKSÅ"
.PP
\fBgpasswd\fR(1),
\fBgroupadd\fR(8).
