.\"     Title: chpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "CHPASSWD" "8" "20\-07\-2006" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
chpasswd \- uppdatera lösenord i satsläge
.SH "SYNOPSIS"
.HP 9
\fBchpasswd\fR [\fIflaggor\fR]
.SH "BESKRIVNING"
.PP

\fBchpasswd\fR
reads a list of user name and password pairs from standard input and uses this information to update a group of existing users. Each line is of the format:
.PP
\fIanvändarnamn\fR:\fIlösenord\fR
.PP
By default the supplied password must be in clear\-text. Default encryption algorithm is DES. Also the password age will be updated, if present.
.PP
This command is intended to be used in a large system environment where many accounts are created at a single time.
.SH "FLAGGOR"
.PP
Flaggorna som gäller för kommandot
\fBchpasswd\fR
är:
.TP 3n
\fB\-e\fR, \fB\-\-encrypted\fR
Insända lösenord är i ett krypterat format.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Visa hjälpmeddelande och avsluta.
.TP 3n
\fB\-m\fR, \fB\-\-md5\fR
Använd MD5\-kryptering istället för DES när insända lösenord inte är krypterade.
.SH "TÄNK PÅ"
.PP
Kom ihåg att ställa in rättigheter eller umask för att förhindra lÃ\(Cssning av okrypterade filer för andra användare.
.SH "SE OCKSÅ"
.PP
\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBuseradd\fR(8).
