.\"     Title: faillog
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: 
.\"    Source: 
.\"
.TH "FAILLOG" "5" "20\-07\-2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
faillog \- login failure logging file
.SH "BESKRIVNING"
.PP
\fI/var/log/faillog\fR
maintains a count of login failures and the limits for each account. The file is fixed length record, indexed by numerical UID. Each record contains the count of login failures since the last successful login; the maximum number of failures before the account is disabled; the line the last login failure occurred on; the date the last login failure occurred; and the time in seconds how long the account will be locked after a failure.
.PP
Strukturen för filen är:
.sp
.RS 3n
.nf
struct	faillog {
	short   fail_cnt;
	short   fail_max;
	char    fail_line[12];
	time_t  fail_time;
	long    fail_locktime;
};
.fi
.RE
.SH "FILER"
.TP 3n
\fI/var/log/faillog\fR
Failure logging file.
.SH "SE OCKSÅ"
.PP

\fBfaillog\fR(8)
