.\"     Title: groupadd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "GROUPADD" "8" "20\-07\-2006" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
groupadd \- skapa en ny grupp
.SH "SYNOPSIS"
.HP 9
\fBgroupadd\fR [\-g\ \fIGID\fR\ [\-o]] [\-f] [\-K\ \fINYCKEL\fR=\fIVÄRDE\fR] \fIgrupp\fR
.SH "BESKRIVNING"
.PP
The
\fBgroupadd\fR
command creates a new group account using the values specified on the command line and the default values from the system. The new group will be entered into the system files as needed.
.SH "FLAGGOR"
.PP
Flaggorna som gäller för kommandot
\fBgroupadd\fR
är:
.TP 3n
\fB\-f\fR
This option causes to just exit with success status if the specified group already exists. With
\fB\-g\fR, if specified GID already exists, other (unique) GID is chosen (i.e.
\fB\-g\fR
is turned off).
.TP 3n
\fB\-g\fR \fIGID\fR
The numerical value of the group's ID. This value must be unique, unless the
\fB\-o\fR
option is used. The value must be non\-negative. The default is to use the smallest ID value greater than 999 and greater than every other group. Values between 0 and 999 are typically reserved for system accounts.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Visa hjälpmeddelande och avsluta.
.TP 3n
\fB\-K \fR\fB\fINYCKEL\fR\fR\fB=\fR\fB\fIVÄRDE\fR\fR
Åsidosätter standardvärden i
\fI/etc/login.defs\fR
(GID_MIN, GID_MAX och andra). Flera flaggor av
\fB\-K\fR
kan anges.
.sp
Exempel:
\fB\-K \fR\fIGID_MIN\fR=\fI100\fR\fB \-K \fR\fIGID_MAX\fR=\fI499\fR
.sp
Notera:
\fB\-K \fR\fIGID_MIN\fR=\fI10\fR,\fIGID_MAX\fR=\fI499\fR
fungerar ännu inte.
.TP 3n
\fB\-o\fR
Denna flagga tillåter att en grupp med ett icke\-unikt GID läggs till.
.SH "FILER"
.TP 3n
\fI/etc/group\fR
Gruppkontoinformation.
.TP 3n
\fI/etc/gshadow\fR
Säker gruppkontoinformation.
.TP 3n
\fI/etc/login.defs\fR
Shadow password suite configuration.
.SH "TÄNK PÅ"
.PP
Groupnames must begin with a lower case letter or an underscore, and only lower case letters, underscores, dashes, and dollar signs may follow. In regular expression terms: [a\-z_][a\-z0\-9_\-]*[$]
.PP
Groupnames may only be up to 16 characters long.
.PP
If the groupname already exists in an external group database such as NIS,
\fBgroupadd\fR
will deny the group creation request.
.PP
Groupnames may only be up to 16 characters long.
.SH "AVSLUTNINGSVÄRDEN"
.PP
Kommandot
\fBgroupadd\fR
avslutas med följande värden:
.TP 3n
\fI0\fR
lyckad
.TP 3n
\fI2\fR
ogiltig kommandosyntax
.TP 3n
\fI3\fR
ogiltigt argument till flagga
.TP 3n
\fI4\fR
GID inte unikt (när
\fB\-o\fR
inte används)
.TP 3n
\fI9\fR
gruppnamn inte unikt
.TP 3n
\fI10\fR
kan inte uppdatera gruppfilen
.SH "SE OCKSÅ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8).
