.\"     Title: groupdel
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "GROUPDEL" "8" "20\-07\-2006" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
groupdel \- ta bort en grupp
.SH "SYNOPSIS"
.HP 9
\fBgroupdel\fR \fIgrupp\fR
.SH "BESKRIVNING"
.PP
The
\fBgroupdel\fR
command modifies the system account files, deleting all entries that refer to
\fIgroup\fR. The named group must exist.
.PP
You must manually check all file systems to insure that no files remain with the named group as the file group ID.
.SH "TÄNK PÅ"
.PP
Du får inte ta bort den primära gruppen för någon existerande anvÃ\(Csndare. Du måste ta bort användaren innan du tar bort gruppen.
.SH "FILER"
.TP 3n
\fI/etc/group\fR
Gruppkontoinformation.
.TP 3n
\fI/etc/gshadow\fR
Säker gruppkontoinformation.
.SH "AVSLUTNINGSVÄRDEN"
.PP
Kommandot
\fBgroupdel\fR
avslutas med följande värden:
.TP 3n
\fI0\fR
lyckad
.TP 3n
\fI2\fR
ogiltig kommandosyntax
.TP 3n
\fI8\fR
kan inte ta bort användarens primära grupp
.TP 3n
\fI10\fR
kan inte uppdatera gruppfilen
.SH "SE OCKSÅ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupmod\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)
