.\"     Title: lastlog
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "LASTLOG" "8" "20\-07\-2006" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
lastlog \- reports the most recent login of all users or of a given user
.SH "SYNOPSIS"
.HP 8
\fBlastlog\fR [\fIflaggor\fR]
.SH "BESKRIVNING"
.PP

\fBlastlog\fR
formats and prints the contents of the last login log
\fI/var/log/lastlog\fR
file. The
\fIlogin\-name\fR,
\fIport\fR, and
\fIlast login time\fR
will be printed. The default (no flags) causes lastlog entries to be printed, sorted by their order in
\fI/etc/passwd\fR.
.SH "FLAGGOR"
.PP
Flaggorna som gäller för kommandot
\fBlastlog\fR
är:
.TP 3n
\fB\-b\fR, \fB\-\-before\fR\fIDAGAR\fR
Print only lastlog records older than
\fIDAYS\fR.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Visa hjälpmeddelande och avsluta.
.TP 3n
\fB\-t\fR, \fB\-\-time\fR\fIDAGAR\fR
Print the lastlog records more recent than
\fIDAYS\fR.
.TP 3n
\fB\-u\fR, \fB\-\-user\fR\fIINLOGGNINGSNAMN\fR
Print the lastlog record for user with specified
\fILOGIN\fR
only.
.TP 3n
Flaggan \fB\-t\fR åsidosätter användningen av \fB\-u\fR.
.PP
If the user has never logged in the message
\fI** Never logged in**\fR
will be displayed instead of the port and time.
.SH "NOTERA"
.PP
The
\fIlastlog\fR
file is a database which contains info on the last login of each user. You should not rotate it. It is a sparse file, so its size on the disk is usually much smaller than the one shown by "\fBls \-l\fR" (which can indicate a really big file if you have in
\fIpasswd\fR
users with a high UID). You can display its real size with "\fBls \-s\fR".
.SH "FILER"
.TP 3n
\fI/var/log/lastlog\fR
Databastider för tidigare användarinloggningar.
.SH "TÄNK PÅ"
.PP
Large gaps in UID numbers will cause the lastlog program to run longer with no output to the screen (i.e. if in lastlog database there is no entries for users with UID between 170 and 800 lastlog will appear to hang as it processes entries with UIDs 171\-799).
