.\"     Title: logoutd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "LOGOUTD" "8" "20\-07\-2006" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
logoutd \- Upprätthåll tidsbegränsningar för inloggningar
.SH "SYNOPSIS"
.HP 8
\fBlogoutd\fR
.SH "BESKRIVNING"
.PP

\fBlogoutd\fR
enforces the login time and port restrictions specified in
\fI/etc/porttime\fR.
\fBlogoutd\fR
should be started from
\fI/etc/rc\fR. The
\fI/var/run/utmp\fR
file is scanned periodically and each user name is checked to see if the named user is permitted on the named port at the current time. Any login session which is violating the restrictions in
\fI/etc/porttime\fR
is terminated.
.SH "FILER"
.TP 3n
\fI/etc/porttime\fR
Fil som innehåller portåtkomst
.TP 3n
\fI/var/run/utmp\fR
Lista på aktuella inloggningssessioner.
