.\"     Title: newusers
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "NEWUSERS" "8" "20\-07\-2006" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
newusers \- uppdatera och skapa nya användare satsvis
.SH "SYNOPSIS"
.HP 9
\fBnewusers\fR [\fInya_användare\fR]
.SH "BESKRIVNING"
.PP

\fBnewusers\fR
reads a file of user name and clear\-text password pairs and uses this information to update a group of existing users or to create new users. Each line is in the same format as the standard password file (see
\fBpasswd\fR(5)) with the following exceptions:
.TP 3n
\fIpw_passwd\fR
Detta fält kommer att krypteras och användas som det nya värdet för det krypterade lösenordet.
.TP 3n
\fIpw_age\fR
Detta fält kommer att ignoreras för skugglösenord om användaren redan finns.
.TP 3n
\fIpw_gid\fR
Detta fält kan vara namnet på en existerande grupp och som då den angivna användaren kommer att läggas till som medlem i. Om en icke\-existerande numerisk grupp anges kommer en ny grupp att skapas med detta nummer.
.TP 3n
\fIpw_dir\fR
This field will be checked for existence as a directory and a new directory with the same name will be created if it does not already exist. The ownership of the directory will be set to be that of the user being created or updated.
.PP
Detta kommando är tänkt att användas i större systemmiljöer där många konton uppdateras på samma gång.
.SH "TÄNK PÅ"
.PP
Inmatningsfilen måste skyddas eftersom den innehåller okrypterade lösenord.
.SH "FILER"
.TP 3n
\fI/etc/login.defs\fR
Shadow password suite configuration.
.SH "SE OCKSÅ"
.PP
\fBlogin.defs\fR(5),
\fBpasswd\fR(1),
\fBuseradd\fR(8).
