.\"     Title: nologin
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "NOLOGIN" "8" "20\-07\-2006" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
nologin \- vägra snällt en inloggning
.SH "SYNOPSIS"
.HP 8
\fBnologin\fR
.SH "BESKRIVNING"
.PP
\fBnologin\fR
visar ett meddelande om att kontot inte är tillgÃ\(Csngligt och avslutas med icke\-noll\-status. Det är tänkt som ett ersÃ\(Csttande skalfält för konton som har inaktiverats.
.PP
För att inaktivera alla inloggningar, undersök
\fBnologin\fR(5).
.SH "SE OCKSÅ"
.PP
\fBlogin\fR(1),
\fBnologin\fR(5).
.SH "HISTORIK"
.PP
Kommandot
\fBnologin\fR
dök upp i BSD 4.4.
