.\"     Title: passwd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Användarkommandon
.\"    Source: Användarkommandon
.\"
.TH "PASSWD" "1" "20\-07\-2006" "Användarkommandon" "Användarkommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
passwd \- ändra användarlösenord
.SH "SYNOPSIS"
.HP 7
\fBpasswd\fR [\fIflaggor\fR] [\fIINLOGGNINGSNAMN\fR]
.SH "BESKRIVNING"
.PP
\fBpasswd\fR
ändrar lösenord för användarkonton. En vanlig användare kan endast ändra lösenordet för sitt egna konto men superanvÃ\(Csndaren kan ändra lösenord för alla konton.
\fBpasswd\fR
Ã\(Csndrar även kontoinformation, såsom det fullständiga namnet för anvÃ\(Csndaren, användarens inloggningsskal eller hans/hennes utgångsdatum för lösenordet och intervall.
.SS "Lösenordsändringar"
.PP
Användaren frågas först efter hans/hennes gamla lösenord, om det finns nÃ\(Yegot. Detta lösenord krypteras sedan och jämförs mot det lagrade lösenordet. Användaren har endast en chans att ange det korrekta lösenordet. Superanvändaren tillåts kringgå detta steg så att bortglömda lösenord kan ändras.
.PP
Efter att lösenordet har matats in kontrolleras lösenordets Ã\(Yeldringsinformation för att se om användaren tillåts att ändra lösenord för tillfället. Om inte, nekar
\fBpasswd\fR
att ändra lösenordet och avslutas.
.PP
Användaren frågas sedan två gånger efter ett ersättande lösenord. Den andra inmatningen jämförs mot den första och båda måste stämma överens för att lösenordet ska ändras.
.PP
Sedan testas lösenordet för sin komplexitet. Som en allmän riktlinje bör lösenord innehålla 6 till 8 tecken och inkluderas ett eller flera tecken från var och en av följande punkter:
.TP 3n
\(bu
gemena bokstäver ur alfabetet
.TP 3n
\(bu
siffrorna 0 till 9
.TP 3n
\(bu
skiljetecken
.sp
.RE
.PP
Tänk på att inte inkludera systemets standardtecken för radering eller döda.
\fBpasswd\fR
kommer att neka alla lösenord som inte har lämplig komplexitet.
.\" end of SS subsection "Lösenordsändringar"
.SS "Tips för användarlösenord"
.PP
Säkerhet i ett lösenord beror på styrkan på krypteringsalgoritmen och nyckellängden. Krypteringsmetoden för
\fIUNIX\-system\fR
är baserad på NBS DES\-algoritmen och är mycket säker. Längden på nyckeln Ã\(Csr beroende på slumpmässigheten för det valda lösenordet.
.PP
Problem i lösenordssäkerheten brukar normalt komma från slarvigt valda lösenord eller hantering. Av denna anledning bör du inte välja ett lösenord som finns i en ordbok eller som måste skrivas ner. Lösenordet bör heller inte vara ett korrekt namn, ditt personnummer, födelsedatum eller gatuadress. Dessa kan användas som gissningar för att ta sig in i systemet.
.PP
Ditt lösenord måste vara lätt att komma ihåg så att du inte behöver skriva ner det på en papperslapp. Detta kan göras genom att lägga till tvÃ\(Ye små ord tillsammans och separera dem med ett specialtecken eller siffra. Till exempel, Pass%word.
.PP
Andra metoder för att konstruera lösenord är att välja en literär fras som är lätt att komma ihåg och välja den första eller sista bokstaven från varje ord. Ett exempel på detta är:
.TP 3n
\(bu
Fråga inte för vem klockorna ringer klockan 3
.TP 3n
\(bu
som blir
.TP 3n
\(bu
Fifvkrk3
.sp
.RE
.PP
Du kan vara hyffsat säker på att få hackare har inkluderat detta i sina ordböcker. Du bör dock välja dina egna metoder för att konstruera lösenord och inte enbart förlita dig på de metoder som anges här.
.\" end of SS subsection "Tips för användarlösenord"
.SH "FLAGGOR"
.PP
Flaggorna som gäller för kommandot
\fBpasswd\fR
är:
.TP 3n
\fB\-a\fR, \fB\-\-all\fR
Denna flagga kan endast användas med
\fB\-S\fR
och gör att status visas för alla användare.
.TP 3n
\fB\-d\fR, \fB\-\-delete\fR
Ta bort en användares lösenord (gör det blankt). Detta är ett snabbt sÃ\(Cstt att inaktivera ett lösenord för ett konto. Det kommer att ta bort det angivna kontots lösenord.
.TP 3n
\fB\-e\fR, \fB\-\-expire\fR
Lösenordet för ett konto sätts omedelbart som utgånget. Detta kan tvinga en användare att ändra sitt lösenord vid nästa inloggningsförsök.
.TP 3n
\fB\-h\fR, \fB\-\-help\fR
Visa hjälpmeddelande och avsluta.
.TP 3n
\fB\-i\fR, \fB\-\-inactive\fR\fIINAKTIV\fR
Denna flagga används för att inaktivera ett konto efter att lösenordet har varit utgånget i ett antal dagar. Efter att ett användarkonto har haft ett utgånget lösenord i
\fIINAKTIV\fR
dagar får anvÃ\(Csndaren inte längre logga in med detta konto.
.TP 3n
\fB\-k\fR, \fB\-\-keep\-tokens\fR
Indikera lösenordsändring bör endast genomföras för utgångna autentiseringslösenord. Användaren önskar behålla sitt icke\-utgångna lösenord som tidigare.
.TP 3n
\fB\-l\fR, \fB\-\-lock\fR
Lås angivet konto. Denna flagga inaktiverar ett konto genom att ändra lösenordet till ett värde som inte matchar något möjligt krypterat vÃ\(Csrde.
.TP 3n
\fB\-m\fR, \fB\-\-mindays\fR\fIMIN_DAGAR\fR
Sätter minimalt antal dagar mellan lösenordsändringar till
\fIMIN_DAGAR\fR. Ett nollvärde för detta fält betyder att användaren kan ändra sitt lösenord när som helst.
.TP 3n
\fB\-q\fR, \fB\-\-quiet\fR
Tyst läge.
.TP 3n
\fB\-r\fR, \fB\-\-repository\fR\fIFÖRRÅD\fR
ändra lösenord i förrådet
\fIFÖRRÅD\fR
.TP 3n
\fB\-S\fR, \fB\-\-status\fR
Visa statusinformation för konto. Statusinformationen innehåller 7 fält. Första fältet är användarens inloggningsnamn. Det andra fältet indikerar om användarkontot är låst (L), saknar lösenord (NP) eller har ett användbart lösenord (P). Det tredje fältet anger datumet för senaste lösenordsändringen. De nästa fyra fälten är minimal ålder, maximal Ã\(Yelder, varningsperiod och inaktivitetsperiod för lösenordet. Dessa åldrar anges i dagar.
.TP 3n
\fB\-u\fR, \fB\-\-unlock\fR
Lås upp angivet konto. Denna flagga återaktiverar ett konto genom att Ã\(Csndra tillbaka lösenordet till dess tidigare värde (till värdet före anvÃ\(Csndning av flaggan
\fB\-l\fR).
.TP 3n
\fB\-w\fR, \fB\-\-warndays\fR\fIVARN_DAGAR\fR
Sätter antalet dagar för varning före ett lösenord behöver ändras. Flaggan
\fIVARN_DAGAR\fR
är antalet dagar före anvÃ\(Csndaren varnas om att lösenordet är på väg att bli utgånget.
.TP 3n
\fB\-x\fR, \fB\-\-maxdays\fR\fIMAX_DAGAR\fR
Sätter maximalt antal dagar som ett lösenord ska vara giltigt. Efter
\fIMAX_DAGAR\fR
krävs det att lösenordet ändras.
.SH "TÄNK PÅ"
.PP
Inte alla flaggor kanske stöds. Kontroll av lösenordskomplexiteten kan variera mellan olika system. Användare rekommenderas att välja ett lösenord som är så komplext som han eller hon känner sig komfortabel med. Användare kanske inte kan ändra sina lösenord på ett system om NIS Ã\(Csr aktiverat och de inte är inloggade mot NIS\-servern.
.SH "FILER"
.TP 3n
\fI/etc/passwd\fR
Användarkontoinformation.
.TP 3n
\fI/etc/shadow\fR
Säker användarkontoinformation.
.SH "AVSLUTNINGSVÄRDEN"
.PP
Kommandot
\fBpasswd\fR
avslutas med följande värden:
.TP 3n
\fI0\fR
lyckad
.TP 3n
\fI1\fR
åtkomst nekad
.TP 3n
\fI2\fR
ogiltig kombination av flaggor
.TP 3n
\fI3\fR
oväntat fel, ingenting har genomförts
.TP 3n
\fI4\fR
oväntat fel, filen
\fIpasswd\fR
saknas
.TP 3n
\fI5\fR
Filen
\fIpasswd\fR
är upptagen, försök igen
.TP 3n
\fI6\fR
ogiltigt argument till flagga
.SH "SE OCKSÅ"
.PP
\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5).
