.\"     Title: shadow
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Filformat och konversioner
.\"    Source: Filformat och konversioner
.\"
.TH "SHADOW" "5" "20\-07\-2006" "Filformat och konversioner" "Filformat och konversioner"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
shadow \- krypterad lösenordsfil
.SH "BESKRIVNING"
.PP

\fIshadow\fR
contains the encrypted password information for user's accounts and optional the password aging information. Included is:
.TP 3n
\(bu
inloggningsnamn
.TP 3n
\(bu
krypterat lösenord
.TP 3n
\(bu
dagar sedan 1:a januari, 1970 som lösenordet senast ändrades
.TP 3n
\(bu
dagar innan lösenordet får ändras
.TP 3n
\(bu
dagar efter vilket lösenordet måste ändras
.TP 3n
\(bu
dagar innan lösenordet går ut som användaren varnas
.TP 3n
\(bu
dagar efter att lösenordet gått ut och kontot inaktiveras
.TP 3n
\(bu
dagar sedan 1:a januari 1970 som kontot är inaktiverat
.TP 3n
\(bu
ett reserverat fält
.sp
.RE
.PP
The password field must be filled. The encrypted password consists of 13 to 24 characters from the 64 characters alphabet a thru z, A thru Z, 0 thru 9, \\. and /. Optionally it can start with a "$" character. This means the encrypted password was generated using another (not DES) algorithm. For example if it starts with "$1$" it means the MD5\-based algorithm was used.
.PP
Referera till
\fBcrypt\fR(3)
för detaljer om hur denna sträng tolkas.
.PP
If the password field contains some string that is not valid result of
\fBcrypt\fR(3), for instance ! or *, the user will not be able to use a unix password to log in, subject to
\fBpam\fR(7).
.PP
The date of the last password change is given as the number of days since Jan 1, 1970. The password may not be changed again until the proper number of days have passed, and must be changed after the maximum number of days. If the minimum number of days required is greater than the maximum number of day allowed, this password may not be changed by the user.
.PP
An account is considered to be inactive and is disabled if the password is not changed within the specified number of days after the password expires. An account will also be disabled on the specified day regardless of other password expiration information.
.PP
This information supersedes any password or password age information present in
\fI/etc/passwd\fR.
.PP
Denna fil får inte vara läsbar av vanliga användare om lösenordssÃ\(Cskerheten ska upprätthållas.
.SH "FILER"
.TP 3n
\fI/etc/passwd\fR
Användarkontoinformation.
.TP 3n
\fI/etc/shadow\fR
Säker användarkontoinformation.
.SH "SE OCKSÅ"
.PP
\fBchage\fR(1),
\fBlogin\fR(1),
\fBsu\fR(1),
\fBpasswd\fR(1),
\fBpasswd\fR(5),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBsulogin\fR(8).
