.\"     Title: suauth
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 20.07.2006
.\"    Manual: Filformat och konversioner
.\"    Source: Filformat och konversioner
.\"
.TH "SUAUTH" "5" "20\-07\-2006" "Filformat och konversioner" "Filformat och konversioner"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
suauth \- detaljerad kontrollfil för su
.SH "SYNOPSIS"
.HP 12
\fB/etc/suauth\fR
.SH "BESKRIVNING"
.PP
The file
\fI/etc/suauth\fR
is referenced whenever the su command is called. It can change the behaviour of the su command, based upon:
.sp
.RS 3n
.nf
      1) the user su is targetting
    
.fi
.RE
.sp
.PP
2) the user executing the su command (or any groups he might be a member of)
.PP
Filen är i följande format, med de rader som inleds med # behandlas som kommentarsrader och ignoreras;
.sp
.RS 3n
.nf
      till\-id:från\-id:ÅTGÄRD
    
.fi
.RE
.PP
Där till\-id är antingen ordet
\fIALL\fR, en lista med anvÃ\(Csndarnamn separerade med "," eller orden
\fIALL EXCEPT\fR
följt av en lista med användarnamn separerade med ","
.PP
från\-id är formaterad på samma sätt som till\-id förutom att det extra ordet
\fIGROUP\fR
känns igen.
\fIALL EXCEPT GROUP\fR
är helt giltigt också. Efterföljande till
\fIGROUP\fR
kan vara ett eller flera gruppnamn, separerade med ",". Det är inte tillräckligt att ha primärt grupp\-id för den relevanta gruppen, en post i
\fB/etc/group\fR(5)
är nödvändigt.
.PP
Åtgärden kan endast vara en av följande för närvarande stödda flaggor.
.TP 3n
\fIDENY\fR
Försöket att använda su stoppades före ett lösenord har efterfrågats.
.TP 3n
\fINOPASS\fR
Försöket att använda su lyckades helt automatiskt; inget lösenord har efterfrågats.
.TP 3n
\fIOWNPASS\fR
För att su\-kommandot ska lyckas måste användaren mata in sitt egna lösenord. De blir frågade att göra detta.
.PP
Note there are three separate fields delimited by a colon. No whitespace must surround this colon. Also note that the file is examined sequentially line by line, and the first applicable rule is used without examining the file further. This makes it possible for a system administrator to exercise as fine control as he or she wishes.
.SH "EXEMPEL"
.sp
.RS 3n
.nf
      # exempelfil för /etc/suauth
      #
      # Ett par priviligerade användarnamn som 
      # kan su till root med sina egna lösenord.
      #
      root:bosse,birddog:OWNPASS
      #
      # Alla andra kan inte su till root om de inte finns
      # gruppen wheel. Det är så BSD gör saker.
      #
      root:ALL EXCEPT GROUP wheel:DENY
      #
      # Kanske terry och birddog är konton som
      # ägs av samma person.
      # Tillgång kan ges mellan dem utan
      # lösenord.
      #
      terry:birddog:NOPASS
      birddog:terry:NOPASS
      #
    
.fi
.RE
.sp
.SH "FILER"
.TP 3n
\fI/etc/suauth\fR
.SH "FEL"
.PP
There could be plenty lurking. The file parser is particularly unforgiving about syntax errors, expecting no spurious whitespace (apart from beginning and end of lines), and a specific token delimiting different things.
.SH "DIAGNOSTIK"
.PP
An error parsing the file is reported using
\fBsyslogd\fR(8)
as level ERR on facility AUTH.
.SH "SE OCKSÅ"
.PP
\fBsu\fR(1).
